### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by rhiever** [automl/auto-sklearn#1]
Hi all,

First off: Great project! I was very excited to come across this project and I'm eager to try it out. However, when I attempted to install auto-sklearn, I ran into several difficulties. In particular, I noticed that HPOlib -- a dependency of this project -- requires Python 2.7, which entails that auto-sklearn also requires Python 2.7.

Is there any way around this other than setting up a 2.7 environment? I'd love to integrate this into a Python 3 workflow.

**Comment by mfeurer** [comment]
Hi,
I am sorry to tell you, but at the moment there is no other way than using python 2.7. Although I removed HPOlib from the requirements, I think the other dependencies also won't work with python 3. 

Since you're not the first one requesting python 3 support we will work on this.

**Comment by lsorber** [comment]
+1

**Comment by mfeurer** [comment]
Tests on travis-ci pass with 529d07dcaa4189bf99678489c6cc43d58ad2669e; all dependencies work with python 3 as well.

**Comment by rhiever** [comment]
Thanks! :+1:

**Comment by JPFrancoia** [comment]
+1 for python3. I could really use this in my research.

**Comment by mfeurer** [comment]
Hi @JPFrancoia , thanks for your interest in this project. This issue is closed as all tests pass with python 3. If you find anything which doesn't work, please open a new issue.
