### ISSUE TITLE
Documentation Update for Environment Variables

### ISSUE THREAD

**Issue by ArlindKadra** [automl/auto-sklearn#1009]
Recently, I stumbled upon an issue while using `auto-sklearn` with the gradient boosting algorithm as the only estimator, because, I did not set `OMP_NUM_THREADS=1`. 
For other estimators, `MKL_NUM_THREADS=1 `and `OPENBLAS_NUM_THREADS=1` should also be set.

It would be good to have this in the documentation in the future.

**Comment by mfeurer** [comment]
Documented via #1161
