### ISSUE TITLE
auto-sklearn can only run very few models

### ISSUE THREAD

**Issue by wangcan04** [automl/auto-sklearn#1015]
Hi, I run the exact same code 1 month ago and now, but it shows very different results. And the results I got now looks incorrect.  Since I give 36000 per task, 1200 per run, it should be at least 29 models that been tested. Does anybody have the same issue?
TIME PER TASK: 36000
TIME PER FIT: 1200
auto-sklearn results:
  Dataset name: 566be0fc01692965c41c2dc7aae375e3
  Metric: mean_absolute_error
  Best validation score: 0.219581
  Number of target algorithm runs: 25
  Number of successful target algorithm runs: 15
  Number of crashed target algorithm runs: 7
  Number of target algorithms that exceeded the time limit: 1
  Number of target algorithms that exceeded the memory limit: 2

**Comment by mfeurer** [comment]
Hi @wangcan04 and thanks for reporting this. We have indeed changed the behavior of Auto-sklearn to run the ensemble building script interleaved within the main process. This means that some time that was previously available for fitting models is now used to build ensembles. While this may sound like a drawback, it actually makes Auto-sklearn more predictable as the number of used processes can now be controlled by the `n_jobs` argument. As Auto-sklearn would use between 1 and 2 processes before, you can probably set `n_jobs=2` without any issues.

**Comment by mfeurer** [comment]
Closing this as the original question is answered. Please reopen if that's not the case or if you have further questions.
