### ISSUE TITLE
Documentation for AutoSklearn2Classifier states non-existing parameters

### ISSUE THREAD

**Issue by mdziezyc** [automl/auto-sklearn#1019]
1. Page https://automl.github.io/auto-sklearn/master/api.html describes parameters which are not present in AutoSklearn2Classifier e.g. resampling_strategy which might be misleading to some (including me).
2. Why resampling_strategy is not implemented?

Thanks for your great library :)

**Comment by mfeurer** [comment]
Thanks a lot for bringing this up. We'll remove these in #1030.

Answering your question, AutoSklearn2Classifier predicts which resampling strategy to use based on the dataset properties.
