### ISSUE TITLE
JupyterLab notebook kernel crashes when using AutoSklearnClassifier

### ISSUE THREAD

**Issue by fkromer** [automl/auto-sklearn#1025]
## Describe the bug ##

I'm running JupyterLab and am using `AutoSklearnClassifier` in a notebook cell. If I execute the cell I get an error and the notebook kernel crashes.

## To Reproduce ##

1. Open JupyterLab.

2 . Paste this code into a notebook cell.

```
model = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=5*60,  # 5 Minuten Gesamtlaufzeit
    per_run_time_limit=30,  # Hyperparameter pro Algorithmus 30 Sekunden optimieren
    memory_limit=4*1024,  # Freeze von Notebook verhindern
    n_jobs=8,  # auf 8 CPU-Cores laufen lassen
    ensemble_size=1,  # Overfitting vermeiden (ensemble_size + initial_configurations_via_metalearning)
    initial_configurations_via_metalearning=0,  # Overfitting vermeiden (ensemble_size + initial_configurations_via_metalearning)
)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

model.fit(X_train, y_train)
y_hat = model.predict(X_test)
mae = mean_absolute_error(y_test, y_hat)
mae
```

3. Execute the cell.

## Expected behavior ##

Code executed, JupyterLab notebook not crashing.

## Actual behavior, stacktrace or logfile ##

Output in output cell:

    /home/florian/gitlab/data-processing/.venv/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
      self.re = re.compile(self.reString)

The notebook kernel crashes:

```
Kernel Restarting

The kernel for notebooks/honey.ipynb appears to have died. It will restart automatically.

(OK button)
```

## Environment and installation: ##

Please give details about your installation:

* OS: Ubuntu 20.04
* Is your installation in a virtual environment or conda environment? virtual environment
* Python version: 3.8.2
* Auto-sklearn version: 0.11.1

**Comment by mfeurer** [comment]
Thanks a lot for reporting this issue. This usually happens in case the dependency `pyrfr` is not compiled correctly. Could you please check whether this also happens if you start your code in a regular python environment and also if this following example can execute (https://github.com/automl/SMAC3/blob/master/examples/SMAC4HPO_rf.py)?

**Comment by fkromer** [comment]
Hi @mfeurer, right, I actually had a problem compiling `pyfrf` when I tried to install auto-sklearn the first time. However after some "workarounding" the auto-sklearn installation seemed to be ok. I'll try to find some time for trying out your suggestions.

**Comment by fkromer** [comment]
@mfeurer I executed the script in my projects Python virtual environment and got this output:

```
/home/florian/gitlab/project-gin/.venv/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
INFO:RF-example:Running random forest example for SMAC. If you experience difficulties, try to decrease the memory-limit.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2020-12-08_14:23:02_826167
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic and only evaluate one configuration per iteration!
Speicherzugriffsfehler (Speicherabzug geschrieben)
(.venv) florian@matebook:~/gitlab/project-gin$
```

**Comment by fkromer** [comment]
> Hi @mfeurer, right, I actually had a problem compiling pyfrf when I tried to install auto-sklearn the first time. However after some "workarounding" the auto-sklearn installation seemed to be ok. I'll try to find some time for trying out your suggestions.

Ah, I can remember now. The first time I tried to install `auto-sklearn` the installation failed because `pyrfr` could not be compiled cause `pyrfr` depends on `swig` for compilation. So I installed `swig` onto Ubuntu and the second installation attempt seemed to work.

**Comment by mfeurer** [comment]
This hints at a the issue being the random forest not being compiled correctly. Could you please check your SWIG version? It needs to be SWIG version 3.

**Comment by damounayman** [comment]
Hi, I get the same problem (the notebook kernel crashes). @mfeurer , it works only for SWIG version 3?
I have SWIG Version 4.0.1

**Comment by mfeurer** [comment]
Yes, it only works for SWIG3. We're working on an update of the pyrfr dependency, but aren't sure when that will arrive.

**Comment by grld** [comment]
Hello together, I am facing similar problems and guess it's also due to to fact that I had SWIG 4 installed. I am trying to use SWIG 3 but somehow I am not able to change the version. I have downloaded the .tar according to your description in the installation procedure and managed to install it. But when I type swig -version in my terminal I still get
```
SWIG Version 4.0.2

Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]

Configured options: +pcre
```
Already tried to uninstall it with apt-get but version stays 4.0.2. I am quite new to Linux since I only changed OS this weekend to use the auto-sklearn so sorry if my question is stupid.

**Comment by enving** [comment]
> Already tried to uninstall it with apt-get but version stays 4.0.2. I am quite new to Linux since I only changed OS this weekend to use the auto-sklearn so sorry if my question is stupid.

Hi, yea got the same issue. "Uninstalled" swig4.0 by:

`sudo apt-get autoremove swig4.0
`
wasn't changing anything when going into the conda environment:

```
$ swig -version
-->SWIG Version 4.0.2

Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]
SWIG Version 4.0.2

Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]

Configured options: +pcreSWIG Version 4.0.2

Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]

+pcreSWIG Version 4.0.2
SWIG Version 4.0.2

Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]

Configured options: +pcre
Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]

Configured options: +pcre
Configured options: +pcre
```

Then tried to install swig 3.0.12 with extracting the zip swig 3.0.12 from sourceforge and:
`./configure -prefix=/home/user/Dokumente/Automl/swig-3.0.12
sudo make install`

In the base and outside conda environment I get in terminal:
`$ swig -version

Der Befehl 'swig' wurde nicht gefunden, kann aber installiert werden mit:

sudo apt install swig

`

In my working environment however I get in terminal even after this new installation of 3.0.12. still:
`$ swig -version

SWIG Version 4.0.2

Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]

Configured options: +pcre`

**Comment by fkromer** [comment]
I've setup Ubuntu 20.04 for WSL2 recently. With `Python 3.8.5` and `swig 4.0.1-5build1` I could install `auto-sklearn 0.12.3` without trouble.

**Comment by mfeurer** [comment]
Dear all, we have finally pushed wheels of the pyrfr package to pypi so this should no longer be an issue (on platforms that support the manylinux2010 and manylinux2014 tag). If you find any issues with those wheels, please reopen this issue.
