### ISSUE TITLE
White box only AutoML with auto-sklearn

### ISSUE THREAD

**Issue by akshayparanjape** [automl/auto-sklearn#1033]
Is there a possibility to include only the white-box model for processing using auto-sklearn? 
Auto-sklearn takes `include_estimators` as a parameter, so it is also enough to just know all the white-box models that auto-sklearn supports.

**Comment by mfeurer** [comment]
Yes, that's possible. How do you define white-box models?

**Comment by mfeurer** [comment]
An example will be added as part of #1109. Please reopen if you have further questions.
