### ISSUE TITLE
AutoSklearn stuck on sleep

### ISSUE THREAD

**Issue by BouweCeunen** [automl/auto-sklearn#1036]
## Describe the bug ##
AutoSklearn is stuck on `time.sleep(0.01)` in `automl.py` waiting for a port for the logger?

## To Reproduce ##
```
import autosklearn.classification

auto_sklean_model = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=30,
    per_run_time_limit=1,
    ensemble_size=1,
    n_jobs=-1
)

auto_sklean_model.fit(X_train, y_train)
y_preds_autosklearn = auto_sklean_model.predict(X_test)
```

## Expected behavior ##
/

## Actual behavior, stacktrace or logfile ##
I got this stacktrace after stopping the notebook because nothing was happening.

```
/opt/conda/lib/python3.7/site-packages/autosklearn/automl.py in fit(self, X, y, task, X_test, y_test, feat_type, dataset_name, only_return_configuration_space, load_models)
    464         # By default try to use the TCP logging port or get a new port
    465         self._logger_port = logging.handlers.DEFAULT_TCP_LOGGING_PORT
--> 466         self._logger = self._get_logger(dataset_name)
    467 
    468         # If no dask client was provided, we create one, so that we can

/opt/conda/lib/python3.7/site-packages/autosklearn/automl.py in _get_logger(self, name)
    308             with port.get_lock():
    309                 if port.value == -1:
--> 310                     time.sleep(0.01)
    311                 else:
    312                     break
```
## Environment and installation: ##

Please give details about your installation:

* OS => Linux
* Is your installation in a virtual environment or conda environment? => Conda
* Python version => 3.7.6
* Auto-sklearn version 0.12.0

**Comment by mfeurer** [comment]
Thanks for reporting this. How long has it actually been stuck?

**Comment by BouweCeunen** [comment]
It seems that I didn't wait long enough, my bad!

**Comment by mfeurer** [comment]
> It seems that I didn't wait long enough, my bad!

Yeah, sorry, this is because the logger lives in its own process and we had to switch the subprocess starting from `fork` to `spawn` which can take a bit of time.
