### ISSUE TITLE
Installation documentation - swing version

### ISSUE THREAD

**Issue by mdziezyc** [automl/auto-sklearn#1037]
https://automl.github.io/auto-sklearn/master/installation.html#installation states `SWIG (version 3.0.* is required; >=4.0.0 is not supported) (get SWIG here).`

Therefore I would suggest adding version requirement to all installation instruction especially to: `sudo apt-get install build-essential swig` and `conda install gxx_linux-64 gcc_linux-64 swig`

I feel like `swig<4.0.0` should be ok.

**Comment by mfeurer** [comment]
Thanks a lot for the suggestion, would you like to do a PR to the development branch and add this information?

**Comment by franchuterivera** [comment]
Hello!, I see this is already added to the documentation (https://automl.github.io/auto-sklearn/master/installation.html#installation)....

Can this issue be closed?

**Comment by mfeurer** [comment]
Closing this as we will support swig 4 in the future, see https://github.com/automl/random_forest_run/pull/61
