### ISSUE TITLE
Documentation Regression Example causes Segmentation Fault

### ISSUE THREAD

**Issue by JacksonBurns** [automl/auto-sklearn#1051]
Hi all -

I am just getting started with auto-sklearn and am trying to run the regression example from [the documentation](https://automl.github.io/auto-sklearn/master/examples/20_basic/example_regression.html#sphx-glr-examples-20-basic-example-regression-py), but it throws a number of warnings and then seg faults (full output at the bottom):
`
[WARNING] [2021-01-06 01:34:09,426:Client-AutoMLSMBO(1)::boston] Could not find runs for instance aloi
[WARNING] [2021-01-06 01:34:09,428:Client-AutoMLSMBO(1)::boston] Could not find runs for instance flora
[WARNING] [2021-01-06 01:34:09,431:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-100852
[WARNING] [2021-01-06 01:34:09,461:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-11626
[WARNING] [2021-01-06 01:34:09,461:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance aloi
Segmentation fault (core dumped)
`
The installation documentation was helpful and I believe I followed it correctly, but I'm not sure. I am running on Ubuntu 20.04 with Python 3.8.5. Here is the log file in case it is helpful.
[AutoML(1):boston.log](https://github.com/automl/auto-sklearn/files/5774225/AutoML.1.boston.log)

Full output:
`$ python test.py
/home/jackson/anaconda3/envs/mlbox/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/jackson/anaconda3/envs/mlbox/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/jackson/anaconda3/envs/mlbox/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/jackson/anaconda3/envs/mlbox/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
[WARNING] [2021-01-06 01:45:53,185:Client-AutoMLSMBO(1)::boston] Dataset boston already in meta-data. Removing occurence.
[WARNING] [2021-01-06 01:45:53,199:Client-AutoMLSMBO(1)::boston] Could not find runs for instance aloi
[WARNING] [2021-01-06 01:45:53,201:Client-AutoMLSMBO(1)::boston] Could not find runs for instance flora
[WARNING] [2021-01-06 01:45:53,203:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-100852
[WARNING] [2021-01-06 01:45:53,203:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-10475
[WARNING] [2021-01-06 01:45:53,203:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-10502
[WARNING] [2021-01-06 01:45:53,203:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-10809
[WARNING] [2021-01-06 01:45:53,203:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-10980
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-11
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-11626
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-12569
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-12947
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-12968
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-163
[WARNING] [2021-01-06 01:45:53,204:Client-AutoMLSMBO(1)::boston] Could not find runs for instance qsar-tid-72
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-11
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-10980
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-72
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-163
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-10502
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-12947
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-10475
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-12569
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-100852
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-12968
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-10809
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance qsar-tid-11626
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance aloi
[WARNING] [2021-01-06 01:45:53,233:Client-AutoMLSMBO(1)::boston] Found no best configuration for instance flora
Segmentation fault (core dumped)`

**Comment by MANU-CHAUHAN** [comment]
+1

**Comment by mfeurer** [comment]
Hi @JacksonBurns could you please check if your issue is a duplicate of #858?

**Comment by JacksonBurns** [comment]
@mfeurer I read through and double checked that I had the correct version of SWIG installed, which I did. I then went back through and followed the instructions again in a fresh anaconda environment, and I still get the warning but **test.py** runs to completion.

Ultimately I just ended up using the Docker image and everything seems to work fine - not sure what was wrong with the anaconda environment.

**Comment by mfWeeWee** [comment]
I am getting the same one but for classifiers? nay improvement on this? 
[WARNING] [2021-08-16 13:07:12,801:Client-AutoMLSMBO(1)::1a9db172-fe82-11eb-b539-fc4482a5905b] Could not find meta-data directory /home/vivian/anaconda3/envs/Autoskle/lib/python3.8/site-packages/autosklearn/metalearning/files/accu_binary.classification_dense


I get this and then the algorithm won't proceed.

**Comment by eddiebergman** [comment]
Hi @mfWeeWee, if you could provide a little more context that would help a lot.

* Could you provide you python version `$ python -V`
* What version of autosklearn you are using `$ pip list | grep auto-sklearn`
* If you can provide a minimal working example of your code which causes the hang, that increases the likelyhood we can help dramatically.

Sometimes there's very little feedback by autosklearn so try the same setting with 30 seconds with just a small sample of your dataset. If after a minute or two you still have no response then yes it is hanging. If it's a large dataset, this can also take a while.

This warning should not cause the program to hang. But to give more context as to its origins. The line "accu_binary.classification_dense" consists of 3 parts 
1. The name of the metric `accu`
2. The type of task `binary.classification`
3. The data type its working on `dense` (vs `sparse`)

The 1. part is important here as it's the name of the `metric` that you passed to `AutoSklearnClassifier` either in it's init or fit method. AutoSklearn attempts to use prior performance on similar looking datasets to know which algorithms it should start its search from. In this case the `metric` you passed has a name `accu` which is a custom one you have provided. AutoSklearn has no idea about this custom metric and so can not use metalearning to warm-start the search, hence the warning.

If you want to make use of the meta learning features of autosklearn, you'll have to use one of the metrics provided [here](https://automl.github.io/auto-sklearn/master/api.html#built-in-metrics).
