### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mbahmani** [automl/auto-sklearn#1054]
## Describe the bug ##
 
Just installed the auto-sklearn on Google Colab, and I got the following error when I tried to fit the model.

## To Reproduce ##
 
1. Go to 'google Colab'
2. On the notebook, I tried to install auto-sklearn based on the[ installation page ](https://automl.github.io/auto-sklearn/master/installation.html)
3. Then I created a model based on the [this example](https://automl.github.io/auto-sklearn/master/examples/20_basic/example_classification.html#sphx-glr-examples-20-basic-example-classification-py)
4.  See the following image error:
<a href="https://ibb.co/845ppDq"><img src="https://i.ibb.co/k68ffgj/Selection-016.png" alt="Selection-016" border="0"></a>
## Expected behavior ##
Fit the Model with no error.
## Actual behavior
Fit the Model with some errors. which you see in the [photo](https://ibb.co/845ppDq).
1. AttributeError:  'AutoSklearnClassifier' object has no attribute 'load_models'
2. TypeError: 'NoneType' object is not iterable

Although this error is observed, I could use the automl object to print all the models (automl.show_models()).

## Environment and installation: ##

*  google colab
* Python version: 3.6.9
* Auto-sklearn version: auto-sklearn

**Comment by mfeurer** [comment]
Thanks a lot for reporting this issue. It is indeed only an issue in printing the model returned by fit() - you can therefore use it without any issues further down in your notebook.

This is only an issue for notebook users and does not affect other users.

**Comment by mbahmani** [comment]
Great! Thanks for the quick response.

**Comment by mfeurer** [comment]
Re-opening this issue to remember us to fix this nuisance.

**Comment by franchuterivera** [comment]
I  confirm this issue is the same as #1061  which is fixed by #1063 

I am closing this to avoid having duplicates.
