### ISSUE TITLE
Give an example multilabel regression

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#1057]

**Comment by rajpratyush** [comment]
can I work on this issue??

**Comment by mfeurer** [comment]
Yes, definitely! Please go ahead and create a PR to the development branch

**Comment by rajpratyush** [comment]
Okay @mfeurer

**Comment by mfeurer** [comment]
If you're still interested this would be a new file.

**Comment by rajpratyush** [comment]
actually this is my first time beginning on auto ml project
can you guide me

**Comment by mfeurer** [comment]
Do you have any experience with Auto-sklearn yet?

**Comment by rajpratyush** [comment]
No sir but i am willing to learn

**Comment by mfeurer** [comment]
If you want to contribute on this example you should be familiar with multilabel regression in scikit-learn and Auto-sklearn by reading the scikit-learn docs and the auto-sklearn docs and mostly other examples.

**Comment by isaac-chung** [comment]
@mfeurer if this is still open, I am happy to create a PR for the new example. 
I couldn't find a contribute.md page in the repo. What rule of thumb do you usually follow for commit messages and PR titles/body?

**Comment by mfeurer** [comment]
>  [Edit] Opened up a PR. Would love to help resolve this issue there.

Thanks a lot, the PR looks good. We'd also be happy about improved contributing guidelines to answer questions about how to name commit messages etc.

**Comment by mfeurer** [comment]
Thanks a lot @isaac-chung for your contribution!
