### ISSUE TITLE
Autosklearn does not work -  concurrent.futures._base.CancelledError: run_wrapper-#

### ISSUE THREAD

**Issue by 151083** [automl/auto-sklearn#1058]
Trying to start a autosklearn fit with the following code 

```
import sklearn.datasets
import sklearn.metrics

import autosklearn.regression
X, y = sklearn.datasets.load_boston(return_X_y=True)
X_train, X_test, y_train, y_test = \
sklearn.model_selection.train_test_split(X, y, random_state=1)

automl = autosklearn.regression.AutoSklearnRegressor(
        time_left_for_this_task=120,
        per_run_time_limit=30,
        ensemble_size=1,initial_configurations_via_metalearning=0,
 tmp_folder='./tmp/autosklearn_regression_example_tmp')
automl.fit(X_train, y_train, dataset_name='boston')
```

which produces the following error

> File "/usr/local/lib/python3.6/dist-packages/smac/tae/dask_runner.py", line 180, in get_finished_runs
>     self._extract_completed_runs_from_futures()
>   File "/usr/local/lib/python3.6/dist-packages/smac/tae/dask_runner.py", line 209, in _extract_completed_runs_from_futures
>     self.results.append(future.result())
>   File "/home/aleksandar/.local/lib/python3.6/site-packages/distributed/client.py", line 226, in result
>     raise result
> concurrent.futures._base.CancelledError: run_wrapper-220dd398e1579d6cdc4097b2d8f25e43

I have tried setting the dask_client myself and still get the same error. Setting the number or ensemble_size to 0 doesnt gives an error something like 
AutoSklearnRegressor does not have method load_models.

I've installed swig and have the latest version of all dask and dask.distibuted. Ran this code via jupyter notebook with latest kernel and also with python3.6 from the command line as a python file.

* OS Ubuntu 18
* Is your installation in a virtual environment or conda environment? No
* Python version 3.6
* Auto-sklearn version latest

**Comment by mfeurer** [comment]
@franchuterivera do you know what's going on here and how this can happen?

**Comment by franchuterivera** [comment]
I was trying to reproduce this error, and I was not able, following the provided instruction. I have also not seen this error before, yet the dask issue tracker show this occurring in some very old versions of dask.
@151083 is this an issue you see consistently? can you provide us the output of **pip freeze**? If so, is it possible to try anaconda for this as detailed [here](https://automl.github.io/auto-sklearn/master/installation.html)?
