### ISSUE TITLE
How does autosklearn manages the input time budget (time_left_for_this_task)?

### ISSUE THREAD

**Issue by Yasslight90** [automl/auto-sklearn#1065]
Hello there,

For any input time budget provided by the user (or default = 1 H), autosklearn manages to output a model. 

1- Can you tell me more about its learning procedure under this time constraint?
2- Can you tell me where I can find the code related to this procedure?

Thank you!

Yassine

**Comment by mfeurer** [comment]
Thanks for your interest @Yasslight90. You can find further information in [one of our papers describing Auto-sklearn](https://automl.github.io/auto-sklearn/master/#citing-auto-sklearn). The code related to this procedure is not in a specific file but spread across the whole project.

**Comment by eddiebergman** [comment]
This seems to have been marked as stale but not closed, closing this issue as it seems the information was given
