### ISSUE TITLE
Unexpected Behavior after installation

### ISSUE THREAD

**Issue by schae211** [automl/auto-sklearn#1066]
## Describe the bug ##
So I just installed auto-sklearn (version 0.12.1) as specified on the installation page. Prior to that I installed SWIG (version 3.0.12). The installation process is working fine. However, when I want to test the library I get the following error:

## To Reproduce ##
$ wget https://automl.github.io/auto-sklearn/master/_downloads/650cd19a8dfee813a7d7fb5b90341ed3/example_classification.py
$ python example_classification.py 

## Expected behavior ##
example output

## Actual behavior, stacktrace or logfile ##
/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
Traceback (most recent call last):
  File "example_classification.py", line 35, in <module>
    automl.fit(X_train, y_train, dataset_name='breast_cancer')
  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/estimators.py", line 591, in fit
[ERROR] [2021-01-23 22:07:46,677:Client-AutoML(1):breast_cancer] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': 0, 'subprocess_stdout': 'Exception handling in `fit_predict_try_except_decorator`: traceback: Traceback (most recent call last):\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/__init__.py", line 32, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/train_evaluator.py", line 1079, in eval_holdout\n    evaluator.fit_predict_and_loss(iterative=iterative)\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/train_evaluator.py", line 611, in fit_predict_and_loss\n    self.finish_up(\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 333, in finish_up\n    self.queue.put(rval_dict)\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/multiprocessing/queues.py", line 88, in put\n    self._start_thread()\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread\n    self._thread.start()\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/threading.py", line 852, in start\n    _start_new_thread(self._bootstrap, ())\nRuntimeError: can\'t start new thread\n \nerror message: RuntimeError("can\'t start new thread")\n', 'subprocess_stderr': '', 'exitcode': 0, 'configuration_origin': 'DUMMY'}.
    super().fit(
  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/estimators.py", line 356, in fit
    self.automl_.fit(load_models=self._load_models, **kwargs)
  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/automl.py", line 1386, in fit
    return super().fit(
  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/automl.py", line 604, in fit
    self._do_dummy_prediction(datamanager, num_run)
  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/automl.py", line 423, in _do_dummy_prediction
    raise ValueError(
ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': 0, 'subprocess_stdout': 'Exception handling in `fit_predict_try_except_decorator`: traceback: Traceback (most recent call last):\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/__init__.py", line 32, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/train_evaluator.py", line 1079, in eval_holdout\n    evaluator.fit_predict_and_loss(iterative=iterative)\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/train_evaluator.py", line 611, in fit_predict_and_loss\n    self.finish_up(\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 333, in finish_up\n    self.queue.put(rval_dict)\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/multiprocessing/queues.py", line 88, in put\n    self._start_thread()\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread\n    self._thread.start()\n  File "/home/philipp/miniconda3/envs/AutoML/lib/python3.8/threading.py", line 852, in start\n    _start_new_thread(self._bootstrap, ())\nRuntimeError: can\'t start new thread\n \nerror message: RuntimeError("can\'t start new thread")\n', 'subprocess_stderr': '', 'exitcode': 0, 'configuration_origin': 'DUMMY'}.

Please describe the expected behavior here. If there is a stacktrace, please paste it here. If there is no stacktrace printed, please upload the logfile which was stored in the `tmp_folder`
[AutoML(1):breast_cancer.log](https://github.com/automl/auto-sklearn/files/5861060/AutoML.1.breast_cancer.log)

## Environment and installation: ##
Ubuntu 20.04.1 LTS
Conda environment with python=3.8
Auto-sklearn version 0.12.1
SWIG version 3.0.12

**Comment by foolnotion** [comment]
Same here, running in a Ubuntu 20.04 container
```
/usr/local/lib/python3.8/dist-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
[ERROR] [2021-01-27 12:26:16,601:Client-AutoML(1):a8cee7d766cbbe62e36118a9e4f4d2b5] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': 0, 'subprocess_stdout': 'Exception handling in `fit_predict_try_except_decorator`: traceback: Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/dist-packages/autosklearn/evaluation/__init__.py", line 32, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/autosklearn/evaluation/train_evaluator.py", line 1079, in eval_holdout\n    evaluator.fit_predict_and_loss(iterative=iterative)\n  File "/usr/local/lib/python3.8/dist-packages/autosklearn/evaluation/train_evaluator.py", line 611, in fit_predict_and_loss\n    self.finish_up(\n  File "/usr/local/lib/python3.8/dist-packages/autosklearn/evaluation/abstract_evaluator.py", line 333, in finish_up\n  File "/usr/lib/python3.8/multiprocessing/queues.py", line 88, in put\n    self._start_thread()\n  File "/usr/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread\n    self._thread.start()\n  File "/usr/lib/python3.8/threading.py", line 852, in start\n    _start_new_thread(self._bootstrap, ())\nRuntimeError: can\'t start new thread\n \nerror message: RuntimeError("can\'t start new thread")\n', 'subprocess_stderr': '', 'exitcode': 0, 'configuration_origin': 'DUMMY'}.
```

**Comment by shabir1** [comment]
I am facing the same issue

**Comment by foolnotion** [comment]
What helped in my case was to limit openblas threads to 1 

```
os.environ['OPENBLAS_NUM_THREADS'] = '1'
```

**Comment by mfeurer** [comment]
The issue `"can't start new thread"` is not an error of Auto-sklearn, but a limitation of the enviroment you're running in. Such limitations can usually happen if you're on a shared cluster with strict resource limits or if your system is under heavy load. Could you please figure out whether one of these applies?

**Comment by foolnotion** [comment]
My system is a ryzen 5950X with 64gb of ram running NixOS. I have tried auto sklearn both in NixOS and in a series of containers (ubuntu 18,04, 20.04 and arch linux) and I also tried the docker images (the development one works but only with the "fix" I posted above). There are no resource limits (i.e., `ulimit` returns `unlimited`). There must be some other limitation or bug within the setup but I couldn't find it or spend a lot of time looiking for it.

**Comment by wmbjo** [comment]
I fixed error 'Result queue is empty' by upgrading to auto-sklearn 0.12.3 (originally on 0.12.1)
`sudo pip3 install auto-sklearn --upgrade`

OS: MacOS
Installation in a conda environment
Python version : 3.8
Auto-sklearn version: 0.12.1

**Comment by mfeurer** [comment]
@foolnotion does updating Auto-sklearn and the pynisher also work for you?

The fact that setting `OPENBLAS_NUM_THREADS=1` when using a system with 16 CPU cores works suggests that there's an implicit limit somewhere. I found some suggestions on what to look for (https://stackoverflow.com/questions/32283003/python-cant-start-new-thread-100-active-threads, https://superuser.com/questions/376532/does-gnu-linux-counts-processes-and-threads-together-when-i-limit-their-number, https://stackoverflow.com/questions/344203/maximum-number-of-threads-per-process-in-linux) but I'm not sure how much generic SO posts are helpful here.

Nevertheless, setting `OPENBLAS_NUM_THREADS=1` is general good practice when using Auto-sklearn, maybe we should put that into the docs anyway.
