### ISSUE TITLE
tmp_folder setting doesn't use tmp_folder parameter every time I build the Auto Sklearn Classifier

### ISSUE THREAD

**Issue by DexiongYung** [automl/auto-sklearn#1067]
## Describe the bug ##
I'm running my auto sklearn on a university computer, but I don't have permission access to anything outside my folder so I set the tmp_folder to 'tmp' folder inside of the folder I am running Python command line, but when I call fit it crashes because it still tries to make and access tmp folder in the root directory. This doesn't happen to me all the time, I ran yesterday using the same configuration and it worked.

## To Reproduce ##
1. Type python in Linux command line to start running python command line
2. Import necessary auto sklearn imports, specifically Auto Sklearn Classifier
3. Create variable
'model = autosklearn.classification.AutoSklearnClassifier(tmp_folder='tmp', output_folder='out', delete_output_folder_after_terminate=False)'
4. Check model variable via model.tmp_folder
5. Run fit and see the tmp folder is not the one you set

## Expected behavior ##
Should save all temporary files to specified temp folder.

## Actual behavior, stacktrace or logfile ##
Still creates a temporary folder in the root directory of Linux and attempts to use that

## Environment and installation: ##
Running on Linux
Pip Freeze produces:
auto-sklearn==0.12.1
click==7.1.2
cloudpickle==1.6.0
ConfigSpace==0.4.17
Cython==0.29.21
dask==2020.12.0
distributed==2020.12.0
docutils==0.16
HeapDict==1.0.1
joblib==1.0.0
lazy-import==0.2.2
liac-arff==2.5.0
msgpack==1.0.2
numpy==1.19.5
pandas==1.2.0
psutil==5.8.0
pynisher==0.6.3
pyparsing==2.4.7
pyrfr==0.8.0
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.3.1
scikit-learn==0.24.0
scipy==1.6.0
six==1.15.0
smac==0.13.1
sortedcontainers==2.3.0
tblib==1.7.0
threadpoolctl==2.1.0
toolz==0.11.1
tornado==6.1
zict==2.0.0

Please give details about your installation:

* Linux
* Using Python virtual env
* Running via Python command line
* Python version 3.8.5
* Auto-sklearn version: 0.12.1

**Comment by mfeurer** [comment]
Hey @DexiongYung thanks for reporting this issue. I assume the error is due to Auto-sklearn being executed from the root directory and `'tmp'` being interpreted relative to this. Could you please try using `os.path.expanduser('~/auto-sklearn-tmp')` for the tmp directory and `None` for the output directory?

**Comment by mfeurer** [comment]
Closing this as I posted a potential fix. Please reopen and paste the stacktrace if you have further questions or think the error message should be improved.
