### ISSUE TITLE
Saving best pipeline

### ISSUE THREAD

**Issue by dpn29** [automl/auto-sklearn#1080]
I'd like to train an auto-sklearn estimator on a dataset (X_train, y_train) to obtain good pipelines,  and then refit those pipelines to some other datasets (X_test_1, y_test_1), (X_test_2, y_test_2), ...

It would be important to do the refits on a different runtime, so I'd like to save the resulting pipelines after fitting to (X_train, y_train). Something like this:

`aml = AutoSklearnRegressor(...)`
`aml.fit(X_train, y_train)`

Now save the resulting pipelines to disk.

On a different runtime/computer, import the saved pipelines, then

`imported_aml.refit(X_test, y_test)`

Is there a away to do this? I could find it in the manual, so some help would be greatly appreciated.

**Comment by mfeurer** [comment]
Is [this](https://automl.github.io/auto-sklearn/master/manual.html#model-persistence) what you're looking for?
