### ISSUE TITLE
'Client' object has no attribute 'get_scheduler_info'

### ISSUE THREAD

**Issue by romeroland** [automl/auto-sklearn#1082]
## Describe the bug ##
I'm trying to replicate the example here:
https://automl.github.io/auto-sklearn/master/examples/20_basic/example_classification.html#sphx-glr-examples-20-basic-example-classification-py.

I've tried reinstalling libraries including smac

## To Reproduce ##
I installed auto-sklearn following the site instructions as of today with the prescribed versions of the dependencies.

I ran the example:
```Python
import sklearn.datasets
import sklearn.metrics

import autosklearn.classification

X, y = sklearn.datasets.load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = \
    sklearn.model_selection.train_test_split(X, y, random_state=1)

automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=120,
    per_run_time_limit=30,
    tmp_folder='/tmp/autosklearn_classification_example_tmp',
    output_folder='/tmp/autosklearn_classification_example_out',
)
automl.fit(X_train, y_train, dataset_name='breast_cancer')
```

## Expected behavior ##
Expected behavior is as follows in the example

## Actual behavior, stacktrace or logfile ##
![Screen Shot 2021-02-17 at 6 50 32 PM](https://user-images.githubusercontent.com/63232429/108194058-20b5b100-7151-11eb-93f2-4741cb49c4fb.png)
![Screen Shot 2021-02-17 at 6 50 55 PM](https://user-images.githubusercontent.com/63232429/108194065-21e6de00-7151-11eb-83d3-dcfd52422279.png)
![Screen Shot 2021-02-17 at 6 51 05 PM](https://user-images.githubusercontent.com/63232429/108194072-24493800-7151-11eb-83ff-685771774a0e.png)

## Environment and installation: ##

Please give details about your installation:

* OS: Ubuntu 18.04.3 LTS
* Is your installation in a virtual environment or conda environment? No.
* Python version: 3.7.3
* Auto-sklearn version: 0.12.1

**Comment by mfeurer** [comment]
Thanks a lot for reporting this. @franchuterivera did you ever observe this issue? @romeroland I just pushed Auto-sklearn 0.12.3 to pypi, could you please check with that?

**Comment by romeroland** [comment]
@mfeurer, Thanks. I'll check it out.

**Comment by romeroland** [comment]
@mfeurer Just updated and am no longer experiencing the same issue.
