### ISSUE TITLE
Issue importing auto-sklearn

### ISSUE THREAD

**Issue by diogoalvesderesende** [automl/auto-sklearn#1085]
Hey!

I am having issues importing auto-sklearn. You can find the script here: https://colab.research.google.com/drive/1H99sNUGsWtahpeO7Jl7ixbyq-wnWk7Ax?usp=sharing

And this is the error I get
```
IncorrectPackageVersionError              Traceback (most recent call last)
<ipython-input-3-bb85952a9dd8> in <module>()
----> 1 import autosklearn.classification

2 frames
/usr/local/lib/python3.6/dist-packages/autosklearn/util/dependencies.py in _verify_package(name, operation, version)
     60     if not check:
     61         raise IncorrectPackageVersionError(name, installed_version, operation,
---> 62                                            required_version)
     63 
     64 

IncorrectPackageVersionError: found 'scikit-learn' version 0.22.2.post1 but requires scikit-learn version >=0.24.0
```

Would you be able to help? Thanks in advance.

Diogo

**Comment by rabsr** [comment]
@diogoalvesderesende
For 'auto-sklearn' to work as intended, it has certain package requirements which are mentioned [here](https://github.com/automl/auto-sklearn/blob/master/requirements.txt). As error mentioned, scikit-learn version is not same as required. It requires version >=0.24, however 0.22.2.post1 is installed. Use `pip install "scikit-learn>=0.24"` to re-install scikit-learn.

**Comment by franchuterivera** [comment]
Hello, I think colab has pre-installed version of scikit learn and dask. Somehow during the pip installation, I do not see scikit learn recognized as requiring an update (although, from the error, msg one can see it is required).

I cannot reproduce this outside of collab, but @diogoalvesderesende,  change your code to be this, and it will work:

```
!apt-get install swig -y
!pip install Cython numpy
!pip install distributed
!pip install auto-sklearn==0.12.3
!pip install pydataset
```
Notice how the change is to use the latest version of autosklearn but also re-installing dask.distributed as the version previously installed in collab causes problems.


If you still have problems, kindly re-open this issue (as I said, this is something particular to collab which can be addressed as above)! Thanks for reporting in case other people struggle with this problem.

**Comment by diogoalvesderesende** [comment]
Hey, this is really helpful. Thank you!!

**Comment by joey1616** [comment]
> 您好，我认为colab已预装了scikit learning and dask版本。在安装pip的过程中，以某种方式，我看不到scikit学习被识别为需要更新（尽管从错误中可以看到msg是必需的）。
> 
> 我无法在collab之外重现此代码，但是@diogoalvesderesende，将代码更改为this，它将起作用：
> 
> ```
> !apt-get install swig -y
> !pip install Cython numpy
> !pip install distributed
> !pip install auto-sklearn==0.12.3
> !pip install pydataset
> ```
> 
> 请注意，更改是使用最新版本的autosklearn，还是重新安装dask.distributed，因为以前在collab中安装的版本会引起问题。
> 
> 如果您仍然有问题，请重新打开此问题（正如我所说，这是协作的特有问题，可以如上所述解决）！感谢您提供报告，以防其他人为这个问题而苦恼。



> Hello, I think colab has pre-installed version of scikit learn and dask. Somehow during the pip installation, I do not see scikit learn recognized as requiring an update (although, from the error, msg one can see it is required).
> 
> I cannot reproduce this outside of collab, but @diogoalvesderesende, change your code to be this, and it will work:
> 
> ```
> !apt-get install swig -y
> !pip install Cython numpy
> !pip install distributed
> !pip install auto-sklearn==0.12.3
> !pip install pydataset
> ```
> 
> Notice how the change is to use the latest version of autosklearn but also re-installing dask.distributed as the version previously installed in collab causes problems.
> 
> If you still have problems, kindly re-open this issue (as I said, this is something particular to collab which can be addressed as above)! Thanks for reporting in case other people struggle with this problem.

Hello, I meet the same question. And `!apt-get install swig -y
!pip install Cython numpy
!pip install distributed
!pip install auto-sklearn==0.12.3
!pip install pydataset`
looks like not work.

**Comment by Mr-Optimistic** [comment]
I did a pip install, and then did a runtime restart. autosklearn was imported successully

**Comment by TTigre** [comment]
> get install swig -y
> !pip install Cython numpy
> !pip install distributed
> !pip install auto-sklearn==0.12.3
> !pip install pydataset

As of today it does not work to me
Please reopen the issue
It seems it may be not working even outside colab

**Comment by REPsabah-for-science** [comment]
please i have the same issue
