### ISSUE TITLE
MyDummyClassifer/MyDummyRegressor fails when printed

### ISSUE THREAD

**Issue by rabsr** [automl/auto-sklearn#1119]
## Describe the bug ##
When all the pipelines failed due to any reason, MyDummyClassifier is selected as best model. When using show_models api, execution fails.

## To Reproduce ##
```
import sklearn.datasets
import sklearn.metrics
import autosklearn.classification
X, y = sklearn.datasets.load_breast_cancer(return_X_y=True)
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=30,
    per_run_time_limit=1,
    tmp_folder='/tmp/autosklearn_classification_example_tmp',
    output_folder='/tmp/autosklearn_classification_example_out',
)
automl.fit(X, y, dataset_name='breast_cancer')
print(automl.show_models())
```

## Actual behavior, stacktrace or logfile ##
```
Traceback (most recent call last):
  File "example_classification.py", line 40, in <module>
    print(automl.show_models())
  File "automl/lib/python3.7/site-packages/autosklearn/estimators.py", line 482, in show_models
    return self.automl_.show_models()
  File "automl/lib/python3.7/site-packages/autosklearn/automl.py", line 1355, in show_models
    sio.write("(%f, %s),\n" % (weight, model))
  File "automl/lib/python3.7/site-packages/sklearn/base.py", line 260, in __repr__
    repr_ = pp.pformat(self)
  File "automl/lib/python3.7/site-packages/python3.7/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "automl/lib/python3.7/site-packages/python3.7/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "automl/lib/python3.7/site-packages/python3.7/pprint.py", line 393, in _repr
    self._depth, level)
  File "automl/lib/python3.7/site-packages/sklearn/utils/_pprint.py", line 181, in format
    changed_only=self._changed_only)
  File "automl/lib/python3.7/site-packages/sklearn/utils/_pprint.py", line 425, in _safe_repr
    params = _changed_params(object)
  File "automl/lib/python3.7/site-packages/sklearn/utils/_pprint.py", line 91, in _changed_params
    params = estimator.get_params(deep=False)
  File "automl/lib/python3.7/site-packages/sklearn/base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'MyDummyClassifier' object has no attribute 'dataset_properties'
```

Looks like change [here](https://github.com/automl/auto-sklearn/pull/1077/commits/6627a056e299b2d6221ae179d1b62c20fe4fec24#diff-a6fbf33f3db0542c49821835f32b83a36223630e27982aeb644bf476ca6b42c3L33) is causing the issue. Please help me understand why new params are added [here](https://github.com/automl/auto-sklearn/pull/1077/commits/6627a056e299b2d6221ae179d1b62c20fe4fec24#diff-a6fbf33f3db0542c49821835f32b83a36223630e27982aeb644bf476ca6b42c3L33)?
Let me know if new added params are required. I can submit a fix based on that.

## Environment and installation: ##

Please give details about your installation:

* Is your installation in a virtual environment or conda environment? - Virtual env
* Python version - 3.7.3
* Auto-sklearn version - development branch

**Comment by franchuterivera** [comment]
Hello, thanks a lot for your bringing this to our attention.

We have seen this in our internal testing and created #1114 to address this. When this PR is merged, I will also close this issues.

**Comment by ricoms** [comment]
Hello, this problem is still happening on version `0.12.5`, in which version is it available?

**Comment by rabsr** [comment]
@ricoms This is fixed and added in [0.12.6 release notes](https://github.com/automl/auto-sklearn/releases/tag/v0.12.6). But it looks like package is not published yet. I am unable to download this version

**Comment by ricoms** [comment]
yes, I am also unable to download this version too

**Comment by mfeurer** [comment]
Sorry @ricoms and @rabsr, I just forgot to upload to pypi. I just fixed that now.

**Comment by ricoms** [comment]
no need for apologies @mfeurer . You are doing a great job on auto-sklearn! Thanks a lot for all your work!
