### ISSUE TITLE
install fails on Ubuntu when pip install ConfigSpace, when pip install auto-sklearn

### ISSUE THREAD

**Issue by stock90975** [automl/auto-sklearn#1122]
When I pip install auto-sklearn (in virtual env), there may be an error when ConfigSpace is being pip installed, during (as documented):

`curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install`

the error is something to the effect of "Python.h not found"

I found that this is because python3-dev is not installed.

I suggest to amend the current installation documentation for Ubuntu installation which is only: 
`sudo apt-get install build-essential swig`

to also add:
`sudo apt install python3-dev`
to avoid this error

**Comment by mfeurer** [comment]
Thanks a lot for this suggestion. I just fixed this via c4bb832a2de42c1cf9eda426ad3748642e8be96e and it'll be in the docs after the next release.
