### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by BastianZim** [automl/auto-sklearn#1131]
The current version on PyPI is 0.12.5 whereas the newest GitHub release is 0.12.6. 
Just wanted to check if that's on purpose or if that will get updated later?

**Comment by mfeurer** [comment]
Thanks for letting me know, I must have forgotten that. 

BTW is Auto-sklearn on conda-forge fully functional?

**Comment by BastianZim** [comment]
No worries. Thanks for uploading.

Yes, it should be the exact same as the PyPI version. 
If you want to be on the absolutely safe side, we can also run your tests directly in the feedstock. For that, we would need to switch to GitHub as a source though. I didn't use that initially because you mentioned that you not always release through GitHub and that PyPI might be the safer source. If that changed, just let me know and I'll switch it.

**Comment by mfeurer** [comment]
> Yes, it should be the exact same as the PyPI version.

Sorry, I only asked because I wasn't sure. So we should update the docs about this I guess. I just opened #1132 to remind us of this.

**Comment by BastianZim** [comment]
Yes of course, and happy to answer any other question you might have. What I meant was just that the conda-forge package mimics the source in terms of functionality so any difference should only be in available dependencies (If one of them isn't updated on conda-forge). Sorry if that wasn't clear in my reply, sometimes it's difficult through text. :smile:

And yes, documenting it is probably a good idea as you already recommend a conda environment, from what I can see (Might also be a good idea to document it for the other packages that we brought to conda-forge?). Let me know if you need any additional info here.
