### ISSUE TITLE
Document installation via conda-forge

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#1132]
As explained [here](https://github.com/automl/auto-sklearn/issues/1131#issuecomment-823423641), Auto-sklearn can be installed via conda-forge. This should be reflected in the installation instruction.

**Comment by BastianZim** [comment]
Feedstock: https://github.com/conda-forge/auto-sklearn-feedstock

Package: https://anaconda.org/conda-forge/auto-sklearn

**Comment by satyam-jha** [comment]
i added conda installation in docs can you please check this that its ok ?
https://github.com/automl/auto-sklearn/pull/1144

**Comment by eddiebergman** [comment]
Closed with PR #1144
