### ISSUE TITLE
Give a warning if the final ensemble contains only the dummy model

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#1146]
As this might be interesting to the user. In addition, we could also print warning while running Auto-sklearn if all models so far didn't succeed.

**Comment by eddiebergman** [comment]
@mfeurer allo,

There is already a warning sent to the logger ([here](https://github.com/automl/auto-sklearn/blob/52dd9a1747152d5494812d81dd32b7519ba790e5/autosklearn/automl.py#L1308)), did you mean a simple [warn](https://docs.python.org/3/library/warnings.html#warnings.warn) raised to the user as well?

This would be easy to implement upon any call to `_load_models`, raising the warning along with the logger warning. My guess is you mean upon the end of `fit()` to also check if only a single model can be loaded?

**Comment by mfeurer** [comment]
> There is already a warning sent to the logger (here), did you mean a simple warn raised to the user as well?

This is only a warning if the ensemble file doesn't exist. It does not check for the content of the ensemble.

> My guess is you mean upon the end of fit() to also check if only the dummy model can be loaded?

Yes, exactly that. Also maybe a giving further information on why the model fitting failed.

**Comment by eddiebergman** [comment]
This has been grouped together with issue #1228
