### ISSUE TITLE
Access output after each step of the pipeline

### ISSUE THREAD

**Issue by rabsr** [automl/auto-sklearn#1148]
I want to access the output after each step for the best pipeline. In our use case, currently we are using ensemble size as 1. I can't find any API for this purpose. Is it possible to get these outputs?

**Comment by franchuterivera** [comment]
Hello, just to understand better the request: Do you mean the output of each step of the pipeline? Meaning, the output of data-preprocessing, the output of the balancing, and every other step from [here](https://github.com/automl/auto-sklearn/blob/52dd9a1747152d5494812d81dd32b7519ba790e5/autosklearn/pipeline/classification.py#L288)?

If so, there is currently no API to do so...yet as we are compatible with scikit learn API one could follow directions like this [one](https://stackoverflow.com/questions/54332654/how-to-analyse-the-intermediate-steps-of-sklearn-pipeline).

**Comment by rabsr** [comment]
@franchuterivera Yes, your understanding is correct. I am looking for the same. Thanks for pointing the approach which I can use. 

Would it be in your interest to add this capability? Let me know.

**Comment by mfeurer** [comment]
> Would it be in your interest to add this capability? Let me know.

How would this look like? Would this simplify the usage of the pipeline object by providing access to intermediate steps? If yes, I believe this feature should be added to scikit-learn itself.

**Comment by eddiebergman** [comment]
This can be part of issue #1298 which is in general about improving model and pipeline access so I am closing this.
