### ISSUE TITLE
Auto SkLearn Classifier is Running infinite time on some datasets.

### ISSUE THREAD

**Issue by shabir1** [automl/auto-sklearn#1153]
## Auto SkLearn Classifier is Running infinite time on some datasets. ##
I have some examples of datasets that are running infinite time. I set the time limit of 1800 seconds. It shows the warning message that no model is better than the dummy, After that there is no log and run infinite time. (Dataset has only 700 rows and 5 columns)

## Environment and installation: ##
* OS: **Ubuntu**
* Python running in virtual environment
* Python version **3.8.5**
* Auto-sklearn version **0.12.6**
* Use Trainer as end point

**Comment by franchuterivera** [comment]
Hello, thanks for reporting this problem.

With a log file we will be able to help further, so let us try to create one. I assume you have something like [this](https://automl.github.io/auto-sklearn/master/examples/20_basic/example_classification.html#sphx-glr-examples-20-basic-example-classification-py) taken from the classification example:
```
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=120,
    per_run_time_limit=30,
    tmp_folder='/tmp/autosklearn_classification_example_tmp',
    output_folder='/tmp/autosklearn_classification_example_out',
)
``` 

If you check the documentation [here](https://automl.github.io/auto-sklearn/master/api.html) there is a flag we can enable to preserve the temporal directory where the log file resides (namely `delete_tmp_folder_after_terminate=False`). Could you change the above command to be:
```
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=120,
    per_run_time_limit=30,
    tmp_folder='/tmp/autosklearn_classification_example_tmp',
    output_folder='/tmp/autosklearn_classification_example_out',
    delete_tmp_folder_after_terminate=False
)
``` 
Then, inside of `'/tmp/autosklearn_classification_example_tmp` you will file a log file. Can you share this log file with us, or maybe even, it can give you an intuition on why your run does not finish.
