### ISSUE TITLE
Import Error scipy.optimize._shgo_lib.sobol_seq when import autosklearn.classification

### ISSUE THREAD

**Issue by KaroPy** [automl/auto-sklearn#1162]
Hello, 
I installed auto-sklearn in an virutal enviroment using Python 3.8.5.  i wanted to execute the basic example from the docs, but when i try to import autosklearn.classification I get the error 'ModuleNotFoundError: No module named 'scipy.optimize._shgo_lib.sobol_seq' which is imported in the file: lib/python3.8/site-packages/smac/initial_design/sobol_design.py in line 3 from scipy.optimize._shgo_lib.sobol_seq import Sobol

## Environment and installation: ##
OS: Debian Buster
Python 3.8.5
Scipy version is 1.7.0

## To Reproduce ##
1. create virtual environment with python 3.8.5
> python3 -m venv venv_automl
2. Activate it
> source venv_automl/bin/activate
3. Install auto-sklearn
> curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install

> pip3 install auto-sklearn
4. Open python script and import autosklearn.classification
5. Above Module Error occurs

Maybe someone can help?

**Comment by franchuterivera** [comment]
Hello, thanks a lot for reporting.

There is a new scipy version1.7.0 which is not yet supported by SMAC, one of the packages we depend on.

As a workaround, while this issue is being resolved, could you please try installing an older version of scipy?

```
pip install 'scipy>=0.14.1,<1.7.0'
```

**Comment by mfeurer** [comment]
Fixed in the latest release 0.12.7.
