### ISSUE TITLE
API for regression?

### ISSUE THREAD

**Issue by linlizhu** [automl/auto-sklearn#117]
Hi, auto-sklearn team,
I am very interested in your project. The classification tool runs very well on my dataset. But I was wondering is there an API for regression tasks in auto-sklearn? If not, would you let me know the strategy of implement it?
Thank you so much!

Linli

**Comment by mfeurer** [comment]
Hi Linli,

regression is available in the development branch. Documentation is available [here](http://automl.github.io/auto-sklearn/dev/api.html#autosklearn.regression.AutoSklearnRegressor). Let us know whether it works for you.

Matthias

**Comment by SMeo** [comment]
Hi Matthias,

any idea on when AutoSklearnRegressor will be merged into main branch? Are there any known serious issues with it for now?

**Comment by mfeurer** [comment]
There are no known issues with it. I'm right now on a workshop, the merge can maybe happen within the next 2-4 weeks.

**Comment by SMeo** [comment]
Perfect. Thanks

**Comment by mfeurer** [comment]
Will be released on pypi this afternoon.
