### ISSUE TITLE
auto-sklearn is depending on GPLv3 imports

### ISSUE THREAD

**Issue by austinkeller** [automl/auto-sklearn#1176]
## Describe the bug ##
auto-sklearn is currently in violation of GPLv3 because it depends on `smac`, which itself is in violation of GPLv3 for importing the GPLv3 package `lazy-import` (see https://github.com/automl/SMAC3/issues/725)

## To Reproduce ##
```
pip install auto-sklearn
pip freeze | grep lazy-import
```

## Expected behavior ##
No GPLv3 packages should be imported unless auto-sklearn switches its license to GPLv3 (which probably we don't want)

## Actual behavior, stacktrace or logfile ##
auto-sklearn has been GPLv3'd

## Environment and installation: ##

N/A

**Comment by mfeurer** [comment]
Thanks a lot for posting this issue. This is on our TODO list and we're working on a fix. There should be an updated version of SMAC3 available by Friday evening.

**Comment by rabsr** [comment]
@mfeurer Based on PR https://github.com/automl/SMAC3/pull/744 for new release of SMAC3, the newer version for SMAC which solves for license issue wont be compatible with auto-sklearn. Are there any plans to release new version of auto-sklearn for SMAC latest version compatibility?

**Comment by mfeurer** [comment]
Yes, there are. This incompatible change is also to safe Auto-sklearn from not accidentally becoming uncompatible to SMAC. Unfortunately, our milestones have moved at least a week back, but hopefully we get to relieving this next week.

**Comment by mfeurer** [comment]
Thank you very much for your patience - we've just pushed auto-sklearn 0.13 to pypi - it relies on SMAC 0.14 and does no longer suffer from GPL creep.
