### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#1193]
Currently, our github action for building docker containers is broken: https://github.com/automl/auto-sklearn/runs/3179219504

The issue is most likely that the container uses Ubuntu 18.04, which uses Python 3.6, which we don't support any more.

**Comment by eddiebergman** [comment]
Yes that seems to be the issue, the `scipy 1.7` requires `Python 3.7` or greater, which was introduced in `scipy 1.6` ([release notes](https://docs.scipy.org/doc/scipy/release.1.6.0.html))

It appears from the logs that `Ubuntu 18.04` ships with `python 3.6` so the two solutions I see are:
* To update the dockerfile to use `ubuntu:20.04` or `ubuntu:latest`, which are [equivalent](https://hub.docker.com/_/ubuntu) for now 
* Bundle `pyenv` or manually install `python 3.7` or higher

I'll create a short PR with the first option (`ubuntu:20:04`) as it's what we test against, it's simpler and probably a good idea to have it running on the updated environment.

**Comment by mfeurer** [comment]
That sounds like a good plan, we should probably update all our CI scripts to use Ubuntu 20.04.

**Comment by eddiebergman** [comment]
Addressed in PR #1198

**Comment by mfeurer** [comment]
This can be closed I guess?
