### ISSUE TITLE
Preprocessors are only tested on their default configurations

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1199]
Currently, it seems that data-preprocessors and feature-processors are only tested on their default parameters.
For example, the [tests](https://github.com/automl/auto-sklearn/blob/3d53cd9b5011258c4fdcce9d02e252d0248e5f1d/test/test_pipeline/components/feature_preprocessing/test_select_percentile_classification.py#L13) for `SelectPercentileClassificaiton` only operate on the default hyper parameters.

This could potentially allow unknown bugs to crash or even silently go unnoticed during pipeline exploration.

As the configuration spaces for the pipeline steps often have non-discrete parameters and constraints between parameters, this raises some question about how to effectively test different configurations.

Some possible solutions:
* Randomly sample from valid configurations provided by ConfigurationSpace ([API](https://automl.github.io/ConfigSpace/master/API-Doc.html#ConfigSpace.configuration_space.ConfigurationSpace.sample_configuration)) with a fixed seed. 
    * This isn't garunteed to cover all use cases but gives some more security over the current tests.
* Discretize numeric values into `[low, mid, high]` and do a test over all combinations. 
    * This would produce a noticable increase in testing time required

**Comment by mfeurer** [comment]
Hey, I'm wondering if this function and it's callers do what you're looking for https://github.com/automl/auto-sklearn/blob/4597152e3a60cd6f6e32719a3bef26e13951b102/test/test_pipeline/test_classification.py#L297 ?

**Comment by eddiebergman** [comment]
This does sample multiple configurations but it's for the entire pipeline rather than individual components. I would imagine most of the use cases are covered but it doesn't explicitly cover them.

**Comment by mfeurer** [comment]
That's correct - but I think it also holds for the classifiers and regressors, doesn't it? However, I'm not sure if we can and want to afford more tests on this end?

**Comment by eddiebergman** [comment]
I agree, it's unlikely to be an issue unless there are invalid configurations but they are probably covered through all the other tests. I will close this for now then if you are happy with that?

**Comment by mfeurer** [comment]
I'm fine with that.
