### ISSUE TITLE
Training example error - "auto-sklearn does not implement get_params()"

### ISSUE THREAD

**Issue by crawfordcomeaux** [automl/auto-sklearn#120]
I'm running auto-sklearn in a virtual environment in [Bash on Ubuntu on Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/about) with python 2.7.12 x64. 

The call to `automl.fit(X_train, y_train)` in the second-to-last line of the example in the docs led to this error & the final score was 0.976300013941. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/craw/.venvs/auto-sklearn/local/lib/python2.7/site-packages/sklearn/base.py", line 276, in __repr__
    return '%s(%s)' % (class_name, _pprint(self.get_params(deep=False),
  File "/home/craw/.venvs/auto-sklearn/local/lib/python2.7/site-packages/autosklearn/automl.py", line 584, in get_params
    raise NotImplementedError('auto-sklearn does not implement '
NotImplementedError: auto-sklearn does not implement get_params() because it is not intended to be optimized.
```

```
$ pip freeze
auto-sklearn==0.0.1
ConfigArgParse==0.11.0
ConfigSpace==0.2.1
Cython==0.24.1
docutils==0.12
funcsigs==1.0.2
joblib==0.10.2
liac-arff==2.1.0
linecache2==1.0.0
lockfile==0.12.2
mock==2.0.0
nose==1.3.7
numpy==1.11.1
pandas==0.18.1
pbr==1.10.0
psutil==4.3.1
pynisher==0.4.2
pyparsing==2.1.8
pyrfr==0.2.0
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
scikit-learn==0.17.1
scipy==0.18.0
six==1.10.0
smac==0.1.0
traceback2==1.4.0
unittest2==1.1.0
xgboost==0.4a30
```

**Comment by mfeurer** [comment]
Can you please paste the whole output of auto-sklearn?

**Comment by crawfordcomeaux** [comment]
[auto-sklearn_error_output.txt](https://github.com/automl/auto-sklearn/files/465315/auto-sklearn_error_output.txt)

**Comment by mfeurer** [comment]
Sorry for not getting back to this earlier. It seems like ipython tries to print the model which doesn't work because we're trying to use the default sklearn function for that and don't implement `get_params` (already fixed in the development branch). This error does not effect model building and you should be still able to use the model as normal. Thanks for reporting this.

**Comment by mfeurer** [comment]
I just pushed version 0.1 to pypi and will close this now. Please reopen this issue if the problem persists.
