### ISSUE TITLE
Test timeout on `test_configurations_signed_data` with after merge (#977)

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1202]
After merging (#977) which makes data_preprocessing configurable, one of the test runners timed out ([log](https://github.com/automl/auto-sklearn/runs/3219257169#step:8:1388)) after on testing configuration spaces.

@rabsr When you have a chance can you look at the [test](https://github.com/automl/auto-sklearn/blob/master/test/test_pipeline/test_classification.py#L219) and the log outputs? It is possibly unrelated and was not directly caught in your PR tests but was caught after the merge. I noticed in the commits ([example](https://github.com/automl/auto-sklearn/pull/977/commits/96fee046eb1235ed716c48ebd2237e5b9b8d85fb ))  that you edited the configuration space slightly so my hunch is it's probably related. If you think it is or not, please let me know, it would be kindly appreciated!

**Comment by rabsr** [comment]
@eddiebergman I have validated the mentioned test case. I don't find any issue with it. The test case passed successfully in my local setup. Can you once re-trigger the workflow to validate if issue still persists?

**Comment by eddiebergman** [comment]
Closing this as it seems to have not re-occured, it could have been a Github runner issue as other tests sometimes time out
