### ISSUE TITLE
Occasional test failure for `test_module_idempotent`

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1209]
The tests occasionaly fail when testing `GradientBoosting`, specifically the `test_module_idempotent` as seen [here ](https://github.com/automl/auto-sklearn/runs/3260866212#step:9:1531).

<details>
<summary>Failure log</summary>
<br>
_____________ GradientBoostingComponentTest.test_module_idempotent _____________

self = <test_pipeline.components.classification.test_gradient_boosting.GradientBoostingComponentTest testMethod=test_module_idempotent>

    def test_module_idempotent(self):
    
        if self.__class__ == BaseClassificationComponentTest:
            return
    
        def check_classifier(cls):
            X = np.array([[0, 0], [0, 1], [1, 0], [1, 1],
                          [0, 0], [0, 1], [1, 0], [1, 1],
                          [0, 0], [0, 1], [1, 0], [1, 1],
                          [0, 0], [0, 1], [1, 0], [1, 1]])
            y = np.array([0, 1, 1, 0,
                          0, 1, 1, 0,
                          0, 1, 1, 0,
                          0, 1, 1, 0])
            params = []
    
            for i in range(2):
                try:
                    classifier.fit(X, y)
                except ValueError as e:
                    if (
                        isinstance(e.args[0], str)
                    ) and (
                        "Numerical problems in QDA" in e.args[0]
                    ):
                        continue
                    elif (
                        "BaseClassifier in AdaBoostClassifier ensemble is "
                        "worse than random, ensemble can not be fit." in e.args[0]
                    ):
                        continue
                    else:
                        raise e
                except UnboundLocalError as e:
                    if "local variable 'raw_predictions_val' referenced before assignment" in \
                            e.args[0]:
                        continue
    
                p = classifier.estimator.get_params()
                if 'random_state' in p:
                    del p['random_state']
                if 'base_estimator' in p:
                    del p['base_estimator']
                for ignore_hp in self.res.get('ignore_hps', []):
                    del p[ignore_hp]
                params.append(p)
    
                if i > 0:
                    self.assertEqual(
                        params[-1],
                        params[0],
                    )
    
        classifier = self.module
        configuration_space = classifier.get_hyperparameter_search_space()
        default = configuration_space.get_default_configuration()
        classifier = classifier(random_state=np.random.RandomState(1),
                                **{hp_name: default[hp_name] for hp_name in
                                   default if default[hp_name] is not None})
        check_classifier(classifier)
    
        for i in range(5):
            classifier = self.module
            config = configuration_space.sample_configuration()
            classifier = classifier(random_state=np.random.RandomState(1),
                                    **{hp_name: config[hp_name] for hp_name in
                                       config if config[hp_name] is not None})
>           check_classifier(classifier)

/home/runner/work/auto-sklearn/auto-sklearn/test/test_pipeline/components/classification/test_base.py:290: 

/home/runner/work/auto-sklearn/auto-sklearn/test/test_pipeline/components/classification/test_base.py:271: in check_classifier
    self.assertEqual(
E   AssertionError: {'cat[192 chars]er': 128, 'max_leaf_nodes': 202, 'min_samples_[161 chars]True} != {'cat[192 chars]er': 512, 'max_leaf_nodes': 202, 'min_samples_[161 chars]True}
E     {'categorical_features': None,
E      'early_stopping': True,
E      'l2_regularization': 1.8340340346818956e-05,
E      'learning_rate': 0.05749038268034438,
E      'loss': 'auto',
E      'max_bins': 255,
E      'max_depth': None,
E   -  'max_iter': 128,
E   ?                -
E   
E   +  'max_iter': 512,
E   ?              +
E   
E      'max_leaf_nodes': 202,
E      'min_samples_leaf': 2,
E      'monotonic_cst': None,
E      'n_iter_no_change': 2,
E      'scoring': 'loss',
E      'tol': 1e-07,
E      'validation_fraction': 0.39328363642167863,
E      'verbose': 0,
E      'warm_start': True}
</details>

**Comment by mfeurer** [comment]
Fixed via #1234
