### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by zuliani99** [automl/auto-sklearn#1215]
## Describe the bug ##
I was running autosklearn for a hour on the dataframe kin8nm with id: 189 downloaded from OpenML and then autosklearn stops with this exception **_pickle.UnpicklingError: pickle data was truncated**

## To Reproduce ##
1. Download the dataframe 189 with the OpenML API
2. Apply train_test_split
3. Create the automl instance:
```
automl = autosklearn.regression.AutoSklearnRegressor(
          time_left_for_this_task=timelife*60,
          per_run_time_limit=30,
          memory_limit=psutil.virtual_memory().available,
          n_jobs=-1,
          resampling_strategy_arguments = {'cv': 10}
)
```
Timelife in this case i-s equal to 60

4. Run the fit: ```automl.fit(X_train, y_train)```

## Actual behavior, stacktrace or logfile ##
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
```

## Environment and installation: ##

Please give details about your installation:

* OS: Ubuntu 20.04.2 LTS
* Is your installation in a virtual environment or conda environment? Virtual environment
* Python version: 3.8.10 64-bit
* Auto-sklearn version: 0.12.6

**Comment by eddiebergman** [comment]
Hi @zuliani99,

Thanks for the bug report, the issue seems mostly related to an error in process spawning rather than any pickling that actually happens within AutoSklearn.

A few questions:
* Could you try updating to version 0.13.0 or even the development version? I will try this out myself
* Does this happen early on into the run or late? I will try with a low amount of time first
* As a ballpark, how much memory is `psutil.virtual_memory().available` returning vs how much is the python process using during runtime? If you only have a low amount of memory available on the machine running this program and then you allow autosklearn to use it all then it may cause issues:
    * A quick look at [virtual memory](https://psutil.readthedocs.io/en/latest/index.html?highlight=virtual_memory#psutil.virtual_memory) seems to indicate this " ...is supposed to be used to monitor actual memory usage in a cross platform fashion."
    * I will also try reproduce the crash with the dataset and specify all memory available. If this is a memory issue however, I will probably not be able to reproduce it given the memory I have available on this machine.

I would guess this is a memory issue when spawning a new process which happens within AutoSklearn, as indicated by `pickle data was truncated` in the log. While the memory limit argument in `AutoSklearn` does seem to indicate that you could just specify all your available memory left, in principle I would advise against it and maybe try with 75% at first.

Another read of possible causes of error indicates that dataset downloading can sometimes be corrupted, so you could try:
* Clear the cache for that dataset in `~/.openml/cache`

**Comment by zuliani99** [comment]
First of all, thank you so much for helping me.
1. When I upgrade AutoSklearn to the lastest version I get some dependencies error related to autogluon which required scipy<1.7,>=1.5.4. I'm doing a benchmark on five AutoML packages (AutoSklearn, H2O, MLJAR, TPOT and AutoGluon)
2. These exception happends during the fit of the model
3. So it seems like the problem is that autosklearn use alse the memory assigned to the actual execution of the application
4. Whenever I decide to run autsklearn I check if the dataframe is present on my local machine, if not I download it using fetch_openml with these options: ```X, y = fetch_openml(data_id=row['did'], as_frame=True, return_X_y=True, cache=False)```

**Comment by eddiebergman** [comment]
* Could you run the following in the environment you use autosklearn to know how much memory is available.
    ```bash
    python -c "import psutil; print(psutil.virtual_memory.available)"
    ``` 
* Does this happen with only this dataset? If yes, then could you provide the other datasets you use. [It doesn't seem like its so big ](https://www.openml.org/d/189) so I would be surprised if this was the only dataset that was causing issues for you.
* If you run `ls ~/.openml/cache/org/openml/www/datasets` you will be able to see if dataset 189 is there. If it is, try to delete it and restart your run, if the issue happens again then it's not a corrupted download and we can rule that out.

There were no major changes to multiprocessing or pickling with `autosklearn` to 0.13.0 so updating to a new version is unlikely to be the fix. However, for benchmarking in general, I'd advise you set up your benchmarking to run each library in it's own environment to avoid these dependancy issues. You could end up running a very old version of a library vs a new version of another which invalidates fair results.

*(I've had the same problem before with benchmarking autoML libraries)*

**Comment by zuliani99** [comment]
```
>>> import psutil
>>> print(psutil.virtual_memory().available)
13400109056
>>> 
```

- No it happens also with other dataframe I don't remember which ones 
- If I run `ls ~/.openml/cache/org/openml/www/datasets` the bash tells me that `No such file or directory`

Well but how can I creare multiple environments each one for an AutoML algorithms. Could you tell me please I really appreciate if you help me on this topic

**Comment by eddiebergman** [comment]
It looks like `psutil` returns **bytes** and not **mb**, which is used by autosklearn. I am assuming the pickling error is related to autosklearn thinking it has way more memeory then exists. Please let me know next time you have a chance if this fixes your issue!

Regarding benchmarking:
    * If you're not familiar with python virtual environments, definitely [look them up](https://docs.python.org/3/tutorial/venv.html). Almost every python project should use it's own virtual environment to prevent package conflicts. This uses the same base Python interpreter (located by `$ which python`)
    * If you need different versions of Python available, e.g. onep roject only supports Python 3.5 but another needs Python 3.6, then I use [pyenv](https://github.com/pyenv/pyenv).
    * In general these questions are unrelated to autosklearn itself but I'm happy give these pointers. However this should be enough information to get you going and googling in the right direction.

**Comment by mfeurer** [comment]
Two more comments:

* the memory limit is per job. So if you have set `n_jobs=-1` you need to divide the memory limit by the number of cores you have on your system.
* It might be easier for you to use the existing AutoML benchmark, which integrates the AutoML systems you aim to compare: https://openml.github.io/automlbenchmark/

**Comment by zuliani99** [comment]
Yes I know the repository you linked, the fact is that I am doing my automl benchmark which is also the project for my CS thesis so I have to do it all by myself

**Comment by zuliani99** [comment]
Well @mfeurer I've implemented the division by the number of cores of my system, the problem is that I get an old issue open by me https://github.com/automl/auto-sklearn/issues/1120. In this case I use the ```bigquery-geotab-intersection-congestion```  data frame of Kaggle (here is the link: https://www.kaggle.com/c/bigquery-geotab-intersection-congestion/data).

But if I remove the division everything works fine and the execution of AutoSklearn don't crash.

**Comment by mfeurer** [comment]
Okay, so if you get #1120 you don't have enough memory on your machine to run with that many cores on that dataset. This is then most likely the issue you're observing. How much memory do you have in total and how many cores are you using?

**Comment by zuliani99** [comment]
In my machine I have 8 cores and 16 GBs of RAM, I mean it's strange that even with these specifics I'm still having problem to run autosklearn with some dataframes

**Comment by mfeurer** [comment]
I believe I need to clarify a bit how Auto-sklearn allocates resources: Auto-sklearn will start as many jobs as requested, in your case 8. It will then allow each of these jobs to use `memory_limit` memory. If you pass the amount of main memory in (as written in your first post) this can lead to over-allocation and over usage of memory. If you pass in 2GB this might be too little for the dataset you're using. Typical ratios of n_cores to memory are 1/4 or 1/6; therefore, on your machine you probably want to use 4 cores only.

**Comment by zuliani99** [comment]
So the best configuration of the hyperparameters regarding cores and RAM is setting n_cores to `(total_memory / 4)` and with this number devide the memory_limit hyperparameter.

I mean like so?

```
jobs = int(int(int(psutil.virtual_memory().total * 1e-9))/4)

automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=timelife*60,
    per_run_time_limit=30,
    memory_limit=int(int(psutil.virtual_memory().available * 1e-6) * 0.75)/jobs
    n_jobs=jobs
    resampling_strategy_arguments = {'cv': 10}
)
```

**Comment by mfeurer** [comment]
In your case yes. In general I'd go the other way around and see how many cores I want to run on, and then make sure each of them has sufficient memory (4-6GB).

**Comment by zuliani99** [comment]
So there is no configuration that maximizes the performance of the algorithm with any kind of amount of RAM and cores. It depends on the weight of the dataframe and the other things we mentioned earlier.
The configuration I wrote is optimal for the components I have on my PC but perhaps it is not suitable for other amounts of ram and cores. Or maybe on average the calculation that you recommended turns out to be better for the largest amount of setup?

**Comment by mfeurer** [comment]
Unfortunately I'm not aware on a way to compute the optimal amount of RAM per core for a specific dataset. As long as datasets are small it doesn't really matter. However, as you realized, when they get larger it has an impact and figuring out how much to use automatically would be great, but is so far beyond the scope of Auto-sklearn.
