### ISSUE TITLE
How to resume training

### ISSUE THREAD

**Issue by ChristianRako** [automl/auto-sklearn#1216]
Hi !

Currently, is it possibe with auto-sklearn to pause the model fitting, get the best models, and then, resume the fitting ?

It was possible to do it with the shared_mode argument, but it no longer exists, so what is the new solution ?

**Comment by eddiebergman** [comment]
Hi @ChristianRako,

No this is not possible at the moment but is also a feature I was looking for quite a while back. Currently, when you call fit():
* AutoSklearn uses a library called SMAC to start searching for candidate models
* fit_ensemble is then called to take these candidate models and find the best ensemble it can.
* This ensemble is then used for predictions

There is currently no way to resume this searching for candidate models while using the prior information gained during the original fitting procedure. The method [refit](https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.refit) will only refit the candidate models in the ensemble to new data but will not recreate the ensemble or look for any new candidate models.

I would also like to have this feature in the future and it is on our radar so for now I am afraid this is not possible. I also have no alternatives for you at the moment, apologies.
