### ISSUE TITLE
Occasional doc build failure  `example_debug_logging.py`

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1230]
Occasional issue building docs with `example_single_configuration.py`

Error:
```
generating gallery for examples/40_advanced... [ 50%] example_debug_logging.py

Warning, treated as error:
/home/runner/work/auto-sklearn/auto-sklearn/examples/40_advanced/example_single_configuration.py failed to execute correctly: Traceback (most recent call last):
  File "/home/runner/work/auto-sklearn/auto-sklearn/examples/40_advanced/example_single_configuration.py", line 77, in <module>
    print(pipeline.named_steps)
AttributeError: 'NoneType' object has no attribute 'named_steps'
```

[Test log](https://github.com/automl/auto-sklearn/pull/1229/checks?check_run_id=3414079944)

**Comment by yashrajput0508** [comment]
This issue is opened, can i contribute

**Comment by eddiebergman** [comment]
Hi @yashrajput0508,

It seems this failure hasn't been risen in quite a while, I will close this issue but if you would like to contribute on any other issue, it would be greatly appreciated, thnak you for considering it!

Best,
Eddie
