### ISSUE TITLE
conda installation, glibc conflict error

### ISSUE THREAD

**Issue by guyko81** [automl/auto-sklearn#1240]
## Describe the bug ##
When trying to install through conda forcing conda-forge (I have no other option in workplace) the installation stops with the below error.

## Actual behavior, stacktrace or logfile ##
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package __glibc conflicts for:
@/linux-64::__glibc==2.31=0
auto-sklearn -> smac[version='>=0.13.1,<0.14'] -> __glibc

## To Reproduce ##
conda install auto-sklearn

## Environment and installation: ##

Please give details about your installation:

* Ubuntu 20.04.3 LTS
* conda environment
* Python version: 3.7.6
* Auto-sklearn version: -

**Comment by eddiebergman** [comment]
Hi @guyko81,

Sorry to hear your having problems with the installation. I don't use Conda or Ubuntu myself and the installation instructions were a submitted PR but hopefully we can fix this and update the instructions if necessary.

This line `auto-sklearn -> smac[version='>=0.13.1,<0.14'] -> __glibc` indicates to me that you're not installing the latest version of autosklearn, `0.13.0` as recently change the requirement to `smac >= 0.14`.
Is it intended to use a prior version? It should still work to download a previous version but it might be something worth investigating.

I looked on [conda-forge/autosklearn](https://anaconda.org/conda-forge/auto-sklearn) and it appears the latest version is there and has been for over a month and has been downloaded through there with nearly as many download as `0.12.7` which seems like it's the default.

I had a quick look at that Ubuntu version and it seems your Python version is different. Is this the system Python version or a custom Python version managed by Conda that you manually chose? It seems like you should have Python 3.8 by default. How are you getting your current Python version?

Taken from the [Ubuntu releases page](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Toolchain_Upgrades_.2B2D3e4P4P-):
> Ubuntu 20.04 LTS comes with refreshed state-of-the-art toolchain including new upstream releases of glibc 2.31, ☕ OpenJDK 11, rustc 1.41, GCC 9.3, 🐍 Python 3.8.2, 💎 ruby 2.7.0, php 7.4, 🐪 perl 5.30, golang 1.13. 

Could you run `ldd --version`, this should display your glibc version. I would assume it's 2.31 but honestly the error message isn't very helpful for diagnosing anything other than. We don't require anything special that would require a specific glibc version so why it complains is a mystery.

We also have automatic tests that run using Conda and they seem to be passing fine. I can point you to [this github action](https://github.com/automl/auto-sklearn/blob/master/.github/workflows/pytest.yml#L36) which details how it's automatically installed. This is probably not the ideal way to conda autosklearn but it might help you to have a look through.

I further downloaded the the zip file built and distributed through conda for SMAC based off this line:
`auto-sklearn -> smac[version='>=0.13.1,<0.14'] -> __glibc`
I could not find any occurrence of `glibc`. I do not know why it specifies this as a problem. 
The only thing I could think off here is to make sure you update condas gxx compilers as specified in the [installation instructions](https://automl.github.io/auto-sklearn/master/installation.html#anaconda-installation).

**Comment by guyko81** [comment]
thanks @eddiebergman for the quick and detailed answer!
The ldd --version gives 2.31 indeed.
The python is coming from miniconda, I don't know why it's not 3.8.
I try to create a new environment with python=3.8 and give update.

**Comment by eddiebergman** [comment]
Let me know how it goes!

**Comment by guyko81** [comment]
@eddiebergman I could finally install it, the problem was the conda/python version. After installing the latest conda with python 3.9.5 I could install auto-sklearn smoothly. 
It would still be a good investigation what caused this, but I'm happy with the result now, so thanks!

**Comment by eddiebergman** [comment]
Glad to hear :)

It should have still worked with Python 3.7.6 but perhaps there was some issue with conda and where it was looking for packages which was fixed by the update. 

If anyone else encounters this issue, please feel free to reopen this.
