### ISSUE TITLE
Test to see if Auto-sklearn works with SWIG 4.0

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1241]
My operating system indicates I'm running `SWIG 4.0.2` and it's been installing auto-sklearn fine. This seems to [conflict the installation docs](https://automl.github.io/auto-sklearn/master/installation.html#system-requirements).

If anyone see's this issue and can report that auto-sklearn works with `SWIG>=4.0` that would be tremendously helpful.
```
> swig -version
SWIG Version 4.0.2

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

Otherwise, this can tested using docker containers and github action containers to see if it will correctly run with SWIG 4.0.

**Comment by mfeurer** [comment]
This must be an error in the docs, SWIG 4.01 and above have been enabled via https://github.com/automl/random_forest_run/pull/61

**Comment by eddiebergman** [comment]
Coll I'll make a PR to update the docs!
