### ISSUE TITLE
Unable to add custom component

### ISSUE THREAD

**Issue by kshitijgundale** [automl/auto-sklearn#1253]
## Describe the bug ##
I am trying to follow this [example](https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_preprocessor.html#sphx-glr-examples-80-extending-example-extending-preprocessor-py) from docs in Google Colab. But auto-sklearn refuses to acknowledge the newly added component's existence. 

`ValueError: The provided component 'LDA' for the key 'feature_preprocessor' in the 'include' argument is not valid. The supported components for the step 'feature_preprocessor' for this task are ['densifier', 'extra_trees_preproc_for_classification', 'fast_ica', 'feature_agglomeration', 'kernel_pca', 'kitchen_sinks', 'liblinear_svc_preprocessor', 'no_preprocessing', 'nystroem_sampler', 'pca', 'polynomial', 'random_trees_embedding', 'select_percentile_classification', 'select_rates_classification', _'truncatedSVD']`

**Comment by eddiebergman** [comment]
Hi @kshitijgundale ,

That example works for me, did you perhaps miss the line at the bottom of [this code block](https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_preprocessor.html#sphx-glr-examples-80-extending-example-extending-preprocessor-py)
```
autosklearn.pipeline.components.feature_preprocessing.add_preprocessor(LDA)
```

**Comment by kshitijgundale** [comment]
Hi, @eddiebergman, thanks for reply. I am sure I included that line after the class declaration. I tried the same code example locally in Linux environment and it worked perfectly. Also, it worked the first time I ran the code. But then started throwing above error in successive attempts.  So the problem seems to lie with Google Colab.

**Comment by eddiebergman** [comment]
Im sorry to hear about that but I'm not sure what we can do on our end. I can try in a Jupyter Notebook which will function somewhat similarly to Google Colab and see if I can reproduce the results.
