### ISSUE TITLE
[Question] How to generate Confusion Matrix and get parameters of models found

### ISSUE THREAD

**Issue by m-alshehri** [automl/auto-sklearn#1255]
how to print out the confusion matrix, classification report, and parameter configurations for the best model?

While trying the below example, I tried to print out the confusion matrix, classification report and parameter configurations for the best models, say the best 5 models for further comparison, but I failed. 
https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_calc_multiple_metrics.html#sphx-glr-examples-40-advanced-example-calc-multiple-metrics-py

is there any way to do that? Apologies if this was asked before but searching previous issues such as #1206 and looking at the manual below wasn't helpful at least to beginners like me.
https://automl.github.io/auto-sklearn/master/manual.html

Thanks,
M-alshehri

**Comment by eddiebergman** [comment]
Hi @m-alshehri,

The example you linked is for `metrics` and I'm not sure which particular example you were referring to.
I can't walk you through analysis of models as that's a whole other topic. 

The key point is that we produce `sklearn` compliant [`Pipelines`](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html). This means any analysis you can do with sklearn, you can do on the `Pipeline` models we produce. The reason they are more complicated than just a single classifier or regressor is that this pipeline also includes some data preprocessing and feature preprocessing.

Our current methods of getting models isn't the nicest but here's a small example of generating a confusion matrix.
```python
from sklearn.metrics import confusion_matrix

from autosklearn.classification import AutoSklearnClassifier
from autosklearn.pipeline.util import get_dataset

X_train, y_train, X_test, y_test = get_dataset('iris')
automodel = AutoSklearnClassifier(time_left_for_this_task=30)
automodel.fit(X_train, y_train)

# Iterate through all the Pipeline models in the ensemble and generate their confusion matrix
for weight, model in automodel.get_models_with_weights():
    
    predictions = model.predict(X_test)
    confusion_m = confusion_matrix(y_test, predictions)

    params = model.get_params()
    
    print(params)
    print(confusion_m)    
```

**Comment by m-alshehri** [comment]
ok thanks this was helpful
