### ISSUE TITLE
Conda Install failed

### ISSUE THREAD

**Issue by Louquinze** [automl/auto-sklearn#1256]
When installing with conda (as described in the guide), the dask package is not installed correctly.

## To Reproduce ##
1. Create a new conda environment `conda create --name myenv`
2. Activate the environment `conda activate myenv`
3. follow the anaconda tutorial on https://automl.github.io/auto-sklearn/master/installation.html#conda-forge
4. start python interpreter and enter `>>> from autosklearn.classification import AutoSklearnClassifier`
5. see error

## Workaround
Just install dask after step 3.
```bash
conda install dask
```

## Actual behavior, stacktrace or logfile ##
`>>> from autosklearn.classification import AutoSklearnClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier  # noqa (imported but unused)
  File "/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/autosklearn/estimators.py", line 6, in <module>
    import dask.distributed
  File "/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/dask/distributed.py", line 3, in <module>
    from distributed import *
  File "/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/distributed/__init__.py", line 4, in <module>
    from .actor import Actor, ActorFuture
  File "/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/distributed/actor.py", line 6, in <module>
    from .client import Future, default_client
  File "/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/distributed/client.py", line 30, in <module>
    from dask.compatibility import apply
ImportError: cannot import name 'apply' from 'dask.compatibility' (/home/lukas/anaconda3/envs/import_test/lib/python3.9/site-packages/dask/compatibility.py)
`

## Environment and installation: ##

Please give details about your installation:

* Ubuntu 20.04
* conda version==4.10.1
* python 3.8.8
* autosklearn version 0.14.0

**Comment by erinaldi** [comment]
Any update on this? I have the same problem with python 3.8.5 and Conda 4.10.3

**Comment by mfeurer** [comment]
@BastianZim it appears that this is an issue with the conda package for Auto-sklearn not specifying a dependency correctly. Would you mind having a look into this?

**Comment by BastianZim** [comment]
Will update to the full `dask` package. 

Background:
`auto-sklearn` currently depends on `dask-core` which is the pure implementation of `dask` without any additional dependencies. This is generally recommended except when downstream uses optional modules as well, which seems to be the case here. 
Ref: https://docs.dask.org/en/stable/install.html

**Comment by BastianZim** [comment]
A new build depending on the full `dask` package has been published. A fix for the old version is currently being deployed.

Both need to go through the CDN and will therefore only be available in a couple of hours.

**Comment by BastianZim** [comment]
Both the new build and the fix for the previous versions have been published. 

@Louquinze @erinaldi Can you confirm whether it is working correctly now?

**Comment by eddiebergman** [comment]
Hi @BastianZim,

Thanks a lot for doing this! It appears that @Louquinze was able to create a new environment and it installed without issue. I will close this issue.

If anyone else run's into this issue, please feel free to re-open the discussion.
