### ISSUE TITLE
[Question] AutoSklearn2Classifier and resampling strategy

### ISSUE THREAD

**Issue by DanielWicz** [automl/auto-sklearn#1267]
Does AutoSklearn2Classifier from autosklearn v2 uses resampling strategy or not anymore ?

**Comment by eddiebergman** [comment]
Unfortunately not yet, i'm not sure when it will be part of the core library as it will be documented then. You're best bet is to look at the [code ](https://github.com/automl/auto-sklearn/blob/master/autosklearn/experimental/askl2.py#L180). It inherits from the default `AutoSklearnClassifier` from which point most of the other arguments are forwarded and should work the same.

**Comment by DanielWicz** [comment]
Thanks for answers
