### ISSUE TITLE
After ensemble has been made, retrain models on full training data

### ISSUE THREAD

**Issue by laurentsorber** [automl/auto-sklearn#13]
I noticed that auto-sklearn reserves about one third of the training data for building the ensemble. This means that the individual models could have seen 50% more data than they currently do, which can have a substantial impact if the number of training examples is small. E.g., I tried running auto-sklearn for 7 hours on the Kaggle Titanic competition and got a score of about 0.799, which is not bad, but also not great.

Suggestion: retrain individual models on full training data after ensemble has been built. One difficulty is that the hyperparameters specification should be invariant on the number of training examples. On the other hand, it may not matter much either way since this proposal wouldn't change the number of training examples the models see by more than a factor of 1,5.

**Comment by mfeurer** [comment]
Yes, this would be great to have and is on our todo list.

**Comment by mfeurer** [comment]
This feature is now present and documentation was added in commit 0c548a60c7c191ca75e4278d45af9a152c9b08f1.
