### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by siwang2011** [automl/auto-sklearn#1302]
## Describe the bug ##
when I use the autosklearn.regression.AutoSklearnRegressor
pred_model = AutoSklearnRegressor(
    time_left_for_this_task=30,
    per_run_time_limit=5, n_jobs=16
)
pred_model.fit(x_pd, y_pd)

i have 427 x_pd and y_pd DataFrames
the code is run safely, but after a period of time, it will raise error 
i don't understand the error msg

![image](https://user-images.githubusercontent.com/69880884/141941179-3a38a50e-cccb-46ed-b159-c053583ea7d2.png)
![image](https://user-images.githubusercontent.com/69880884/141941926-2c2722b9-755a-4548-84f1-9023de47d4c4.png)

Please give details about your installation:
pip install auto-sklearn

* OS Centos7
* Is your installation in a virtual environment or conda environment? No
* Python version 3.8
* Auto-sklearn version 0.14.2

**Comment by eddiebergman** [comment]
Hi @siwang2011,

I'm not entirely sure why that would be the case. An initial guess is that when trying to `connect_to_new_process` as seen in the last line of the error log, it can't connect, making me think that either there is some process limitations on your system or that `16 ` `n_jobs` is too many for your system. The fact it happens after a delayed period of time might also support this hypothesis.

* Have you tried lowering `n_jobs`?
* What is the output of the command `lscpu | grep -e "^CPU"`, it should tell you how many cpus you have available.

**Comment by siwang2011** [comment]
Hi @eddiebergman 
the cmd output is 16 cpus.
i try to low the n_jobs = 4 but still raise error
i have 400s dataframes, it will create 400s folder 
but it always will breakdown at 140-160/400s 
i don't know why
i try to low the auto-sklearn version but it don't work 
my English is awful sorry.

**Comment by eddiebergman** [comment]
Hi @siwang2011,

> my English is awful sorry.
No problem, it is okay :)

Could you explain more about how you use 400 datasets?
Do you run them one at a time, do you run them in parallel? Do they all run from the same script or from multiple?

**Comment by siwang2011** [comment]
Hi! @eddiebergman 
I simply iter 400s and every time i build a new model
they are not in parallel and from the same script

**Comment by eddiebergman** [comment]
Hmm, that's a bit unusual from what we would expect so I can't tell you why that fails. Does it fail if you only run 1 iter or 10 iters?

The only work-around I can advise is to try run the script 400 times with an argument and try it that way. This is assuming you can run it from the command line.

```bash
for i in {1..400}; do 
    python my_script.py i # Runs your script with dataframe i
done
```

**Comment by siwang2011** [comment]
@eddiebergman 
thanks I will try

**Comment by eddiebergman** [comment]
Hello @siwang2011, any update?

**Comment by eddiebergman** [comment]
This seems to be an issue with how many subprocess can be spawned from a single process and is operating system dependant. If you have to run autosklearn many times in succession, the recommended approach is have a python script with arguments and run that many times.

```bash
python myscript.py dataset-name
```
