### ISSUE TITLE
Document callback functionality with SMAC

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1304]
Thanks to @thomashlvt, we have new functionality in SMAC to utilize callbacks which can be done through autosklearn. We would require documenting how this might be used and create an example, perhaps even changing the API names slightly to make it more intuitive.

Relevant issues:
* #1223
* SMAC https://github.com/automl/SMAC3/pull/765

**Comment by mfeurer** [comment]
Closed via #1476.
