### ISSUE TITLE
Use isort to sort imports

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#1312]
https://github.com/PyCQA/isort

**Comment by isaac-chung** [comment]
Thoughts on putting isort in pre-commit hooks as well?

**Comment by eddiebergman** [comment]
Hi @isaac-chung,

We already have a [workflow check in our development branch](https://github.com/automl/auto-sklearn/blob/development/.github/workflows/isort_checker.yml). Our plan is to apply black formatting and isort to the entire codebase after our next major release to prevent PR's being incomprehensible.

If you still want to contribute, having black and an isort check to our pre-commit to our development branch we can use it as a bases once we apply it :)

**Comment by eddiebergman** [comment]
Just realised the naming of that workflow file is wrong, I'll have to update that

**Comment by mfeurer** [comment]
@eddiebergman can this be closed?
