### ISSUE TITLE
[Question] How to retain previously searched information?

### ISSUE THREAD

**Issue by CzsGit** [automl/auto-sklearn#1315]
Dear all,

How to reload the content searched before the break in the training after the break.
similar to checkpoints in tensorflow.

Now I'm using the same parameters and the same data set and than I get the same results is obtained after two runs.
but what I'm looking forward to is the second time that we can build on the foundation that we create the first time.
at least it can be different than the first time.

code like this:
`

    while train_times < set_times:

        if train_times > 1:

            reload(model) # may be is path

        model = model.fit(x,y)

        save(model)

`

Ubuntu
python: 3.6.9
Auto-SKlearn: 0.12.7

**Comment by eddiebergman** [comment]
Hi @CzsGit,

Currently this is not possible and has been requested before. We agree that it would very useful in general and is something we want to have. There is a slight complication that prevent us from doing so at the moment. 

One, is that we need to inform our optimizer SMAC about the previous runs so that it continue it's search in a proper way. I'm not 100% sure SMAC can handle this warm-starting but there may be some way around it.

**Comment by CzsGit** [comment]
> SMAC

Thanks.

I can receive metrics on completion,but what should do if I want to output metrics during fit? or others such as validate...
Have some hooks i can call when fitting?

**Comment by eddiebergman** [comment]
Yes you can, it's not documented as we need to create API changes to make this intuitive. The function with `Optional[bool]` can pass back `False` for early stopping.

```python
from typing import Optional

from autosklearn.classification import AutoSklearnClassifier
from sklearn.datasets import load_iris

from smac.callbacks import IncorporateRunResultCallback
from smac.optimizer.smbo import SMBO
from smac.runhistory.runhistory import RunInfo, RunValue


class CallbackObject(IncorporateRunResultCallback):

    def __call__(self, smbo: SMBO, run_info: RunInfo, result: RunValue, time_left: float) -> Optional[bool]:
        print(f"{smbo=}")
        print(f"{run_info=}")
        print(f"{result=}")
        print(f"{time_left=}")


iris = load_iris()
my_callback = CallbackObject()

automodel = AutoSklearnClassifier(
    time_left_for_this_task=30,
    get_trials_callback=my_callback
)

automodel.fit(X=iris.data, y=iris.target)
```

```python
# Just one output of the callback function
smbo=<smac.optimizer.smbo.SMBO object at 0x7f053d107370>

run_info=RunInfo(config=Configuration:
  balancing:strategy, Value: 'none'
  classifier:__choice__, Value: 'random_forest'
  classifier:random_forest:bootstrap, Value: 'True'
  classifier:random_forest:criterion, Value: 'gini'
  classifier:random_forest:max_depth, Constant: 'None'
  classifier:random_forest:max_features, Value: 0.5
  classifier:random_forest:max_leaf_nodes, Constant: 'None'
  classifier:random_forest:min_impurity_decrease, Constant: 0.0
  classifier:random_forest:min_samples_leaf, Value: 1
  classifier:random_forest:min_samples_split, Value: 2
  classifier:random_forest:min_weight_fraction_leaf, Constant: 0.0
  data_preprocessor:__choice__, Value: 'feature_type'
  data_preprocessor:feature_type:categorical_transformer:categorical_encoding:__choice__, Value: 'one_hot_encoding'
  data_preprocessor:feature_type:categorical_transformer:category_coalescence:__choice__, Value: 'minority_coalescer'
  data_preprocessor:feature_type:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction, Value: 0.01
  data_preprocessor:feature_type:numerical_transformer:imputation:strategy, Value: 'mean'
  data_preprocessor:feature_type:numerical_transformer:rescaling:__choice__, Value: 'standardize'
  feature_preprocessor:__choice__, Value: 'no_preprocessing'
, instance='{"task_id": "7898b91d-4c48-11ec-9411-f47b09df72c1"}', instance_specific='0', seed=0, cutoff=3.0, capped=False, budget=0.0, source_id=0)

result=RunValue(cost=0.020000000000000018, time=1.9172518253326416, status=<StatusType.SUCCESS: 1>, starttime=1637663469.8006718, endtime=1637663471.7321455, additional_info={'duration': 1.848536729812622, 'num_run': 2, 'train_loss': 0.0, 'configuration_origin': 'Initial design'})

time_left=3.740787506477595e-14
```

**Comment by CzsGit** [comment]
> 

Thank you very much. I'll give it a try

> Yes you can, it's not documented as we need to create API changes to make this intuitive. The function with `Optional[bool]` can pass back `False` for early stopping.
> 
> ```python
> from typing import Optional
> 
> from autosklearn.classification import AutoSklearnClassifier
> from sklearn.datasets import load_iris
> 
> from smac.callbacks import IncorporateRunResultCallback
> from smac.optimizer.smbo import SMBO
> from smac.runhistory.runhistory import RunInfo, RunValue
> 
> 
> class CallbackObject(IncorporateRunResultCallback):
> 
>     def __call__(self, smbo: SMBO, run_info: RunInfo, result: RunValue, time_left: float) -> Optional[bool]:
>         print(f"{smbo=}")
>         print(f"{run_info=}")
>         print(f"{result=}")
>         print(f"{time_left=}")
> 
> 
> iris = load_iris()
> my_callback = CallbackObject()
> 
> automodel = AutoSklearnClassifier(
>     time_left_for_this_task=30,
>     get_trials_callback=my_callback
> )
> 
> automodel.fit(X=iris.data, y=iris.target)
> ```
> 
> ```python
> # Just one output of the callback function
> smbo=<smac.optimizer.smbo.SMBO object at 0x7f053d107370>
> 
> run_info=RunInfo(config=Configuration:
>   balancing:strategy, Value: 'none'
>   classifier:__choice__, Value: 'random_forest'
>   classifier:random_forest:bootstrap, Value: 'True'
>   classifier:random_forest:criterion, Value: 'gini'
>   classifier:random_forest:max_depth, Constant: 'None'
>   classifier:random_forest:max_features, Value: 0.5
>   classifier:random_forest:max_leaf_nodes, Constant: 'None'
>   classifier:random_forest:min_impurity_decrease, Constant: 0.0
>   classifier:random_forest:min_samples_leaf, Value: 1
>   classifier:random_forest:min_samples_split, Value: 2
>   classifier:random_forest:min_weight_fraction_leaf, Constant: 0.0
>   data_preprocessor:__choice__, Value: 'feature_type'
>   data_preprocessor:feature_type:categorical_transformer:categorical_encoding:__choice__, Value: 'one_hot_encoding'
>   data_preprocessor:feature_type:categorical_transformer:category_coalescence:__choice__, Value: 'minority_coalescer'
>   data_preprocessor:feature_type:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction, Value: 0.01
>   data_preprocessor:feature_type:numerical_transformer:imputation:strategy, Value: 'mean'
>   data_preprocessor:feature_type:numerical_transformer:rescaling:__choice__, Value: 'standardize'
>   feature_preprocessor:__choice__, Value: 'no_preprocessing'
> , instance='{"task_id": "7898b91d-4c48-11ec-9411-f47b09df72c1"}', instance_specific='0', seed=0, cutoff=3.0, capped=False, budget=0.0, source_id=0)
> 
> result=RunValue(cost=0.020000000000000018, time=1.9172518253326416, status=<StatusType.SUCCESS: 1>, starttime=1637663469.8006718, endtime=1637663471.7321455, additional_info={'duration': 1.848536729812622, 'num_run': 2, 'train_loss': 0.0, 'configuration_origin': 'Initial design'})
> 
> time_left=3.740787506477595e-14
> ```
