### ISSUE TITLE
Getting Error: __init__() got an unexpected keyword 'include'

### ISSUE THREAD

**Issue by SameenInqline** [automl/auto-sklearn#1319]
I am trying to train a decision tree regressor model using auto-sklearn. For that i am trying to use the 'include' parameter but getting error: 

TypeError: __init__() got an unexpected keyword 'include'

My auto-sklearn version is 0.14.0 and i am running the program on a Mac. I have taken the syntax from here:
https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_single_configuration.html#sphx-glr-examples-40-advanced-example-single-configuration-py

The screenshot of the error is attached. Kindly help me resolve the issue. 
!['include' error](https://user-images.githubusercontent.com/91462548/143070426-38fe7e63-ba14-4c1a-9213-89dc75fb088d.png)

**Comment by eddiebergman** [comment]
Hi @SameenInqline,

Sorry to hear you're having this problem. I can't reproduce this and looking at the code, the fact you have this error makes no sense to me.

Here's a minimal example that should reproduce the error
```python
import autosklearn.regression

automl = autosklearn.regression.AutoSklearnRegressor(
    include={"regressor": ["decision_tree"]
)
```

**Comment by SameenInqline** [comment]
Hi, I am getting the same error with the code you provided.
![SameError](https://user-images.githubusercontent.com/91462548/143595908-2c9c5a87-56e6-4ed2-a0d8-e6bfc8ba8711.png)

**Comment by eddiebergman** [comment]
I'm really not sure why that is considering you say your version is `0.14.0`. My only guess is that either the version is not the one you think it is somehow or that some previous code it causing an issue here.

If you can provide your full code, I could help more. Please don't post it as a screenshot but encase it with three backticks '`' at the start at end ...

```
... so that it shows up as monospace code font
```
