### ISSUE TITLE
I have confusion with final ensemble model.

### ISSUE THREAD

**Issue by shabir1** [automl/auto-sklearn#1324]
My constractor: 
`automl = autosklearn.classification.AutoSklearnClassifier( 
            time_left_for_this_task=3600,
            memory_limit=3072,
            ensemble_size=10,
            ensemble_nbest=10,
            max_models_on_disc=10,
            delete_tmp_folder_after_terminate=False,
)`
Below is my model's sprint_statistics
Number of target algorithm runs: 17\n  
Number of successful target algorithm runs: 4\n  
Number of crashed target algorithm runs: 2\n  
Number of target algorithms that exceeded the time limit: 9\n  
Number of target algorithms that exceeded the memory limit: 2\n'

output of `show_model()` :
`"[(1.000000, SimpleClassificationPipeline({'balancing:strategy': 'weighting', 'classifier:__choice__': 'random_forest', 'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'no_encoding', 'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'minority_coalescer', 'data_preprocessing:numerical_transformer:imputation:strategy': 'mean', 'data_preprocessing:numerical_transformer:rescaling:__choice__': 'robust_scaler', 'feature_preprocessor:__choice__': 'select_rates_classification', 'classifier:random_forest:bootstrap': 'False', 'classifier:random_forest:criterion': 'gini', 'classifier:random_forest:max_depth': 'None', 'classifier:random_forest:max_features': 0.23832696118792362, 'classifier:random_forest:max_leaf_nodes': 'None', 'classifier:random_forest:min_impurity_decrease': 0.0, 'classifier:random_forest:min_samples_leaf': 1, 'classifier:random_forest:min_samples_split': 16, 'classifier:random_forest:min_weight_fraction_leaf': 0.0, 'data_preprocessing:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction': 0.035949803138524174, 'data_preprocessing:numerical_transformer:rescaling:robust_scaler:q_max': 0.7356350569414665, 'data_preprocessing:numerical_transformer:rescaling:robust_scaler:q_min': 0.2902106911441806, 'feature_preprocessor:select_rates_classification:alpha': 0.3610975428987517, 'feature_preprocessor:select_rates_classification:score_func': 'mutual_info_classif'},\ndataset_properties={\n  'task': 2,\n  'sparse': False,\n  'multilabel': False,\n  'multiclass': True,\n  'target_type': 'classification',\n  'signed': False})),\n]"`

My question is why I got only one algorithm/configuration in final ensemble model if my successful target algorithms are 4 and ensemble size are 10? My final model should be ensemble of 4 configurations, right?

**Comment by eddiebergman** [comment]
Hi @shabir1,

This essentially means there were ten models added to the ensemble and in every round of deciding what model to add to the ensemble, that one model was the best thing to add (meaning that the other successful models were not good).

The way ensembles are constructed in (clear but not concise) pseudo code is as follows:

```python
def performance(ens) -> float: ...
    """ Takes an ensemble and gives it's performance """
    
successful_models = [m1, m2, m3, m4]
counts = [0, 0, 0, 0] # How many times each model was added to the ensemble

current_best_ensemble = []  
while len(current_best_ensemble) < 10:
    
    # We will track the performance of the ensemble if we try add a model into it
    performances = []
    for model in successful_models:
         ensemble = current_best_ensemble.copy() + [model] # Try the model in the ensemble
         ensemble_performance = performance(ensemble) # get performance
         performances.append(ensemble_performance) # record performance
    
    # Get the model which has the best performance when added     
    idx = np.argmax(performances)
    best_model_to_add = successful_models[idx]
    
    # Add that model to the current list of ensembles
    current_best_ensemble.append(best_model_to_add)
    counts[idx] += 1 # We added this model so increment the count
    
# We now have an ensemble which may include multiple entries of the same model,
# instead of calling the same model multiple times, we give them a weight.
# This is just done by normalizing their count values
weights = [ count / sum(counts) for count in counts ]
```

**Comment by shabir1** [comment]
@eddiebergman Thank you
