### ISSUE TITLE
FileExistsError when n_jobs of autosklearn.classification.AutoSklearnClassifier larger than 1

### ISSUE THREAD

**Issue by bladesaber** [automl/auto-sklearn#1328]
## Describe the bug ##
when I set the n_jobs of class autosklearn.classification.AutoSklearnClassifier larger than 1, it will cause the error FileExistsError: [Errno 17] File exists: tmp/autosklearn_on_example_tmp'. It seems that multi processor will create the folder at the same locatin. 

Looking forward to solution quickly, thanks.

## To Reproduce ##
import sklearn.datasets
import sklearn.metrics

import autosklearn.classification

X, y = sklearn.datasets.load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)

automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=90,
    per_run_time_limit=30,
    tmp_folder='/tmp/autosklearn_on_example_tmp',
    n_jobs=-1,
    ensemble_size=5,
    ensemble_nbest=20
)
automl.fit(X_train, y_train, dataset_name='breast_cancer')

print(automl.leaderboard())

print(automl.show_models())

## Actual behavior, stacktrace or logfile ##
FileExistsError: [Errno 17] File exists: '/tmp/autosklearn_on_example_tmp'

## Environment and installation: ##

Please give details about your installation:

* OS Ubantu 18.0.4
* Is your installation in a virtual environment or conda environment? use conda
* Python version 3.7.6
* Auto-sklearn version 0.14.2

**Comment by eddiebergman** [comment]
Hi @bladesaber, you're right in that it's due to parallelization. Due to how we use `dask`, our processes distributer, we require a `__main__` gaurd. 

Could you try wrapping it in a `__main__` and seeing if it works?

* https://automl.github.io/auto-sklearn/master/#example

We have updated our documentation in the next release which should mention this more explictly.

**Comment by bladesaber** [comment]
Thank you very much, it works. ^_^
