### ISSUE TITLE
Docstrings for include and exclude argument not up-to-date

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#1331]
The docstrings for include and exclude of the AutoSklearnClassifier and AutoSklearnRegressor are not up-to-date as they do not yet address that one should pass in a dict (and no longer a list).

**Comment by eddiebergman** [comment]
They seems to correctly specify dict? However they are not very clear so I will update them.

**Comment by mfeurer** [comment]
This can be closed now that you merged #1332, right?
