### ISSUE TITLE
Cannot install sklearn

### ISSUE THREAD

**Issue by BaggioGiacomo** [automl/auto-sklearn#1343]
# Issue description
Hi all! I'm having troubles while installing sklearn using  `pip install sklearn`.
It throws those errors while preparing metadata (pyproject.toml).
![image](https://user-images.githubusercontent.com/58849430/145551859-f3763921-c0ae-4a3e-a5df-45eb04940cd8.png)

## What is my environment?
- Python 3.10.1 installed from the [Offical site] (https://www.python.org/downloads/)
- Pip 21.3.1
- MSVC v143 - VS 2022 C++ x64/x86 build tools (latest)
- VS Code

### Other info
I can install other modules (such as pandas) except this one.

I hope you can help me!

**Comment by eddiebergman** [comment]
Hi @BaggioGiacomo,

This is not really a question for us as it has to do with building sklearn. You can test this by just installing sklearn by itself. However, it seems this is a problem with your C/C++ environment. One of the lines in the first section says `cant open include file 'stdio.h' ... ` which is part of the core C++ stdlib.

I'm closing this issue as it's not directly related to auto-sklearn.
