### ISSUE TITLE
cryptic info line [INFO)

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#135]
Just to make sure this is no bug - what does this line tells us? And why is there _Autosklearnuiaeo_ which looks like classifier class name plus the vowels?

[INFO] [2016-09-21 08:04:22,556:AutoMLSMBO(3)::Autosklearn] ['822_acc', '26_acc', '962_acc', '1002_acc', '554_acc', '923_acc', '881_acc', '1112_acc', '799_acc', '1139_acc', '401_acc', '273_acc', '849_acc', '182_acc', '**Autosklearnuiaeo**', '1114_acc', '904_acc', '901_acc', '181_acc', '1000_acc', '903_acc', '734_acc', '914_acc', '1036_acc', '1130_acc', '300_acc', '180_acc', '57_acc', '179_acc', '723_acc', '1040_acc', '953_acc', '24_acc', '398_acc', '392_acc', '743_acc', '1019_acc', '1111_acc', '1049_acc', '816_acc', '807_acc', '1021_acc', '396_acc', '399_acc', '351_acc', '21_acc', '910_acc', '912_acc', '797_acc', '1053_acc', '46_acc', '185_acc', '395_acc', '1119_acc', '871_acc', '184_acc', '28_acc', '978_acc', '866_acc', '60_acc', '354_acc', '36_acc', '14_acc', '913_acc', '727_acc', '22_acc', '976_acc', '293_acc', '393_acc', '1069_acc', '6_acc', '30_acc', '1142_acc', '44_acc', '737_acc', '741_acc', '12_acc', '917_acc', '959_acc', '833_acc', '357_acc', '1138_acc', '18_acc', '1056_acc', '897_acc', '843_acc', '1068_acc', '1128_acc', '16_acc', '823_acc', '752_acc', '837_acc', '679_acc', '761_acc', '38_acc', '819_acc', '3_acc', '995_acc', '389_acc', '803_acc', '31_acc', '813_acc', '846_acc', '1146_acc', '966_acc', '979_acc', '722_acc', '977_acc', '934_acc', '845_acc', '993_acc', '1116_acc', '980_acc', '32_acc', '971_acc', '720_acc', '1134_acc', '751_acc', '958_acc', '1018_acc', '390_acc', '806_acc', '847_acc', '1161_acc', '930_acc', '715_acc', '1166_acc', '391_acc', '1120_acc', '772_acc', '718_acc', '735_acc', '1050_acc', '740_acc', '1041_acc', '23_acc', '728_acc', '1020_acc', '1067_acc', '991_acc', '821_acc']

**Comment by mfeurer** [comment]
Sorry for the weird output, this will be gone in the next release. Besides that, it tells you all datasets for which metadata was loaded. Autosklearnuiaeo is a placeholder for the current run (we cannot assume to always have a dataset name).

**Comment by Motorrat** [comment]
to avoid stupid questions (like this one :-)) you could turn to industry standart foobar, quux etc. http://www.hacker-dictionary.com/terms/metasyntactic%20variable
