### ISSUE TITLE
Security vulnerability in dask < 2021.10.0

### ISSUE THREAD

**Issue by EchoDelta** [automl/auto-sklearn#1353]
There is a [security vulnerability](https://github.com/advisories/GHSA-j8fq-86c5-5v2r) in the required version of `dask` used by `auto-sklearn`.

Could you update the requirements of `dask` to a version >= `2021.10.0`?

**Comment by eddiebergman** [comment]
Hi @EchoDelta, I'm making a [hotfix](https://github.com/automl/auto-sklearn/pull/1354) for master, just going to wait until the tests pass before merging.

**Comment by eddiebergman** [comment]
Hi @EchoDelta, the maintainer who has access to publish it to Pypi won't be back until early January, until then, I'm afraid you'll have to git clone off of `master`.

**Comment by EchoDelta** [comment]
Will do! Thanks for the fix!

**Comment by EchoDelta** [comment]
@eddiebergman Will the new version be published soon?

**Comment by eddiebergman** [comment]
Hi @EchoDelta,

Apologies, we sorted out the upload rights yesterday, the fixed master branch will be on PyPi within a few hours.

**Comment by eddiebergman** [comment]
Should be up now :)
https://pypi.org/project/auto-sklearn/
