### ISSUE TITLE
Do classifier instances (seeds) learn from each other? 

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#136]
I see the results of four various seeds to be very close to each other. This wasn't like this before in the previous version. What is the mechanism of sharing the learnings between the seeds? It was the temp folder before, but now I can find there only the logs. So I wonder whether the seeds runs aren't redundant?
cleaned up log - check for same or similar values for each run for all the seeds 

> timestamp	seed	run	duration	loss	status
03:48,1	0	3	Duration 5.799072	 loss 1.764112	 status 1
03:45,1	1	3	Duration 5.632590	 loss 1.706683	 status 1
03:46,0	2	3	Duration 5.754339	 loss 1.709787	 status 1
03:58,2	3	3	Duration 5.847006	 loss 1.687308	 status 1
03:56,1	0	4	Duration 1.422963	 loss 1.313838	 status 1
03:46,9	1	4	Duration 1.271036	 loss 1.324792	 status 1
03:47,8	2	4	Duration 1.269344	 loss 1.314700	 status 1
04:00,1	3	4	Duration 1.431224	 loss 1.291165	 status 1
03:58,9	0	5	Duration 2.257483	 loss 1.442216	 status 1
03:49,4	1	5	Duration 2.017542	 loss 1.410159	 status 1
03:50,4	2	5	Duration 2.074972	 loss 1.452840	 status 1
04:02,8	3	5	Duration 2.249182	 loss 1.463350	 status 1
04:00,8	0	6	Duration 1.411720	 loss 1.678901	 status 1
03:51,1	1	6	Duration 1.116434	 loss 1.682632	 status 1
03:52,0	2	6	Duration 0.980053	 loss 1.674216	 status 1
04:04,4	3	6	Duration 1.125833	 loss 1.681341	 status 1
05:38,5	0	7	Duration 35.349396	 loss 1.586451	 status 1
05:29,5	1	7	Duration 35.376950	 loss 1.557382	 status 1
05:34,7	2	7	Duration 34.413876	 loss 1.552701	 status 1
05:40,5	3	7	Duration 35.262642	 loss 1.557247	 status 1
05:44,7	0	8	Duration 5.510241	 loss 2.000000	 status 3
05:35,6	1	8	Duration 5.719026	 loss 2.000000	 status 3
05:41,4	2	8	Duration 6.280138	 loss 2.000000	 status 3
05:46,6	3	8	Duration 5.740623	 loss 2.000000	 status 3
15:46,8	0	9	Duration 601.685987	 loss 2.000000	 status 2
15:37,8	1	9	Duration 601.780182	 loss 2.000000	 status 2
15:43,5	2	9	Duration 601.720668	 loss 2.000000	 status 2
15:48,1	3	9	Duration 601.134337	 loss 2.000000	 status 2
16:15,5	0	10	Duration 27.269738	 loss 1.159288	 status 1
16:06,9	1	10	Duration 27.455706	 loss 1.155510	 status 1
16:13,1	2	10	Duration 27.996709	 loss 1.155094	 status 1
16:17,7	3	10	Duration 28.034637	 loss 1.164679	 status 1
26:46,4	0	11	Duration 630.452452	 loss 2.000000	 status 2
26:37,9	1	11	Duration 630.596784	 loss 2.000000	 status 2
26:44,4	2	11	Duration 630.948807	 loss 2.000000	 status 2
26:48,3	3	11	Duration 630.166757	 loss 2.000000	 status 2
27:52,1	0	12	Duration 65.303907	 loss 2.000000	 status 3
27:40,3	1	12	Duration 61.980831	 loss 2.000000	 status 3
27:50,8	2	12	Duration 65.995025	 loss 2.000000	 status 3
27:49,2	3	12	Duration 60.468752	 loss 2.000000	 status 3
27:58,5	0	13	Duration 5.906705	 loss 2.000000	 status 3
27:46,4	1	13	Duration 5.609589	 loss 2.000000	 status 3
27:57,1	2	13	Duration 5.758646	 loss 2.000000	 status 3
27:55,3	3	13	Duration 5.665392	 loss 2.000000	 status 3
29:07,2	0	14	Duration 53.938259	 loss 1.515393	 status 1
28:48,7	1	14	Duration 53.900104	 loss 1.493657	 status 1
29:07,1	2	14	Duration 54.405707	 loss 1.528135	 status 1
28:56,9	3	14	Duration 53.525376	 loss 1.519362	 status 1
34:10,9	0	15	Duration 296.898395	 loss 2.000000	 status 3
34:30,4	1	15	Duration 341.135119	 loss 2.000000	 status 3
34:03,2	2	15	Duration 295.349895	 loss 2.000000	 status 3
33:54,4	3	15	Duration 296.956049	 loss 2.000000	 status 3
44:42,6	0	16	Duration 631.314885	 loss 2.000000	 status 2
45:02,2	1	16	Duration 631.312346	 loss 2.000000	 status 2
44:34,9	2	16	Duration 631.326861	 loss 2.000000	 status 2
44:26,7	3	16	Duration 631.344727	 loss 2.000000	 status 2
47:03,9	0	17	Duration 140.699918	 loss 1.248361	 status 1
47:22,6	1	17	Duration 139.886494	 loss 1.248361	 status 1
46:54,8	2	17	Duration 139.394717	 loss 1.248361	 status 1
46:47,8	3	17	Duration 140.422540	 loss 1.248361	 status 1
47:09,9	0	18	Duration 5.625130	 loss 2.000000	 status 3
47:28,9	1	18	Duration 5.835405	 loss 2.000000	 status 3
47:00,9	2	18	Duration 5.608520	 loss 2.000000	 status 3
46:53,9	3	18	Duration 5.649095	 loss 2.000000	 status 3
48:20,3	0	19	Duration 68.638045	 loss 1.121470	 status 1
48:38,4	1	19	Duration 67.947264	 loss 1.126752	 status 1
48:12,5	2	19	Duration 69.987358	 loss 1.124776	 status 1
48:04,6	3	19	Duration 68.906394	 loss 1.128814	 status 1
48:26,2	0	20	Duration 5.513572	 loss 2.000000	 status 3
48:44,2	1	20	Duration 5.379403	 loss 2.000000	 status 3
48:18,5	2	20	Duration 5.560100	 loss 2.000000	 status 3
48:11,2	3	20	Duration 6.143962	 loss 2.000000	 status 3

```
[INFO] [2016-09-21 08:03:48,077:AutoMLSMBO(0)::Autosklearn] Finished evaluating 3. configuration on SUBSET. Duration 5.799072; loss 1.764112; status 1; additional run info: ;duration: 5.799071550369263;num_run:00003
[INFO] [2016-09-21 08:03:56,110:AutoMLSMBO(0)::Autosklearn] Finished evaluating 4. configuration on SUBSET. Duration 1.422963; loss 1.313838; status 1; additional run info: ;duration: 1.4229631423950195;num_run:00004
[INFO] [2016-09-21 08:03:58,884:AutoMLSMBO(0)::Autosklearn] Finished evaluating 5. configuration on SUBSET. Duration 2.257483; loss 1.442216; status 1; additional run info: ;duration: 2.2574832439422607;num_run:00005
[INFO] [2016-09-21 08:04:00,827:AutoMLSMBO(0)::Autosklearn] Finished evaluating 6. configuration on SUBSET. Duration 1.411720; loss 1.678901; status 1; additional run info: ;duration: 1.4117202758789062;num_run:00006
[INFO] [2016-09-21 08:05:38,526:AutoMLSMBO(0)::Autosklearn] Finished evaluating 7. configuration. Duration 35.349396; loss 1.586451; status 1; additional run info: ;duration: 35.349395751953125;num_run:00007
[INFO] [2016-09-21 08:05:44,666:AutoMLSMBO(0)::Autosklearn] Finished evaluating 8. configuration. Duration 5.510241; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:15:46,778:AutoMLSMBO(0)::Autosklearn] Finished evaluating 9. configuration. Duration 601.685987; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:16:15,547:AutoMLSMBO(0)::Autosklearn] Finished evaluating 10. configuration. Duration 27.269738; loss 1.159288; status 1; additional run info: ;duration: 27.26973843574524;num_run:00010
[INFO] [2016-09-21 08:26:46,376:AutoMLSMBO(0)::Autosklearn] Finished evaluating 11. configuration. Duration 630.452452; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:27:52,145:AutoMLSMBO(0)::Autosklearn] Finished evaluating 12. configuration. Duration 65.303907; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:27:58,460:AutoMLSMBO(0)::Autosklearn] Finished evaluating 13. configuration. Duration 5.906705; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:29:07,219:AutoMLSMBO(0)::Autosklearn] Finished evaluating 14. configuration. Duration 53.938259; loss 1.515393; status 1; additional run info: ;duration: 53.93825888633728;num_run:00014
[INFO] [2016-09-21 08:34:10,859:AutoMLSMBO(0)::Autosklearn] Finished evaluating 15. configuration. Duration 296.898395; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:44:42,601:AutoMLSMBO(0)::Autosklearn] Finished evaluating 16. configuration. Duration 631.314885; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:47:03,866:AutoMLSMBO(0)::Autosklearn] Finished evaluating 17. configuration. Duration 140.699918; loss 1.248361; status 1; additional run info: ;duration: 140.69991755485535;num_run:00017
[INFO] [2016-09-21 08:47:09,908:AutoMLSMBO(0)::Autosklearn] Finished evaluating 18. configuration. Duration 5.625130; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:48:20,276:AutoMLSMBO(0)::Autosklearn] Finished evaluating 19. configuration. Duration 68.638045; loss 1.121470; status 1; additional run info: ;duration: 68.63804507255554;num_run:00019
[INFO] [2016-09-21 08:48:26,180:AutoMLSMBO(0)::Autosklearn] Finished evaluating 20. configuration. Duration 5.513572; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:03:45,102:AutoMLSMBO(1)::Autosklearn] Finished evaluating 3. configuration on SUBSET. Duration 5.632590; loss 1.706683; status 1; additional run info: ;duration: 5.632590055465698;num_run:00003
[INFO] [2016-09-21 08:03:46,893:AutoMLSMBO(1)::Autosklearn] Finished evaluating 4. configuration on SUBSET. Duration 1.271036; loss 1.324792; status 1; additional run info: ;duration: 1.2710356712341309;num_run:00004
[INFO] [2016-09-21 08:03:49,418:AutoMLSMBO(1)::Autosklearn] Finished evaluating 5. configuration on SUBSET. Duration 2.017542; loss 1.410159; status 1; additional run info: ;duration: 2.0175418853759766;num_run:00005
[INFO] [2016-09-21 08:03:51,062:AutoMLSMBO(1)::Autosklearn] Finished evaluating 6. configuration on SUBSET. Duration 1.116434; loss 1.682632; status 1; additional run info: ;duration: 1.116434097290039;num_run:00006
[INFO] [2016-09-21 08:05:29,458:AutoMLSMBO(1)::Autosklearn] Finished evaluating 7. configuration. Duration 35.376950; loss 1.557382; status 1; additional run info: ;duration: 35.37695002555847;num_run:00007
[INFO] [2016-09-21 08:05:35,615:AutoMLSMBO(1)::Autosklearn] Finished evaluating 8. configuration. Duration 5.719026; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:15:37,783:AutoMLSMBO(1)::Autosklearn] Finished evaluating 9. configuration. Duration 601.780182; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:16:06,883:AutoMLSMBO(1)::Autosklearn] Finished evaluating 10. configuration. Duration 27.455706; loss 1.155510; status 1; additional run info: ;duration: 27.455706357955933;num_run:00010
[INFO] [2016-09-21 08:26:37,910:AutoMLSMBO(1)::Autosklearn] Finished evaluating 11. configuration. Duration 630.596784; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:27:40,343:AutoMLSMBO(1)::Autosklearn] Finished evaluating 12. configuration. Duration 61.980831; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:27:46,407:AutoMLSMBO(1)::Autosklearn] Finished evaluating 13. configuration. Duration 5.609589; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:28:48,661:AutoMLSMBO(1)::Autosklearn] Finished evaluating 14. configuration. Duration 53.900104; loss 1.493657; status 1; additional run info: ;duration: 53.9001042842865;num_run:00014
[INFO] [2016-09-21 08:34:30,362:AutoMLSMBO(1)::Autosklearn] Finished evaluating 15. configuration. Duration 341.135119; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:45:02,217:AutoMLSMBO(1)::Autosklearn] Finished evaluating 16. configuration. Duration 631.312346; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:47:22,627:AutoMLSMBO(1)::Autosklearn] Finished evaluating 17. configuration. Duration 139.886494; loss 1.248361; status 1; additional run info: ;duration: 139.8864939212799;num_run:00017
[INFO] [2016-09-21 08:47:28,889:AutoMLSMBO(1)::Autosklearn] Finished evaluating 18. configuration. Duration 5.835405; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:48:38,444:AutoMLSMBO(1)::Autosklearn] Finished evaluating 19. configuration. Duration 67.947264; loss 1.126752; status 1; additional run info: ;duration: 67.94726419448853;num_run:00019
[INFO] [2016-09-21 08:48:44,199:AutoMLSMBO(1)::Autosklearn] Finished evaluating 20. configuration. Duration 5.379403; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:03:46,013:AutoMLSMBO(2)::Autosklearn] Finished evaluating 3. configuration on SUBSET. Duration 5.754339; loss 1.709787; status 1; additional run info: ;duration: 5.754339218139648;num_run:00003
[INFO] [2016-09-21 08:03:47,781:AutoMLSMBO(2)::Autosklearn] Finished evaluating 4. configuration on SUBSET. Duration 1.269344; loss 1.314700; status 1; additional run info: ;duration: 1.2693443298339844;num_run:00004
[INFO] [2016-09-21 08:03:50,430:AutoMLSMBO(2)::Autosklearn] Finished evaluating 5. configuration on SUBSET. Duration 2.074972; loss 1.452840; status 1; additional run info: ;duration: 2.074971914291382;num_run:00005
[INFO] [2016-09-21 08:03:51,999:AutoMLSMBO(2)::Autosklearn] Finished evaluating 6. configuration on SUBSET. Duration 0.980053; loss 1.674216; status 1; additional run info: ;duration: 0.9800529479980469;num_run:00006
[INFO] [2016-09-21 08:05:34,706:AutoMLSMBO(2)::Autosklearn] Finished evaluating 7. configuration. Duration 34.413876; loss 1.552701; status 1; additional run info: ;duration: 34.41387581825256;num_run:00007
[INFO] [2016-09-21 08:05:41,395:AutoMLSMBO(2)::Autosklearn] Finished evaluating 8. configuration. Duration 6.280138; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:15:43,486:AutoMLSMBO(2)::Autosklearn] Finished evaluating 9. configuration. Duration 601.720668; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:16:13,062:AutoMLSMBO(2)::Autosklearn] Finished evaluating 10. configuration. Duration 27.996709; loss 1.155094; status 1; additional run info: ;duration: 27.996708631515503;num_run:00010
[INFO] [2016-09-21 08:26:44,383:AutoMLSMBO(2)::Autosklearn] Finished evaluating 11. configuration. Duration 630.948807; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:27:50,836:AutoMLSMBO(2)::Autosklearn] Finished evaluating 12. configuration. Duration 65.995025; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:27:57,061:AutoMLSMBO(2)::Autosklearn] Finished evaluating 13. configuration. Duration 5.758646; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:29:07,091:AutoMLSMBO(2)::Autosklearn] Finished evaluating 14. configuration. Duration 54.405707; loss 1.528135; status 1; additional run info: ;duration: 54.40570688247681;num_run:00014
[INFO] [2016-09-21 08:34:03,172:AutoMLSMBO(2)::Autosklearn] Finished evaluating 15. configuration. Duration 295.349895; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:44:34,894:AutoMLSMBO(2)::Autosklearn] Finished evaluating 16. configuration. Duration 631.326861; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:46:54,845:AutoMLSMBO(2)::Autosklearn] Finished evaluating 17. configuration. Duration 139.394717; loss 1.248361; status 1; additional run info: ;duration: 139.39471697807312;num_run:00017
[INFO] [2016-09-21 08:47:00,875:AutoMLSMBO(2)::Autosklearn] Finished evaluating 18. configuration. Duration 5.608520; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:48:12,503:AutoMLSMBO(2)::Autosklearn] Finished evaluating 19. configuration. Duration 69.987358; loss 1.124776; status 1; additional run info: ;duration: 69.9873583316803;num_run:00019
[INFO] [2016-09-21 08:48:18,450:AutoMLSMBO(2)::Autosklearn] Finished evaluating 20. configuration. Duration 5.560100; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:03:58,214:AutoMLSMBO(3)::Autosklearn] Finished evaluating 3. configuration on SUBSET. Duration 5.847006; loss 1.687308; status 1; additional run info: ;duration: 5.847005605697632;num_run:00003
[INFO] [2016-09-21 08:04:00,096:AutoMLSMBO(3)::Autosklearn] Finished evaluating 4. configuration on SUBSET. Duration 1.431224; loss 1.291165; status 1; additional run info: ;duration: 1.4312241077423096;num_run:00004
[INFO] [2016-09-21 08:04:02,808:AutoMLSMBO(3)::Autosklearn] Finished evaluating 5. configuration on SUBSET. Duration 2.249182; loss 1.463350; status 1; additional run info: ;duration: 2.2491819858551025;num_run:00005
[INFO] [2016-09-21 08:04:04,431:AutoMLSMBO(3)::Autosklearn] Finished evaluating 6. configuration on SUBSET. Duration 1.125833; loss 1.681341; status 1; additional run info: ;duration: 1.1258330345153809;num_run:00006
[INFO] [2016-09-21 08:05:40,493:AutoMLSMBO(3)::Autosklearn] Finished evaluating 7. configuration. Duration 35.262642; loss 1.557247; status 1; additional run info: ;duration: 35.2626416683197;num_run:00007
[INFO] [2016-09-21 08:05:46,603:AutoMLSMBO(3)::Autosklearn] Finished evaluating 8. configuration. Duration 5.740623; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:15:48,121:AutoMLSMBO(3)::Autosklearn] Finished evaluating 9. configuration. Duration 601.134337; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:16:17,732:AutoMLSMBO(3)::Autosklearn] Finished evaluating 10. configuration. Duration 28.034637; loss 1.164679; status 1; additional run info: ;duration: 28.034636974334717;num_run:00010
[INFO] [2016-09-21 08:26:48,278:AutoMLSMBO(3)::Autosklearn] Finished evaluating 11. configuration. Duration 630.166757; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:27:49,232:AutoMLSMBO(3)::Autosklearn] Finished evaluating 12. configuration. Duration 60.468752; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:27:55,294:AutoMLSMBO(3)::Autosklearn] Finished evaluating 13. configuration. Duration 5.665392; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:28:56,926:AutoMLSMBO(3)::Autosklearn] Finished evaluating 14. configuration. Duration 53.525376; loss 1.519362; status 1; additional run info: ;duration: 53.52537560462952;num_run:00014
[INFO] [2016-09-21 08:33:54,362:AutoMLSMBO(3)::Autosklearn] Finished evaluating 15. configuration. Duration 296.956049; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:44:26,739:AutoMLSMBO(3)::Autosklearn] Finished evaluating 16. configuration. Duration 631.344727; loss 2.000000; status 2; additional run info:
[INFO] [2016-09-21 08:46:47,794:AutoMLSMBO(3)::Autosklearn] Finished evaluating 17. configuration. Duration 140.422540; loss 1.248361; status 1; additional run info: ;duration: 140.42253994941711;num_run:00017
[INFO] [2016-09-21 08:46:53,869:AutoMLSMBO(3)::Autosklearn] Finished evaluating 18. configuration. Duration 5.649095; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 08:48:04,608:AutoMLSMBO(3)::Autosklearn] Finished evaluating 19. configuration. Duration 68.906394; loss 1.128814; status 1; additional run info: ;duration: 68.90639448165894;num_run:00019
[INFO] [2016-09-21 08:48:11,184:AutoMLSMBO(3)::Autosklearn] Finished evaluating 20. configuration. Duration 6.143962; loss 2.000000; status 3; additional run info:

```

**Comment by Motorrat** [comment]
Watching the stderr I see the confirmation of my theory. Different seeds try exactly the same models.

`[INFO] [2016-09-21 10:01:01,460:AutoMLSMBO(5)::Autosklearn] Finished evaluating 8. configuration. Duration 5.644773; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 10:01:01,484:AutoMLSMBO(5)::Autosklearn] Starting to evaluate 9. configuration (meta-learning configuration) with time limit 600s.
[INFO] [2016-09-21 10:01:01,484:AutoMLSMBO(5)::Autosklearn] Configuration:
  balancing:strategy, Value: 'none'
  classifier:__choice__, Value: 'adaboost'
  classifier:adaboost:algorithm, Value: 'SAMME'
  classifier:adaboost:learning_rate, Value: 1.0081104516473922
  classifier:adaboost:max_depth, Value: 6
  classifier:adaboost:n_estimators, Value: 468
  imputation:strategy, Value: 'mean'
  one_hot_encoding:use_minimum_fraction, Value: 'False'
  preprocessor:__choice__, Value: 'liblinear_svc_preprocessor'
  preprocessor:liblinear_svc_preprocessor:C, Value: 1.1828431725901418
  preprocessor:liblinear_svc_preprocessor:dual, Constant: 'False'
  preprocessor:liblinear_svc_preprocessor:fit_intercept, Constant: 'True'
  preprocessor:liblinear_svc_preprocessor:intercept_scaling, Constant: 1
  preprocessor:liblinear_svc_preprocessor:loss, Value: 'squared_hinge'
  preprocessor:liblinear_svc_preprocessor:multi_class, Constant: 'ovr'
  preprocessor:liblinear_svc_preprocessor:penalty, Constant: 'l1'
  preprocessor:liblinear_svc_preprocessor:tol, Value: 0.0022792606924326923
  rescaling:__choice__, Value: 'min/max'

[INFO] [2016-09-21 10:01:13,468:AutoMLSMBO(3)::Autosklearn] Finished evaluating 8. configuration. Duration 5.595659; loss 2.000000; status 3; additional run info:
[INFO] [2016-09-21 10:01:13,486:AutoMLSMBO(3)::Autosklearn] Starting to evaluate 9. configuration (meta-learning configuration) with time limit 600s.
[INFO] [2016-09-21 10:01:13,487:AutoMLSMBO(3)::Autosklearn] Configuration:
  balancing:strategy, Value: 'none'
  classifier:__choice__, Value: 'adaboost'
  classifier:adaboost:algorithm, Value: 'SAMME'
  classifier:adaboost:learning_rate, Value: 1.0081104516473922
  classifier:adaboost:max_depth, Value: 6
  classifier:adaboost:n_estimators, Value: 468
  imputation:strategy, Value: 'mean'
  one_hot_encoding:use_minimum_fraction, Value: 'False'
  preprocessor:__choice__, Value: 'liblinear_svc_preprocessor'
  preprocessor:liblinear_svc_preprocessor:C, Value: 1.1828431725901418
  preprocessor:liblinear_svc_preprocessor:dual, Constant: 'False'
  preprocessor:liblinear_svc_preprocessor:fit_intercept, Constant: 'True'
  preprocessor:liblinear_svc_preprocessor:intercept_scaling, Constant: 1
  preprocessor:liblinear_svc_preprocessor:loss, Value: 'squared_hinge'
  preprocessor:liblinear_svc_preprocessor:multi_class, Constant: 'ovr'
  preprocessor:liblinear_svc_preprocessor:penalty, Constant: 'l1'
  preprocessor:liblinear_svc_preprocessor:tol, Value: 0.0022792606924326923
  rescaling:__choice__, Value: 'min/max'`

**Comment by mfeurer** [comment]
It seems that you're using meta-learning configurations in each of the processes. Meta-learning as implemented in auto-sklearn is deterministic, not dependend on a seed and proposes the same configurations each time it is started. Thus, the first thirty or so configurations will always be the same. If you pass the argument `initial_configurations_via_metalearning=0` to the `AutoSklearnClassifier`, you should get back the desired behaviour.

**Comment by Motorrat** [comment]
Thanks, this was it!
