### ISSUE TITLE
How do you treat the missing values?

### ISSUE THREAD

**Issue by shabir1** [automl/auto-sklearn#1360]
# How do you treat the missing values?
If the dataset contains missing values, how are you handling these missing values Are you dropping them or you are using some method to fill these missing values.

**Comment by eddiebergman** [comment]
We generally do imputation which is a hyperparameter that autosklearn tries out. For example, with numerical imputation, you can see [here](https://github.com/automl/auto-sklearn/blob/cd4fef98620cd4be599b9124f06b12a39c2c3526/autosklearn/pipeline/components/data_preprocessing/imputation/numerical_imputation.py#L65) the choices here , `["mean", "median", "most_frequent"]`

Here's the code to guide you in finding the answers in more detail:

* Our [data-preprocessors](https://github.com/automl/auto-sklearn/tree/master/autosklearn/pipeline/components/data_preprocessing)
* `CategoricalPreprocessingPipeline._get_pipeline_steps` - Applied to each categorical column
* `NumericalPreprocessingPipeline._get_pipeline_steps` - Applied to each numerical column

**Comment by eddiebergman** [comment]
That seems to be an issue in the `NoPreprocessing` doesn't work as expected. That is how we treat missing values though
