### ISSUE TITLE
Slow import of AutoSklearn2Classifier

### ISSUE THREAD

**Issue by totalhack** [automl/auto-sklearn#1362]
## Describe the bug ##

AutoSklearn2Classifier takes over a minute to import.

## To Reproduce ##

```
>>> import time
>>> start=time.time(); from autosklearn.experimental.askl2 import AutoSklearn2Classifier; print(time.time()-start)
63.7589054107666
```

## Expected behavior ##

It should be as fast as AutoSklearnClassifier.

## Environment and installation: ##

Please give details about your installation:
```
root@0d672cced72d:/app# uname -a
Linux 0d672cced72d 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 GNU/Linux

root@0d672cced72d:/app# pip freeze | grep sklearn
auto-sklearn==0.14.2
```

Python version 3.8.7

**Comment by eddiebergman** [comment]
Hi @totalhack,

That seems odd, I will try it out today and see what I can find.
