### ISSUE TITLE
`AutoML::fit_ensemble` with `ensemble_size =0` causes crash

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1365]
It seems there is no validation on `fit_ensemble` when ensemble size is `0`, causing an issue to appear as seen in #1327

**Comment by bkpcoding** [comment]
Hey, I am looking to contribute to this issue. Currently, I am going through the contributing guidelines and setting up the development environment. 
So as far as I understand the current ```show_models()``` function crashes if the ```ensemble_size = 0``` and this needs to be addressed by just returning an empty dictionary? Or there has to be an error or warning message?

**Comment by eddiebergman** [comment]
Hi @bkpcoding,

Turns out this is wrong and I think it has actually to do with `fit_ensemble(train_y, ensemble_size=0)` in the provided issue. The extra code was misleading to me and I will update the post and title.

I still think this issue might be easy enough though, having a quick look at `autosklearn/automl/AutoML::fit_ensemble` and tracing through a little bit, it seems there's no real check for the ensemble_size parameter.

If you'd like to contribute anything there, please do :)

**Comment by bkpcoding** [comment]
What exact behaviour are we expecting if ```ensemble_size = 0```? Are we supposed to show all the models trained when the ```show_models()``` function is called?

**Comment by eddiebergman** [comment]
Hey, thanks for trying to reproduce the error, the unreproducibilty of it means it's probably related to now models being found for the dataset in that time limit.

I would honestly advocate for the simplest solutions:
* `fit_ensemble` gives a ValueError with `ensemble_size = 0`.

* As for `show_models()`, I'm currently on my phone and can't easily check, but I recall it only shows Ensemble members. It would be good to extend this to all models but I think for simplicity sake, a warning and an empty dict will suffice.

I have been working on a generic backend for `auto-sklearn` and `auto-pytorch` at [automl_common](https://github.com/automl/automl_common/tree/development) which should help with model and ensemble interaction. This is in the pipeline for the end of this month so I wouldn't spend to much time on perfecting this PR.
