### ISSUE TITLE
Proper way of doing leave-one-out cross validation in auto-sklearn

### ISSUE THREAD

**Issue by pradipneupane** [automl/auto-sklearn#1377]
I have some confusion regarding the examples and documents provided in auto-sklearn. For model evaluation, we can do either Kfold or train_test_split but it is not required to do both at least not in scikit-learn as Kfold cross validation takes care of test and train itself for each folds when running. 

As example provided here in the Cross Validation section, it is using still splitted data even though the resampling strategy is set to 5Fold. https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_resampling.html#sphx-glr-examples-40-advanced-example-resampling-py

My question is that, how is the code implemented? I am not interested to check the result from the test_set only as it is quite imbalanced data set in my case and I would like to go with leave-one-out cross validation by using the full dataset and record the model evaluation. Similar to the `cross_val_score `or `cross_val_predict `in the scikit-learn. 

Can I use this kind of  similar approach: 
```
    X, y, = feature_data, target_data
    model = AutoSklearnRegressor(
        time_left_for_this_task=180,
        n_jobs=10, memory_limit=28000,
        metric=some_metrics,
        resampling_strategy='cv',
        resampling_strategy_arguments={'folds': len(y)}
    )
    # perform the search
    model.fit(X, y)
    # summarize
    print(model.sprint_statistics())
    # evaluate best model
    model.refit(X.copy(), y.copy())
    c = pd.DataFrame(model.cv_results_)
```

**Comment by eddiebergman** [comment]
Ahh, I can see from your parameters you already found that issue. For reference, iterate through the splitter's splits [here](https://github.com/automl/auto-sklearn/blob/master/autosklearn/evaluation/train_evaluator.py#L302).

[This is where](https://github.com/automl/auto-sklearn/blob/master/autosklearn/evaluation/train_evaluator.py#L1066) the CV splitter is created based on the args provided.
