### ISSUE TITLE
Category Coalescence

### ISSUE THREAD

**Issue by cristobalny** [automl/auto-sklearn#1381]
Hi, does anyone know what Category Coalescence is and how to put it on a Pipeline when building the top model?

**Comment by eddiebergman** [comment]
Hi @cristobalny,

We try category coalescence as part of the `data_preprocessing` pipeline, I'm not quite sure I know what you mean though, could you provide further context?
* What do you mean by category Coalescence?
* Do you have an implementation of what you mean?
* How would you like the code to look?

**Comment by cristobalny** [comment]
Hi @eddiebergman, I'm trying to build the best ensemble I got from auto-sklearn and retrain the model with new data to save computing time. One of the models in the ensemble uses category coalscence: minority_coalescer and I can't find this on the sklearn library.

`"'data_preprocessor:feature_type:categorical_transformer:categorical_encoding:__choice__': "
 "'one_hot_encoding', "
 "'data_preprocessor:feature_type:categorical_transformer:category_coalescence:__choice__': "
 "'minority_coalescer',
 "'data_preprocessor:feature_type:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction': "`

Thanks for your help!

**Comment by eddiebergman** [comment]
This should be possible with [`refit`](https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.refit). It seems this issue is answered but feel free to repoen if anything is unclear.
