### ISSUE TITLE
Return mulitple metrics when using cross validation

### ISSUE THREAD

**Issue by SaffronWolf** [automl/auto-sklearn#1419]
Is it possible to return multiple metrics for a model? I would like to calculate f1, accuracy, precision and recall for every fold in cross-validation and rank models using f1. One solution I think would be to use some kind of logging service and include it in scoring function, (not sure if this would work).

```
def accuracy(solution, prediction):
    # calculate f1, acc, precsion, recall
    log(f1)
    log(acc)
    return f1
```

**Comment by eddiebergman** [comment]
Hi @SaffronWolf,

Very sorry for the delay! Yes it should be possible using the `scoring_functions`. See this example: https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_calc_multiple_metrics.html#build-and-fit-a-classifier
