### ISSUE TITLE
Cannot install with conda install in docker ubuntu environment

### ISSUE THREAD

**Issue by sasshi-i** [automl/auto-sklearn#1424]
## Describe the bug ##
I can not install auto-sklearn with `conda install` in docker ubuntu environment.

## To Reproduce ##
1.  Create Dockerfile as follows.
```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y vim libpq-dev wget
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    sh Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 && \
    rm -r Miniconda3-latest-Linux-x86_64.sh
ENV PATH /opt/miniconda3/bin:$PATH
RUN conda update conda
RUN conda install python=3.7
RUN conda install -c rdkit rdkit -y
RUN conda install -c anaconda gxx_linux-64 gcc_linux-64 swig -y
RUN conda config --add channels conda-forge
RUN conda config --set channel_priority strict
RUN conda install auto-sklearn
```

2. Run  `docker build -t test .`
3. See error

## Expected behavior ##
auto-sklearn install is finished correctly.

## Actual behavior, stacktrace or logfile ##
Installation is killed in the middle of the process.
```
=> ERROR [10/10] RUN conda install auto-sklearn 
------                                                                                                                                       
 > [10/10] RUN conda install auto-sklearn:                                                                                                   
#13 1.012 Collecting package metadata (current_repodata.json): ...working... done                                                            
#13 12.92 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.                                 
#13 19.71 Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
#13 32.95 Collecting package metadata (repodata.json): ...working... Killed
------
executor failed running [/bin/sh -c conda install auto-sklearn]: exit code: 137
```

## Environment and installation: ##

Please give details about your installation:

* OS: ubuntu 20.04
* Is your installation in a virtual environment or conda environment?
-> yes. I use docker(3.6.0).
* conda version: 4.12.0
* Python version:  3.7.11
* Auto-sklearn version: Cannot install

following is `conda info` output.
```
     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.11.final.0
       virtual packages : __linux=5.10.47=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.11 Linux/5.10.47-linuxkit ubuntu/20.04.4 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```

**Comment by eddiebergman** [comment]
Hi @sasshi-i,

Apologies for the late reply. I really don't know why this is. I'm not hugely familiar with docker setups, nor with using conda. I know there was a recent enough issue with installing from conda (outside docker) but that was fixed #1256. You can continue to look through our issue for "conda" in the hopes of something that might help.

In general, we upload to PyPI (which `pip` uses) and there is a [feedstock](https://github.com/conda-forge/auto-sklearn-feedstock) for conda which non of us maintain. A contributor showed up once and set it up for us and will fix things once in a while. 

We also have a [`Dockerfile`](https://github.com/automl/auto-sklearn/blob/master/Dockerfile) that uses regular pip.

I wish I could provide more help here but I'm not sure there is much advice I can offer beyond this. Apologies.

Best,
Eddie

**Comment by mfeurer** [comment]
Ping @bastianzim as he set up the auto-sklearn conda package.

**Comment by BastianZim** [comment]
Hi everybody,

this line `#13 32.95 Collecting package metadata (repodata.json): ...working... Killed` seems like it's related to the overall conda infrastructure and not `auto-sklearn` itself as that has nothing really to do with the package.

Can you provide a more verbose log by running the command with `-vv`?

**Comment by eddiebergman** [comment]
Hi @sasshi-i,

Are you able to provide any more detais? I'll close this end of next week otherwise if there is no further feedback/issue.
