### ISSUE TITLE
[Balancing strategy] How can I disable the balancing strategy for an AutoSklearnClassifier?

### ISSUE THREAD

**Issue by johnantonn** [automl/auto-sklearn#1431]
# How can I disable the `balancing` strategy parameter for an `AutoSklearnClassifier`?

I am experimenting with CASH optimization using AutoSklearn. I use a `AutoSklearnClassifier` instance and I have disabled feature preprocessing and data preprocessing components following the provided examples, like so:

`include={`
`'classifier': classifiers,`
`    'feature_preprocessor': ['no_preprocessing'],`
`    'data_preprocessor': ['NoPreprocessing']`
`}`

However, I noticed in `cv_results` that there is an additional balancing strategy hyperparameter that results in double the evaluations  without affecting the final metrics. More specifically, it takes two values:

- `'balancing:strategy': 'none'`
- `'balancing:strategy': 'weighted'`

 The parameter is referenced in the [AutoSklearnClassifier API](https://automl.github.io/auto-sklearn/master/api.html) (screenshot provided below), but I am not quite sure how to disable it. Any ideas?

![image](https://user-images.githubusercontent.com/8168416/160133015-5b33df70-66fe-482a-b70d-519d0615e62e.png)

**Comment by johnantonn** [comment]
Hi @eddiebergman,

Thanks for the prompt response, much appreciated.

Indeed not including the `Balancing` instance inside `classification.py`, as you suggested, worked. I also tried providing the argument `strategy='none'` and keeping `Balancing` in the pipeline steps list, but  the results showed that both 'none' and 'weighted' balancing were used anyway.

I guess the code is missing a handler at this point, as you already noticed. I will update the question if I find more on this.

Best,
Giannis

**Comment by mfeurer** [comment]
Indeed, the solution by @eddiebergman is the only way to disable `balancing` that is possible right now, and there is a handler missing to do this programatically. We'll fix this together with #379 when we get there.
