### ISSUE TITLE
The pcs format does not support categorical hyperparameters with assigend weights/probabilities

### ISSUE THREAD

**Issue by juhonkang** [automl/auto-sklearn#1435]
## Describe the bug ##
Please describe the bug you're experiencing as precise as possible.
I just run the example and can't run with this error
![image](https://user-images.githubusercontent.com/67153600/160324021-db5a5006-3a9c-4f6e-9827-07ca8a233265.png)

## Environment and installation: ##

Please give details about your installation:

* OS: ubuntu
* Is your installation in a virtual environment or conda environment? Yes
* Python version: 3.9.7
* Auto-sklearn version: 0.14

**Comment by eddiebergman** [comment]
Hi @juhonkang,

Could you please put this into one of the cells and post the output here? We recently updated ConfigSpace, the library that handles hyperparameters for us but I made sure that autosklearn doesn't use it. You should expect to see `ConfigSpace v0.4.21` but I'm expecting from that error that you have `ConfigSpace v0.5.0`.

```
!pip list
```

You can forcibly install the earlier version of ConfigSpace with `!pip install ConfigSpace==0.4.21`

Best,
Eddie
