### ISSUE TITLE
Is there a way to retrieve feature importance for the ensemble classifier?

### ISSUE THREAD

**Issue by zkliesmete** [automl/auto-sklearn#1437]
I have tried different inputs for the auto-sklearn classification pipeline and found the best set of features and parameters that seem to work well for what I am trying to predict. Is there any way to pull out the individual predictor importance for the ensemble classifier? Or, alternatively, freeze the ensemble classifier parameter settings and do predictions while iteratively leaving 1 predictor variable out? 

Something in this range for model evaluation would be highly appreciated. I apologise deeply in case this is already clearly stated somewhere in the documentation, I did search for this but I am still new to automl and auto-sklearn and have maybe overseen something.

Thank you!

Best wishes,
Zane

**Comment by eddiebergman** [comment]
Hi @zkliesmete,

This is currently not a built in feature but you can find an example of how do so with sklearn here near the bottom:
* https://github.com/automl/auto-sklearn-talks/blob/main/2021_07_28_EuroPython/Tutorial.ipynb 

This gives an overall idea to the `automl` instance as a whole but not for specific models.

On a per model level, this is harder to achieve. Some models such as Random Forest may give some model-level idea of feature importance but this is unique to certain models and not something we can generalize. Given that the end result is a weighted ensemble, which may contain some of these "interoperable" models and some that aren't, I'm not sure how to feasible give a number that says "Feature x is has y importance".

Best,
Eddie

**Comment by mfeurer** [comment]
The feature importances are also available in [this example](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_inspect_predictions.html). The permutation importance example appears to be exactly what you are looking for.

I agree on @eddiebergman's comment that the models are all different and we cannot put their individual interpretations of what is an important feature together (especially given that some models might use preprocessing that changes the features). However, if you want to know more about your models, you can inspect them individually: https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_get_pipeline_components.html#inspect-the-components-of-the-best-model
