### ISSUE TITLE
No successful configuration due to `Directory not empty` when saving run to the runs directory in autosklearn 2

### ISSUE THREAD

**Issue by ravinkohli** [automl/auto-sklearn#1438]
## Describe the bug ##
I am trying to run autosklearn2 on openml tasks. However, all of the configurations that are found during search are crashing with `FileNotFoundError(2, 'No such file or directory')`.

## To Reproduce ##
```
    gb_autosklearn = AutoSklearn2Classifier(
        tmp_folder=os.path.join(args.exp_dir, 'autosklearn'),
        delete_tmp_folder_after_terminate=False,
        metric=balanced_accuracy,
        )
    gb_autosklearn.fit(X_train.copy(), y_train.copy(), dataset_name=dataset.name)
    print(gb_autosklearn.sprint_statistics())
    y_test_pred = gb_autosklearn.predict(X_test)
    y_train_pred = gb_autosklearn.predict(X_train)

    train_acc = balanced_accuracy_score(
        y_train,
        y_train_pred,
    )
    test_acc = balanced_accuracy_score(
        y_test,
        y_test_pred,
    )

    information = {
        'train_acc': train_acc,
        'test_acc': test_acc,
    }
    create_dir(result_directory)
    with open(os.path.join(result_directory, 'final_result.json'), 'w') as file:
        json.dump(information, file)
```

## Actual behavior, stacktrace or logfile ##
This error is repeated for all configurations.
 ```
 os.rename(tmpdir, self.get_numrun_directory(seed, idx, budget))
OSError: [Errno 39] Directory not empty: './ask/working_dir/autosklearn/.auto-sklearn/runs/tmpv1fk11u2' -> './ask/working_dir/autosklearn/.auto-sklearn/runs/11_76_6.25'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/evaluation/__init__.py\", line 42, in fit_predict_try_except_decorator
  return ta(queue=queue, **kwargs)
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py\", line 1408, in eval_iterative_cv
    eval_cv(
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py\", line 1383, in eval_cv
    evaluator.fit_predict_and_loss(iterative=iterative)
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py\", line 459, in fit_predict_and_loss
    self.finish_up(
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/evaluation/abstract_evaluator.py\", line 365, in finish_up
    file_out_loss, additional_run_info_ = self.file_output(
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/evaluation/abstract_evaluator.py\", line 508, in file_output
    self.backend.save_numrun_to_dir(
  File \"/home/ravin/anaconda3/envs/autosklearn-env/lib/python3.9/site-packages/autosklearn/automl_common/common/utils/backend.py\", line 486, in save_numrun_to_dir
    os.rename(
FileNotFoundError: [Errno 2] No such file or directory: './ask/working_dir/autosklearn/.auto-sklearn/runs/11_76_6.25' -> './ask/working_dir/autosklearn/.auto-sklearn/runs/./ask/working_dir/autosklearn/.auto-sklearn/runs/tmpv1fk11u2.old'"
```

## Environment and installation: ##

Please give details about your installation:

* OS- Ubuntu 20.04
* Is your installation in a virtual environment or conda environment? Conda
* Python version- 3.8
* Auto-sklearn version- 0.14.6

**Comment by eddiebergman** [comment]
It seems like this is a multi-processing issue, I have no real idea what is causing issue here:
* Could be that there are two runs evaluated with the same budget, meaning when trying to do `os.rename(src, dst)`, it can't delete `dst` as it's already populated.
* Could be that there is some process stuck doing something in `src` meaning it can't be deleted as part of the rename.

Given the code is from a `try: catch` [statement](https://github.com/automl/automl_common/blob/main/common/utils/backend.py#L483) and the only file consistent in both is the non tmp one, I would hazard a guess it's the first issue.

I've reworked ensemble builder in autosklearn at the moment, just writing tests. I will try to address it there but I don't see any quick fix. It's also weird this hasn't been reported before if it's happening for all your runs. It also seems to be autosklearn2 specific, in which case the only difference is the budget part which I assume SMAC handles.

@mfeurer thoughts?

Best,
Eddie

**Comment by mfeurer** [comment]
This is indeed a weird error. I have no idea why it has not happened before. 

From @ravinkohli's code it appears that there is no multi-processing so I am not 100% sure if @eddiebergman's first suggestion can be the culprit?

What I wonder right now, why is the path it tries to rename to in the 2nd error message (`'./ask/working_dir/autosklearn/.auto-sklearn/runs/./ask/working_dir/autosklearn/.auto-sklearn/runs/tmpv1fk11u2.old'`) so weird? Maybe it doesn't find the directory `'./ask/working_dir/autosklearn/.auto-sklearn/runs/./ask/working_dir/autosklearn/.auto-sklearn/runs'` it tries to rename to and fails because of that?

**Comment by eddiebergman** [comment]
The path is definitely with the extra `.` in the middle.

It occurs in the `catch` and the renaming is essentially to move it and then delete it. I'm not sure why this is done because it's not really much safer than deleting it.

**Comment by eddiebergman** [comment]
Hey @ravinkohli,

Is `args.exp_dir` a relative path or an absolute one? We think it might be related to path expansions and relative paths.

Best,
Eddie

**Comment by ravinkohli** [comment]
Okay I think it was because of the relative path. I tried to run it without passing a tmp directory and it all worked fine. Thanks for your replies. I'll close this issue.
