### ISSUE TITLE
Non-breaking ERROR printed: "init_dgesdd failed init" while running AutoSklearnClassifier

### ISSUE THREAD

**Issue by teresa-m** [automl/auto-sklearn#1439]
## Describe the bug ##

Hi,

I am getting the Error 'init_dgesdd failed init' when I perform longer runs (> 46000 s) of the AutoSklearnClassifier. My dataset has the shape (42589, 26). The call still results in an optimized model. So I suspect that only some optimization runs are failing. The AutoSklearnClassifier is called like this:

```
 estim = AutoSklearnClassifier(
            n_jobs = 6,
            ensemble_size = 1,
            memory_limit = 8000,
            time_left_for_this_task = 46000,
            metric = autosklearn.metrics.f1,
            max_models_on_disc = 1
            )
```

also if the n_jobs are reduced to 2 and the memory limit is increased this error occurs. Also running my code on an instance with more total memory. 
Googling this issue suggested that this happens in numpy if the memory limits are exceeded. Do you have an idea why and where this could happen? Thanks a lot for your help!

## To Reproduce ##
I was using this script
1. Go to https://github.com/smautner/biofilm/blob/master/biofilm/biofilm-optimize6.py

calling it like this:
```
python -W ignore -m biofilm.biofilm-optimize6  --infile /home/uhlm/Dokumente/Teresa/build_model_with_graph_featurs//PARIS_human_RBP/feature_files/training_data_PARIS_human_RBP_context_150  --featurefile /home/uhlm/Dokumente/Teresa/build_model_with_graph_featurs/PARIS_human_RBP//model//features/PARIS_human_RBP_context_150 --memoryMBthread 10000 --folds 0 --out /home/uhlm/Dokumente/Teresa/build_model_with_graph_featurs/PARIS_human_RBP/model/optimized/PARIS_human_RBP_context_150 --preprocess True --n_jobs 6 --time 50000
```

## Expected behavior ##
I am not sure if this error is due to my OS. I did test it on 3 different instances two with 64 GB and one with 128 GB memory. 

## Actual behavior, stacktrace or logfile ##
my output:
```
ERROR: init_dgesdd failed init
init_dgesdd failed init
init_dgesdd failed init
init_dgesdd failed init
init_dgesdd failed init
init_dgesdd failed init
Traceback (most recent call last):
  File "/home/uhlm/Progs/anaconda3/envs/cherri/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/uhlm/Progs/anaconda3/envs/cherri/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/uhlm/Progs/anaconda3/envs/cherri/lib/python3.8/site-packages/biofilm/biofilm-optimize6.py", line 82, in <module>
    main()
  File "/home/uhlm/Progs/anaconda3/envs/cherri/lib/python3.8/site-packages/biofilm/biofilm-optimize6.py", line 78, in main
    print('\n',pipeline.steps[2][1].choice.preprocessor.get_support())
AttributeError: 'PolynomialFeatures' object has no attribute 'get_support'

For call: python -W ignore -m biofilm.biofilm-optimize6  --infile /home/uhlm/Dokumente/Teresa/build_model_with_graph_featurs//PARIS_human_RBP/feature_files//training_data_PARIS_human_RBP_context_150  --featurefile /home/uhlm/Dokumente/Teresa/build_model_with_graph_featurs//PARIS_human_RBP//model//features/PARIS_human_RBP_context_150 --memoryMBthread 10000 --folds 0 --out /home/uhlm/Dokumente/Teresa/build_model_with_graph_featurs//PARIS_human_RBP//model//optimized/PARIS_human_RBP_context_150 --preprocess True --n_jobs 6 --time 50000
adding .npz to filename
optimization datatype: <class 'numpy.ndarray'>
[WARNING] [2022-04-07 11:03:42,882:Client-AutoML(1):9aaebae0-b651-11ec-8fe3-901b0eb924fa] Capping the per_run_time_limit to 24999.0 to have time for a least 2 models in each process.
adding .npz to filename
```

## Environment and installation: ##

I am running the code on Ubuntu 20.04.4 LTS and a conda enviormat with:
python                    3.8.12          ha38a3c6_3_cpython    conda-forge
auto-sklearn              0.14.2             pyhd8ed1ab_0    conda-forge

**Comment by eddiebergman** [comment]
Hi @teresa-m,

Unfortunatly I do not know which model is causing this error exactly but you're right in that it seems to be a numpy related issue, which probably stems from one of the sklearn models being trained.

What happens is that we create a new process for each model as it's being trained. If one of these models fails (with an error like above), then we just say it's not viable and move on to try the next one. I don't believe it's something we can fix, other than to try "eat" and hide the output. However I don't think this is a good idea as we may end up hiding something useful.

Some extra printing happening during training to indicate where these errors stem from and that they can be ignored might be a useful addition though :)

If you're okay with it, I'm going to close this as it's not an Issue we can really do anything about and does not impact the running of auto-sklearn.

The only other useful information I might ask is if you somehow know which model causes it. Looking at your proided script where you use `max_models_on_disk=1`, it's likely been deleted so any obvious trace of it is gone. Don't worry too much if ypu don't know, these issues tend to come and go as numpy and sklearn change and optimize. 

#### Extra Note
It seems (as mentioned) that the run will continue to completion.
The Traceback with your ValueError seems to be a part of your [code](https://github.com/smautner/biofilm/blob/master/biofilm/biofilm-optimize6.py#L87) which I wan't to advertise to future viewers and is not a problem with auto-sklearn, it just chose a different feature_preprocessor which doesn't have the method `get_support`.

Best,
Eddie

**Comment by teresa-m** [comment]
Hi @eddiebergman,
thanks a lot for your clarification. Yes, I catch everything in strerr and print it as error for my information. Therefore it is good to know that we can ignore this error. 
Unfortunately, we can not track down which of the modifications were failing. 
I would be fine if you close the issue. 
Best,
Teresa
