### ISSUE TITLE
Custom data preprocessing (code from the example) not working n_jobs>1

### ISSUE THREAD

**Issue by seraus** [automl/auto-sklearn#1443]
## Describe the bug ##
Trying to use my custom data preprocessing and feature preprocessing with auto-sklearn, I started with this code:
https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_data_preprocessor.html#sphx-glr-examples-80-extending-example-extending-data-preprocessor-py

but it seems not to work when I use "n_jobs>1".

## To Reproduce ##
1) copy the whole code of 
https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_data_preprocessor.html#sphx-glr-examples-80-extending-example-extending-data-preprocessor-py
in a python notebook
2) add n_jobs=4 in the constructor 

clf = autosklearn.classification.AutoSklearnClassifier( ...)

## Expected behavior ##

print meaningful accuracy (with n_jobs=1 it's about 0.97)
 
no errors

## Actual behavior, stacktrace or logfile ##
```
print("accuracy: ", sklearn.metrics.accuracy_score(y_pred, y_test))
accuracy:  0.27972027972027974

pprint(clf.show_models(), indent=4)
RuntimeError: No model found. Try increasing 'time_left_for_this_task'

for runkey, runval in clf.automl_.runhistory_.data.items():
    print(runval)

RunValue(cost=1.0, time=0.08638882637023926, status=<StatusType.CRASHED: 3>, starttime=1650362064.2901857, endtime=1650362064.447507, additional_info={'traceback': 'Traceback (most recent call last):\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/evaluation/__init__.py", line 42, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/evaluation/train_evaluator.py", line 1175, in eval_holdout\n    evaluator = TrainEvaluator(\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/evaluation/train_evaluator.py", line 183, in __init__\n    super().__init__(\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 284, in __init__\n    self.model = self._get_model()\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 305, in _get_model\n    model = self.model_class(config=self.configuration,\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/pipeline/classification.py", line 85, in __init__\n    super().__init__(\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/pipeline/base.py", line 52, in __init__\n    self._validate_include_exclude_params()\n  File "/workspace/condaenv/automl/lib/python3.8/site-packages/autosklearn/pipeline/base.py", line 501, in _validate_include_exclude_params\n    **raise ValueError("The provided component \'{}\' for the key \'{}\' in the \'{}\'"\nValueError: The provided component \'NoPreprocessing\' for the key \'data_preprocessor\' in the \'include\' argument is not valid. The supported components for the step \'data_preprocessor\' for this task are [\'feature_type\']\n', 'error': 'ValueError("The provided component \'NoPreprocessing\' for the key \'data_preprocessor\' in the \'include\' argument is not valid. The supported components for the step \'data_preprocessor\' for this task are [\'feature_type\']")', 'configuration_origin': 'Default'})**
```

## Environment and installation: ##

Please give details about your installation:

* OS debian bullseye/sid
* conda environment  
* python 3.8
* auto-sklearn==0.14.6
* Jupyter Notebook

**Comment by eddiebergman** [comment]
Hey @seraus,

Thanks for this, I would guess it's due to the fact it's in a jupyter notebook where parallelizing stuff is quite weird. Normally we require a `if __name__ == "__main__":` gaurd. It's not actually a requirement of ours but of `dask` which handles parallelism. Could you try in just a regular python file and see if it works?

As a side note, I included that your code is running in a jupyter notebook in the original issue.

@mfeurer I assume this is related to #1295?

Best,
Eddie

**Comment by seraus** [comment]
Hello Eddie,

I'll try in a regular python file and let you know, but I can tell you this: 

with the following code (n_jobs=4, without the code for excluding data_preprocessing), all is running fine in jupyterlab

import sklearn
from pprint import pprint

#automl
import autosklearn.classification


#from autosklearn.experimental.askl2 import AutoSklearn2Classifier
#automl = AutoSklearn2Classifier(time_left_for_this_task=120, n_jobs=4)
automl = autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=120, per_run_time_limit=30, n_jobs=4,
                                                          memory_limit=5120, 
                                                          tmp_folder='/workspace/automl/titanic/src/python/titanic/tmp',
                                                          delete_tmp_folder_after_terminate=False,
                                                          resampling_strategy='cv',
                                                          resampling_strategy_arguments={'folds':10},
                                                          ensemble_size=50,
                                                          metric=autosklearn.metrics.f1_macro,
                                                          scoring_functions=[autosklearn.metrics.accuracy,
                                                                             autosklearn.metrics.precision,
                                                                             autosklearn.metrics.recall,
                                                                             autosklearn.metrics.f1_macro])

automl.fit(X_train, y_train, X_test, y_test, dataset_name='titanic')
y_hat = automl.predict(X_test)
