### ISSUE TITLE
the code of example_extending_regression can not run successfully

### ISSUE THREAD

**Issue by belzheng** [automl/auto-sklearn#1453]
## Describe the bug ##
when I run this extending example,it reported error in 'Fit the model using KRR' ,and the error is:
'[ERROR] [2022-05-01 20:40:45,872:Client-AutoML(1):e67085f2-c94b-11ec-8f82-012d09f79750] Dummy prediction failed with run state StatusType.MEMOUT and additional output: {'error': 'Memout (used more than 3072 MB).', 'configuration_origin': 'DUMMY'}.'

## To Reproduce ##
1. Go to '(https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_regression.html#sphx-glr-examples-80-extending-example-extending-regression-py)''
2. See error

## Environment and installation: ##

Please give details about your installation:

* OS
* Is your installation in a virtual environment or conda environment?   I installed in a virtual environment
* Python version 3.9
* Auto-sklearn version

**Comment by eddiebergman** [comment]
Hi @belzheng,

Sorry to hear you had issues, how much RAM do you have and cpu cores?
In general, we divide the memory so that each job [core] gets (RAM/jobs) amount of memory.

You can try [setting explicit memory limits ](https://automl.github.io/auto-sklearn/master/manual.html#resource-limits) so you don't get this error.

**Comment by belzheng** [comment]
> Hi @belzheng,
> 
> Sorry to hear you had issues, how much RAM do you have and cpu cores? In general, we divide the memory so that each job [core] gets (RAM/jobs) amount of memory.
> 
> You can try [setting explicit memory limits ](https://automl.github.io/auto-sklearn/master/manual.html#resource-limits) so you don't get this error.

**Comment by belzheng** [comment]
thanks, but now here is the problem,it reports 'type error' in the same code:
'__init__() got an unexpected keyword argument 'include'' 
I wondered if there was something wrong in the function?
![bug](https://user-images.githubusercontent.com/91657801/166209018-85d4de22-53f3-43d0-8ca7-a34b7a929037.PNG)

**Comment by eddiebergman** [comment]
What version of `autosklearn` are you using? You can run
`!pip list` in your notebook to find out

**Comment by belzheng** [comment]
> What version of `autosklearn` are you using? You can run `!pip list` in your notebook to find out

Its version is 0.12.7

**Comment by eddiebergman** [comment]
Ahh okay, you're using a very outdated version, try `pip install auto-sklearn==0.14.7` for a more up to date version. Unfortunatly we do not have older documentation available and I was not around to know what the parameter name was back then.

**Comment by belzheng** [comment]
![bug](https://user-images.githubusercontent.com/91657801/166215196-14814823-35ba-4dac-b364-21bb5c4b7a11.PNG)
there is no version that match 0.14.7,and when I try to install 0.14.6,error appeared like this :
![bug](https://user-images.githubusercontent.com/91657801/166215923-88a013fb-59cd-4818-9db4-6c5c7fcde2b1.PNG)
what am I supposed to do now?

**Comment by eddiebergman** [comment]
Sorry `0.14.7` wasn't realeased to PyPi (where pip gets packages from).

As for why you can't install `0.14.6`, I don't know but it doesn't look like an autosklearn issue, it seems more like a network issue with whever you're running your notebook. Can you install any other packages from PyPi? You can try with a random package like `typing_extensions`. The `--no-cache-dir` means don't use the cache and download it fresh.

`pip uninstall typing_extensions -y; pip install --no-cache-dir typing_extensions`

**Comment by belzheng** [comment]
There is no problem installing other packages,you can see :
![bug](https://user-images.githubusercontent.com/91657801/166232727-8f7b8952-b72b-4f24-a050-af357722421e.PNG)
but the problem with installing 0.14.6 still exists,how to solve it ?

**Comment by belzheng** [comment]
> Hi @belzheng,
> 
> Sorry to hear you had issues, how much RAM do you have and cpu cores? In general, we divide the memory so that each job [core] gets (RAM/jobs) amount of memory.
> 
> You can try [setting explicit memory limits ](https://automl.github.io/auto-sklearn/master/manual.html#resource-limits) so you don't get this error.

I have installed the 0.14.6 version of auto-sklearn,but the problem gets back to the original one,i.e:
![bug](https://user-images.githubusercontent.com/91657801/166236073-5817c847-73f7-4983-9c7e-b974dc1c7b23.PNG)
And I want to know how to  setting explicit memory limits in my code ?

**Comment by eddiebergman** [comment]
Please read our [documentation that I linked earlier](https://automl.github.io/auto-sklearn/master/manual.html#resource-limits) on how and why to do that.

You should be aware of how much RAM you have available. If you're using your own dataset instead of the example one, you may run into issues.

The code output generated in the example is from automatic runs that happen on github actions servers which have 4GB of RAM so I'm not sure why that would be an issue here.

**Comment by belzheng** [comment]
When I ran the example code for regression and classification with or without extending(4 cases), they all reported the same error,i.e:
![clf](https://user-images.githubusercontent.com/91657801/166698220-2ff743ce-6eba-4607-8193-8de37f46f854.PNG)
![clfext](https://user-images.githubusercontent.com/91657801/166698247-5dc048c8-434d-4705-b76e-ab162da83379.PNG)
![reg](https://user-images.githubusercontent.com/91657801/166698272-c53a45df-902c-496e-a8aa-f7ee4dd98477.PNG)
![regext](https://user-images.githubusercontent.com/91657801/166698297-d6f103b9-22aa-422e-ab22-7ea1e5e8479e.PNG)
I would like to ask if this is because of the version, by the way, when is 0.14.7 expected to be released?

**Comment by eddiebergman** [comment]
I released the hotfix version `0.14.7` today, it should no longer have issues with conflicting requirements if installed in a new virtual environment.

> And I want to know how to setting explicit memory limits in my code ?
In general, the best place to view documentation (for any library) is their API docs, it lets you know exactly what paremeters you can and can't set. [Here is our's](https://automl.github.io/auto-sklearn/master/api.html#classification)

As mentioned previously, have you checked how much RAM you have available and setting a memory limit? It's hard to tell whether your machine has limited memory and `3072` which is the default is too much for your system. If you have more than 4GB then it should be fine. You also never have your OS in the original issue, that would help to know as limiting memory is quite unstable on Mac and would help us debug things.

**Comment by belzheng** [comment]
Thanks a lot, the problem is finally solved by setting 'memory_limit=6144',as you can see:
![suc](https://user-images.githubusercontent.com/91657801/166881115-5190b025-2bc8-4c46-a8cb-123f5fbdef43.PNG)

**Comment by eddiebergman** [comment]
No problem, that seems like a large memory limit and I'll have to investigate why this is, I'll leave this open until I figure out if it's some autosklearn issue.

**Comment by eddiebergman** [comment]
I'm going to actually close this issue and tag you and this issue in a different thread more specific to the Memory related issue. Notably it's in #1460
