### ISSUE TITLE
ImportError while import the auto-sklearn

### ISSUE THREAD

**Issue by HuangChiEn** [automl/auto-sklearn#1456]
I got the Import Error while importing the auto-sklearn package.

> ImportError: cannot import name 'BetaFloatHyperparameter' from 'ConfigSpace.hyperparameters'

How can i solve it by downgrade the version of auto-sklearn?
Since I can not change the other package version just for fitting auto-sklearn requirements.

PS. Seems simply install auto-sklearn by pip install auto-sklearn is not the recommended way.

![image](https://user-images.githubusercontent.com/52521165/166638973-7e0f4ee6-96ce-4213-8fd6-28fb1ef94165.png)

**Comment by mfeurer** [comment]
This cannot be solved by downgrading the version of Auto-sklearn. Instead, you need to either downgrade the version of `smac` to < 1.3.X or upgrade the ConfigSpace to >= 0.5.0.

**Comment by eddiebergman** [comment]
Sorry, I meant to make a release with the requirements fixed, this has been done and is available on PyPi now, `pip install auto-sklearn` should install `0.14.7` which has this fixed. you might need to make a fresh virtual env. Closing for now but re-open if it's still an issue

**Comment by HuangChiEn** [comment]
> 

Thank you very much~ the problem is solved ~
![image](https://user-images.githubusercontent.com/52521165/166849059-02545aa0-3ae7-4706-a513-86ed07862f1a.png)
