### ISSUE TITLE
[Question] When I disable meta-learning, how Auto-Sklearn selects initial configurations to evaluate?

### ISSUE THREAD

**Issue by jmren168** [automl/auto-sklearn#1463]
Hi Auto-Sklearn team,

It looks like I can set initial_configurations_via_metalearning=0 to disable meta-learning. If this is correct, then how auto-sklearn selects initial configurations to evaluate? Random selection? Or try all possible combinations of data preprocessors, feature preprocessors, and models?

`automl = autosklearn.classification.AutoSklearnClassifier(
    ensemble_size=1,
    initial_configurations_via_metalearning=0
)`

The above code makes auto-sklearn use the regular SMAC algorithm for suggesting new hyperparameter configurations. 
If so, how auto-sklearn selects initial data preprocessors, feature preprocessors and models in order to make SMAC suggest new hyperparameter configuations?

Thanks in advance.

Ref: https://automl.github.io/auto-sklearn/master/manual.html

**Comment by eddiebergman** [comment]
Hi @jmren168,

I did some quick following of the parameter `initial_configurations_via_metalearning` through the code and essentially this gets turned into some configs that SMAC will use to evaluate first. In the case where this is `0`, no initial configurations are passed to SMAC in which case SMAC will use whatever it's default strategy is when it has no information about configuration performance. As far as I'm aware, this is just random sampling for the first few configurations.

Using the answer in #1462, you can inspect the run history and see if a configuration was randomly sampled or selected according to SMAC's acquisition function, which it uses to sample configurations more likely to perform well.

In essence, we can provide intial configurations to SMAC and setting this to `0` means we go with SMAC's behaviour which is random sampling to start.

Best,
Eddie

**Comment by jmren168** [comment]
Hi @eddiebergman,

Following your guides, I set `initial_configurations_via_metalearning` to 0, and found that SMAC uses `'Local Search', 'Random Search', and 'Random Search (sorted)'` to initialize the configuration search. Here's the code [colab example](https://colab.research.google.com/drive/1qBj9iPcAhfduno7t6M1-w0BRupPJfAAV#scrollTo=V_Q2_R4ZlAS5). 

Again, I still got confused with the number of pipelines and the number of iterations evaluated in autosklearn as mentioned in https://github.com/automl/auto-sklearn/issues/1462#issuecomment-1120139550. Hope you could give some hits to these questions. Many thanks.

Best,
JM

**Comment by eddiebergman** [comment]
Hi @jmren168,

I will close this issue then and answer in the other issue!

Best,
Eddie
