### ISSUE TITLE
Dummy prediction failed with "Directory not empty"

### ISSUE THREAD

**Issue by 18756** [automl/auto-sklearn#1469]
that's my code:

```
automl = autosklearn.regression.AutoSklearnRegressor(
        time_left_for_this_task=68400,
        per_run_time_limit=1800,
        memory_limit=4096,
        ensemble_size=10,
        metric=autosklearn.metrics.mean_squared_error,
        resampling_strategy='holdout',
        resampling_strategy_arguments={'train_size': 0.8}
    )
automl.fit(X_train, y_train, dataset_name='features')
```

every time running the script, I get this error:

[ERROR] [2022-05-10 23:52:51,268:Client-AutoML(1):features] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/nfs/home/asmirnov/anaconda3/lib/python3.8/site-packages/autosklearn/evaluation/__init__.py", line 350, in run\n    obj(**obj_kwargs)\n  File "/nfs/home/asmirnov/anaconda3/lib/python3.8/site-packages/pynisher-0.6.4-py3.8.egg/pynisher/limit_function_call.py", line 302, in __call__\n    tmp_dir.cleanup()\n  File "/nfs/home/asmirnov/anaconda3/lib/python3.8/tempfile.py", line 831, in cleanup\n    self._rmtree(self.name)\n  File "/nfs/home/asmirnov/anaconda3/lib/python3.8/tempfile.py", line 813, in _rmtree\n    _shutil.rmtree(name, onerror=onerror)\n  File "/nfs/home/asmirnov/anaconda3/lib/python3.8/shutil.py", line 722, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File "/nfs/home/asmirnov/anaconda3/lib/python3.8/shutil.py", line 720, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \'/mnt/tank/scratch/asmirnov/automl/auto-sklearn/tree_new_features_nan_rug/day_24/tmp4bi2oojt\'\n', 'error': "OSError(39, 'Directory not empty')"}.

so, I set up tmp_folder and error was gone

**Comment by eddiebergman** [comment]
Hi @18756,

Sorry for the delay and sorry to hear about that. I'm not sure why that would be, it seems from the system you're running on, the `tmp` dir is relatively unique from what we normally expect, i.e. you have `'/mnt/tank/scratch/asmirnov/automl/auto-sklearn/tree_new_features_nan_rug/day_24/tmp4bi2oojt'`.

We will release a new `pynisher` version soon (where this error occured) that does not deal with temporary directories and hopefully this should fix your issue. I'm glad you managed to find a solution that worked for you in the meantime.

I'm going to close this as I think it's something to do with your system setup and how pythongs [`tempfile.TemporaryDirectory::cleanup`](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) interact. We could pass a parameter there that ignores errors but it's not something we will handle as we no longer need this in the new Pynisher version.

Best,
Eddie
