### ISSUE TITLE
[Dev only] MOO ensemble can fail to return pareto front if automl instance consutrcted with single metric 

### ISSUE THREAD

**Issue by eddiebergman** [automl/auto-sklearn#1496]
If constructing the automl instance with only a single metric but then using multiple metrics during ensemble, querying for the pareto front will fail with:
```python
File "/home/skantify/code/automlbenchmark-fairness-private/frameworks/autosklearn_moo/lib/auto-sklearn/autosklearn/automl.py", line 1656, in _load_pareto_set
    raise ValueError("Pareto set is only available for two or more metrics.")
```

**Comment by eddiebergman** [comment]
I guess this is an odd case and doesn't seem easy to fix, I'll close

**Comment by mfeurer** [comment]
Couldn't we fix this case by checking if the loaded ensemble is a multi-objective ensemble instead of checking if we have multiple metrics?

**Comment by eddiebergman** [comment]
That's an easy fix for sure, but the issue also lies in the fact that the point of entry for metrics is at `__init__` time.

If you wish to have single objective SMAC runs, you pass in a single objective. Any `Ensembler` is then lmited to this one metric and it makes no sense to have a multiobjective one. I guess the easiest workaround is allow `fit_ensemble` to take `metrics`?

How does this sound?
```python
automl = AutoSklearnCalssifier(metric=acc, ensemble=None)

automl.fit(X, y)

automl.fit_ensemble(X, y, metrics=[acc, auc])
```

**Comment by mfeurer** [comment]
That sounds good. I somehow assumed `fit_ensemble` accepts `metric`, but apparently, it doesn't.
