### ISSUE TITLE
Silence subprocesses

### ISSUE THREAD

**Issue by brianmingus** [automl/auto-sklearn#15]
This generates gobs of output. Need a silent mode. Standard context manager approaches to hiding stdout don't work here.

**Comment by mfeurer** [comment]
Have a look at the development branch. It's much less verbose. I'll merge it to the master branch soon.

**Comment by mfeurer** [comment]
Subprocess is silent as of 5c884ee3afb2dac6bebd922bc9b0101c06dd899a (currently only on the development branch).
