### ISSUE TITLE
[Question] How to get the number of target algorithm runs without fitting data?

### ISSUE THREAD

**Issue by jmren168** [automl/auto-sklearn#1502]
Hi there,

To get the number of target algorithm runs, auto-sklearn needs to fit data, and finally call `sprint_statistics()`. Is there any other way to get the number of target algorithm runs without fitting data? Since in my case, it just got 10 runs under **time_left_for_this_wask=3600**. To evaluate more runs. I know I could increase the time limit. In addition to do in this way, does anyone know how auto-sklearn decides the number of target algorithm runs?

Thanks a lot.

**Comment by eddiebergman** [comment]
Hi @jmren168, the number of pipelines evaluated is random so you can't know without fitting to data. For example, consider a dataset with only 100 points, it's a lot faster to fit models so more will be done. Compare this with a massive dataset, fitting pipelines will take more time, hence we can't know ahead of time.

You can control the time limit per run with `per_run_time_limit` which defaults to being a tenth of the total time. If a pipeline finishes earlier, great, then autosklearn evaluates more. See the API here: https://automl.github.io/auto-sklearn/master/api.html

Best,
Eddie

**Comment by jmren168** [comment]
Hi @eddiebergman,

After reading the paper you mentioned, there are 4 types of SMAC3, which one is really implemented in autosklearn? Some of them? All of them? Thanks.

**SMAC4BB**: SMAC for Low-dimensional and Continuous Black-Box Functions
**SMAC4HPO**: SMAC for CASH and Structured Hyperparameter Optimization
**SMAC4MF**: SMAC for Expensive Tasks and Automated Deep Learning
**SMAC4AC**: SMAC for Algorithm Configuration
