### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [automl/auto-sklearn#1568]
I tried pip install auto-sklearn and the error is below:

Collecting auto-sklearn
  Downloading auto-sklearn-0.14.7.tar.gz (6.4 MB)
     ---------------------------------------- 6.4/6.4 MB 19.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\nguye\AppData\Local\Temp\pip-install-u3x1d6ld\auto-sklearn_80bc9e982dee4994954cc5e0da5bba81\setup.py", line 9, in <module>
          raise ValueError(
      ValueError: Detected unsupported operating system: win32. Please check the compability information of auto-sklearn: https://automl.github.io/auto-sklearn/master/installation.html#windows-osx-compatibility
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Daniel-Trung-Nguyen** [comment]
Ah, saw the installation guide. I was installing it on a windows machine

**Comment by ojeifoissy** [comment]
Hello Daniel I tried installing with anaconda and getting the same problem. Even when I followed the guidelines

**Comment by mfeurer** [comment]
Dear @ojeifoissy, please open a new github issue if this problem persists as we are not tracking and answering closed issues.
