### ISSUE TITLE
Feature request: handle pandas

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#157]
Issued by @yasserabbass in [#79](https://github.com/automl/auto-sklearn/issues/79#issuecomment-251619422).

**Comment by Motorrat** [comment]
Pandas proved to be very handy for datasets that are available in a tabular form. So it would be great to see auto-sklearn to be able to interface it directly. Currently I just have to do ```
X=dataframe.drop(['id','category'], axis=1).values
y = pd.np.array(dataframe['category'], dtype='int')
```
to pass it to auto-sklearn as arrays

**Comment by Motorrat** [comment]
BTW - to be able to match the prediction back to the source it would be handy to be able to carry an ID column through the pipeline, that would be excluded from all modelling. It should re-appear in the prediction y_pred then. So we could "join" back to the original data.

**Comment by mfeurer** [comment]
I think scikit-learn is adding such a feature at the moment. This can be done once all the other pipeline-related work is done (FeatureUnion, upgrade to 0.18).

**Comment by aravind-vasudevan** [comment]
@mfeurer Is this enhancement still open?

**Comment by mfeurer** [comment]
Yes, no one is working on it or has worked on it. However, I am not too familiar with how scikit-learn handles pandas and how easy it will therefore be to add this.

**Comment by aravind-vasudevan** [comment]
I am happy to go do a bit of exploring and come up with an estimate/plan to fix this issue. Seeing as there are no takers for this issue for the past year and a half, please assign it to me :) I will however require some help in figuring out how things should interface from auto-sklearn's side.

**Comment by mfeurer** [comment]
Unfortunately, I cannot assign you in github, but yeah, this is your issue now :)

And there's no hurry. If you have a question I'll do my best to enswer quickly.

**Comment by mfeurer** [comment]
Input support for pandas was added via #889 

Indices are not yet passed through the scikit-learn pipeline, though, so I don't think we can support this easily at the moment. Here's a brief script to check:

```python
import sklearn.datasets
import sklearn.pipeline
import sklearn.preprocessing
import sklearn.ensemble

X, y = sklearn.datasets.fetch_openml(data_id=3, as_frame=True, return_X_y=True)

print(X)

pipeline = sklearn.pipeline.Pipeline(
    steps=(
        ('preproc', sklearn.preprocessing.OneHotEncoder()),
        ('rf', sklearn.ensemble.RandomForestClassifier()),
    )
)

pipeline.fit(X, y)
print(pipeline.predict(X))
```
and the output:
```
/home/feurerm/miniconda/3-4.5.4/envs/autosklearn/bin/python3.7 /home/feurerm/sync_dir/projects/automl_competition_2015/auto-sklearn/local/pandas_.py
     bkblk bknwy bkon8 bkona bkspr bkxbq  ... wkcti wkna8 wknck wkovl wkpos wtoeg
0        f     f     f     f     f     f  ...     f     f     f     t     t     n
1        f     f     f     f     t     f  ...     f     f     f     t     t     n
2        f     f     f     f     t     f  ...     f     f     f     t     t     n
3        f     f     f     f     f     f  ...     f     f     f     t     t     n
4        f     f     f     f     f     f  ...     f     f     f     t     t     n
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
3191     t     f     f     f     f     f  ...     f     t     f     t     f     n
3192     t     f     f     f     f     f  ...     f     t     f     t     f     n
3193     t     f     f     f     f     f  ...     f     t     f     t     f     n
3194     t     f     t     f     f     f  ...     f     t     f     f     f     n
3195     t     f     t     f     f     f  ...     f     t     f     f     f     n

[3196 rows x 36 columns]
['won' 'won' 'won' ... 'nowin' 'nowin' 'nowin']
```
