### ISSUE TITLE
Where in the codebase is per_run_time_limit enforced?

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#158]
I want to let all classifiers from autosklearn.pipeline.components.classification._classifiers to run once on the dataset so I can measure their typical fit time. 
So I call clf.fit(X,y) via multiprocessing and want to kill the fit processes that take longer than max_classifier_time_budget. But some classifiers seem to ignore the TERM signal. So they run for about half an hour or so, even the budget is set to 10 minutes.

```
        for pr in processes:
            pr.join(max_classifier_time_budget) # will block for max_classifier_time_budget or
            # until the classifier fit process finishes. After max_classifier_time_budget
            # we will terminate all still running processes here.
            if pr.is_alive():
                p("terminating "+pr.name+" process due to timeout")
                pr.terminate()
```
How do you kill the processes that auto-sklearn is starting? Could you point me to the place in your code where you have to stop the classifier after per_run_time_limit? 
Thanks!

**Comment by mfeurer** [comment]
The problem you're observing is likely to tools like the SVM which catch SIGTERM internally. We're using a tool called [pynisher](https://github.com/sfalkner/pynisher), which is instantiated [here](https://github.com/automl/auto-sklearn/blob/master/autosklearn/evaluation/__init__.py).
