### ISSUE TITLE
Indicate progress during optimization

### ISSUE THREAD

**Issue by aron-bram** [automl/auto-sklearn#1599]
**Problem description:**
Building an AutoML model and calling the _fit()_ function does not give any indication of how much time is left from the optimization process. This may cause confusion especially for fresh users not familiar with the API.

**Solution idea:**
It would be great to have some sort of signal in the console showing the current progress of the search. 
Possibly by adding tqdm as a dependency and utilizing it to display a progress bar.
This feature could be turned on by a boolean parameter.

**Importance:**
This is a minor feature, which could potentially improve the usability of the API without breaking it or requiring too many dependencies.

**Comment by eddiebergman** [comment]
* Closes #1599

**Comment by mrektor** [comment]
I agree that this would be very useful
