### ISSUE TITLE
Installation error: "python setup.py egg_info" failed (pyrfr)

### ISSUE THREAD

**Issue by colingoldberg** [automl/auto-sklearn#161]
Hi,

I got the following error in the first installation step:
pip install -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NkKOIN/pyrfr/

The last information output before the error was:
Collecting pyrfr (from -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt (line 24))
  Downloading pyrfr-0.2.0.tar.gz (340kB)
    100% |████████████████████████████████| 348kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NkKOIN/pyrfr/setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build

This is on an AWS EC2 instance (recently created). I did not set up a virtual or anaconda environment. 

$pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

$python -V
Python 2.7.10

$gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)

Please help.

Thanks

Colin Goldberg

**Comment by mfeurer** [comment]
Hi,

Please excuse the inconvenience and thank you for reporting this. This issue will be fixed in the next release. In the meantime to overcome this problem, please execute the command `pip install Cython` and redo the installation. 

Best,
Matthias

**Comment by colingoldberg** [comment]
Thank you - that worked.

I came across another error (not sure if I should create a new issue for it).

Taking your example:
import autosklearn.classification
import sklearn.datasets
digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target
import numpy as np
indices = np.arange(X.shape[0])
np.random.shuffle(indices)
X = X[indices]
y = y[indices]
X_train = X[:1000]
y_train = y[:1000]
X_test = X[1000:]
y_test = y[1000:]
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
print(automl.score(X_test,y_test))

I get the following:
/usr/local/lib64/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "example1.py", line 16, in <module>
    automl.fit(X_train, y_train)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/automl.py", line 175, in fit
    return self._fit(loaded_data_manager)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/automl.py", line 289, in _fit
    data_manager_path = self._backend.save_datamanager(datamanager)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/util/backend.py", line 130, in save_datamanager
    with lockfile.LockFile(lock_path):
AttributeError: 'module' object has no attribute 'LockFile'

Regards

Colin Goldberg

**Comment by mfeurer** [comment]
This issues seems to be unrelated to the previous one, please open a new one.
