### ISSUE TITLE
[Question] select_percentile_regression has no methods

### ISSUE THREAD

**Issue by MrKevinDC** [automl/auto-sklearn#1626]
How does the `select_percentile_regression `work? It has no fit or transform methods:

https://github.com/automl/auto-sklearn/blob/development/autosklearn/pipeline/components/feature_preprocessing/select_percentile_regression.py

**Comment by eddiebergman** [comment]
Hi @MrKevinDC,

You should follow it's inheritance chain, you can do this through github as well by clicking the classes it inherits from. For reference it inherits from [`SelectPercentileBase`](https://github.com/automl/auto-sklearn/blob/a978478f6053f2e966955347e32b20d6d35c0a61/autosklearn/pipeline/components/feature_preprocessing/select_percentile.py#L1).

I'm going to close this but feel free to continue if this does not answer your question.

**Comment by MrKevinDC** [comment]
Thank you for your helpful reply @eddiebergman, that solves my question!
