### ISSUE TITLE
Error: 'module' object has no attribute 'LockFile'

### ISSUE THREAD

**Issue by colingoldberg** [automl/auto-sklearn#164]
Hi,

I get error "'module' object has no attribute 'LockFile'" running your digits example.

Taking your example:
import autosklearn.classification
import sklearn.datasets
digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target
import numpy as np
indices = np.arange(X.shape[0])
np.random.shuffle(indices)
X = X[indices]
y = y[indices]
X_train = X[:1000]
y_train = y[:1000]
X_test = X[1000:]
y_test = y[1000:]
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
print(automl.score(X_test,y_test))

I get the following:
/usr/local/lib64/python2.7/site-packages/sklearn/cross_validation.py:44: [DeprecationWarning: ...]
Traceback (most recent call last):
File "example1.py", line 16, in 
automl.fit(X_train, y_train)
File "/usr/local/lib64/python2.7/site-packages/autosklearn/estimators.py", line 271, in fit
feat_type, dataset_name)
File "/usr/local/lib64/python2.7/site-packages/autosklearn/automl.py", line 175, in fit
return self._fit(loaded_data_manager)
File "/usr/local/lib64/python2.7/site-packages/autosklearn/automl.py", line 289, in _fit
data_manager_path = self._backend.save_datamanager(datamanager)
File "/usr/local/lib64/python2.7/site-packages/autosklearn/util/backend.py", line 130, in save_datamanager
with lockfile.LockFile(lock_path):
AttributeError: 'module' object has no attribute 'LockFile'

Regards

Colin Goldberg

**Comment by Ayaro** [comment]
Hi,
Afair, the problem is in the version of your "lockfile" python module: old class name is FileLock, while the new one is LockFile - please, try updating the module.

**Comment by colingoldberg** [comment]
Thank you.

I upgraded to 0.12.2 and it no longer gave this error.
