### ISSUE TITLE
[Question] Is Auto Sklearn 2 availible, Is auto-sklearn==0.15.0 the latest version?

### ISSUE THREAD

**Issue by shabir1** [automl/auto-sklearn#1643]
What is the latest version of auto-sklearn ?
How to install auto-sklearn 2?

**Comment by shabir1** [comment]
git hub shows the latest version as 0.14.7 but the documentation shows 0.15.0 as the latest. so I am confused

**Comment by aron-bram** [comment]
Hi,

Sorry for the confusion and thanks for pointing this out.

The latest version is 0.15.0 as indicated in docs. However, the version wasn't published. Until now.

Regarding your second question:
You only have to install autosklearn. If you would like to use the classifier from autosklearn2, then you would write the following import statement:

`from autosklearn.experimental.askl2 import AutoSklearn2Classifier`

And then call the classifier like you would with the regular classifier from autosklearn:
````
import sklearn.datasets

X, y = sklearn.datasets.load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
    X, y, random_state=1
)

automl = AutoSklearn2Classifier(
    time_left_for_this_task=120,
    per_run_time_limit=30,
)
automl.fit(X_train, y_train, dataset_name="example_dataset")

automl.leaderboard()

...
````
