### ISSUE TITLE
[Question] Opinions on including SplineTransformer as feature preprocessing step

### ISSUE THREAD

**Issue by MrKevinDC** [automl/auto-sklearn#1650]
I was wondering if there were any plans of bringing the [SplineTransformer() preprocessor](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.SplineTransformer.html) into `auto-sklearn` (it became available in `sklearn` in a newer version that what is currently being used). I have been testing it recently as a custom component and it has been achieving great results for me although I am aware it is the type of preprocessor that could result in models with poor generalization capacity due to its nature.

Have you worked with this preprocessor before? What are your opinions about including it in an automated ML workflow such as `auto-sklearn`?

**Comment by aron-bram** [comment]
Hi,
Thank you for your suggestion. We are working on bumping up our dependecny to 1.2x on sklearn. We will likely also consider newly added estimators that were not available for version 0.24x, such as spline transformer.
It's reassuring to hear that you've had great success with including it as a custom component.

**Comment by aron-bram** [comment]
I will close this issue if you don't mind. We will carefully examine and run extensive experiments all the available estimators once it becomes relevant.
