### ISSUE TITLE
[Question] Will this project be maintained and updated?

### ISSUE THREAD

**Issue by AmirAlavi** [automl/auto-sklearn#1676]
# Short Question Description
Will `auto-sklearn` be maintained and updated moving forward, and are there any timelines that you can share? We understand this is academic software.

# Context
I really like the opinionated pipelines that `auto-sklearn` uses to build its models, and the ensembling approach. Those advantages are why I have built my automl pipelines centered around `auto-sklearn` over the past year, but the old version of scikit-learn that is required (0.24) has held back my project.

At the time, I believed this would just be a temporary setback, as there was an active [PR to update to newer Scikit-learn](https://github.com/automl/auto-sklearn/pull/1611). However, that PR has now closed due to inactivity (and it seemed so close to being complete 😅).

We've been able to work around issues, pinning our other dependencies to very old versions to ensure things work with this old scikit.

However, as of 2 days ago, another issue has popped up causing all our CI tests to fail: new Cython was released that [isn't compatible with older scikit-learn,](https://github.com/scikit-learn/scikit-learn/issues/26858) and the maintainers of scikit-learn have explicitly said they will not support such old versions:
https://github.com/scikit-learn/scikit-learn/issues/26858#issuecomment-1641998866

This is related to #1675 

As the issues add up, I'm wondering if this tool has reached the end of its life? I don't want to jump the gun, as maybe there are things in the works and we'll see updates very soon, but if not, it would also be really helpful to know. The maintainers could make that clear in bold on the main README, and then they could even share recommendations for other tools out there to replace this.

**Comment by eddiebergman** [comment]
Hi, please see #1677

**Comment by AmirAlavi** [comment]
@eddiebergman thanks, glad to hear about the upcoming changes and improvements! Looking forward to testing out the new prototype when it's ready. Closing this issue for now.
