### ISSUE TITLE
Add warning if dependencies are not met

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#170]
There should be a warning if one of the following dependencies is not met:
- scikit-learn==0.17
- smac==0.0.1
- lockfile>=0.10
- ConfigSpace>=0.2.1
- pyrfr==0.2.1

**Comment by colingoldberg** [comment]
Any ETA on an upgrade to scikit-learn?

**Comment by mfeurer** [comment]
Given the amount of necessary changes before we can do that, I expect that it will take us at least two more months to do so.

**Comment by mfeurer** [comment]
I need to mention you @Ayaro before I can assign this issue to you.

**Comment by mfeurer** [comment]
Hm, doesn't work. I think I need to add you to the organization.

**Comment by mfeurer** [comment]
Closed by #188
