### ISSUE TITLE
Limiting usage of disk space

### ISSUE THREAD

**Issue by zygmuntz** [automl/auto-sklearn#173]
auto-sklearn is rather hungry for disk space: an hour's run produced 1.2G of tmp stuff, mostly models. I think there should be an option to limit the disk space used (for example by automatically pruning low-performing models).

**Comment by mfeurer** [comment]
Thank you for your suggestion. We'll consider it for the next release, or invite you to contribute this feature to auto-sklearn.

**Comment by mfeurer** [comment]
I just added a simpler solution which defers the issue a little bit into the future by zipping models and predictions. It will be added in the next bugfix release.

**Comment by mfeurer** [comment]
Hey, it took quite a while, but we finally added a new argument `max_models_on_disc` to Auto-sklearn, which governs the number of models and predictions kept on disc (https://automl.github.io/auto-sklearn/master/api.html). 

Please reopen if there are still issues with this.
