### ISSUE TITLE
fit_ensemble() undocumented 

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#174]
I could not find any documentation on this method apart from the code itself and this below example.
https://github.com/automl/auto-sklearn/blob/master/example/example_parallel.py

Previously it was listed here https://github.com/automl/auto-sklearn/commit/7e879cebb545f603521a966dad626587b3dcb50b

**Comment by mfeurer** [comment]
Added documentation in PR #273. Will be merged into development/master soon.
