### ISSUE TITLE
BufferError: memoryview: underlying buffer is not C-contiguous

### ISSUE THREAD

**Issue by arnaudsj** [automl/auto-sklearn#178]
Hi I am trying to perform the following in a jupyter notebook:

{code}
    cls = autosklearn.classification.AutoSklearnClassifier(resampling_strategy="cv", 
                                                           resampling_strategy_arguments={"cv": {"folds": 5}})
    cls.fit(X, y)
{code}

But I am getting in return the following error:
{code}
/home/ubuntu/.local/lib/python3.4/site-packages/autosklearn/automl.py in fit(self, X, y, task, metric, feat_type, dataset_name)
    149         if dataset_name is None:
    150             m = hashlib.md5()
--> 151             m.update(X.data)
    152             dataset_name = m.hexdigest()
    153 

BufferError: memoryview: underlying buffer is not C-contiguous
{code}

Any ideas?

**Comment by mfeurer** [comment]
This is a duplicate #115, please use `X_train=np.ascontig‌​uousarray(X_train)` prior to fitting auto-sklearn.

**Comment by arnaudsj** [comment]
Thank you @mfeurer - this works as intended now!

**Comment by codlife** [comment]
+1
