### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by mlindauer** [automl/auto-sklearn#18]
All error thrown in SMAC are not shown to the user. For example, one of the required packages was not properly installed in my case and hence, all target algorithm run crashed, but it was not shown to me and the code crashed later with an incomprehensible error message. Please add a proper DEBUG mode. (btw: some modules use logging and some use print statements)

**Comment by mfeurer** [comment]
Latest commit to the development branch adds a feature to output training statistics, including the number of crashed runs.
