### ISSUE TITLE
Document installation in Anaconda environment

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#180]
If a user is installing auto-sklearn in an environment where the compiler version and the version of the compiler which was used to compile the python runtime don't work with each other, importing the SMAC random forest will fail. This is for example present in #155, #176, #168, #161, #159, #141, #119, #101. I have pushed an easy workaround in #179 which uses a gcc shipped with anaconda. This easy workaround needs to be document documented so new users have less trouble with the installation.

**Comment by Motorrat** [comment]
On ubuntu 
`sudo apt-get install build-essential gcc`
resolved the problem

**Comment by Motorrat** [comment]
```
pip uninstall xgboost; pip install --no-cache-dir -v xgboost==0.4a30
conda install libgcc 
```
were needed for xgboost in 0.1.3

**Comment by mfeurer** [comment]
Documented in #273. Will be merged into development/master.
