### ISSUE TITLE
How to proceed after fit()

### ISSUE THREAD

**Issue by zygmuntz** [automl/auto-sklearn#184]
So I fitted(). Now, how to

1. save the model/params to be able to load it later?
2. re-fit the ensemble on the full training set (I assume it's fitted on 2/3 of data in holdout mode)?

**Comment by mfeurer** [comment]
You can check the [examples](https://github.com/automl/auto-sklearn/tree/master/example) to learn about how to fit the learned models on the whole dataset. Saving the models/parameters via pickle is currently broken (fix under development). For now you can use the solution from #30.
