### ISSUE TITLE
dependency upgrade

### ISSUE THREAD

**Issue by geoHeil** [automl/auto-sklearn#186]
Hi,

is it possible to upgrade the dependencies of auto-sklearn (sk-learn + xgboost) to the latest published versions?

**Comment by mfeurer** [comment]
Unfortunately, this is not possible. We need to change a lot of code and update all metadata. But we're working on this. Is there any model or new feature of scikit-learn you're missing in the current auto-sklearn version?

**Comment by geoHeil** [comment]
I am using the latest version of xgboost. I am not missing anything but
have already ported a lot of code to the latest sklearn and would like to
try auto-ml.
Matthias Feurer <notifications@github.com> schrieb am Mi. 9. Nov. 2016 um
16:53:

**Comment by philippschw** [comment]
Hi, 
I have the same problem as geoHeil. I am using the latest stable version of xgboost, which is not compatible with auto-sklearn. Importing auto-sklearn throws the following error: 

> autosklearn.util.dependencies.IncorrectPackageVersionError: 'xgboost 0.6' version mismatch (==0.4a30)

I am really enthusiastic about trying out the tool but I am not able to install xgboost==0.4a30 parallel to my current installation of xgboost==0.6. I am using conda and whenever I am create another virtual environment xgboost==0.6 is already installed. I also wonder if I can downgrade xgboost without risking to corrupt everything. Thank you!

**Comment by mfeurer** [comment]
Finally, the latest version of auto-sklearn works with scikit-learn 0.18.1. XGBoost dropped because of incompatibility with the pynisher (see issue #271).

**Comment by joseph-jnl** [comment]
I'm having a similar issue now with scikit-learn 0.18.2 that was released this June.

**Comment by mfeurer** [comment]
I just pushed a fix to the development branch, allowing both `sklearn==0.18.1` and `sklearn==0.18.2`.
