### ISSUE TITLE
SMAC configuration

### ISSUE THREAD

**Issue by bscully** [automl/auto-sklearn#187]
How can I correct this error message?   Nothing was mentioned in the install or example pages

[ERROR] [2016-11-08 11:51:01,910:AutoMLSMBO(1)::c3430cb9aff96a8543a03a052e9f72db] zero-size array to reduction operation minimum which has no identity
[ERROR] [2016-11-08 11:51:01,910:AutoMLSMBO(1)::c3430cb9aff96a8543a03a052e9f72db] Error in getting next configurations with SMAC. Using random configuration!

**Comment by mfeurer** [comment]
Thanks for reporting this issue. This is a bug in auto-sklearn and will hopefully be removed with the next release.

**Comment by mfeurer** [comment]
Fixed in the development branch by a8c9bc18078d582489a316a853100ac37852b94f. Will be in the upcoming bugfix release of auto-sklearn.

**Comment by webanalytics** [comment]
I installed the most recent version in two different machines and got the same error message: 
[ERROR] [2017-09-27 17:24:17,629:AutoMLSMBO(1)::boston] fit() got an unexpected keyword argument 'rng'
[ERROR] [2017-09-27 17:24:17,629:AutoMLSMBO(1)::boston] Error in getting next configurations with SMAC. Using random configuration!
---
I'm using python3.
Any suggestion on how to fix this problem?
Thanks.
