### ISSUE TITLE
Confused directories of .auto-sklearn/predictions_ensemble

### ISSUE THREAD

**Issue by kalan** [automl/auto-sklearn#20]
As of 3be0189, the whole thing is broken, as tested on a fresh dedicated Ubuntu 15.10 installation.

When running `example/example1.py`, `tmp_dir/ensemble_err_1.log` is full of messages like this:

```
[DEBUG] [13:06:20:ensemble_selection_script.py] Prediction directory /tmp/autoslearn_example_tmp/.auto-sklearn/predictions_ensemble does not exist!
```
No kind of optimization is performed, and the script finishes with:
```
Traceback (most recent call last):
  File "example1.py", line 31, in <module>
    main()
  File "example1.py", line 26, in main
    automl.fit(X_train, y_train, dataset_name='digits')
  File "/usr/local/lib/python2.7/dist-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 255, in fit
    feat_type, dataset_name)
  File "/usr/local/lib/python2.7/dist-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 244, in fit
    return self._fit(loaded_data_manager)
  File "/usr/local/lib/python2.7/dist-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 456, in _fit
    self._load_models()
  File "/usr/local/lib/python2.7/dist-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 542, in _load_models
    raise ValueError('No models fitted!')
ValueError: No models fitted!
```

Further investigation pointed out that `tmp_dir/.auto-sklearn/predictions_ensemble` doesn’t exist indeed; instead, it is created as `./.auto-sklearn/predictions_ensemble` — in the current directory.

The bug seems to be introduced by 3be0189; installing a version as of previous commit, 7666120, appears to work fine.

**Comment by mfeurer** [comment]
Sorry for that. I reverted the commits. Can you please check again?

**Comment by kalan** [comment]
The newest version I could build and install (21758dd, two commits behind master at the time of this writing) works fine.

Build is broken since a592e3d. Output from the aforementioned dedicated clean setup:
```
kalan@subsmultock:~/auto-sklearn$ sudo python setup.py install
/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.0.1dev' to '0.0.1.dev0'
  normalized_version,
running install
Building runsolver
Makefile:23: runsolver.d: No such file or directory
Makefile:23: SignalNames.d: No such file or directory
Makefile:23: SyscallNames.d: No such file or directory
grep '#define[[:space:]]*__NR' /usr/include/x86_64-linux-gnu/asm/unistd_64.h | grep -v '^/' | awk '{print $2}' | sed -e 's/^__NR_//' | awk '{printf "list[__NR_%s]=\"%s\";\n",$1,$1}' > tmpSyscallList.cc
g++ -o CreateSyscallsNames CreateSyscallsNames.cc
./CreateSyscallsNames
rm tmpSyscallList.cc CreateSyscallsNames 
/bin/sh -ec 'cc -MM -Dtmpdebug -Wall -DVERSION=\"3.3.4\" -DSVNVERSION=\"1649\" -DWSIZE=64 SyscallNames.cc \
| sed -e '\''s/SyscallNames\.o[ :]*/SyscallNames.d &/g'\'' > SyscallNames.d'
/bin/sh -ec 'cc -MM -Dtmpdebug -Wall -DVERSION=\"3.3.4\" -DSVNVERSION=\"1649\" -DWSIZE=64 SignalNames.cc \
| sed -e '\''s/SignalNames\.o[ :]*/SignalNames.d &/g'\'' > SignalNames.d'
/bin/sh -ec 'cc -MM -Dtmpdebug -Wall -DVERSION=\"3.3.4\" -DSVNVERSION=\"1649\" -DWSIZE=64 runsolver.cc \
| sed -e '\''s/runsolver\.o[ :]*/runsolver.d &/g'\'' > runsolver.d'
g++ -Dtmpdebug -Wall -DVERSION=\"3.3.4\" -DSVNVERSION=\"1649\" -DWSIZE=64 -O3 -c runsolver.cc
runsolver.cc: In member function ‘void RunSolver::run(char**)’:
runsolver.cc:1068:21: warning: ignoring return value of ‘int pipe(int*)’, declared with attribute warn_unused_result [-Wunused-result]
  pipe(stdoutRedirFD);
                     ^
In file included from runsolver.cc:86:0:
ProcessTree.hh: In member function ‘void ProcessTree::readGlobalData()’:
ProcessTree.hh:385:50: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
       fgets(loadavgLine,sizeof(loadavgLine),file);
                                                  ^
ProcessTree.hh:421:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
       ,&memTotal,&memFree,&swapTotal,&swapFree);
                                                ^
ProcessTree.hh:430:16: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
       ,&uptime);
                ^
g++ -Dtmpdebug -Wall -DVERSION=\"3.3.4\" -DSVNVERSION=\"1649\" -DWSIZE=64 -O3 -c SignalNames.cc
g++ -Dtmpdebug -Wall -DVERSION=\"3.3.4\" -DSVNVERSION=\"1649\" -DWSIZE=64 -O3 -c SyscallNames.cc
g++   -O3 -o runsolver runsolver.o SignalNames.o SyscallNames.o -lpthread
running bdist_egg
running egg_info
writing requirements to AutoSklearn.egg-info/requires.txt
writing AutoSklearn.egg-info/PKG-INFO
writing top-level names to AutoSklearn.egg-info/top_level.txt
writing dependency_links to AutoSklearn.egg-info/dependency_links.txt
writing pbr to AutoSklearn.egg-info/pbr.json
reading manifest file 'AutoSklearn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'autosklearn/binaries/smac-v2.08.01-development-1/smac-v2.08.01-development-1/'
writing manifest file 'AutoSklearn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying autosklearn/automl.py -> build/lib.linux-x86_64-2.7/autosklearn
copying autosklearn/data/competition_data_manager.py -> build/lib.linux-x86_64-2.7/autosklearn/data
copying autosklearn/binaries/runsolver -> build/lib.linux-x86_64-2.7/autosklearn/binaries
copying autosklearn/data/competition_c_functions.pyx -> build/lib.linux-x86_64-2.7/autosklearn/data
running build_ext
building 'autosklearn.data.competition_c_functions' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c autosklearn/data/competition_c_functions.c -o build/temp.linux-x86_64-2.7/autosklearn/data/competition_c_functions.o
x86_64-linux-gnu-gcc: error: autosklearn/data/competition_c_functions.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Not sure whether to start a separate thread for that.

**Comment by mfeurer** [comment]
Hm, I cannot reproduce it. On my machine I get different output:

    running build_ext
    cythoning autosklearn/data/competition_c_functions.pyx to autosklearn/data/competition_c_functions.c
    building 'autosklearn.data.competition_c_functions' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c autosklearn/data/competition_c_functions.c -o build/temp.linux-x86_64-2.7/autosklearn/data/competition_c_functions.o
    In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from autosklearn/data/competition_c_functions.c:242:
    /usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /usr/include/python2.7/numpy/ndarrayobject.h:26:0,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from autosklearn/data/competition_c_functions.c:242:
    /usr/include/python2.7/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
     _import_array(void)
     ^
    In file included from /usr/include/python2.7/numpy/ufuncobject.h:327:0,
                 from autosklearn/data/competition_c_functions.c:243:
    /usr/include/python2.7/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
     _import_umath(void)
     ^
    autosklearn/data/competition_c_functions.c: In function ‘__pyx_pf_11autosklearn_4data_23competition_c_functions_6read_dense_file’:
    autosklearn/data/competition_c_functions.c:3699:13: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
       fscanf(__pyx_v_cfile, __pyx_k_f, (&__pyx_v_v));
             ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/autosklearn/data/competition_c_functions.o -o build/lib.linux-x86_64-2.7/autosklearn/data/competition_c_functions.so

In your output, the line `cythoning ...` is missing. Can you please try the development branch?

**Comment by mfeurer** [comment]
The latest version available on pypi should solve this problem.
