### ISSUE TITLE
Rebuilding metadata

### ISSUE THREAD

**Issue by elibol** [automl/auto-sklearn#209]
We are trying to recreate the original auto-sklearn experiment, but we're having a hard time rebuilding the metadata with a different collection of datasets. The code in `scripts/update_metadata` appears to be outdated. Since we are working within an infrastructure that only supports python 2.7, we're working with a branch from the `0.1` tag of this repository.

We've made some progress updating the metadata creation scripts to work with the latest automl interface (see https://github.com/elibol/auto-sklearn/commit/13bb2330def4e2534c1d880f545d7e5626b291f3). We're getting the error below after running `autosklearn --output-dir /tmp/metadata/1536 --temporary-output-directory /tmp/metadata/1536 --seed 0 --time-limit 360 --per-run-time-limit 30 --ml-memory-limit 16000 --resampling-strategy holdout --ensemble-size 0 --metalearning-configurations 0 --data-format arff --metric auc --target Class --task multiclass.classification --dataset /home/v-huelib/dev/auto-sklearn-melih/scripts/update_metadata/datasets/1536`.

```
Traceback (most recent call last):
  File "/home/v-huelib/local/anaconda2/envs/auto-sklearn-melih/bin/autosklearn", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/v-huelib/dev/auto-sklearn-melih/scripts/autosklearn", line 223, in <module>
    automl.start_automl(args)
  File "/home/v-huelib/dev/auto-sklearn-melih/autosklearn/automl.py", line 110, in start_automl
    self.run()
  File "/home/v-huelib/dev/auto-sklearn-melih/autosklearn/automl.py", line 129, in run
    self._fit(self._datamanager)
  File "/home/v-huelib/dev/auto-sklearn-melih/autosklearn/automl.py", line 410, in _fit
    self._load_models()
  File "/home/v-huelib/dev/auto-sklearn-melih/autosklearn/automl.py", line 548, in _load_models
    raise ValueError('No models fitted!')
ValueError: No models fitted!
```

Any thoughts on why this is happening? Any thoughts in general on what we should consider as we work through this? We will be sure to contribute our updates to these scripts in a cleaned branch once we're done!

**Comment by mfeurer** [comment]
I rewrote the complete set of scripts for generating meta-data. It's so far only in the delevopment branch, but will soon be merged into master.
