### ISSUE TITLE
Trying to upgrade to new version

### ISSUE THREAD

**Issue by walterjgsp** [automl/auto-sklearn#211]
Hi, 

I'm using the auto-sklearn 0.0.2 within ananconda python 2.7 and i'm trying now to upgrade to the new version. I'm getting the following error:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Dp1152/auto-sklearn/

And when i try to download the source code from github and build on my machine i get the following error:

autosklearn.util.dependencies.IncorrectPackageVersionError: 'smac 0.0.1' version mismatch (==0.2.1)

What you think is necessary to upgrade the package?

Greetings 
Walter

**Comment by mfeurer** [comment]
To use auto-sklearn 0.1 you need to use python3.4 or python3.5. There is an error in our installation procedure which then breaks `pip install auto-sklearn --upgrade`. Therefore, you need to uninstall auto-sklearn and install auto-sklearn according to the installation procedure given in the documentation.
