### ISSUE TITLE
Executing Vanilla AutoSklearn

### ISSUE THREAD

**Issue by walterjgsp** [automl/auto-sklearn#217]
I was trying to use the Vanilla version of the execution without the ensemble and the MetaLearn for comparison reasons. I try to put the ensemble size equal to 0 to remove the feature.

When i put the ensemble_size=0 i get the following error.

'NoneType' object has no attribute 'get_model_identifiers'

Is there a way to run the algorithm without the ensemble and the metalearn?

Greetings
Walter

**Comment by mfeurer** [comment]
You need to set the ensemble size to 1 in order to use the best model. I leave this open as a reminder to document this feature.

**Comment by walterjgsp** [comment]
If i don't want to use the metalearn, i set the initial configurations as 0, like this?

initial_configurations_via_metalearning=0

Greetings
Walter

**Comment by mfeurer** [comment]
Correct.

**Comment by mfeurer** [comment]
Will be documented in the next version. So far, documentation lives in PR #273.
