### ISSUE TITLE
Cannot pickle model file created by fit_ensemble()

### ISSUE THREAD

**Issue by nyseion** [automl/auto-sklearn#218]
Although 9415f38fcfc79a255ffb7a716d3814c6c73cfb3a fixed pickling of model files created with fit(), I am still receiving 
``TypeError: Pickling an AuthenticationString object is disallowed for security reasons``
when trying to save a model created by fit_ensemble().

For example, after importing joblib, adding `joblib.dump(automl, 'test.pkl')` before line 96 in autosklearn/example/example_parallel.py will yield the error. 

I am using auto-sklearn 0.1.2 installed via `pip install auto-sklearn`.

**Comment by mfeurer** [comment]
Thank you for reporting this and please excuse the long delay. Apparently, this issue only comes up when using the method `fit_ensemble`. I just pushed a fix to the development branch. You can get it by cherry-picking commit 31e687ae01fea03184b32e8e5fffc6608244cca8 or just copy-pasting this single line of code.
