### ISSUE TITLE
Duplicate code not commented

### ISSUE THREAD

**Issue by Aaaaaaare** [automl/auto-sklearn#219]
Hi! If I have understood the code correctly (well, part of it at least), in the file autosklearn\smbo.py, the code at lines 543 and 544 are repeated below it after a massive comment section, means it is repeated at lines 571 and 573. This is the code:

543       smac.solver.stats.start_timing()
544       smac.solver.incumbent = smac.solver.initial_design.run()
######## all comments here
 571       smac.solver.stats.start_timing()
 572       # == first, evaluate all metelearning and default configurations
 573       smac.solver.incumbent = smac.solver.initial_design.run()

**Comment by mfeurer** [comment]
Thanks for reporting this. You're right, the code is duplicated and this is clearly an error. It's already fixed in the development branch, though (see [here](https://github.com/automl/auto-sklearn/blob/development/autosklearn/smbo.py#L577)).

**Comment by Aaaaaaare** [comment]
Ahh, yes, you are right. Thank you! I forgot to check the development branch.
