### ISSUE TITLE
Get model co-efficients

### ISSUE THREAD

**Issue by namankumar** [automl/auto-sklearn#224]
How am I able to get coefficients from the final model?

Thanks!
Naman

**Comment by mfeurer** [comment]
The following snippet returns a dictionary, which contains all pipelines used in the final ensemble:

    automl._automl._automl.models_

You could this piece of code to access one of the actual pipelines:

    list(automl._automl._automl.models_.values())[0].pipeline_

The pipeline itself is a [scikit-learn pipeline object](http://scikit-learn.org/0.17/).

**Comment by namankumar** [comment]
Yes, I was able to get them from .pipeline_.estimator.coef_ !

Thanks.

**Comment by jfold** [comment]
I get "AttributeError: 'AutoMLRegressor' object has no attribute '_automl'" when I run

`automl._automl._automl.models_` or `list(automl._automl._automl.models_.values())[0].pipeline_`

What to do?

Thanks!
Jonathan

**Comment by teresaconc** [comment]
@aimanakheel 
For a 'SimpleClassificationPipeline' object you can use `pipeline.automl._final_estimator.estimator.coef_`

where _pipeline_ is the 'SimpleClassificationPipeline' object.

**Comment by aimanakheel** [comment]
@teresaconc 
Thanks for the response.

I have tried several times to create 'SimpleClassificationPipeline' object but If I am doing it in the way shown in my comment above, it returns a Tuple and not a callable object.  

How can I call the 'SimpleClassificationPipeline' object?

Many thanks

**Comment by mfeurer** [comment]
You can use `print(list(automl._automl.models_.values())[0].steps)`.

I'm reopening this so that we add an example of this.

**Comment by teresaconc** [comment]
@aimanakheel 
list(automl._automl.models_.values())[0] should be a 'SimpleClassificationPipeline' object.

automl._automl.models_ is a dictionary where the keys are the models' ids (which are tuples) and the values are 'SimpleClassificationPipeline' objects. 

What tuple are you getting? Maybe you're accessing list(automl._automl.models_)[0] instead of list(automl._automl.models_.values())[0]?

**Comment by aimanakheel** [comment]
![image](https://user-images.githubusercontent.com/36748803/50842727-27d82700-131c-11e9-926d-36474625e50b.png)

`list(automl._automl.models_.values())[0]` returns a dictionary.

**Comment by aimanakheel** [comment]
My New Input:

`pipeline = list(automl._automl.models_.values())[0]
print(pipeline)

XgClass = pipeline._final_estimator.choice # .estimator.coef_
print ('-----------------------')
print (XgClass)

XGEstmtr = XgClass.estimator
print ('-----------------------')
print (XGEstmtr)

feature_importance = XGEstmtr.coef_
print ('-----------------------')
print (feature_importance)`

My Output:

![image](https://user-images.githubusercontent.com/36748803/50861717-62f34e00-134e-11e9-8e63-28d6e1cabc21.png)

**Comment by domainoverflow** [comment]
I'm having the same problem but with a forest regressor ( details in issue #719 )
