### ISSUE TITLE
python 2.7 auto-sklearn version release date

### ISSUE THREAD

**Issue by vinodrajendran001** [automl/auto-sklearn#226]
When will the compatible version for python 2.7 will be available?

**Comment by mfeurer** [comment]
We dropped python2.7 support around half a year ago to ease maintenance and use new features such as type annotations. We encourage our users to use python3.5 or higher.

**Comment by antontarasenko** [comment]
@mfeurer 

What's the latest version that 100% supports Python 2.7?

**Comment by mfeurer** [comment]
We didn't actively track this, but I assume it's version 0.1, as it is the only release which was done prior to the commit for dropping it: https://github.com/automl/auto-sklearn/commit/ead20848ae8dc2882c3609f66d696da095e4963a#diff-354f30a63fb0907d4ad57269548329e3

However, it strongly advise you to use the latest version of Auto-sklearn as it contains a lot of bugfixes and improvements.
