### ISSUE TITLE
fatal error: limits.h: No such file or directory

### ISSUE THREAD

**Issue by NickYi1990** [automl/auto-sklearn#230]
I had see similar issue, but their solution is not fit for me, below are my pip command and issue
my OS is macOS Sierra 10.12.2

(//anaconda/envs/Auto-SKlearn)bash-3.2$ CC=//anaconda/envs/Auto-SKlearn/bin/gcc pip install pyrfr
Collecting pyrfr
  Using cached pyrfr-0.2.0.tar.gz
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command //anaconda/envs/Auto-SKlearn/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/pip-build-5blg_2mb/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/tmpfn0ii5d9pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-3.5
  creating build/lib.macosx-10.6-x86_64-3.5/pyrfr
  copying pyrfr/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyrfr
  running build_ext
  building 'pyrfr.regression' extension
  creating build/temp.macosx-10.6-x86_64-3.5
  creating build/temp.macosx-10.6-x86_64-3.5/pyrfr
  //anaconda/envs/Auto-SKlearn/bin/gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/envs/Auto-SKlearn/include -arch x86_64 -I./include -I//anaconda/envs/Auto-SKlearn/lib/python3.5/site-packages/numpy/core/include -I//anaconda/envs/Auto-SKlearn/include/python3.5m -c pyrfr/regression.cpp -o build/temp.macosx-10.6-x86_64-3.5/pyrfr/regression.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /anaconda/envs/Auto-SKlearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.2/include-fixed/syslimits.h:7:0,
                   from /anaconda/envs/Auto-SKlearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.2/include-fixed/limits.h:34,
                   from //anaconda/envs/Auto-SKlearn/include/python3.5m/Python.h:11,
                   from pyrfr/regression.cpp:38:
  /anaconda/envs/Auto-SKlearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.2/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command '//anaconda/envs/Auto-SKlearn/bin/gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command //anaconda/envs/Auto-SKlearn/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/pip-build-5blg_2mb/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/pip-878spmju-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-3.5
    creating build/lib.macosx-10.6-x86_64-3.5/pyrfr
    copying pyrfr/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyrfr
    running build_ext
    building 'pyrfr.regression' extension
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/pyrfr
    //anaconda/envs/Auto-SKlearn/bin/gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/envs/Auto-SKlearn/include -arch x86_64 -I./include -I//anaconda/envs/Auto-SKlearn/lib/python3.5/site-packages/numpy/core/include -I//anaconda/envs/Auto-SKlearn/include/python3.5m -c pyrfr/regression.cpp -o build/temp.macosx-10.6-x86_64-3.5/pyrfr/regression.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /anaconda/envs/Auto-SKlearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.2/include-fixed/syslimits.h:7:0,
                     from /anaconda/envs/Auto-SKlearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.2/include-fixed/limits.h:34,
                     from //anaconda/envs/Auto-SKlearn/include/python3.5m/Python.h:11,
                     from pyrfr/regression.cpp:38:
    /anaconda/envs/Auto-SKlearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.2/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command '//anaconda/envs/Auto-SKlearn/bin/gcc' failed with exit status 1
    
    ----------------------------------------
Command "//anaconda/envs/Auto-SKlearn/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/pip-build-5blg_2mb/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/pip-878spmju-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rq/3sscfwc56n14fd5fpb21h0p00000gn/T/pip-build-5blg_2mb/pyrfr/

**Comment by mfeurer** [comment]
You could have a look at how we install conda for travis-ci, maybe that helps: [.travis.yml](https://github.com/automl/auto-sklearn/blob/development/.travis.yml)? Otherwise, I'm afraid that I can't help at all.

**Comment by NickYi1990** [comment]
Thanks!
