### ISSUE TITLE
auto-sklearn kills anaconda intallation

### ISSUE THREAD

**Issue by noteven2degrees** [automl/auto-sklearn#233]
Hi, I have some deep troubles getting auto-sklearn to run, or even not to destroy a working Anaconda installation.
System: Ubuntu 16.04 freshly installed in a Virtual Machine on Windows 10. Steps after ubuntu setup:

1. Download / installation of Anaconda 4.3.0, 64-bit, Python 3.6
2. Checking installation: works fine, especially all sklearn import work
3. Installation of auto-sklearn according to https://automl.github.io/auto-sklearn/stable/#installation, first curl, then pip, both fine. `conda list` displays two sklearn packages, the 0.17 needed by auto-sklearn, and the current 0.18 version
4. Checking `import autosklearn.classification` --> fails
5. Checking `from sklearn import svm` --> also fails

Latest in traceback:
`ImportError: /home/myhome/anaconda3/lib/python3.6/site-packages/sklearn/cluster/_dbscan_inner.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E
`
I had the same now several times, with different ubuntu versions, 32-bit/64 bit, alternating installation order, etc.

**Comment by TaXxER** [comment]
Yes, I had the same problem a couple of days ago. I think the problem could be that the your initial sklearn install (0.18) might have been installed through conda, while the auto-sklearn requirements script installs version 0.17 through pip. Maybe pip has then problems recognizing the other install which was not performed though pip. For me the solution was to pip uninstall the 0.17, conda uninstall the 0.18, and then run pip install through the auto-sklearn requirements script again.

**Comment by noteven2degrees** [comment]
Thanks, but no. Unfortunately didn't do the job. The errors also appear to happen quite randomly on submodules. After the steps above,
'import sklearn' works
`from sklearn import svm` works
`from sklearn import cluster` fails with `_dbscan_inner.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E`
`import autosklearn` works
`autosklearn.classification` fails with `site-packages/pyrfr/regression.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE`
Note that previously, `cluster` was working and `svm` was failing, now it is vice versa.

**Comment by noteven2degrees** [comment]
Just food for thought: Is auto-sklearn relying on exactly Python 3.5 (as it is with sklearn 0.17)? My Anaconda came with Python 3.6, does it make a difference?

**Comment by mfeurer** [comment]
Sorry for the issue. I only tried installing auto-sklearn in miniconda, for which no problems appear because it does not ship any python package. If you do not rely on the full anaconda distribution, you could give miniconda a try.

I did not test with python3.6 yet, but I heard that there are problems because of changes in the standard library. python3.4 will work though.

**Comment by noteven2degrees** [comment]
Thanks a lot. Before I read your answer, I tried it with a legacy Anaconda version which shipped Python 3.5. It works smoothly now. Great work!
