### ISSUE TITLE
Trying to install auto-sklearn:  command 'x86_64-linux-gnu-gcc' failed

### ISSUE THREAD

**Issue by Coqueiro** [automl/auto-sklearn#235]
Hello! I'm trying to install auto-sklearn on my ubuntu 16.04, with gcc version 5.4.0. I rely on pip. I ran installation as indicated [here](https://automl.github.io/auto-sklearn/stable/#installation). I'm getting the following error when executing the bash command `curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install`:

```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-07ak0u7n/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1vizg84l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-07ak0u7n/psutil/
```

In case that's not enough, here's the [full installation log](http://text-share.com/view/raw/19890cba).

Thanks in advance :)

**Comment by dddanmar** [comment]
`fatal error: Python.h`

Looks like you are missing the python3-dev package.

`sudo apt install python3-dev python3 python3-pip `

**Comment by Coqueiro** [comment]
Nice, it worked! Seems I can't roll auto-sklearn with the most recent version of scikit-learn, but that's another story. Thanks for your help!

**Comment by mfeurer** [comment]
Great that this is already solved. The fact that auto-sklearn requires scikit-learn version 0.17 is part of issue #186.
