### ISSUE TITLE
A few easily fixable warnings

### ISSUE THREAD

**Issue by lsorber** [automl/auto-sklearn#238]
When training an ensemble with auto-sklearn 0.1.2, I see the following easily fixable warnings:

```
[...]/env/lib/python3.5/site-packages/autosklearn/pipeline/implementations/ProjLogit.py:36:
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
yt = np.zeros((n, k))
```
```
[...]/env/lib/python3.5/site-packages/autosklearn/pipeline/implementations/ProjLogit.py:38:
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
yt[i, Y[i]] = 1
```
```
[...]/env/lib/python3.5/site-packages/sklearn/utils/class_weight.py:62:
DeprecationWarning: The class_weight='auto' heuristic is deprecated in 0.17 in favor of a new heuristic class_weight='balanced'. 'auto' will be removed in 0.19
" 0.19", DeprecationWarning)
```

Fixing these would not take much time, and would help reduce the noise in the output.

**Comment by mfeurer** [comment]
Should be fixed in the development branch via 91017edd7fb3ae407b83492619ced7401b31a396, I hope that I can do a release today.

**Comment by lsorber** [comment]
This does reduce the noise, but doesn't actually address the underlying problems (which should also be easy to resolve).

**Comment by mfeurer** [comment]
Warning one and two will be resolved by removing ProjLogit because of lack of a maintainer of that source code. The class_weight issue will be tackled based on #207.
