### ISSUE TITLE
how to define hyperparameter_search_space for preprocessing?

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#245]
Until recently I was using the following code
```
    #constructing preprocessor pipeline and transforming sample dataset
    # we don't care about the data here but need to preprocess, otherwise the classifiers crash
    default_cs = SimpleClassificationPipeline.get_hyperparameter_search_space(
                            include={ 'imputation': 'most_frequent'
                                        , 'rescaling': 'standardize' }
                                        ).get_default_configuration()
    preprocessor = SimpleClassificationPipeline(default_cs, random_state=42)
    preprocessor.fit(X,y)
    X_tr,dummy = preprocessor.pre_transform(X,y)
```
now the include= parameter is no longer accepted by get_hyperparameter_search_space()

> in max_estimators_fit_duration
>     , 'rescaling': 'standardize' }
> TypeError: get_hyperparameter_search_space() got an unexpected keyword argument 'include'

but     `default_cs = SimpleClassificationPipeline.get_hyperparameter_search_space().get_default_configuration()`

works. 
How should I construct the SimpleClassificationPipeline to only have the imputation and rescaling?

**Comment by mfeurer** [comment]
You can pass the `include` and `exclude` parameters to the `SimpleClassificationPipeline` constructor:
```
default_cs = SimpleClassificationPipeline(
    include={'imputation': 'most_frequent', 'rescaling': 'standardize'}).\
    get_hyperparameter_search_space().get_default_configuration()
```

**Comment by Motorrat** [comment]
with these changes I get this error 
```
include={'imputation':'most_frequent', 'rescaling':'standardize'}).\
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 81, in __init__
    random_state, init_params)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 35, in __init__
    self.config_space = self.get_hyperparameter_search_space()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 208, in get_hyperparameter_search_space
    dataset_properties=self.dataset_properties_)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 174, in _get_hyperparameter_search_space
    exclude=exclude, include=include, pipeline=pipeline)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 286, in _get_base_search_space
    pipeline, dataset_properties, include=include, exclude=exclude)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/create_searchspace_util.py", line 34, in get_match_array
    exclude=node_exclude).keys()))
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/base.py", line 332, in get_available_components
    "%s" % incl)
ValueError: Trying to include unknown component: s
```

**Comment by mfeurer** [comment]
Sorry, my mistake. It should be:
```
default_cs = SimpleClassificationPipeline(
    include={'imputation': ['most_frequent'], 'rescaling': ['standardize']}).\
    get_hyperparameter_search_space().get_default_configuration()
```

**Comment by Motorrat** [comment]
this is what comes out now :-) ```
Traceback (most recent call last):
  File "zeroconf.py", line 215, in <module>
    per_run_time_limit = max_estimators_fit_duration(X_train.values,y_train,max_classifier_time_budget,sample_factor)
  File "zeroconf.py", line 77, in max_estimators_fit_duration
    preprocessor = SimpleClassificationPipeline(default_cs, random_state=42)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 81, in __init__
    random_state, init_params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 52, in __init__
    '%s' % diff)
ValueError: Configuration passed does not come from the same configuration space. Differences are: --- 

+++ 

@@ -153,7 +153,7 @@

     preprocessor:select_rates:alpha, Type: UniformFloat, Range: [0.01, 0.5], Default: 0.10000000000000001
     preprocessor:select_rates:mode, Type: Categorical, Choices: {fpr, fdr, fwe}, Default: fpr
     preprocessor:select_rates:score_func, Type: Categorical, Choices: {chi2, f_classif}, Default: chi2
-    rescaling:__choice__, Type: Categorical, Choices: {minmax, none, normalize, standardize}, Default: standardize
+    rescaling:__choice__, Type: Categorical, Choices: {standardize}, Default: standardize
   Conditions:
     classifier:adaboost:algorithm | classifier:__choice__ == 'adaboost'
     classifier:adaboost:learning_rate | classifier:__choice__ == 'adaboost'
@@ -309,15 +309,22 @@

     (Forbidden: classifier:liblinear_svc:penalty == 'l1' && Forbidden: classifier:liblinear_svc:loss == 'hinge')
     (Forbidden: classifier:liblinear_svc:dual == 'False' && Forbidden: classifier:liblinear_svc:penalty == 'l2' && Forbidden: classifier:liblinear_svc:loss == 'hinge')
     (Forbidden: classifier:liblinear_svc:dual == 'False' && Forbidden: classifier:liblinear_svc:penalty == 'l1')
+    (Forbidden: preprocessor:__choice__ == 'extra_trees_preproc_for_classification' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: preprocessor:__choice__ == 'fast_ica' && Forbidden: classifier:__choice__ == 'multinomial_nb')
+    (Forbidden: preprocessor:__choice__ == 'feature_agglomeration' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: preprocessor:__choice__ == 'kernel_pca' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: preprocessor:__choice__ == 'kitchen_sinks' && Forbidden: classifier:__choice__ == 'multinomial_nb')
+    (Forbidden: preprocessor:__choice__ == 'liblinear_svc_preprocessor' && Forbidden: classifier:__choice__ == 'multinomial_nb')
+    (Forbidden: preprocessor:__choice__ == 'no_preprocessing' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: preprocessor:__choice__ == 'nystroem_sampler' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: preprocessor:__choice__ == 'pca' && Forbidden: classifier:__choice__ == 'multinomial_nb')
+    (Forbidden: preprocessor:__choice__ == 'polynomial' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: preprocessor:__choice__ == 'random_trees_embedding' && Forbidden: classifier:__choice__ == 'gaussian_nb')
     (Forbidden: preprocessor:__choice__ == 'random_trees_embedding' && Forbidden: classifier:__choice__ == 'gradient_boosting')
     (Forbidden: preprocessor:__choice__ == 'random_trees_embedding' && Forbidden: classifier:__choice__ == 'lda')
     (Forbidden: preprocessor:__choice__ == 'random_trees_embedding' && Forbidden: classifier:__choice__ == 'qda')
+    (Forbidden: preprocessor:__choice__ == 'select_percentile_classification' && Forbidden: classifier:__choice__ == 'multinomial_nb')
+    (Forbidden: preprocessor:__choice__ == 'select_rates' && Forbidden: classifier:__choice__ == 'multinomial_nb')
     (Forbidden: classifier:__choice__ == 'adaboost' && Forbidden: preprocessor:__choice__ == 'kitchen_sinks')
     (Forbidden: classifier:__choice__ == 'adaboost' && Forbidden: preprocessor:__choice__ == 'nystroem_sampler')
     (Forbidden: classifier:__choice__ == 'decision_tree' && Forbidden: preprocessor:__choice__ == 'kitchen_sinks')
```

**Comment by mfeurer** [comment]
This happens because the search (which generates the configurations) does not know about the restricted preprocessing. I need to rewrite the arguments to Auto-sklearn a little bit in order to make that work. I estimate that I get this done for the next release (hopefully next week).

**Comment by Motorrat** [comment]
Just to make sure, I am using this to avoid the pipeline crashing when timing all estimators one by one on my dataset. I don't care neither about the model  nor about actual pipeline content. Just need the approx time of the pipeline on this dataset. 


Is the above inclusion of imputation and scaling the best way to ensure that the pipeline won't fail? 

May be now (with the current version of the auto-sklearn) I could leave it out altogether? 

You can check the code here https://github.com/paypal/autosklearn-zeroconf/blob/master/zeroconf.py#L68

**Comment by mfeurer** [comment]
Okay, then this should do the job:
```
from sklearn.datasets import load_iris

from autosklearn.pipeline.classification import SimpleClassificationPipeline


iris = load_iris()
X = iris.data
y = iris.target

pipeline = SimpleClassificationPipeline(
    include={'imputation': ['most_frequent'], 'rescaling': ['standardize']})

default_cs = pipeline.get_hyperparameter_search_space().get_default_configuration()

pipeline = pipeline.set_hyperparameters(default_cs)
pipeline.fit(X, y)
X_tr, dummy = pipeline.pre_transform(X, y)
```
So since version 0.1.3 the pipeline needs to know about how the dataset actually looks like, that's why it became stateful.

**Comment by Motorrat** [comment]
Thanks, this did it! This can be closed.
