### ISSUE TITLE
xgboost fails

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#247]
/home/ubuntu/anaconda3/lib/python3.5/site-packages/xgboost/./wrapper/libxgboostwrapper.so: invalid ELF header

**Comment by mfeurer** [comment]
This seems like there is an issue with your xgboost installation. Could you try to purge xgboost and reinstall it to make sure there aren't any stale files which cause this.

**Comment by Motorrat** [comment]
I have tried to pip uninstall xgboost and then install via requirements.txt but it did not help.

**Comment by Motorrat** [comment]
the solution was to re-compile xgboost locally
`pip uninstall xgboost; pip install --no-cache-dir -v xgboost==0.4a30`
and pre-pending `export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6":"/usr/lib/x86_64-linux-gnu/libgomp.so.1"; python` to let it find the missing libraries.

**Comment by mfeurer** [comment]
Hm, in case your running this in Anaconda, you can also do `conda install libgcc`. I ran into issues with Anaconda and XGBoost as well, but don't really know what to do about them. Since it works for you, can I close this?

**Comment by Motorrat** [comment]
the above manipulations seem to have resolved the missing libraries issue so it can be closed now.
