### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by TinaShi** [automl/auto-sklearn#253]
Hi, I recently heard of auto-sklearn and really want to try it out. But after reading so many posts, I am still stuck at installing the pyrfr in order to use auto-sklearn. Can you help me to figure out it? The problem is about the random package. 
The error is cited here:"warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    pyrfr/regression.cpp:496:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1"

I know some people experienced similar situation, but the possible solutions discussed in some posts do not work for me. Here is some additional information:
which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
which python3
/Users/tinashi/anaconda/bin/python3
which pip
/Users/tinashi/anaconda/bin/pip
pip -V
pip 9.0.1 from /Users/tinashi/anaconda/lib/python3.5/site-packages (python 3.5)
gcc --version
gcc (GCC) 4.8.5
g++ --version
g++ (GCC) 4.8.5

Can anyone help me with this? I am really anxious to try it out. Any suggestions are appreciated.

**Comment by mlindauer** [comment]
Hi,

first please note that auto-sklearn is not compatible with Python 2.7.
Using Anaconda with Python 3  should work.
Please check whether the solution in the following thread works for you---it was successful for MacOS and Debian.

https://github.com/automl/auto-sklearn/issues/155

```
conda install gcc
pip uninstall pyrfr auto-sklearn
curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
CC=/Users/username/anaconda/bin/gcc pip install pyrfr auto-sklearn --no-cache-dir
```

**Comment by TinaShi** [comment]
Thank you. I know that some person made it work on Mac under Anaconda environment. I also tried that, but I failed. I just tried your code again. It threw two errors to me.
Part of first one is the same as before: 
"warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    pyrfr/regression.cpp:496:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/tinashi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/db/tg852n_x7_dbwgl4x4py45xr0000gp/T/pip-build-2jagfxbe/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/db/tg852n_x7_dbwgl4x4py45xr0000gp/T/pip-r9wlqvi5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/db/tg852n_x7_dbwgl4x4py45xr0000gp/T/pip-build-2jagfxbe/pyrfr/"

Part of second one:
"unable to execute '/Users/username/anaconda/bin/gcc': No such file or directory
    error: command '/Users/username/anaconda/bin/gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/tinashi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/db/tg852n_x7_dbwgl4x4py45xr0000gp/T/pip-build-eqzgdcsd/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/db/tg852n_x7_dbwgl4x4py45xr0000gp/T/pip-42f6d4z3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/db/tg852n_x7_dbwgl4x4py45xr0000gp/T/pip-build-eqzgdcsd/pyrfr/"

**Comment by TinaShi** [comment]
Here is one more piece of information about the GCC.
which gcc
/Users/tinashi/anaconda/bin/gcc
It look like at the right place, but why does the error says not such file or directory.

**Comment by TinaShi** [comment]
I saw that post and tried the code posted on other post, it did not work. What works really well and solved my problem is this line "CC=/Users/username/anaconda/bin/gcc pip install pyrfr auto-sklearn --no-cache-dir". I just forgot to change the "username" and got an error, now it is fixed. I am very excited to try it out. I will comment once it is also running well on my computer. Please don't close it now.

**Comment by TinaShi** [comment]
Hi,
It is still running, but it throws an error to me:
"Process pynisher function call:
Traceback (most recent call last):
  File "/Users/tinashi/anaconda/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/tinashi/anaconda/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/evaluation/train_evaluator.py", line 284, in eval_holdout
    evaluator.fit_predict_and_loss(iterative=iterative)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/evaluation/train_evaluator.py", line 77, in fit_predict_and_loss
    i, train_indices=train_split, test_indices=test_split)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/evaluation/train_evaluator.py", line 211, in _partial_fit_and_predict
    self.Y_train[train_indices])
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 340, in _fit_and_suppress_warnings
    model.fit(X, y)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 89, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 104, in fit_estimator
    self.steps[-1][-1].fit(X, y, **fit_params)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/pipeline/components/base.py", line 379, in fit
    return self.choice.fit(X, y, **kwargs)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/autosklearn/pipeline/components/classification/libsvm_svc.py", line 122, in fit
    self.estimator.fit(X, Y)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/sklearn/svm/base.py", line 193, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/Users/tinashi/anaconda/lib/python3.5/site-packages/sklearn/svm/base.py", line 251, in _dense_fit
    max_iter=self.max_iter, random_seed=random_seed)
  File "sklearn/svm/libsvm.pyx", line 187, in sklearn.svm.libsvm.fit (sklearn/svm/libsvm.c:2098)
ValueError: cache_size <= 0"

Here is my code that I learned from example:
"import autosklearn.classification
import sklearn.cross_validation
import sklearn.datasets
import sklearn.metrics

digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target
X_train, X_test, y_train, y_test = sklearn.cross_validation.train_test_split(X,y,random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
y_hat = automl.predict(X_test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))"

**Comment by mlindauer** [comment]
Some ML-pipelines can throw errors but this should not affect auto-sklearn too much and it should nevertheless return something in the end. I hope it did!?

The concrete error you posted indicates that your system had no free memory anymore.
We compute the cache memory for the SVM in the following way: 
https://github.com/automl/auto-sklearn/blob/master/autosklearn/pipeline/components/classification/libsvm_svc.py#L80

**Comment by TinaShi** [comment]
Thank you. In the end, it gives a pretty good result:
"Accuracy score 0.993333333333"
Thanks a lot for your help. I need to clean my computer a little bit more and learn more about memory issue since I do not have much knowledge about it. 
The other question I have is: is it possible to get to know which model yields such good results? I recently learned that scikit-learn focuses on predictive analysis. With my background in statistics, one of the reasons I use auto-sklearn is to figure out which algorithm works well, then I can trace the particular algorithm and try to learn more about the data properties. In my current output, only the score gets returned.

**Comment by mlindauer** [comment]
> is it possible to get to know which model yields such good results?

Auto-Sklearn returns an ensemble of models.
You can use `automl.show_models()` to look at the ensemble.

In general, I recommend to read the paper on auto-sklearn to get an understanding what it does:
`Efficient and Robust Automated Machine Learning` at NIPS'15

I would guess we can close this thread?

**Comment by TinaShi** [comment]
Sure. Thanks so much for your help. It is really cool.
