### ISSUE TITLE
possible regressors and classifiers documentation

### ISSUE THREAD

**Issue by mvogelsang** [automl/auto-sklearn#262]
The documentation is unfortunately lacking in its description of possible inputs to several hyperparameters. Specifically, the possible includable and excludable regressors and classifiers.

**Comment by mvogelsang** [comment]
I've found the regressors and put them here for reference
![image](https://cloud.githubusercontent.com/assets/9369667/25118493/a20d17de-23e4-11e7-87bc-96c9e6e3cad0.png)

**Comment by mvogelsang** [comment]
I've found the classifiers and put them here for reference
![image](https://cloud.githubusercontent.com/assets/9369667/25118540/bd92132e-23e4-11e7-814f-5394fe1f6f4c.png)

**Comment by Motorrat** [comment]
as per https://github.com/automl/auto-sklearn/issues/142
import autosklearn.pipeline.components.classification
print autosklearn.pipeline.components.classification._classifiers

**Comment by mfeurer** [comment]
Thanks @KEggensperger for fixing this in PR #264. Will be in the next release. Until then, it can be found [here](http://automl.github.io/auto-sklearn/dev/manual.html).
