### ISSUE TITLE
Backend.load_datamanager() has masleading name

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#27]
because it loads a pickled data manager. The data manager is loaded when a data manager class initialized.

**Comment by johnymephisto** [comment]
Can i take it up? Please do give pointers on how to get on with it.

**Comment by mfeurer** [comment]
The method in question is this one: https://github.com/automl/auto-sklearn/blob/development/autosklearn/util/backend.py#L303

The goal of this issue is to simply rename the method. However, I'm not sure to what exactly. Closing this for now as I don't think this is necessary and cannot come up with a better name.
