### ISSUE TITLE
ImportError: No module named classification

### ISSUE THREAD

**Issue by giorgio79** [automl/auto-sklearn#28]
I am facing a weird error whereby the autosklearn.classification is missing. 

I installed autosklearn into a mini conda environment as requested on the install guide.

Any tips? :)

>>> import autosklearn.classification
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import autosklearn.classification
ImportError: No module named classification
>>>

I can access fine autosklearn via the command line in the environment
>>>(auto2)[root@CentOS-72-64-minimal ~]# autosklearn
usage: autosklearn [-h] [-c CONFIG] [--output-dir OUTPUT_DIR]
                   [--temporary-output-directory TEMPORARY_OUTPUT_DIRECTORY]
                   [--keep-output] [--time-limit TIME_LIMIT]
....
>>>

**Comment by giorgio79** [comment]
Looks like I garbled up my environment. Had to delete a python script I created for running autosklearn. Importing works fine new. Phew.

**Comment by WesleyHsieh** [comment]
I'm having the same issue. What did you do to fix it?

**Comment by mfeurer** [comment]
Is your script maybe named autosklearn or do you have a script named autosklearn in your working directory?

**Comment by WesleyHsieh** [comment]
Nope, using a virtual environment fixed the error. Thanks though!
