### ISSUE TITLE
Generate regression meta-data

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#280]

**Comment by sohrabtowfighi** [comment]
Is there a straight-forward procedure to contribute to this?

**Comment by mfeurer** [comment]
In theory it should be possible by following [this instructions](https://github.com/automl/auto-sklearn/blob/master/scripts/readme.md). However, as there is no regression meta-data, this workflow is obviously untested.

**Comment by mfeurer** [comment]
We re-added metadata for regression in ef5685e1c1ac61f0267ee1f504c92b6c867a3ce7 and it will be available in the next release.

**Comment by 18756** [comment]
Is it really solved issue? I get this warning with 0.14.6 version
