### ISSUE TITLE
Getting Information of Models

### ISSUE THREAD

**Issue by bacalfa** [automl/auto-sklearn#286]
Is there a way to retrieve the information of the best cross-validated "model"? For example, after calling `fit` and `refit`, how can I get more information on the final model? If I simply `print` the "automl" object after calling those fitting functions, I get something like:

```
AutoSklearnRegressor(configuration_mode='SMAC',
             delete_output_folder_after_terminate=True,
             delete_tmp_folder_after_terminate=True,
             disable_evaluator_output=False, ensemble_nbest=50,
             ensemble_size=50, exclude_estimators=None,
             exclude_preprocessors=None, include_estimators=None,
             include_preprocessors=None,
             initial_configurations_via_metalearning=25,
             ml_memory_limit=3072, output_folder=None,
             per_run_time_limit=360, resampling_strategy='cv',
             resampling_strategy_arguments={'folds': 5}, seed=1,
             shared_mode=False, time_left_for_this_task=3600,
             tmp_folder=None)
```

**Comment by mfeurer** [comment]
Similar to [scikit-learn's gridsearch](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) you can use the attribute `cv_results_` to get further information about the trained models. The final ensemble can be displayed by a call to `regressor.show_models()`.
