### ISSUE TITLE
[Suggestion] Distributed learning

### ISSUE THREAD

**Issue by always19** [automl/auto-sklearn#287]
Do you have any plans to make it learn with multiple machines?
I'd like to run automl on multiple aws ec2 instances for speed-up.

Here are some possible suggestions.
1. training/tuning one model in a worker machine
    1. aggregating result in a master machine 
    1. redistribute target hyperparameters to workers
1. using spark https://github.com/databricks/spark-sklearn
1. minibatch like the tensorflow https://www.tensorflow.org/deploy/distributed

Is this already available in a way?
Can I parallelize like https://github.com/automl/auto-sklearn/blob/master/example/example_parallel.py in multiple machines with same shared disk such as s3, hdfs, or NAS ?

**Comment by mfeurer** [comment]
auto-sklearn supports parallel computation as described [in the manual](http://automl.github.io/auto-sklearn/stable/manual.html#parallel-computation). We do not plan to implement any of the suggested mechanisms as the current mechanism is sufficient for what we're doing.

**Comment by always19** [comment]
Thanks! I should have read the manual throughly. 
I'll try the parallel(distributed) computation with aws ec2 machines and s3 disk.
