### ISSUE TITLE
Program is very chatty

### ISSUE THREAD

**Issue by mitar** [automl/auto-sklearn#291]
All those `You are already timing task: index_run3` messages. Are they really necessary.

Maybe auto-sklearn could use [logging](https://docs.python.org/3/library/logging.html) package and then one could configure which types of messages to print out.

**Comment by mfeurer** [comment]
Thanks for reporting. These outputs are indeed unnecessary and we will remove them as soon as we find the time to do so.

**Comment by mfeurer** [comment]
@mitar this should now be fixed in the development branch. Please reopen if it still exists.
