### ISSUE TITLE
Missing 1 character in examples

### ISSUE THREAD

**Issue by 88d52bdba0366127fffca9dfa93895** [automl/auto-sklearn#297]
I tried with some examples and found a small mistake here:

```
tmp_folder='/tmp/autoslearn_cv_example_tmp',
output_folder='/tmp/autosklearn_cv_example_out',
```

`autoslearn` should be `autosklearn`

**Comment by mfeurer** [comment]
Fixed by 23a02d6, will be fixed in the next release. Thanks a lot for reporting this!
