### ISSUE TITLE
OS X installation?

### ISSUE THREAD

**Issue by lenguyenthedat** [automl/auto-sklearn#3]
Might just be me but it's been stuck for a while, anyone experiencing this?

    ~/GitHub/cabinet/auto-sklearn $ python setup.py install
    /Library/Python/2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.0.1dev' to '0.0.1.dev0'
      normalized_version,
    running install
    Building runsolver
    Makefile:23: runsolver.d: No such file or directory
    Makefile:23: SignalNames.d: No such file or directory
    Makefile:23: SyscallNames.d: No such file or directory
    grep '#define[[:space:]]*__NR'  | grep -v '^/' | awk '{print $2}' | sed -e 's/^__NR_//' | awk '{printf "list[__NR_%s]=\"%s\";\n",$1,$1}' > tmpSyscallList.cc

**Comment by mfeurer** [comment]
Hi,
this error seems to occur when building the runsolver. The runsolver is an integral part of auto-sklearn and limits the time and memory usage when running a machine learning algorithm. 

I'm not sure if the runsolver would work with OS X. You download it from [here](http://www.cril.univ-artois.fr/~roussel/runsolver/) and try to build it to see if that causes the error. Nevertheless, we cannot test auto-sklearn on OS X and therefore cannot support it.

**Comment by lenguyenthedat** [comment]
I see, will test it myself and let you know if it's working for me, maybe opening a PR for OS X instruction! :smile: :+1:

**Comment by mfeurer** [comment]
Please try installing the package from pip. We dumped the runsolver now and it should be possible to install auto-sklearn on a MAC.

**Comment by mfeurer** [comment]
I have added OSX testing in #179 which confirms that auto-sklearn works on a MAC.
