### ISSUE TITLE
Error while including estimators but excluding preprocessors

### ISSUE THREAD

**Issue by ZankoNT** [automl/auto-sklearn#302]
Sorry if I'm saying nosense or not using GitHub correctly, it's my first time using it.

I was trying today to use AutoML while including some estimators and excluding some preprocessors simultaneously.
I got an error concerning the line 28-31 of autosklearn/util/pipeline.py:

if include_estimators is not None and \
            exclude_preprocessors is not None:
        raise ValueError('Cannot specify include_estimators and '
                         'exclude_estimators.')

The same happens at line 550 of smbo.py

Shouldn't be exclude_estimators instead of exclude_preprocessors? I think what the code is trying to do is to check the mutual exclusivity of include and exclude arguments, but it checks for the wrong argument.

Sorry again if what I'm saying is incorrect, which is probably the case considering my code expertise. Thank you for your awesome work in this.

**Comment by KEggensperger** [comment]
Yes, you are totally right: This check is wrong. Thank you for reporting that issue.

**Comment by mfeurer** [comment]
Thanks @ZankoNT for reporting and @KEggensperger for fixing this.
