### ISSUE TITLE
Feature request: export ensemble

### ISSUE THREAD

**Issue by mi7plus** [automl/auto-sklearn#306]
Can we have an export function that generates a python code for the ensemble found? Similar to what tpot does.

**Comment by mfeurer** [comment]
The function [show_models()](http://automl.github.io/auto-sklearn/stable/api.html#autosklearn.classification.AutoSklearnClassifier.show_models) provides similar functionality. In case that is not what you need, could you please provide an example of how the code is supposed to look like?

**Comment by mi7plus** [comment]
I dont have an example. I am currently researching for options on automl. The best I have found for now are tpot, auto-sklearn and caret. On auto-sklearn I havent found an export/import model solution which I need for my project. Tpot exports models to a python script, pretty much ready to go as far as I have read. I apologize I havent actually tested each of them. I am just reading up before implementing the proper solution for my project. Thank you for your help.

**Comment by mfeurer** [comment]
You can always [pickle](http://automl.github.io/auto-sklearn/stable/manual.html#model-persistence) to save the whole auto-sklearn object to disc. Maybe it would be a good idea to in the long run use the [VotingClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html) inside auto-sklearn which would be easier to export/print.

**Comment by mi7plus** [comment]
Thank you very much. I didn't know about pickle. I'll give it a try. I am very gratefull for your advice and your work.
