### ISSUE TITLE
Can not install pyrfr ,  error: command 'swig' failed with exit status 1

### ISSUE THREAD

**Issue by eromoe** [automl/auto-sklearn#314]
Hi,

I tried to install auto-sklearn in a ubuntu docker, but stuck at `pyrfr` :

```
  Running setup.py install for pyrfr ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d86q_ln9/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zwpxskjr-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    ./include/rfr/trees/binary_fanova_tree.hpp:329: Error: Syntax error in input(3).
    error: command 'swig' failed with exit status 1
```

ENV: 
- ubuntu 14.04 docker
- gcc 4.8.4
- swig 2.0.11
- python 3.5

**Comment by mfeurer** [comment]
I think this is related to #277 and you need swig3. Let me know if this solves the issue.

**Comment by eromoe** [comment]
Change to swig3 works , thank you !

Solution here:
```
apt-get remove swig
apt-get install swig3.0
ln -s /usr/bin/swig3.0 /usr/bin/swig
```

**Comment by vudya1000** [comment]
Have exactly same issue, but installing swig 3.0 not helped. Please help
ENV:
linux mint 19.2
gcc 7.4
swig 3
python 3.7

**Comment by satyas13** [comment]
!apt-get install swig -y
!pip install auto-sklearn
 solved all the installation issues of auto-sklearn for me.

**Comment by eddiebergman** [comment]
I noticed this issue still gets traffic, to clarify, `swig4` will also work. In general, you can just install `swig` without specifying a version, as mentioned by @satyas13
