### ISSUE TITLE
auto-sklearn deleted my entire home directory necessitating Linux reinstall

### ISSUE THREAD

**Issue by sohrabtowfighi** [automl/auto-sklearn#317]
I run Ubuntu.
I installed pyrfr via pip. I then installed auto-sklearn via pip.
I ran a basic example with minimal modifications.

I received the following error, then my entire home/$username/* directory was deleted. I think I need to reinstall Ubuntu because of auto-sklearn. Maybe there is a notice in the docs somewhere that the output dir must be deleteable, but I don't think that is reasonable.

FileNotFoundError: [Errno 2] No such file or directory: '/home/$username/.local/lib/python3.5/site-packages/autosklearn/util/logging.yaml'
[WARNING] [14:08:38:autosklearn.util.backend] Could not delete output dir: /home/$username

I am guessing that file was not found because it was deleted.
I cannot produce the entire trace because my Linux box is destroyed and I am typing this on second computer.

**Comment by sohrabtowfighi** [comment]
Any easy fix is to only permit using empty directories as tmp and output dir.

**Comment by mfeurer** [comment]
First of all, please excuse us for not safeguarding against auto-sklearn running havoc and deleting your home directory. In order to somehow find out how this happened, do you remember to what location you set the `tmp_dir`?

**Comment by sohrabtowfighi** [comment]
I do not remember to what I set the tmp_dir. It was not the home dir, as far as I remember.

Besides that, the code works great.

**Comment by mfeurer** [comment]
I just pushed a new release with should fix this via #484 - please reopen if this issue is still present with the latest version.
