### ISSUE TITLE
'DataFrame' object has no attribute 'flags'

### ISSUE THREAD

**Issue by MichalGala** [automl/auto-sklearn#318]
Hi Guys,
I had no problem running the autosklearn classifier. 
But when i tried today to run the regressor, i ran into a problem that i cannot solve:

`AttributeError: 'DataFrame' object has no attribute 'flags'`

Having a look at the details of the error, it seems to come from the line 489:

> ~/.local/lib/python3.5/site-packages/autosklearn/estimators.py in fit(self, X, y, metric, feat_type, dataset_name)
>     487         return super(AutoSklearnRegressor, self).fit(X=X, y=y, metric=metric,
>     488                                                      feat_type=feat_type,
> --> 489                                                      dataset_name=dataset_name)
>     490 

This is the code i used:

> automl = autosklearn.regression.AutoSklearnRegressor(time_left_for_this_task=120, per_run_time_limit=30)
> automl.fit(X_train, y_train)
> 

My training sets are pandas DataFrame.

Do you have any idea to fix this?

Have a great day!

**Comment by MichalGala** [comment]
It works when transforming my dataframe with `.values()`

**Comment by mfeurer** [comment]
Great to see that you solved the issue yourself. As this is a duplicate of #157 I'm closing this.

**Comment by jmtatsch** [comment]
Nowadays its recommended to use df.to_numpy()
