### ISSUE TITLE
Installing auto-sklearn with docker does not work

### ISSUE THREAD

**Issue by skycrazer** [automl/auto-sklearn#320]
Does anybody has experience with the auto-sklearn docker container?

I pulled the docker image from https://hub.docker.com/r/mfeurer/auto-sklearn/ and ran it on my docker toolbox (under windows 7 pro) using the following docker command:
"docker run -dt -d -p 8080:8080 mfeurer/auto-sklearn"

As evidenced by the "docker ps" command, the container loads correctly. However, when starting my browser and opening localhost:8080 I get an error message.

Appreciate any comments.

**Comment by mfeurer** [comment]
Sorry, I don't have any experience with the docker images. @ffelixleungsc do you have any idea?

**Comment by mileserickson** [comment]
> As evidenced by the "docker ps" command, the container loads correctly. However, when starting my browser and opening localhost:8080 I get an error message.

@skycrazer What error message do you get? If you can submit the full text and/or a screenshot of the error message, it will help us to understand what is happening. (This is important advice for reporting issues with any software!)

**Comment by felixleungsc** [comment]
To start a Jupyter notebook, you could run e.g.:
```
docker run -it -v $PWD:/opt/nb -p 8888:8888 mfeurer/auto-sklearn \
/bin/bash -c "mkdir -p /opt/nb && jupyter notebook --notebook-dir=/opt/nb --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
```
You would then be prompted with a link to open the notebook in a browser. I would expect `import autosklearn` and the examples to work. If so, this issue can be closed.

@mfeurer perhaps instructions could be added to README.md?

@skycrazer Very sorry I didn't get to reply earlier... I saw your question over at Docker hub only days ago, but still haven't figured out how to get notified of comments there. And unfortunately [in the above](https://github.com/automl/auto-sklearn/issues/320#issuecomment-314650259) I wasn't @ correctly either :/ Hope this is not too late. Would be great if you could report any success in running the Docker image.

**Comment by sharpe5** [comment]
@felixleungsc Can confirm that this works perfectly on Windows 10 x64 + Docker Stable as of 2017-10-30.

**Comment by felixleungsc** [comment]
Awesome! Thanks @sharpe5.

**Comment by mileserickson** [comment]
We haven't heard from @skycrazer since Day 0 and the issue appears to have a resolution. Is there anything left to be done (i.e. documentation updates) before this gets closed?

**Comment by felixleungsc** [comment]
No, other than maybe a short note in the documentation (on how to start the
docker image). Happy to do a PR if you can tell me where in the
documentation to edit. Thanks Miles.

**Comment by mfeurer** [comment]
Sorry for being really slow on following up on all the docker things and thank you for answering these questions! As this is mostly a question about how to install Auto-sklearn, I think it would be best suited in `doc/installation.rst`?

**Comment by mfeurer** [comment]
We finally added those instructions to the manual.

**Comment by Prinsodular** [comment]
> To start a Jupyter notebook, you could run e.g.:
> 
> ```
> docker run -it -v $PWD:/opt/nb -p 8888:8888 mfeurer/auto-sklearn \
> /bin/bash -c "mkdir -p /opt/nb && jupyter notebook --notebook-dir=/opt/nb --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
> ```

Did not work for me on Win 10 x64 + Docker 2.5.0.0 (49427) Stable. I had to put curly braces around `PWD`. Not sure if this might be useful to update instructions @mfeurer :
`docker run -it -v ${PWD}:/opt/nb -p 8888:8888 mfeurer/auto-sklearn:master /bin/bash -c "mkdir -p /opt/nb && jupyter notebook --notebook-dir=/opt/nb --ip='0.0.0.0' --port=8888 --no-browser --allow-root"`

**Comment by mfeurer** [comment]
@eddiebergman could you please have a brief look at whether we want to add the curly braces to the docs?

**Comment by eddiebergman** [comment]
It would make more sense to me to use `$()` with the command `$(pwd):/opt/nb` instead of relying on the environment variable. I'll have a look
