### ISSUE TITLE
can not install pyrfr ,  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by pyfwill** [automl/auto-sklearn#341]
Hi 
  I tried to install auto-sklearn in a ubuntu 16.04, but fail to install pyrfr: 
  Environment configuration:
  Ubuntu 16.04
  gcc 5.4.0
  python 3.5
  swig 3.0.8
  the detailed log is following:

python3.5 setup.py install
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
running build_ext
building '_regression' extension
swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
swig -python -c++ -modern -features nondynamic -I/home/sfalkner/repositories/github/random_forest_run/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sfalkner/repositories/github/random_forest_run/include -I./include -I/usr/include/python3.5m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.5/pyrfr/regression_wrap.o -O2 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/python3.5m/pyport.h:9:0,
                 from /usr/include/python3.5m/Python.h:50,
                 from pyrfr/regression_wrap.cpp:171:
/usr/local/include/inttypes.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^
In file included from /usr/local/include/inttypes.h:48:0,
                 from /usr/include/python3.5m/pyport.h:9,
                 from /usr/include/python3.5m/Python.h:50,
                 from pyrfr/regression_wrap.cpp:171:
/usr/local/include/stdint.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:9:0,
                 from /usr/include/python3.5m/pyport.h:13,
                 from /usr/include/python3.5m/Python.h:50,
                 from pyrfr/regression_wrap.cpp:171:
/usr/local/include/stdint.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^
In file included from ./include/cereal/external/rapidjson/rapidjson.h:168:0,
                 from ./include/cereal/external/rapidjson/stream.h:15,
                 from ./include/cereal/external/rapidjson/writer.h:18,
                 from ./include/cereal/external/rapidjson/prettywriter.h:18,
                 from ./include/cereal/archives/json.hpp:53,
                 from ./include/rfr/forests/regression_forest.hpp:21,
                 from ./include/rfr/trees/k_ary_tree.hpp:26,
                 from pyrfr/regression_wrap.cpp:3171:
/usr/local/include/inttypes.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^
In file included from /usr/local/include/inttypes.h:48:0,
                 from /usr/include/python3.5m/pyport.h:9,
                 from /usr/include/python3.5m/Python.h:50,
                 from pyrfr/regression_wrap.cpp:171:
/usr/local/include/stdint.h:135:30: error: expected initializer before ‘int64_t’
 typedef signed __int64       int64_t;
                              ^
/usr/local/include/stdint.h:136:30: error: expected initializer before ‘uint64_t’
 typedef unsigned __int64     uint64_t;
                              ^
/usr/local/include/stdint.h:147:9: error: ‘uint64_t’ does not name a type
 typedef uint64_t  uint_least64_t;
         ^
/usr/local/include/stdint.h:157:9: error: ‘uint64_t’ does not name a type
 typedef uint64_t  uint_fast64_t;
         ^
/usr/local/include/stdint.h:164:30: error: conflicting declaration ‘typedef int intptr_t’
    typedef _W64 signed int   intptr_t;
                              ^
In file included from /usr/include/python3.5m/Python.h:36:0,
                 from pyrfr/regression_wrap.cpp:171:
/usr/include/unistd.h:270:20: note: previous declaration as ‘typedef __intptr_t intptr_t’
 typedef __intptr_t intptr_t;
                    ^
In file included from /usr/local/include/inttypes.h:48:0,
                 from /usr/include/python3.5m/pyport.h:9,
                 from /usr/include/python3.5m/Python.h:50,
                 from pyrfr/regression_wrap.cpp:171:
/usr/local/include/stdint.h:170:9: error: ‘uint64_t’ does not name a type
 typedef uint64_t  uintmax_t;
         ^
In file included from /usr/include/python3.5m/pyport.h:9:0,
                 from /usr/include/python3.5m/Python.h:50,
                 from pyrfr/regression_wrap.cpp:171:
/usr/local/include/inttypes.h:288:1: error: ‘_inline’ does not name a type
 _inline
 ^
In file included from /usr/include/python3.5m/Python.h:50:0,
                 from pyrfr/regression_wrap.cpp:171:
/usr/include/python3.5m/pyport.h:109:21: error: ‘uint64_t’ does not name a type
 #define PY_UINT64_T uint64_t
                     ^
/usr/include/python3.5m/pyhash.h:65:9: note: in expansion of macro ‘PY_UINT64_T’
         PY_UINT64_T k0;
         ^
/usr/include/python3.5m/pyport.h:109:21: error: ‘uint64_t’ does not name a type
 #define PY_UINT64_T uint64_t
                     ^
/usr/include/python3.5m/pyhash.h:66:9: note: in expansion of macro ‘PY_UINT64_T’
         PY_UINT64_T k1;
         ^
/usr/include/python3.5m/pyport.h:109:21: error: ‘uint64_t’ does not name a type
 #define PY_UINT64_T uint64_t
                     ^
/usr/include/python3.5m/longintrepr.h:51:9: note: in expansion of macro ‘PY_UINT64_T’
 typedef PY_UINT64_T twodigits;
         ^
In file included from /usr/include/c++/4.9/bits/char_traits.h:380:0,
                 from /usr/include/c++/4.9/string:40,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from pyrfr/regression_wrap.cpp:3092:
/usr/include/c++/4.9/cstdint:69:11: error: ‘::uint64_t’ has not been declared
   using ::uint64_t;
           ^
/usr/include/c++/4.9/cstdint:74:11: error: ‘::uint_fast64_t’ has not been declared
   using ::uint_fast64_t;
           ^
/usr/include/c++/4.9/cstdint:79:11: error: ‘::uint_least64_t’ has not been declared
   using ::uint_least64_t;
           ^
/usr/include/c++/4.9/cstdint:81:11: error: ‘::uintmax_t’ has not been declared
   using ::uintmax_t;
           ^
In file included from /usr/include/c++/4.9/random:49:0,
                 from pyrfr/regression_wrap.cpp:3165:
/usr/include/c++/4.9/bits/random.h:1551:5: error: ‘uint_fast64_t’ was not declared in this scope
     uint_fast64_t,
     ^
/usr/include/c++/4.9/bits/random.h:1557:27: error: template argument 1 is invalid
     6364136223846793005ULL> mt19937_64;
                           ^
/usr/include/c++/4.9/bits/random.h:1557:27: note: invalid template non-type parameter
/usr/include/c++/4.9/bits/random.h:1557:27: note: invalid template non-type parameter
/usr/include/c++/4.9/bits/random.h:1557:27: note: invalid template non-type parameter
/usr/include/c++/4.9/bits/random.h:1557:27: note: invalid template non-type parameter
/usr/include/c++/4.9/bits/random.h:1557:27: note: invalid template non-type parameter
/usr/include/c++/4.9/bits/random.h:1557:39: error: invalid type in declaration before ‘;’ token
     6364136223846793005ULL> mt19937_64;
                                       ^
/usr/include/c++/4.9/bits/random.h:1562:38: error: ‘uint_fast64_t’ was not declared in this scope
   typedef subtract_with_carry_engine<uint_fast64_t, 48, 5, 12>
                                      ^
/usr/include/c++/4.9/bits/random.h:1562:62: error: template argument 1 is invalid
   typedef subtract_with_carry_engine<uint_fast64_t, 48, 5, 12>
                                                              ^
/usr/include/c++/4.9/bits/random.h:1563:18: error: invalid type in declaration before ‘;’ token
     ranlux48_base;
                  ^
In file included from ./include/cereal/access.hpp:38:0,
                 from ./include/cereal/details/traits.hpp:43,
                 from ./include/cereal/cereal.hpp:43,
                 from ./include/rfr/splits/binary_split_one_feature_rss_loss.hpp:14,
                 from pyrfr/regression_wrap.cpp:3170:
./include/cereal/details/helpers.hpp:59:21: error: ‘uint64_t’ does not name a type
   using size_type = uint64_t;
                     ^
./include/cereal/details/helpers.hpp:215:25: error: ‘uint64_t’ has not been declared
     BinaryData( T && d, uint64_t s ) : data(std::forward<T>(d)), size(s) {}
                         ^
./include/cereal/details/helpers.hpp:218:5: error: ‘uint64_t’ does not name a type
     uint64_t size; //!< size in bytes
     ^
./include/cereal/details/helpers.hpp: In constructor ‘cereal::BinaryData<T>::BinaryData(T&&, int)’:
./include/cereal/details/helpers.hpp:215:66: error: class ‘cereal::BinaryData<T>’ does not have any field named ‘size’
     BinaryData( T && d, uint64_t s ) : data(std::forward<T>(d)), size(s) {}
                                                                  ^
In file included from ./include/rfr/splits/binary_split_one_feature_rss_loss.hpp:14:0,
                 from pyrfr/regression_wrap.cpp:3170:
./include/cereal/cereal.hpp: At global scope:
./include/cereal/cereal.hpp:564:26: error: ‘size_type’ was not declared in this scope
       std::unordered_set<size_type> itsVersionedTypes;
                          ^
./include/cereal/cereal.hpp:564:35: error: template argument 1 is invalid
       std::unordered_set<size_type> itsVersionedTypes;
                                   ^
./include/cereal/cereal.hpp:564:35: error: template argument 2 is invalid
./include/cereal/cereal.hpp:564:35: error: template argument 3 is invalid
./include/cereal/cereal.hpp:564:35: error: template argument 4 is invalid
./include/cereal/cereal.hpp: In member function ‘uint32_t cereal::OutputArchive<ArchiveType, Flags>::registerClassVersion()’:
./include/cereal/cereal.hpp:478:53: error: request for member ‘insert’ in ‘((cereal::OutputArchive<ArchiveType, Flags>*)this)->cereal::OutputArchive<ArchiveType, Flags>::itsVersionedTypes’, which is of non-class type ‘int’
         const auto insertResult = itsVersionedTypes.insert( hash );
                                                     ^
In file included from ./include/cereal/types/bitset.hpp:34:0,
                 from ./include/rfr/splits/binary_split_one_feature_rss_loss.hpp:15,
                 from pyrfr/regression_wrap.cpp:3170:
./include/cereal/types/string.hpp: In function ‘typename std::enable_if<cereal::traits::is_output_serializable<cereal::BinaryData<T>, Archive>::value, void>::type cereal::save(Archive&, const std::basic_string<CharT, Traits, Alloc>&)’:
./include/cereal/types/string.hpp:44:36: error: ‘size_type’ does not name a type
     ar( make_size_tag( static_cast<size_type>(str.size()) ) );
                                    ^
./include/cereal/types/string.hpp: In function ‘typename std::enable_if<cereal::traits::is_input_serializable<cereal::BinaryData<T>, Archive>::value, void>::type cereal::load(Archive&, std::basic_string<CharT, Traits, Alloc>&)’:
./include/cereal/types/string.hpp:53:5: error: ‘size_type’ was not declared in this scope
     size_type size;
     ^
./include/cereal/types/string.hpp:54:24: error: ‘size’ was not declared in this scope
     ar( make_size_tag( size ) );
                        ^
In file included from ./include/rfr/util.hpp:12:0,
                 from ./include/rfr/splits/binary_split_one_feature_rss_loss.hpp:16,
                 from pyrfr/regression_wrap.cpp:3170:
./include/cereal/types/vector.hpp: In function ‘typename std::enable_if<((cereal::traits::is_output_serializable<cereal::BinaryData<T>, Archive>::value && std::is_arithmetic<T>::value) && (! std::is_same<T, bool>::value)), void>::type cereal::save(Archive&, const std::vector<T, A>&)’:
./include/cereal/types/vector.hpp:44:36: error: ‘size_type’ does not name a type
     ar( make_size_tag( static_cast<size_type>(vector.size()) ) ); // number of elements
                                    ^
./include/cereal/types/vector.hpp: In function ‘typename std::enable_if<((cereal::traits::is_input_serializable<cereal::BinaryData<T>, Archive>::value && std::is_arithmetic<T>::value) && (! std::is_same<T, bool>::value)), void>::type cereal::load(Archive&, std::vector<T, A>&)’:
./include/cereal/types/vector.hpp:54:5: error: ‘size_type’ was not declared in this scope
     size_type vectorSize;
     ^
./include/cereal/types/vector.hpp:55:24: error: ‘vectorSize’ was not declared in this scope
     ar( make_size_tag( vectorSize ) );
                        ^
./include/cereal/types/vector.hpp: In function ‘typename std::enable_if<((! cereal::traits::is_output_serializable<cereal::BinaryData<T>, Archive>::value) || (! std::is_arithmetic<T>::value)), void>::type cereal::save(Archive&, const std::vector<T, A>&)’:
./include/cereal/types/vector.hpp:67:36: error: ‘size_type’ does not name a type
     ar( make_size_tag( static_cast<size_type>(vector.size()) ) ); // number of elements
                                    ^
./include/cereal/types/vector.hpp: In function ‘typename std::enable_if<((! cereal::traits::is_input_serializable<cereal::BinaryData<T>, Archive>::value) || (! std::is_arithmetic<T>::value)), void>::type cereal::load(Archive&, std::vector<T, A>&)’:
./include/cereal/types/vector.hpp:78:5: error: ‘size_type’ was not declared in this scope
     size_type size;
     ^
./include/cereal/types/vector.hpp:79:24: error: ‘size’ was not declared in this scope
     ar( make_size_tag( size ) );
                        ^
./include/cereal/types/vector.hpp: In function ‘void cereal::save(Archive&, const std::vector<bool, A>&)’:
./include/cereal/types/vector.hpp:90:36: error: ‘size_type’ does not name a type
     ar( make_size_tag( static_cast<size_type>(vector.size()) ) ); // number of elements
                                    ^
./include/cereal/types/vector.hpp: In function ‘void cereal::load(Archive&, std::vector<bool, A>&)’:
./include/cereal/types/vector.hpp:99:5: error: ‘size_type’ was not declared in this scope
     size_type size;
     ^
./include/cereal/types/vector.hpp:100:24: error: ‘size’ was not declared in this scope
     ar( make_size_tag( size ) );
                        ^
In file included from ./include/cereal/external/rapidjson/stream.h:15:0,
                 from ./include/cereal/external/rapidjson/writer.h:18,
                 from ./include/cereal/external/rapidjson/prettywriter.h:18,
                 from ./include/cereal/archives/json.hpp:53,
                 from ./include/rfr/forests/regression_forest.hpp:21,
                 from ./include/rfr/trees/k_ary_tree.hpp:26,
                 from pyrfr/regression_wrap.cpp:3171:
./include/cereal/external/rapidjson/internal/../allocators.h: In member function ‘void* rapidjson::MemoryPoolAllocator<BaseAllocator>::Malloc(std::size_t)’:
./include/cereal/external/rapidjson/rapidjson.h:273:55: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                       ^
./include/cereal/external/rapidjson/internal/../allocators.h:180:16: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         size = CEREAL_RAPIDJSON_ALIGN(size);
                ^
./include/cereal/external/rapidjson/rapidjson.h:273:85: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                                                     ^
./include/cereal/external/rapidjson/internal/../allocators.h:180:16: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         size = CEREAL_RAPIDJSON_ALIGN(size);
                ^
./include/cereal/external/rapidjson/rapidjson.h:273:55: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                       ^
./include/cereal/external/rapidjson/internal/../allocators.h:185:63: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         void *buffer = reinterpret_cast<char *>(chunkHead_) + CEREAL_RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + chunkHead_->size;
                                                               ^
./include/cereal/external/rapidjson/rapidjson.h:273:85: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                                                     ^
./include/cereal/external/rapidjson/internal/../allocators.h:185:63: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         void *buffer = reinterpret_cast<char *>(chunkHead_) + CEREAL_RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + chunkHead_->size;
                                                               ^
./include/cereal/external/rapidjson/internal/../allocators.h: In member function ‘void* rapidjson::MemoryPoolAllocator<BaseAllocator>::Realloc(void*, std::size_t, std::size_t)’:
./include/cereal/external/rapidjson/rapidjson.h:273:55: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                       ^
./include/cereal/external/rapidjson/internal/../allocators.h:198:24: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         originalSize = CEREAL_RAPIDJSON_ALIGN(originalSize);
                        ^
./include/cereal/external/rapidjson/rapidjson.h:273:85: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                                                     ^
./include/cereal/external/rapidjson/internal/../allocators.h:198:24: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         originalSize = CEREAL_RAPIDJSON_ALIGN(originalSize);
                        ^
./include/cereal/external/rapidjson/rapidjson.h:273:55: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                       ^
./include/cereal/external/rapidjson/internal/../allocators.h:199:19: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         newSize = CEREAL_RAPIDJSON_ALIGN(newSize);
                   ^
./include/cereal/external/rapidjson/rapidjson.h:273:85: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                                                     ^
./include/cereal/external/rapidjson/internal/../allocators.h:199:19: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         newSize = CEREAL_RAPIDJSON_ALIGN(newSize);
                   ^
./include/cereal/external/rapidjson/rapidjson.h:273:55: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                       ^
./include/cereal/external/rapidjson/internal/../allocators.h:206:67: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         if (originalPtr == reinterpret_cast<char *>(chunkHead_) + CEREAL_RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + chunkHead_->size - originalSize) {
                                                                   ^
./include/cereal/external/rapidjson/rapidjson.h:273:85: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                                                     ^
./include/cereal/external/rapidjson/internal/../allocators.h:206:67: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         if (originalPtr == reinterpret_cast<char *>(chunkHead_) + CEREAL_RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + chunkHead_->size - originalSize) {
                                                                   ^
./include/cereal/external/rapidjson/internal/../allocators.h: In member function ‘bool rapidjson::MemoryPoolAllocator<BaseAllocator>::AddChunk(std::size_t)’:
./include/cereal/external/rapidjson/rapidjson.h:273:55: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                       ^
./include/cereal/external/rapidjson/internal/../allocators.h:240:88: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         if (ChunkHeader* chunk = reinterpret_cast<ChunkHeader*>(baseAllocator_->Malloc(CEREAL_RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + capacity))) {
                                                                                        ^
./include/cereal/external/rapidjson/rapidjson.h:273:85: error: ‘uint64_t’ does not name a type
 #define CEREAL_RAPIDJSON_ALIGN(x) (((x) + static_cast<uint64_t>(7u)) & ~static_cast<uint64_t>(7u))
                                                                                     ^
./include/cereal/external/rapidjson/internal/../allocators.h:240:88: note: in expansion of macro ‘CEREAL_RAPIDJSON_ALIGN’
         if (ChunkHeader* chunk = reinterpret_cast<ChunkHeader*>(baseAllocator_->Malloc(CEREAL_RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + capacity))) {
                                                                                        ^
In file included from ./include/cereal/external/rapidjson/internal/dtoa.h:22:0,
                 from ./include/cereal/external/rapidjson/writer.h:21,
                 from ./include/cereal/external/rapidjson/prettywriter.h:18,
                 from ./include/cereal/archives/json.hpp:53,
                 from ./include/rfr/forests/regression_forest.hpp:21,
                 from ./include/rfr/trees/k_ary_tree.hpp:26,
                 from pyrfr/regression_wrap.cpp:3171:
./include/cereal/external/rapidjson/internal/itoa.h: At global scope:
./include/cereal/external/rapidjson/internal/itoa.h:123:21: error: ‘rapidjson::internal::u64toa’ declared as an ‘inline’ variable
 inline char* u64toa(uint64_t value, char* buffer) {
                     ^
./include/cereal/external/rapidjson/internal/itoa.h:123:21: error: ‘uint64_t’ was not declared in this scope
./include/cereal/external/rapidjson/internal/itoa.h:123:37: error: expected primary-expression before ‘char’
 inline char* u64toa(uint64_t value, char* buffer) {
                                     ^
./include/cereal/external/rapidjson/internal/itoa.h:123:49: error: expression list treated as compound expression in initializer [-fpermissive]
 inline char* u64toa(uint64_t value, char* buffer) {
                                                 ^
./include/cereal/external/rapidjson/internal/itoa.h:123:51: error: expected ‘,’ or ‘;’ before ‘{’ token
 inline char* u64toa(uint64_t value, char* buffer) {
                                                   ^
In file included from ./include/cereal/external/rapidjson/internal/dtoa.h:23:0,
                 from ./include/cereal/external/rapidjson/writer.h:21,
                 from ./include/cereal/external/rapidjson/prettywriter.h:18,
                 from ./include/cereal/archives/json.hpp:53,
                 from ./include/rfr/forests/regression_forest.hpp:21,
                 from ./include/rfr/trees/k_ary_tree.hpp:26,
                 from pyrfr/regression_wrap.cpp:3171:
./include/cereal/external/rapidjson/internal/diyfp.h:34:20: error: expected ‘}’ before end of line
 CEREAL_RAPIDJSON_DIAG_PUSH
                    ^
./include/cereal/external/rapidjson/internal/diyfp.h:34:20: error: expected ‘}’ before end of line
./include/cereal/external/rapidjson/internal/diyfp.h:34:20: error: expected declaration before end of line
pyrfr/regression_wrap.cpp:3054:25: warning: ‘swig_module’ defined but not used [-Wunused-variable]
 static swig_module_info swig_module = {swig_types, 41, 0, 0, 0, 0};
                         ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Any idea?

Thank you in advance.

**Comment by mfeurer** [comment]
Is this with `pyrfr==0.5.0`? If yes, please downgrade to `0.4.0` (`pip install pyrfr==0.4.0`). I hope to get a release out soon which fixes this.

**Comment by pyfwill** [comment]
Hi @mfeurer , i hava tried 0.4.0, use `pip3 install pyrfr==0.4.0`, and also failed

**Comment by mfeurer** [comment]
Could you please post the error message? Adding @sfalkner, maybe he knows what's the issue here.

**Comment by mfeurer** [comment]
Please excuse the slow response. We have updated the auto-sklearn on pypi to work with the latest version of the pyrfr package which should solve the current installation issues. If you still encouter this issue with the latest version please post how you installed auto-sklearn, providing information on:

* whichever applies:
    * plain linux + name + version 
    * virtual environment 
    * AnaConda + version
* compiler and swig version
* python version

and the error log of the installation. Note however that we are currently experiencing some problems with the latest AnaConda version, while AnaConda 4.3.21 works.

**Comment by asemic-horizon** [comment]
I'm not using Anaconda. 

I am on:

* Ubuntu 18.04
* `venv` for a virtual environment, pip 9.0.1
* gcc 7.4.0
* swig 3.0.12

Maybe relevant, maybe not is that this is a Google Compute instance. I've been able to install auto-sklearn on a more vanilla (DigitalOcean) setup before, but GC instances appear to be subtly nonstandard (beginning with the fact that one can't ssh to them without the special GC tooling).

**Comment by mfeurer** [comment]
I'm not familiar with google compute, but the error message suggests that the program `cc1plus` is not installed. According to [this SO answer](https://stackoverflow.com/a/44708372) you need to install the `build-essential` package for your OS.
