### ISSUE TITLE
fit() got unexpected argument 'rng' error

### ISSUE THREAD

**Issue by DDongbak** [automl/auto-sklearn#342]
I'm executing AutoSklearnRegressor now
I got some error about random number generator, but I don't know how to fix it and what the problem is

The errors are as follow.

[ERROR] [2017-08-22 12:17:50,433:AutoMLSMBO(1)::e51e220e9cb6bb8290d11fc269435844] fit() got an unexpected keyword argument 'rng'
[ERROR] [2017-08-22 12:17:50,435:AutoMLSMBO(1)::e51e220e9cb6bb8290d11fc269435844] Error in getting next configurations with SMAC. Using random configuration!

I'm using following version of python pakage.

pyrfr==0.4.0
smac==0.5.0
auto-sklearn==0.2.0

what is problem and how to fix it?
Thanks!

**Comment by KEggensperger** [comment]
This is the same issue as in https://github.com/automl/SMAC3/issues/298 so the error happens in SMAC3. Currently, I don't know where this error comes from, but as @mlindauer pointed out changing this line in SMAC3 should be fine. For that you would need to clone and install SMAC3 from source.

In any case I would recommend to completely reinstall all packages and maybe the API conflict resolves itself.

**Comment by mfeurer** [comment]
Please excuse the slow response. We have updated the auto-sklearn on pypi to work with the latest version of the pyrfr package which should solve the current installation issues. If you still encouter this issue with the latest version please post how you installed auto-sklearn, providing information on:

* whichever applies:
    * plain linux + name + version 
    * virtual environment 
    * AnaConda + version
* compiler and swig version
* python version

and the error log of the installation. Note however that we are currently experiencing some problems with the latest AnaConda version, while AnaConda 4.3.21 works.

**Comment by DGaffney** [comment]
I'm still hitting this issue.

OS: Ubuntu 14.04.5 LTS
Python: 3.4.3
GCC: 4.8.5
Swig: 3.0.2

Stack follows (this is working off of the [cross validation](https://github.com/automl/auto-sklearn/blob/master/example/example_crossvalidation.py) example):
```
>>> automl.fit(X_train.copy(), y_train.copy(), dataset_name='digits')
[WARNING] [2017-10-16 14:43:19,817:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2017-10-16 14:43:19,817:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2017-10-16 14:43:54,908:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2017-10-16 14:43:54,908:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2017-10-16 14:43:54,923:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2017-10-16 14:43:54,923:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 417, in fit
    dataset_name=dataset_name)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 316, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 23, in fit
    self._automl.fit(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 558, in fit
    return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 195, in fit
    return self._fit(loaded_data_manager, metric)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 449, in _fit
    _proc_smac.run_smbo()
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/smbo.py", line 630, in run_smbo
    challengers = self.choose_next(smac)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/smbo.py", line 682, in choose_next
    num_configurations_by_random_search_sorted=500)
  File "/usr/local/lib/python3.4/dist-packages/smac/optimizer/smbo.py", line 216, in choose_next
    self.model.train(X, Y)
  File "/usr/local/lib/python3.4/dist-packages/smac/epm/base_epm.py", line 111, in train
    return self._train(X, Y)
  File "/usr/local/lib/python3.4/dist-packages/smac/epm/rf_with_instances.py", line 142, in _train
    self.rf.fit(data, rng=self.rng)
TypeError: fit() got an unexpected keyword argument 'rng'
```

**Comment by mfeurer** [comment]
According to @sfalkner this is due to an old version of the pyrfr package. Try running `pip uninstall pyrfr` until it says that the package isn't installed, then do `pip install pyrfr==0.6.1`.

**Comment by sslavian812** [comment]
I got the same issue:

OS: Ubuntu 14.04.5 LTS
Python: 3.4.3
GCC: 4.8.5
Swig: 3.0.2
pyrfr (0.6.1)
smac (0.7.2)

The following code:

```
smac = SMAC(scenario=my_scenario, rng=np.random.RandomState(42), tae_runner=my_runner)
parameters = smac.optimize()
```
Causes:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 379, in run
    parameters = self.smac.optimize()
  File "/usr/local/lib/python3.4/site-packages/smac/facade/smac_facade.py", line 369, in optimize
    incumbent = self.solver.run()
  File "/usr/local/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 178, in run
    challengers = self.choose_next(X, Y)
  File "/usr/local/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 246, in choose_next
    self.model.train(X, Y)
  File "/usr/local/lib/python3.4/site-packages/smac/epm/base_epm.py", line 111, in train
    return self._train(X, Y)
  File "/usr/local/lib/python3.4/site-packages/smac/epm/rf_with_instances.py", line 142, in _train
    self.rf.fit(data, rng=self.rng)
TypeError: fit() got an unexpected keyword argument 'rng'
```

**Comment by sfalkner** [comment]
Could you update to pyrfr 0.7.2 (the latest version on PYPI) and see if the problem still exists?

**Comment by sslavian812** [comment]
@sfalkner 
I'm not sure, if it helped or not. I've Installed pyrfr 0.7.2 and I got another issue instead:
https://github.com/automl/auto-sklearn/issues/384

Aster fixing that with reinstalling ConfigSpace 0.3.10, I got this issue about 'rng' again.

It's really confusing.

**Comment by sslavian812** [comment]
@sfalkner 
Can you please help me with this issue? 
I'm still stuck with it. Some packages just not fir together, and I can't make them work.
 
I'm getting the following error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 69, in run
    self.parameters = smac.optimize()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 180, in run
    challengers = self.choose_next(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 241, in choose_next
    self.model.train(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/epm/base_epm.py", line 111, in train
    return self._train(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/epm/rf_with_instances.py", line 142, in _train
    self.rf.fit(data, rng=self.rng)
TypeError: fit() got an unexpected keyword argument 'rng'
````
I believe, that the error comes from here:
https://github.com/automl/SMAC3/blob/master/smac/epm/rf_with_instances.py#L142

Consider the following:
```
from pyrfr import regression
. . .
    self.rf = regression.binary_rss_forest()
    . . .
    self.rf.fit(data, rng=self.rng)
```
Seems, that rss_forest has different api, and there is no "rng" argument. 
I need help here to figure out more about it.


The whole pip list output is here:
```
alabaster (0.7.10)
argparse (1.4.0)
Babel (2.5.1)
certifi (2017.11.5)
chardet (3.0.4)
ConfigSpace (0.4.3)
cycler (0.10.0)
Cython (0.27.3)
docutils (0.14)
idna (2.6)
imagesize (0.7.1)
Jinja2 (2.10)
joblib (0.11)
MarkupSafe (1.0)
matplotlib (2.1.0)
numpy (1.13.3)
pandas (0.21.0)
pip (1.5.4)
psutil (5.4.3)
Pygments (2.2.0)
pynisher (0.4.2)
pyparsing (2.2.0)
pyrfr (0.7.2)
python-dateutil (2.6.1)
pytz (2017.3)
requests (2.18.4)
scikit-learn (0.19.1)
scipy (1.0.0)
setuptools (2.2)
six (1.11.0)
sklearn (0.0)
smac (0.8.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
typing (3.6.2)
urllib3 (1.22)
```

**Comment by mfeurer** [comment]
Could you please try to use the versions given in the `requirements.txt` file?
```
ConfigSpace>=0.3.3,<0.4
pynisher>=0.4
pyrfr>=0.6.1,<0.7
smac>=0.6.0,<0.7
```

**Comment by VincentBonnivard** [comment]
I have the same issue using AutoSkLearn 0.3.0.

I tried to use a previous smac version (0.6.0), but got the following error message when importing autosklearn:
IncorrectPackageVersionError: 'smac 0.6.0' version mismatch (>=0.8)

Installing smac 0.8.0, I end up with ConfigSpace 0.4.4.
Pyrfr is version 0.6.1, pynisher 0.4.2

**Comment by mfeurer** [comment]
There was an issue with previous versions of the `pyrfr` which installed it twice, please try uninstalling it multiple times and then install the latest version.

**Comment by VincentBonnivard** [comment]
Thanks for your answer. Actually, I did try to uninstall it twice, and then install the latest version, but it didn't solve the issue.

The only solution I found was to modify the file SMAC3/smac/epm/rf_with_instances.py, removing the keyword 'rng' in self.rf.fit, as proposed here:
https://github.com/automl/SMAC3/issues/365

**Comment by mfeurer** [comment]
Yeah, we're not sure why this is the case; sorry for that.

**Comment by peterz3g** [comment]
/opt/conda/lib/python3.6/site-packages/smac/epm/rf_with_instances.py in _train(self, X, y, **kwargs)
140 self.rf.options = self.rf_opts
141 data = self.__init_data_container(self.X, self.y)
--> 142 self.rf.fit(data, rng=self.rng)
143 return self
144

TypeError: fit() got an unexpected keyword argument 'rng'
#############################################

pip list| grep pyrfr
pyrfr 0.7.4

the same issue with pyrfr 0.7.4

**Comment by mfeurer** [comment]
@AndreBiedenkapp recently mentioned to me that this happens with an older version of SWIG and that it doesn't happen with the latest version. @AndreBiedenkapp could you please provide a few more details here?
