### ISSUE TITLE
Can't install pyrfr.

### ISSUE THREAD

**Issue by inoue0426** [automl/auto-sklearn#343]
I saw another issue, but I could not install pyfrf.

**environment**

> 02:06:57:yoshitaka-i$ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/Users/inoueyoshitaka/anaconda/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
> Target: x86_64-apple-darwin11.4.2
> Configured with: ./configure --prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++ --bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin --datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share --libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib --with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
> Thread model: posix
> gcc version 4.8.5 (GCC) 
> 02:07:00:yoshitaka-i$ g++ -v
> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/Users/inoueyoshitaka/anaconda/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
> Target: x86_64-apple-darwin11.4.2
> Configured with: ./configure --prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++ --bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin --datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share --libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib --with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
> Thread model: posix
> gcc version 4.8.5 (GCC) 
> 02:07:28:yoshitaka-i$ python --version
> Python 3.6.2 :: Anaconda custom (x86_64)

**Error code**

> 
> 02:07:34:~:yoshitaka-i$ pip install pyrfr
> Collecting pyrfr
>   Using cached pyrfr-0.5.2.tar.gz
> Installing collected packages: pyrfr
>   Running setup.py install for pyrfr ... error
>     Complete output from command /Users/inoueyoshitaka/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/mw/pt0k8m5s3gx973mbqc4twgbc0000gn/T/pip-build-b1c7gldu/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mw/pt0k8m5s3gx973mbqc4twgbc0000gn/T/pip-ze1lfid6-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build_ext
>     building '_regression' extension
>     swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
>     swig -python -c++ -modern -features nondynamic -I/ihome/sfalkner/repositories/github/random_forest_run/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
>     creating build
>     creating build/temp.macosx-10.7-x86_64-3.6
>     creating build/temp.macosx-10.7-x86_64-3.6/pyrfr
>     gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/inoueyoshitaka/anaconda/include -arch x86_64 -I/Users/inoueyoshitaka/anaconda/include -arch x86_64 -I/ihome/sfalkner/repositories/github/random_forest_run/include -I./include -I/Users/inoueyoshitaka/anaconda/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.7-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
>     In file included from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/inttypes.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
>      #error "Use this header only with Microsoft Visual C++ compilers!"
>       ^
>     In file included from /Users/inoueyoshitaka/anaconda/include/inttypes.h:48:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
>      #error "Use this header only with Microsoft Visual C++ compilers!"
>       ^
>     In file included from ./include/cereal/external/rapidjson/rapidjson.h:168:0,
>                      from ./include/cereal/external/rapidjson/stream.h:15,
>                      from ./include/cereal/external/rapidjson/writer.h:18,
>                      from ./include/cereal/external/rapidjson/prettywriter.h:18,
>                      from ./include/cereal/archives/json.hpp:53,
>                      from ./include/rfr/forests/regression_forest.hpp:21,
>                      from ./include/rfr/trees/k_ary_tree.hpp:26,
>                      from pyrfr/regression_wrap.cpp:3168:
>     /Users/inoueyoshitaka/anaconda/include/inttypes.h:38:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
>      #error "Use this header only with Microsoft Visual C++ compilers!"
>       ^
>     In file included from /Users/inoueyoshitaka/anaconda/include/inttypes.h:48:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:135:30: error: expected initializer before ‘int64_t’
>      typedef signed __int64       int64_t;
>                                   ^
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:136:30: error: expected initializer before ‘uint64_t’
>      typedef unsigned __int64     uint64_t;
>                                   ^
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:164:30: error: conflicting declaration ‘typedef int intptr_t’
>         typedef _W64 signed int   intptr_t;
>                                   ^
>     In file included from /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include/stdint.h:9:0,
>                      from /usr/include/sys/resource.h:72,
>                      from /usr/include/sys/wait.h:110,
>                      from /usr/include/stdlib.h:65,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:34,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/stdint.h:93:16: error: ‘intptr_t’ has a previous declaration as ‘typedef long int intptr_t’
>      typedef long   intptr_t;
>                     ^
>     In file included from /Users/inoueyoshitaka/anaconda/include/inttypes.h:48:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:165:30: error: conflicting declaration ‘typedef unsigned int uintptr_t’
>         typedef _W64 unsigned int uintptr_t;
>                                   ^
>     In file included from /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include/stdint.h:9:0,
>                      from /usr/include/sys/resource.h:72,
>                      from /usr/include/sys/wait.h:110,
>                      from /usr/include/stdlib.h:65,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:34,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/stdint.h:98:25: error: ‘uintptr_t’ has a previous declaration as ‘typedef long unsigned int uintptr_t’
>      typedef unsigned long   uintptr_t;
>                              ^
>     In file included from /Users/inoueyoshitaka/anaconda/include/inttypes.h:48:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:169:19: error: conflicting declaration ‘typedef int64_t intmax_t’
>      typedef int64_t   intmax_t;
>                        ^
>     In file included from /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include/stdint.h:9:0,
>                      from /usr/include/sys/resource.h:72,
>                      from /usr/include/sys/wait.h:110,
>                      from /usr/include/stdlib.h:65,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:34,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/stdint.h:106:37: error: ‘intmax_t’ has a previous declaration as ‘typedef long int intmax_t’
>      typedef __INTMAX_TYPE__             intmax_t;
>                                          ^
>     In file included from /Users/inoueyoshitaka/anaconda/include/inttypes.h:48:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/stdint.h:170:19: error: conflicting declaration ‘typedef uint64_t uintmax_t’
>      typedef uint64_t  uintmax_t;
>                        ^
>     In file included from /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include/stdint.h:9:0,
>                      from /usr/include/sys/resource.h:72,
>                      from /usr/include/sys/wait.h:110,
>                      from /usr/include/stdlib.h:65,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:34,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/stdint.h:115:38: error: ‘uintmax_t’ has a previous declaration as ‘typedef long unsigned int uintmax_t’
>      typedef __UINTMAX_TYPE__             uintmax_t;
>                                           ^
>     In file included from /Users/inoueyoshitaka/anaconda/include/python3.6m/pyport.h:6:0,
>                      from /Users/inoueyoshitaka/anaconda/include/python3.6m/Python.h:50,
>                      from pyrfr/regression_wrap.cpp:173:
>     /Users/inoueyoshitaka/anaconda/include/inttypes.h:288:1: error: ‘_inline’ does not name a type
>      _inline
>      ^
>     error: command 'gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "/Users/inoueyoshitaka/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/mw/pt0k8m5s3gx973mbqc4twgbc0000gn/T/pip-build-b1c7gldu/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mw/pt0k8m5s3gx973mbqc4twgbc0000gn/T/pip-ze1lfid6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/mw/pt0k8m5s3gx973mbqc4twgbc0000gn/T/pip-build-b1c7gldu/pyrfr/

**Comment by mfeurer** [comment]
Could you please use `pyrfr==0.4.0` instead of `pyrfr==0.5.2`? The latter one isn't compatible with Auto-sklearn. However, there's no guarantee that Auto-sklearn will work on OSX.

Nevertheless, @sfalkner do you have any idea what's going wrong here? Is the new pyrfr maybe not working on OSX.

**Comment by mfeurer** [comment]
Please excuse the slow response. We have updated the auto-sklearn on pypi to work with the latest version of the pyrfr package which should solve the current installation issues. If you still encouter this issue with the latest version please post how you installed auto-sklearn, providing information on:

* whichever applies:
    * plain linux + name + version 
    * virtual environment 
    * AnaConda + version
* compiler and swig version
* python version

and the error log of the installation. Note however that we are currently experiencing some problems with the latest AnaConda version, while AnaConda 4.3.21 works.
