### ISSUE TITLE
"No valid pipeline found" Error

### ISSUE THREAD

**Issue by LishengSun** [automl/auto-sklearn#346]
Hi Matthias,

I am using auto-sklearn (2.0) to tune SGD for a multilabel problem. I use it as:
`autosklearn.classification.AutoSklearnClassifier(include_estimators='sgd', time_left_for_this_task=int(time_budget), per_run_time_limit=int(time_budget*1/5), output_folder=result_dir, tmp_folder=tmp_dir, delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False)`

And it quit because of the error:

`File "/usr/local/lib/python3.5/dist-packages/autosklearn/pipeline/base.py", line 290, in _get_base_search_space
    assert np.sum(matches) != 0, "No valid pipeline found."
AssertionError: No valid pipeline found.`

How did this happen? What should I try to get rid of this error? Thank you very much!

**Comment by KEggensperger** [comment]
Hi Lisheng,

include_estimators should be a list. Could you please try:

```autosklearn.classification.AutoSklearnClassifier(include_estimators=['sgd', ], time_left_for_this_task=int(time_budget), per_run_time_limit=int(time_budget*1/5), output_folder=result_dir, tmp_folder=tmp_dir, delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False)```

I assume this will fix your problem, although I get a different error message when I try to run your code:
>  ValueError: Trying to include unknown component: s

**Comment by LishengSun** [comment]
Hi Katharina,

Thank you for your quick reply! 

Sorry I had that typo, actually what I have tried was:
`autosklearn.classification.AutoSklearnClassifier(include_estimators=['sgd'], time_left_for_this_task=int(time_budget), per_run_time_limit=int(time_budget*1/5), output_folder=result_dir, tmp_folder=tmp_dir, delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False)`

So it was indeed a list. I have retried it, and still got "No valid pipeline found" error.

**Comment by KEggensperger** [comment]
Hi, I overlooked that you are running it on a multilabel problem. 
As SGD can't handle multilabel (see the properties: https://github.com/automl/auto-sklearn/blob/master/autosklearn/pipeline/components/classification/sgd.py#L111) there is indeed no valid pipeline in your searchspace left.

You could use a different classifier that handles multilabel problems, such as
- liblinear_svc
- bernoulli_nb
- decision_tree
- extra_trees
- gaussian_nb
- k_nearest_neighbor
- ...

**Comment by LishengSun** [comment]
Hi Katharina,

Thank you for pointing it out. I transformed the multilabel classification problem into multiple binary classification problems and now it is working fine.
