### ISSUE TITLE
Possible to save intermediate predictions?

### ISSUE THREAD

**Issue by LishengSun** [automl/auto-sklearn#348]
Hi,

I would like to know if it's possible to save the intermediate predictions made by a auto-sklearn classifier / regressor within the 'time_left_for_this_task'? I would like to do this for plotting the learning curve (performance as a function of time). 

Thank you!

**Comment by mfeurer** [comment]
Hi,

this is kind of possible and already implemented. Have a look into this file: https://github.com/automl/auto-sklearn/blob/master/autosklearn/evaluation/train_evaluator.py

We're doing this to make sure that iterative algorithms have a higher chance of finishing within the time limit. However, the intermediate predictions are overwritten once the training has evolved a bit, so you actually need to adapt that code (for example, save the predictions to a different file with the epoch number attached). Keep in mind that this can become very costly if you want to save the predictions for each epoch.

**Comment by franchuterivera** [comment]
Hello! This was implemented [here](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_pandas_train_test.html#sphx-glr-examples-40-advanced-example-pandas-train-test-py) in this example.

Please reopen if this example does not solve your problem. Thanks for using AutoSklearn!
