### ISSUE TITLE
Meta features definition?

### ISSUE THREAD

**Issue by LishengSun** [automl/auto-sklearn#352]
Hi Matthias,

I would like to know where I can find the definitions of the meta features you mentioned in your paper https://papers.nips.cc/paper/5872-efficient-and-robust-automated-machine-learning.

In the supplemental material, I only found the list of all meta features, is there any detailed definition of them?

Thank you very much!

**Comment by mfeurer** [comment]
Hey, I'm afraid that you need to look into the source code to get the exact definitions.

**Comment by mfeurer** [comment]
Closing this as this has (hopefully) been answered a few years ago. Just in case, the code is [here](https://github.com/automl/auto-sklearn/blob/master/autosklearn/metalearning/metafeatures/metafeatures.py)
