### ISSUE TITLE
Pyrfr build fails on AWS ubuntu machines

### ISSUE THREAD

**Issue by olivier-boisard** [automl/auto-sklearn#353]
Hi,

First of all, congrats to you guys for putting up such a great framework! However, I must admit I haven't been able to install it on my AWS machines.

The first thing I tried was to install it on the target machine (a BitFusion Tensforflow g2.2xlarge instance). The curl command shown in the installation instructions (with pip3 run as sudo) gives a very weird error during the compilation of pyrfr: `#error "Use this header only with Microsoft Visual C++ compilers!"`. See [bitfusion.txt](https://github.com/automl/auto-sklearn/files/1314421/bitfusion.txt) for the complete output of that command.

After that, I tried on a brand new machine, to see if the issue was specific to my environment. TL,DR: in that case, I get different issues, but I'm still unable to install auto-sklearn properly.

So, here's what I did, in details:
1. I  launched a brand new machine on AWS, (Ubuntu Server 16.04 LTS (HVM), t2.medium)
2. I installed a building environment for C++11, as well as pip for python 3:
```
sudo apt-get update
sudo apt-get install build-essential swig python3-pip

```
I installed the dependencies (note the small difference with the installation instruction here: I use pip3, and not pip.):
```
curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install

```
This fails (see [curl.txt](https://github.com/automl/auto-sklearn/files/1314419/curl.txt) file).
The error is "bad installation directory or PYTHONPATH". According to the logs, one way of fixing this is to append build/bdist.linux-x86_64/wheel/ to the PYTHONPATH, which I did:

`export PYTHONPATH="$PYTHONPATH:build/bdist.linux-x86_64/wheel/".`

I then tried to run the "curl" command again. This time, the installation of pyrfr fails with the following error:

```
Installing collected packages: pyrfr
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 344, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 322, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/.local/lib/python3.5/site-packages/pyrfr-0.6.0-py3.5-linux-x86_64.egg'

```
Finally, I tried to force the installation of pyrfr 0.4.0 with pip, as suggested in several issues I've seen on github. The build fails, but somehow pip still claims that the installation was successful. Problem: running the curl command still forces the installation of pyrfr 0.6. So I downloaded the requirement file, forced the pyrfr version to 0.4.0, and tried the installation of the requirements again - the build of pyrfr fails again.

So I just tried to run pip3 install auto-sklearn anyway. It claims to have installed everything successfully, but running pythion3 and trying to import autosklearn.classification fails (module not found).

At this point, I gave up this approach and tried with Conda. Here's what I did, again on a brand new machine as before:
1. I downloaded anaconda: `wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh`
2. I ran the installation: `chmod u+x Anaconda3-4.4.0-Linux-x86_64.sh && ./Anaconda3-4.4.0-Linux-x86_64.sh`
3. Added anaconda's directory to PATH: `export PATH=/home/ubuntu/anaconda3/bin:$PATH`
4. Ran the curl command, forcing the use of anaconda's pip: `curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 /home/ubuntu/anaconda3/bin/pip install &> conda.txt`

At that point, it failed again due to some error with pyrfr (see [conda.txt](https://github.com/automl/auto-sklearn/files/1314420/conda.txt)). Hence, I tried to install the gcc and swig packages for conda, as suggested in the installation instructions, but it failed with the following error:

```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/ubuntu/anaconda3/bin/.gcc-post-link.sh
==> script messages <==
<None>
Attempting to roll back.

LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/ubuntu/anaconda3/bin/.gcc-post-link.sh
==> script messages <==
<None>

```
Not sure what to do next, to be honnest.

Thanks a lot for your support of this matter :)

**Comment by Motorrat** [comment]
>  Problem: running the curl command still forces the installation of pyrfr 0.6.
this seems strange, https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt specifically asks for pyrfr to be >=4.0<5.0. May I suggest you check what exactly is going on there?
The build of pyrfr may fail and as long as 
>  pip still claims that the installation was successful. 
you should be fine. 
So could it be there is a confusion in the version of python and environment that you are calling _after_ the installation?

**Comment by mfeurer** [comment]
Please excuse the slow response. We have updated the auto-sklearn on pypi to work with the latest version of the pyrfr package which should solve the current installation issues. If you still encouter this issue with the latest version please post how you installed auto-sklearn, providing information on:

* whichever applies:
    * plain linux + name + version 
    * virtual environment 
    * AnaConda + version
* compiler and swig version
* python version

and the error log of the installation. Note however that we are currently experiencing some problems with the latest AnaConda version, while AnaConda 4.3.21 works.

**Comment by mroman09** [comment]
olivier-boisard - were you able to get this to work on the aws-ubuntu boxes you specified in your final attempt (using Conda)? I am still in the same boat. A community AMI with auto-sklearn installed would be amazing. 

Thank you.

**Comment by olivier-boisard** [comment]
Yes, it works fine for me now. Will work on an AMI whenever I have time :)

2017-11-01 4:09 GMT+01:00 Michael Roman <notifications@github.com>:
