### ISSUE TITLE
Upgrade to scikit-learn 0.19.0?

### ISSUE THREAD

**Issue by mitar** [automl/auto-sklearn#356]
Any plans to upgrade to scikit-learn version 0.19.0?

**Comment by mfeurer** [comment]
Yes, we plan to upgrade to scikit-learn 0.19 in the mid-future. Prior to that, we need to fix the recurring installation issues and several other issues.

**Comment by mfeurer** [comment]
I just pushed a new release which uses scikit-learn 0.19.1
