### ISSUE TITLE
pyrfr/regression_wrap.cpp:3163:10: fatal error: 'random' file not found

### ISSUE THREAD

**Issue by vlatorre847** [automl/auto-sklearn#360]
Dear All,

I am trying to install auto-scikit on macos and get the infamous problem with pyrfr.

My setup is:
macosx ver.  10.9.5
Python 3.5.2 :: Anaconda custom (x86_64)
gcc version 4.8.5
gcc version in conda 4.8.5
xcode version 6.2

When I use the instruction in the terminal
pip install auto-sklearn 
or the instruction
pip install pyrfr

I get:

`Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /Users/Valyria/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/pip-build-qu06za12/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/tmpnxo_7uolpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-3.5
  creating build/lib.macosx-10.6-x86_64-3.5/pyrfr
  copying pyrfr/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyrfr
  copying pyrfr/docstrings.i -> build/lib.macosx-10.6-x86_64-3.5/pyrfr
  running build_ext
  building '_regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build/temp.macosx-10.6-x86_64-3.5
  creating build/temp.macosx-10.6-x86_64-3.5/pyrfr
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Valyria/anaconda/include -arch x86_64 -I./include -I/Users/Valyria/anaconda/include/python3.5m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.5/pyrfr/regression_wrap.o -O2 -std=c++11
  pyrfr/regression_wrap.cpp:3167:10: fatal error: 'random' file not found
  #include <random>
           ^
  1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command /Users/Valyria/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/pip-build-qu06za12/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/pip-9yefex8f-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/pyrfr
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Valyria/anaconda/include -arch x86_64 -I./include -I/Users/Valyria/anaconda/include/python3.5m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.5/pyrfr/regression_wrap.o -O2 -std=c++11
    pyrfr/regression_wrap.cpp:3167:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/Valyria/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/pip-build-qu06za12/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/pip-9yefex8f-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/4q/g84zdhps5gzbk3t5mfplqjsc0000gn/T/pip-build-qu06za12/pyrfr/
`

Any suggestions?

**Comment by vlatorre847** [comment]
Ok, I was able to install and launch the package, still I am not sure it will 100% work.

Basically you must have, a version of gcc more recent than the 4.7 and have xcode installed.

You cannot install pyrfr by pip, and the only option is to download the package and install it manually.
Be careful to download the 0.6.1 version of the package. If you install the 0.7, auto-sklearn will try to downgrade it at the 0.6.1, downloading it from the repository giving you once again the error.

open the folder were you unzipped the codes and search for the setup.py file.
just change the following line:
extra_compile_args = ['-O2', '-std=c++11']
into:
extra_compile_args = ['-O2', '-std=c++11', '-stdlib=libc++', '-mmacosx-version-min=10.7']

and then install it from the terminal (don't forget to be in the right folder) with the instuction:
sudo python setup.py install

**Comment by mfeurer** [comment]
Thank you very much for posting this installation help. I will link this issue in the docs of the next release.

**Comment by engelen** [comment]
Just to confirm: @vlatorre847's solution worked for me as well. Thanks a lot!

**Comment by suj97** [comment]
Now, this does work for me as well. But after installation is done, when i try to `import autosklearn.classification` , it results in the follwing error : 

`Traceback (most recent call last):
  File "/Users/sujay_khandagale/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/sujay_khandagale/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyrfr._regression'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sujay_khandagale/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 17, in <module>
    _regression = swig_import_helper()
  File "/Users/sujay_khandagale/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 16, in swig_import_helper
    return importlib.import_module('_regression')
  File "/Users/sujay_khandagale/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/sujay_khandagale/anaconda3/lib/python3.6/site-packages/_regression.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  Referenced from: /Users/sujay_khandagale/anaconda3/lib/python3.6/site-packages/_regression.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/sujay_khandagale/anaconda3/lib/python3.6/site-packages/_regression.cpython-36m-darwin.so` 

And i'd also like to add that I had removed the "-stdlib=libc++" flag from the setup.py file. As this is not needed after OSX Mavericks as per https://stackoverflow.com/a/19774902/5756524 
Can this be the issue?

**Comment by jonashaag** [comment]
Works for me with @vlatorre847's instructions and I can run the example (https://automl.github.io/auto-sklearn/stable/#example) as well.

**Comment by aravind1078** [comment]
If you are on mac 10.14 and @vlatorre847  solution is not working for you can refer to this:[https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/52530212#52530212](url)

**Comment by dutyhong** [comment]
@aravind1078, hello,  i can't find the issue that you mentioned above , has it been deleted?

**Comment by mfeurer** [comment]
You can copy the [stackoverflow link](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/52530212#52530212): https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/52530212#52530212

It seems like there is simply something wrong with the formatting of the comment from @aravind1078 which makes github render it incorrectly.

**Comment by aravind1078** [comment]
@dutyhong I have updated my comment

**Comment by orchidmajumder** [comment]
On OSX Mojave, I also had to make `pip` forcefully use the `brew` installed GCC instead of Apple default one by using this command
`env CXX=/usr/local/Cellar/gcc/9.1.0/bin/g++-9 CC=/usr/local/Cellar/gcc/9.1.0/bin/gcc-9 pip install auto-sklearn`

**Comment by youkaichao** [comment]
I solved it by using 
`env CC="/usr/bin/gcc -stdlib=libc++ -mmacosx-version-min=10.7" pip install auto-sklearn`

**Comment by TraumaAI** [comment]
> I solved it by using
> `env CC="/usr/bin/gcc -stdlib=libc++ -mmacosx-version-min=10.7" pip install auto-sklearn`

Suggestion by youkaichao worked.  able to install pyrfr directly.

**Comment by zaphodnothingth** [comment]
I just have to install swig first

`sudo apt-get install -y swig`

**Comment by ricoms** [comment]
I'm running on mac-os, although I was able to run auto-sklearn before, on another notebook.

I found this question that is related to the log that I get: https://stackoverflow.com/questions/14657270/resource-limits-setrlimit-on-mac-os-x

The log error that I get is: 
```
ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': "<class 'pynisher.limit_function_call.AnythingException'>", 'subprocess_stdout': '', 'subprocess_stderr': 'Process pynisher function call:\nTraceback (most recent call last):\n  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap\n    self.run()\n  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File "/Users/ricardo.savii/Library/Caches/pypoetry/virtualenvs/automl-5jcDAkX8-py3.9/lib/python3.9/site-packages/pynisher/limit_function_call.py", line 108, in subprocess_func\n    resource.setrlimit(resource.RLIMIT_AS, (mem_in_b, mem_in_b))\nValueError: current limit exceeds maximum limit\n', 'exitcode': 1, 'configuration_origin': 'DUMMY'}.
```

**Comment by ricoms** [comment]
[update] I discovered what was wrong. I'm using gin-config to facilitate passing parameters, and this turns things into non-pickable. And auto-sklearn depends on pickable things to parallelize.
