### ISSUE TITLE
Loading Model from the output of show_models

### ISSUE THREAD

**Issue by webanalytics** [automl/auto-sklearn#361]
I've loaded a regressor from the output of show_models:
 reg = SimpleRegressionPipeline({'preprocessor:feature_agglomeration:pooling_func':'mean','regressor:random_forest:criterion':'mse','regressor:random_forest:n_estimators':100,'regressor:random_forest:min_samples_leaf':1,'regressor:__choice__':'random_forest','regressor:random_forest:max_features':1.0,'regressor:random_forest:min_samples_split':2,'regressor:random_forest:bootstrap':'False','regressor:random_forest:min_weight_fraction_leaf':0.0,'regressor:random_forest:max_depth':'None','preprocessor:feature_agglomeration:n_clusters':25,'regressor:random_forest:max_leaf_nodes':'None','preprocessor:feature_agglomeration:linkage':'average','rescaling:__choice__':'minmax','preprocessor:__choice__':'feature_agglomeration','one_hot_encoding:use_minimum_fraction':'False','preprocessor:feature_agglomeration:affinity':'cosine','imputation:strategy':'mean'},dataset_properties{'task':4,'sparse':False,'target_type':'regression','multilabel':False,'multiclass':False,'signed':False})
---
but I'm getting the error: 
AttributeError: 'OneHotEncoder' object has no attribute 'preprocessor'
when I call the predict function:
reg.predict(X_test)

Any ideas?

Thanks.

**Comment by mfeurer** [comment]
The method can return an unfitted version of the final ensemble. In this case you need to fit the model to the data prior to using it. Is there any reason why you're using the ensemble from show_models instead of the `AutoSklearnClassifier` directly? If not, the `AutoSklearnClassifier` should be able to predict directly (or after a call to `refit`).

**Comment by webanalytics** [comment]
Fitting the models to the data solved the problem.
Thanks!
