### ISSUE TITLE
About show_models response

### ISSUE THREAD

**Issue by mkcedward** [automl/auto-sklearn#372]
Tried to find related document for the return of show_models. If there is no documents yet, suggesting to add it later on. If having documents, please kindly share it. So that, consumer can study and choose a better model from it.

Second things is that, can we return as an object rather than a string format? Because it will be much more easier for consumer to visualize response object

**Comment by mfeurer** [comment]
Hi, I think you're looking for this function: http://automl.github.io/auto-sklearn/stable/api.html#autosklearn.classification.AutoSklearnClassifier.get_models_with_weights

**Comment by mkcedward** [comment]
Thank you for your suggestion. As I am using 0.2 version which does not come with get_models_with_weigths. Will try it once upgraded to 0.2.1 version.

**Comment by mfeurer** [comment]
Sorry, with 0.2 you have to use the string representation.
