### ISSUE TITLE
Add SelectRates for regression

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#375]
as it is currently only implemented for classification.

**Comment by johnymephisto** [comment]
Can I take it up? Please do give pointers on how to get on with it.

**Comment by mfeurer** [comment]
Hey, thanks for offering your help! I think the following steps are necessary:

1. Get familiar with how different components are implemented in Auto-sklearn. Therefore, please check https://github.com/automl/auto-sklearn/tree/master/autosklearn/pipeline/components/feature_preprocessing and https://automl.github.io/auto-sklearn/master/extending.html
2. Extend the existing select rates class to regression as done for select percentile.
3. Write a unit test, for example following https://github.com/automl/auto-sklearn/blob/development/test/test_pipeline/components/feature_preprocessing/test_select_percentile_regression.py
4. Create a pull request to the development branch.

**Comment by mfeurer** [comment]
Finally, this will be available in the next release.
