### ISSUE TITLE
arff_dict exception

### ISSUE THREAD

**Issue by ingmarschuster** [automl/auto-sklearn#380]
Hi,

when trying to fit the `AutoSklearnClassifier`, I get the following error on Anaconda python 3.6, with dependencies installed through pip:
```
/auto-sklearn/autosklearn/metalearning/input/aslib_simple.py in _read_algorithm_runs(self, filename)
     75             arff_dict = arff.load(fh)
     76 
---> 77         if arff_dict["attributes"][0][0].upper() != "INSTANCE_ID":
     78             self.logger.error(
     79                 "instance_id as first attribute is missing in %s" % (filename))

TypeError: 'generator' object is not subscriptable
```
any ideas?

**Comment by mfeurer** [comment]
I must admit that I've never seen this. Do you maybe have the [arff package](https://pypi.python.org/pypi/arff) installed? If not, would you please provide some further information on the data you're fitting? Also, could you please add some print statements in line 76 to show the type and content of `arff_dict``?

**Comment by ingmarschuster** [comment]
Yes, arff is installed in version 0.9. Everything runs on Anaconda with a Python 3.6 environment, with autosklearn dependencies installed through conda and pip. arff_dict is a generator object, and trying to do `print([string(i) for i in arff_dict])` results in `*** TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper` which I'm not really sure what to do with. A minimal example is actually from the documentation:
```
import autosklearn.classification, sklearn.model_selection, sklearn.datasets, sklearn.metrics
X, y = sklearn.datasets.load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
```
and the call to `fit ` is what throws the exception.

**Comment by mfeurer** [comment]
The issue here is that both the arff package and the liac-arff package install themselves under the name arff in python. We use the latter one, and apparently they are not compatible which is why you see this error message.

**Comment by ingmarschuster** [comment]
Yep, that was the problem, thank you! Now another thing pops up, but I'll post that in the respective issue.

**Comment by maneri13** [comment]
How can I resolve this issue? I am a beginner, trying to run this on Google Colab

**Comment by mfeurer** [comment]
Please make sure that you don't have the package `arff` installed in your colab and only ahve the package `liac-arff` installed.

**Comment by maneri13** [comment]
Thank you, it works now.

After reading the original post, I thought arff was required and not liac-arff for some reason.
