### ISSUE TITLE
Unable to uninstall auto-sklearn

### ISSUE THREAD

**Issue by suj97** [automl/auto-sklearn#387]
I am unable to install auto-sklearn on OSX. Whenever I try to install it using `pip install auto-sklearn` it gives the following error : 
`Using cached auto-sklearn-0.2.1.tar.gz
Requirement already satisfied: setuptools in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: nose in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: six in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: Cython in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: numpy>=1.9.0 in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: scipy>=0.14.1 in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: scikit-learn<0.19.0,>=0.18.1 in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: lockfile in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: joblib in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: psutil in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: pyyaml in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: liac-arff in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: pandas in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: ConfigSpace<0.4,>=0.3.3 in /Library/Python/2.7/site-packages (from auto-sklearn)
Requirement already satisfied: pynisher<0.5,>=0.4 in /Library/Python/2.7/site-packages (from auto-sklearn)
Collecting pyrfr<0.7,>=0.6.1 (from auto-sklearn)
  Could not find a version that satisfies the requirement pyrfr<0.7,>=0.6.1 (from auto-sklearn) (from versions: 0.4.0)
No matching distribution found for pyrfr<0.7,>=0.6.1 (from auto-sklearn)`

And then when I try to install pyrfr using `pip install pyrfr` it fails with
`Failed building wheel for pyrfr`.
Please help me with this.

**Comment by mfeurer** [comment]
Hi, you could try following this instructions: https://github.com/automl/auto-sklearn/issues/360

However, we're not actively aiming for OSX compatibility, so we cannot guarantee that anything here works.
