### ISSUE TITLE
RuntimeWarning: invalid value encountered in greater return (self.a < x) & (x < self.b)

### ISSUE THREAD

**Issue by mkcedward** [automl/auto-sklearn#390]
I am trying to new AutoML in order to automate ML pipeline and I realized that AutoML seems match what I need. So i tried the following sample code to check how can I use it. However, After executing the following code, lots of warming is thrown within 10 seconds. 

Please kindly provide advise on it.

**Environment**
python: 3.5.2
sklearn: 0.18.1 (also tried 0.19.1)
pandas: 0.19.2
numpy: 1.12.1 (also tried 1.13.1)
scipy: 0.19.1
xgb: 0.6
autosklearn: 0.2.0

**Sample Code**
```
import autosklearn.regression
import numpy as np
import datetime

x = np.random.randint(2, size=(250000,100))
y = np.random.randint(2, size=(250000,1))

print(datetime.datetime.now(), 'start')
feature_types = (['numerical'] * 100)

automl = autosklearn.regression.AutoSklearnRegressor(
    time_left_for_this_task=3000, per_run_time_limit=600
)

automl.fit(x, y, dataset_name='boston', feat_type=feature_types)
```

**Warming/ Exception Snippet**
```
2017-11-16 05:45:32.479377 start
[WARNING] [2017-11-16 05:45:33,937:AutoMLSMBO(1)::boston] Could not find meta-data directory /home/anaconda3/lib/python3.5/site-packages/autosklearn/metalearning/files/r2_regression_dense

/home/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py:737: RuntimeWarning: invalid value encountered in true_divide
  (1. - dataset_minimum))
/home/anaconda3/lib/python3.5/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/home/anaconda3/lib/python3.5/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
```

**Comment by mkcedward** [comment]
Seems like I found the root cause which is there is too many 0 in some rows

Reference: https://stackoverflow.com/questions/32115900/python-scipy-scipy-stats-spearmanr-returning-nans

**Comment by mfeurer** [comment]
I doubt your conclusion and assume that something goes wrong in the calculation of the minimal value observed on that dataset - if there is no configuration with a valid value it'll be a NaN which will trigger the rest. This basically means that the first run started by Auto-sklearn failed - maybe you need to increase your time or memory budget.

**Comment by mkcedward** [comment]
Yes, I will further try it. However, I think memory should not be an issue because my machine has more than 100GB memory.

**Comment by mfeurer** [comment]
I pushed a new release. Could you please try again?

**Comment by bioguy2018** [comment]
@mfeurer Hi, I am also facing the same problem I get the following warning messages

> RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)

> RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)

> RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

I am using scikit-learn==0.20.3.

any suggestions ? 

Thanks in advance!

**Comment by mfeurer** [comment]
Hey, which version of Auto-sklearn do you use? Also, does Auto-sklearn emit further output, for example in which line this happens? If not, could you please set up python to raise an error on these warnings and provide me with this information?

**Comment by bioguy2018** [comment]
@mfeurer Hi, Thanks a lot for your reply. I have checked my modules using pip freeze and I actually do not have any module for Auto-sklearn.
I am not directly using the command but I am running it through a package called Scanpy for analyzing data.

https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.rank_genes_groups.html#scanpy.tl.rank_genes_groups

from what I understood, its utilizing it through scikit-learn and my version for it is
scikit-learn==0.20.3.

I still get an output though but I wanna know if this warning is affecting my result and why in the first place I am getting it.

**Comment by mfeurer** [comment]
I'm afraid that your issue has nothing to do with Auto-sklearn and is either a Scanpy or a scikit-learn issue. Please post the issue at the issue tracker of one of these.

Closing this issue as the original issue is regarding Auto-sklearn 0.2.0 and we're currently at 0.5.2.
