### ISSUE TITLE
initial_configurations_via_metalearning and num_metalearning_cfgs?how work?

### ISSUE THREAD

**Issue by FontTian** [automl/auto-sklearn#399]
Please excuse my poor English,I have a few questions to ask you.

First, what about the relationship between initial_configurations_via_metalearning andnum_metalearning_cfgs? Second, there is no explicit mention of the role of the seed in the API, is it used for holdout? thank you.

Recently I translated some things on your official website and wrote the introduction guide, of course they are all in Chinese. I am going to post these on my blog. What should I pay attention to? thank you.

**Comment by FontTian** [comment]
Sorry,I want to say what about the relationship between ensemble_size and num_metalearning_cfgs

**Comment by mfeurer** [comment]
Hi, could you please point me to the place where `num_metalearning_cfgs` is visible to the user? It should only be used internally.

The seed is so far only used to determine the names of output files (they have the seed in their filenames) and as as seed for SMAC.

Great to hear that you like Auto-sklearn so much that you're actually translating our user guide. You should make the examples explicit as they are very helpful.

**Comment by FontTian** [comment]
num_metalearning_cfgs = initial_configurations_via_metalearning ?I  want translation all.not only the example and user guide.But now,I don't understand what the Numbers mean about the initial_configurations_via_metalearning,and It's associated with this variable(num_metalearning_cfgs)

**Comment by mfeurer** [comment]
`initial_configurations_via_metalearning` determines the number of configurations chosen via meta-learning to warmstart the SMAC algorithm. Check [our paper on Auto-sklearn](https://papers.nips.cc/paper/5872-efficient-and-robust-automated-machine-learning) to learn more about this.

You can simply ask further questions in this issue.

**Comment by FontTian** [comment]
Thank you very much for your reply.

Besides, I am using Beijing time. What time zone is your time zone?

In addition, please understand my poor English level. I am very sorry about this.

**Comment by mfeurer** [comment]
Don't worry about your english level, I got your questions so far. If I don't get a question I will ask for clarification. Please do not hesitate to ask further questions. Please do not post questions in German as this excludes a lot of people from github from participating in discussions. 

I usually try to reply within one or two business days during normal working hours of UTC+1.

**Comment by mfeurer** [comment]
Assuming this is solved. If you have any further questions, please reopen this issue.

**Comment by nunocesarsa** [comment]
Hey great package!

I have a follow-up though if we do not warm-start autosklearn it necessarely needs long computation times correct?

**Comment by mfeurer** [comment]
> Hey great package!

Thanks a lot :)

> I have a follow-up though if we do not warm-start autosklearn it necessarely needs long computation times correct?

Yes, that's correct. Although long somewhat depends on the dataset size (for a really small dataset 1h can be more than sufficient while for a large dataset you want to rather spend one day or more).
