### ISSUE TITLE
Using other classifiers with sklearn signatures

### ISSUE THREAD

**Issue by mpearmain** [automl/auto-sklearn#4]
The authors of XGBoost have recently added wrappers to have the same signatures as sklearn classifiers.

https://github.com/dmlc/xgboost/blob/master/demo/guide-python/sklearn_examples.py

Is there an easy way to add this or other classifiers to the list of trained and optimized classifiers?

**Comment by mfeurer** [comment]
There is neither a documented way, nor an API call for that. Nevertheless, please have a look at the [ParamSklearn](https://bitbucket.org/mfeurer/paramsklearn) project, which holds all information about the sklearn models, for example [GB](https://bitbucket.org/mfeurer/paramsklearn/src/72fd1d26f03b46e03ac4c515182ffa125fdb5553/ParamSklearn/components/classification/gradient_boosting.py?at=master).

To add XGBoost support, you have to create such a wrapper class and put it into the module `paramsklearn.components.classification`. You can even use software packages that do not adhere to the sklearn signature by calling different methods in the `fit` and `predict` methods of the wrapper.

**Comment by mfeurer** [comment]
This functionality is finally added and documented, please have a look [here](http://auto-sklearn.readthedocs.org/en/master/extending.html)
