### ISSUE TITLE
Problems installing the dependencies for auto-sklearn on MacOS High Sierra 10.13.2.

### ISSUE THREAD

**Issue by shyamalschandra** [automl/auto-sklearn#400]
I tried the following command form shell and many of the dependencies were not found for MacOS High Sierra:

```
curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
```

What should I do?  Are there replacements for macOS?

I am getting the following error when I run `pip install --user auto-sklearn`:

```
Collecting pyrfr<0.7,>=0.6.1 (from auto-sklearn)
  Could not find a version that satisfies the requirement pyrfr<0.7,>=0.6.1 (from auto-sklearn) (from versions: 0.4.0)
No matching distribution found for pyrfr<0.7,>=0.6.1 (from auto-sklearn)
```

**Comment by wgmueller1** [comment]
I had the same problem. pyrfr requires python3.

**Comment by ratchetwrench** [comment]
Same problem when running python 3.6.3

**Comment by mfeurer** [comment]
We're not testing for OSX compatibility, therefore I cannot give you any advice on how to set up Auto-sklearn on a MacOS. My best guess is to use AnaConda. You could also try the docker image which is provided.

**Comment by ratchetwrench** [comment]
Understood, I have tried with conda and venv thus far on OSX but still no luck.

**Comment by mfeurer** [comment]
Hm, I cannot find a version of pyrfr other than `0.7.2` on [pypi](https://pypi.python.org/pypi/pyrfr). @sfalkner do you have any idea where the other versions went?

@ratchetwrench we're investigating this, it seems like it has nothing to do with OSX.

**Comment by mfeurer** [comment]
Okay, pypi  hosts other versions than 0.7.2 again.
