### ISSUE TITLE
ModuleNotFoundError: No module named 'autosklearn'

### ISSUE THREAD

**Issue by ratchetwrench** [automl/auto-sklearn#402]
When running the sample code in an Anaconda3 env after following instructions. Using sample code:
ModuleNotFoundError: No module named 'autosklearn'

**Comment by mfeurer** [comment]
Could you please execute `pip install auto-sklearn` again and paste the full output? Could you please also give your OS?

**Comment by ratchetwrench** [comment]
Using macOS High Sierra
...
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-048cc99c0d13> in <module>()
      1 import pandas as pd
----> 2 import autosklearn.classification
      3 import sklearn.model_selection
      4 import sklearn.metrics

ModuleNotFoundError: No module named 'autosklearn'

**Comment by mfeurer** [comment]
Could you please paste the output of the installation process? If it is the error from issue #400 we'll try to fix it over there.

**Comment by mfeurer** [comment]
I just pushed a new release - please reopen if this issue is still present with the latest version.

**Comment by dvaosta** [comment]
I have this error trying to use autosklearn in ubuntu 18.04 on virtualbox.
Here is the output of pip install auto-sklearn:
Collecting auto-sklearn
Collecting pyrfr<0.8,>=0.6.1 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/c3/c6/c555cfa3c7d0078dded091d4901ed52344bbb925077aa70b871faf35fd58/pyrfr-0.7.4.tar.gz
Requirement already satisfied: six in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.11.0)
Collecting scikit-learn<0.20,>=0.19 (from auto-sklearn)
  Downloading https://files.pythonhosted.org/packages/eb/f1/8ab06a3ae2f047098a953e43e1714f47ae0db28d2960afcacaa04d671b51/scikit_learn-0.19.2-cp37-cp37m-manylinux1_x86_64.whl (4.9MB)
    100% |████████████████████████████████| 4.9MB 5.6MB/s
Requirement already satisfied: Cython in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.28.5)
Requirement already satisfied: numpy>=1.9.0<=1.14.5 in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.15.1)
Requirement already satisfied: lockfile in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.12.2)
Requirement already satisfied: psutil in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (5.4.7)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.0 in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.4.7)
Requirement already satisfied: liac-arff in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (2.3.1)
Requirement already satisfied: scipy>=0.14.1 in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.1.0)
Requirement already satisfied: setuptools in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (40.2.0)
Requirement already satisfied: pyyaml in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (3.13)
Requirement already satisfied: nose in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.3.7)
Requirement already satisfied: pynisher<0.5,>=0.4 in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.4.2)
Collecting smac<0.9,>=0.8 (from auto-sklearn)
Collecting xgboost==0.7.post3 (from auto-sklearn)
Requirement already satisfied: pandas in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.23.4)
Requirement already satisfied: joblib in /home/davide/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.13.0)
Requirement already satisfied: typing in /home/davide/anaconda3/lib/python3.7/site-packages (from ConfigSpace<0.5,>=0.4.0->auto-sklearn) (3.6.6)
Requirement already satisfied: pyparsing in /home/davide/anaconda3/lib/python3.7/site-packages (from ConfigSpace<0.5,>=0.4.0->auto-sklearn) (2.2.0)
Requirement already satisfied: docutils>=0.3 in /home/davide/anaconda3/lib/python3.7/site-packages (from pynisher<0.5,>=0.4->auto-sklearn) (0.14)
Collecting sphinx-rtd-theme (from smac<0.9,>=0.8->auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/ef/0c/e4a462190506bc4bff6ca8cf93da07b2d13e540466d2e8a760352d0c69b0/sphinx_rtd_theme-0.4.2-py2.py3-none-any.whl
Requirement already satisfied: sphinx in /home/davide/anaconda3/lib/python3.7/site-packages (from smac<0.9,>=0.8->auto-sklearn) (1.7.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/davide/anaconda3/lib/python3.7/site-packages (from pandas->auto-sklearn) (2.7.3)
Requirement already satisfied: pytz>=2011k in /home/davide/anaconda3/lib/python3.7/site-packages (from pandas->auto-sklearn) (2018.5)
Requirement already satisfied: Jinja2>=2.3 in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.10)
Requirement already satisfied: Pygments>=2.0 in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.2.1)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.6.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (0.7.11)
Requirement already satisfied: imagesize in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.1.0)
Requirement already satisfied: requests>=2.0.0 in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.19.1)
Requirement already satisfied: packaging in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (17.1)
Requirement already satisfied: sphinxcontrib-websupport in /home/davide/anaconda3/lib/python3.7/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/davide/anaconda3/lib/python3.7/site-packages (from Jinja2>=2.3->sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/davide/anaconda3/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (2018.8.24)
Requirement already satisfied: idna<2.8,>=2.5 in /home/davide/anaconda3/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/davide/anaconda3/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/davide/anaconda3/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (3.0.4)
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /home/davide/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xon9zdnu/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-gm2k0zxe --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'pyrfr._regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr, scikit-learn, sphinx-rtd-theme, smac, xgboost, auto-sklearn
  Running setup.py install for pyrfr ... error
    Complete output from command /home/davide/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xon9zdnu/pyrfr/setup.py';f=getattr(tokenize, 'open',open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1wxv4e2m/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'pyrfr._regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1

    ----------------------------------------
Command "/home/davide/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xon9zdnu/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1wxv4e2m/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xon9zdnu/pyrfr/

**Comment by mfeurer** [comment]
You need to install swig. Please check the [installation instructions](C++ compiler (with C++11 supports) and SWIG (version 3.0 or later)).

**Comment by SoYoungCho** [comment]
Hi, having the same issue here.
Code ran just fine about 15 hours ago, and suddenly this error shows up.
```
Traceback (most recent call last):
  File "20KHz_sklearn.py", line 7, in <module>
    import autosklearn.classification as clf
  File "/home/user/syc/code_scripts/20KHz/autosklearn.py", line 7, in <module>
    import autosklearn.classification as clf
ModuleNotFoundError: No module named 'autosklearn.classification'; 'autosklearn' is not a package
```
Using ```Ubuntu 18.04.4 LTS```, installed swig and autosklearn about a month ago.
Any help?

**Comment by mfeurer** [comment]
I think the issue here is that you have a file called `autosklearn.py` in the directory `20KHz`. When you do `import autosklearn.classification as clf` it tries to import this file instead of auto-sklearn. Please rename the file and try again.

**Comment by SoYoungCho** [comment]
Yes. It turned out that I did name a file wrong.
Should be more careful naming files as well.  Thanks a lot 👍

**Comment by patpankaj** [comment]
i am getting an error as shown below when installing the auto-learn library
i am using the below command to install that library
!pip install auto-sklearn
Collecting auto-sklearn
  Using cached auto-sklearn-0.15.0.tar.gz (6.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
WARNING: Ignoring invalid distribution -rkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ryptography (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ryptography (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [17 lines of output]
  Traceback (most recent call last):
    File "C:\Users\panka\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\panka\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\panka\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\panka\AppData\Local\Temp\pip-build-env-zpvz8frp\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\panka\AppData\Local\Temp\pip-build-env-zpvz8frp\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "C:\Users\panka\AppData\Local\Temp\pip-build-env-zpvz8frp\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\panka\AppData\Local\Temp\pip-build-env-zpvz8frp\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 10, in <module>
  ValueError: Detected unsupported operating system: win32. Please check the compability information of auto-sklearn: https://automl.github.io/auto-sklearn/master/installation.html#windows-osx-compatibility
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution -rkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ryptography (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)

Even i am also  upgrade the pip  i am getting following error,

i am using the below command to install that library
!pip install --upgrade pip
Requirement already satisfied: pip in c:\users\panka\appdata\roaming\python\python38\site-packages (22.1.2)
Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)

[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
WARNING: Ignoring invalid distribution -rkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ryptography (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ryptography (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)
ERROR: To modify pip, please run the following command:
C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip
WARNING: Ignoring invalid distribution -rkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ryptography (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ckaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)
import pandas as pd

**Comment by aron-bram** [comment]
Hi, 
As far as I can see, you are trying to run autosklearn on a Windows, which is an operating system not officially supported by us. However, there are some workarounds for running on Windows. Please refer to [Windows/macOS compatibility](https://automl.github.io/auto-sklearn/master/installation.html#windows-macos-compatibility) for more information.

**Comment by SkoilElikikou** [comment]
Hello,
I installed the autosklearn(0.15.0) in colab using python 3.9.12 following the installation guide and the same error pops up.

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-27-bb85952a9dd8>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import autosklearn.classification

ModuleNotFoundError: No module named 'autosklearn'

**Comment by eddiebergman** [comment]
@SkoilElikikou did you restart your notebook after install `autosklearn`?

**Comment by SkoilElikikou** [comment]
Yes and the issue persisted, but since the docker approach  mentioned in the installation guide works fine  I am able to continue my projects. Thanks for the reply.
