### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by gvelchuru** [automl/auto-sklearn#403]
Since I've been having the abort on first crash issue, I've been trying to install from the development branch. Everything works fine until I actually run my code, which returns the following error:
![image](https://user-images.githubusercontent.com/1124570/34510225-d66c8a02-f006-11e7-9ae6-55bc7a32e4a0.png)

**Comment by mfeurer** [comment]
This appears to be an issue with your installation, but I do not know how to solve it and where it comes from. Do you have libgcc installed? Also, did you try to google the error message?

**Comment by gvelchuru** [comment]
I already have libgcc installed and I tried to google the error message, but I mostly found errors with libgcc installations which I don't seem to have.

**Comment by mfeurer** [comment]
Hm, it's really hard to tell where this could come from. Do other python programs work as expected in your virtual environment?

**Comment by mfeurer** [comment]
I just pushed a new release. Could you please try that?

**Comment by gvelchuru** [comment]
Same error, I actually get this error even when running the test scripts with EXAMPLES set to true.

**Comment by mfeurer** [comment]
According to googling, you're using a 64bit OS, but link against a 32bit shared object, see for example [here](https://www.linuxquestions.org/questions/linux-newbie-8/libgcc_s-so-1-must-be-installed-for-pthread_cancel-to-work-4175474124/). You could try to find out by running:
```bash
find ~/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/ -name '*.so' | xargs -l -n 1 ldd | grep libgcc_s.so.1
```
in which you replace the path to your site packages path. The output is something like this:
```
	libgcc_s.so.1 => /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/utils/../../../../libgcc_s.so.1 (0x00007f72dc685000)
	libgcc_s.so.1 => /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/cluster/../../../../libgcc_s.so.1 (0x00007fb4ab4af000)
	libgcc_s.so.1 => /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/cluster/../../../../libgcc_s.so.1 (0x00007fab6f70d000)
	libgcc_s.so.1 => /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/svm/../../../../libgcc_s.so.1 (0x00007ff6f5083000)
	libgcc_s.so.1 => /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/svm/../../../../libgcc_s.so.1 (0x00007fe03cca1000)
	libgcc_s.so.1 => /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/svm/../../../../libgcc_s.so.1 (0x00007eff64428000)
```
Now you can do:
```
file /home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/utils/../../../../libgcc_s.so.1
```
which displays you some stats about the libgcc you link against:
```
/home/feurerm/miniconda3_4.3.30/envs/benchmark_smac/lib/python3.6/site-packages/sklearn/utils/../../../../libgcc_s.so.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```
(obviously, you need to replace the paths to the respective paths on your system).

**Comment by gvelchuru** [comment]
I followed your steps, and I received a message that seems identical to yours:

`/home/gvelchuru/miniconda/envs/testenv/lib/libgcc_s.so.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
`
Is this correct. or should it be linking to the 32-bit libgcc?

**Comment by mfeurer** [comment]
Hm, that looks fine. Is this a completely new environment?

**Comment by gvelchuru** [comment]
Yes, I followed the same environment creation path as done on the Travis CI runners.

**Comment by mfeurer** [comment]
Thats should work. I'm getting clueless. Any chances that you're on a 32-bit OS?

**Comment by gvelchuru** [comment]
Nope, neofetch returns the following:
            .-/+oossssoo+/-.               gvelchuru@Mycroft
        `:+ssssssssssssssssss+:`           -----------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 16.04.3 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: Workform_2000.v6 S15694817700535
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.10.0-42-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 4 days, 2 hours, 31 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2195
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.3.48
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Cinnamon
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter (Muffin)
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: ()
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Ambiance [GTK3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Ubuntu-mono-dark [GTK3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: /dev/pts/8
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel Xeon E5-2620 v4 (32) @ 3.000GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA NVIDIA Corporation Device 1cb2
      -+sssssssssssssssssyyyssss+-         Memory: 11839MiB / 128807MiB
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.

**Comment by mfeurer** [comment]
Okay, one more to try:
```bash
for so in `find ~/miniconda3_4.3.30/envs/benchmark_smac/ -name '*.so'`; 
do 
    contains_libgcc=`ldd $so | grep libgcc_s.so.1`
    if [ ! -z "$contains_libgcc" ]; then
        echo $so
        ldd $so 
    fi
done
```
This should show all libraries that potentially link against the culprit library. If there is any library linking against a 32-bit version, that's the issue.

**Comment by gvelchuru** [comment]
Every single library links to a 64-bit version :(

**Comment by mfeurer** [comment]
Since this issue is not necessarily an Auto-sklearn issue, you could try to pin down which part of your installation causes issues by trying out the different parts of Auto-sklearn:

* SMAC
* scikit-learn
* pynisher
* psutil
* the python threading/subprocess library
* python

In order to narrow down the source of the errors, you could add print statements with the argument `flush=True` throughout the code to see where it fails.

**Comment by gvelchuru** [comment]
I couldn't figure it out but I managed to just get SMAC working on its own
