### ISSUE TITLE
CompilerCrash when running python3 setup.py install

### ISSUE THREAD

**Issue by gvelchuru** [automl/auto-sklearn#405]
![image](https://user-images.githubusercontent.com/1124570/34544999-ae683680-f09e-11e7-9c00-2089c848c3a4.png)

**Comment by mfeurer** [comment]
Could you please paste the output instead of providing an image? Also, what Cython and Python version are you using?

According to travis-ci, there's currently no problem with the configuration space package: https://github.com/automl/ConfigSpace/tree/master/ConfigSpace

**Comment by mfeurer** [comment]
I just pushed a new release. Could you please try with the latest version?

**Comment by gvelchuru** [comment]
I think I had the wrong requirements, reinstalling requirements seemed to work
