### ISSUE TITLE
Is parallel computation possible in the newest code?

### ISSUE THREAD

**Issue by BoyuanChen** [automl/auto-sklearn#414]
Hi,

I am wondering if it is possible to use multi cores to run parallel computation on the newest code base. I saw there was a issue last year and it said that the default mode at the point was able to use 2 cpus. Is there any updates on that?

Thanks!

**Comment by mfeurer** [comment]
Yes, this is still possible. Please take a look into the example directory. You can find:

* example_parallel: a parallel version which does ensemble building after the optimization
* example_sequential: a sequential version which does ensemble building after the optimization (and therefore only uses a single core)
* a lot of other examples indeed using up to two cores (not 100% correct, they use two processes - depending on the setup of your BLAS library, they still might use all cores).

I hope this helps.

**Comment by BoyuanChen** [comment]
@mfeurer Thank you so much for your swift response! Regarding example_parallel, I am supposing this code helps run multiple autosklearn instances parallelly but does not help run each instance parallelly. Is this correct? Basically, my understanding of this code is that: it will not help speed up each autosklearn instance, right? Thanks for your detailed explanation again!

Cheers!

**Comment by mfeurer** [comment]
I am not sure if I got the question 100% correct. Is the question you're asking whether the script `example_parallel.py` will share information across different runs? If so, the answer is yes. The argument `shared_mode=True` will make the underlying optimization algorithm try to read output of related classifiers.

**Comment by Motorrat** [comment]
@BoyuanChen whether each instance uses one core only or multiple cores depends on the algorithms happen to be in its pipeline. There are some that use multiple cores at some point in their run time. And just to be clear the instances share their results as @mfeurer has pointed out above. 

If you want to look into massively parallel execution you might be interested in the further extension of the example_parallel https://github.com/paypal/autosklearn-zeroconf

**Comment by mfeurer** [comment]
Closing this as the question seems to be answered.
