### ISSUE TITLE
Huge file size when saving model

### ISSUE THREAD

**Issue by Hawkings** [automl/auto-sklearn#421]
After running auto-sklearn for several hours to generate a regression model, I save it with joblib. The generated file has a size of 2.5 GiB. I suspect that unnecessary data is being saved to the disk. Can I save the best model found only? I just need to make predictions with the model in the future, nothing else.

**Comment by mfeurer** [comment]
There is currently no mechanism to only retrieve the underlying scikit-learn model, however, such a functionality would be great. Also, I doubt that this is an issue with saving unnecessary data to disk. Could you please pickle the different models which are loaded into memory and report the file size of each single one? You can access them via `regressor._automl.models_.values()`.

**Comment by mfeurer** [comment]
I just pushed a new release which should fix this issue via #458 - please reopen if this issue is still present with the latest version.

**Comment by teresaconc** [comment]
@mfeurer I faced this issue recently. 
My dataset is quite big (1 or 2 GB) and I ran the optimization for around 6h producing a pickle file (after fitting the ensemble) of around 15GB.

Is this the expected behaviour? Seems like it is not just saving the final ensemble model.
