### ISSUE TITLE
Issue with import autosklearn.classification

### ISSUE THREAD

**Issue by ek676e** [automl/auto-sklearn#427]
ModuleNotFoundError: No module named 'resource'

I get this error when I try to execute " import autosklearn.classification" in Spider. Can you please help me with this. 

Thank you, 
Ehsan Khan

**Comment by mfeurer** [comment]
Could you please report your OS?

**Comment by ek676e** [comment]
Hello it's windows OS (64).

Thanks,
Ehsan Khan

Regards,
Ehsan Khan
mdehsank@gmail.com
www.linkedin.com/in/mdehsankhan
318-533-9126

**Comment by ek676e** [comment]
Windows 64

**Comment by mfeurer** [comment]
Auto-sklearn does not support Windows as the `resource` module is not available on Windows. Note to ourselves: make a better error message!

**Comment by mfeurer** [comment]
Added in 69cbb14c706cf41fc51595edbc601faef02629c6.
