### ISSUE TITLE
Is there a functionality to run each pipeline for a certain number of iterations?

### ISSUE THREAD

**Issue by chengrunyang** [automl/auto-sklearn#428]
It seems I can limit runtime/memory that auto-sklearn can take but not iterations of each pipeline (http://automl.github.io/auto-sklearn/stable/manual.html?highlight=iteration#time-and-memory-limits). Is this correct? It seems I need to specify time_left_for_this_task according to line 60 of the code at https://github.com/automl/auto-sklearn/blob/master/autosklearn/automl.py.

Thanks!

**Comment by mfeurer** [comment]
It is correct that you can only specify the runtime and memory limits of Auto-sklearn via arguments to Auto-sklearn. However, you can also pass arguments to the underlying Bayesian optimization algorithm like this:
```python
automl = AutoSklearnClassifier(
    smac_scenario_args={'runcount_limit': 1000},
)
```

**Comment by chengrunyang** [comment]
It seems (from previous links I pasted here) that either runtime or memory limit is a must; is it correct? Your example seems to show that it is possible for me to only specify a runcount_limit without limiting runtime or memory.

**Comment by mfeurer** [comment]
I just tried whether it is possible to not set a maximum time or a maximum memory usage - however, we don't support that. You could simply set both to a very high value.

**Comment by chengrunyang** [comment]
Thanks for the information!

**Comment by jmren168** [comment]
After setting runcount_limit to limit the number of run for each pipeline, it is possible to get how many runs finally executed for each pipeline? Any comments are highly appreciated.

**Comment by mfeurer** [comment]
@jmren168 please open a new issue for asking a question.
