### ISSUE TITLE
Auto-sklearn on Windows 10 with Ubuntu Bash Shell

### ISSUE THREAD

**Issue by RomuloDrumond** [automl/auto-sklearn#431]
Hello everybody!

I just wanna inform that is possible to use auto-sklearn on Windows 10 with Ubuntu Bash Shell. I've been using auto-sklearn + jupyter notebook with the Ubuntu bash shell for a week now.
I may suggest adding in the "Windows/OSX compability" section of the page http://automl.github.io/auto-sklearn/stable/installation.html that "Windows 10 bash shell" is a tested possible solution.

If you want a quick tutorial in installing the bash shell: https://docs.microsoft.com/en-us/windows/wsl/install-win10. After that you install things like you are in an ubuntu bash shell.

Best regards.

**Comment by Alexandre66** [comment]
Hello @RomuloDrumond !

I've just downloaded Ubuntu Bash Shell on Windows 10. I was using jupyter notebook on Windows but I want to test auto sklearn. 
I am really not familiar with Ubuntu, do I need to download Jupyter on Ubuntu Bash Shell in order to use the auto sklearn package ?

Thanks.

**Comment by mfeurer** [comment]
Hi @Alexandre66, jupyter is independent of BASH or Ubuntu, check out [this explanation of jupyter](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook). Therefore, you do not need to download jupyter to run Auto-sklearn inside a python script on Ubuntu subsystem.

**Comment by Alexandre66** [comment]
Thanks @mfeurer for your answer.
However a problem remains. I have followed the procedure explained in https://docs.microsoft.com/en-us/windows/wsl/install-win10 in order to have the Ubuntu Bash Shell. 
Then I used the auto sklearn documentation to install auto-sklearn https://automl.github.io/auto-sklearn/stable/installation.html#installation. This is where I have a problem.

**Comment by mfeurer** [comment]
Sorry for the late answer, I'm not receiving any emails for this repo any more and didn't notice this.

Probably you need to replace `pip` with `pip3` in the installation command. If that helps, please let me know.

**Comment by diogo-bastos** [comment]
I used the ubuntu bash shell to develop my contribution to auto-sklearn. I had to use pip3 instead of pip to install it and even replaced pip by pip3 and nosetests by nosetests3 in the makefile. 

I got it working and was able to run the tests.

**Comment by asmgx** [comment]
While installing AutoSklearn I got this error

ValueError: SMAC requires Python 3.4 or newer.
enter image description here

when I checked python version it was 3.6.7

Why am I getting this error??

![](https://i.stack.imgur.com/AG45Y.png)

another question,

I am using Spyder from Anaconda on my windows. can I still use that for AutoSklearn? i mean using bash on Windows will allow Anaconda access AutoSklearn??

if not then how can I use Python from bash??

**Comment by NaderNazemi** [comment]
> While installing AutoSklearn I got this error
> 
> ValueError: SMAC requires Python 3.4 or newer.
> enter image description here
> 
> when I checked python version it was 3.6.7
> 
> Why am I getting this error??
> 
> ![](https://camo.githubusercontent.com/af2e03efcda04e471d7e149675440df3687cdcf0/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f41473435592e706e67)
> 
> another question,
> 
> I am using Spyder from Anaconda on my windows. can I still use that for AutoSklearn? i mean using bash on Windows will allow Anaconda access AutoSklearn??
> 
> if not then how can I use Python from bash??

I would like to know the answer as well.

**Comment by asmgx** [comment]
Finally I found the way to install Auto Sklearn

It is long but it works (at least worked for me)

1-

Install Ubuntu from Microsoft Store
2-

sudo apt-get install software-properties-common
3-

sudo apt-add-repository universe
4-

sudo apt-get update
5-

sudo apt-get install python-pip
6-

sudo apt install python3-pip
7-

sudo apt-get install swig
8-

pip3 uninstall numpy
9-

pip3 uninstall numpy
10-

pip uninstall numpy
11-

pip uninstall numpy
12-

curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install
13-

pip3 uninstall numpy
14-

pip3 uninstall numpy
15-

pip uninstall numpy
16-

pip uninstall numpy
17-

pip3 install numpy
18-

pip3 install auto-sklearn

**Comment by zhuygln** [comment]
> Finally I found the way to install Auto Sklearn
> 
> It is long but it works (at least worked for me)
> 
> 1-
> 
> Install Ubuntu from Microsoft Store
> 2-
> 
> sudo apt-get install software-properties-common
> 3-
> 
> sudo apt-add-repository universe
> 4-
> 
> sudo apt-get update
> 5-
> 
> sudo apt-get install python-pip
> 6-
> 
> sudo apt install python3-pip
> 7-
> 
> sudo apt-get install swig
> 8-
> 
> pip3 uninstall numpy
> 9-
> 
> pip3 uninstall numpy
> 10-
> 
> pip uninstall numpy
> 11-
> 
> pip uninstall numpy
> 12-
> 
> curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install
> 13-
> 
> pip3 uninstall numpy
> 14-
> 
> pip3 uninstall numpy
> 15-
> 
> pip uninstall numpy
> 16-
> 
> pip uninstall numpy
> 17-
> 
> pip3 install numpy
> 18-
> 
> pip3 install auto-sklearn

it works for me with 

`sudo apt-get install python-dev libxml2-dev libxslt-dev
`

**Comment by mfeurer** [comment]
Thanks a lot everyone for your discussion and suggestions. I will close this for now and reference this issue from the manual.
