### ISSUE TITLE
Could not find a version that satisfies the requirement smac<0.9,>=0.8

### ISSUE THREAD

**Issue by Steven-AA** [automl/auto-sklearn#433]
I have install the smac from https://github.com/automl/SMAC3
and it is fine when I am doing
 `curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install`
I got this
`Requirement already satisfied: smac in /home/***/anaconda2/envs/py35/lib/python3.5/site-packages`
however, when I run  ` pip install auto-sklearn`

I got this error
`Collecting smac<0.9,>=0.8 (from auto-sklearn)  
Could not find a version that satisfies the requirement smac<0.9,>=0.8 (from auto-sklearn) (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2) No matching distribution found for smac<0.9,>=0.8 (from auto-sklearn)`

I am using Ubuntu, anaconda, python3.5.

**Comment by hohdiy** [comment]
if you use anaconda，you must run `conda install gxx_linux-64 gcc_linux-64 swig` first，then the problem will be solved.

**Comment by Steven-AA** [comment]
It works, thanks a lot.
I should read the document more carefully.
