### ISSUE TITLE
Temp files (especially hidden .autosklearn model files) taking 330 GB

### ISSUE THREAD

**Issue by PRBorole** [automl/auto-sklearn#454]
Hi,
I ran Autosk learn for one dataset (70 row, 7598 columns). The time_left_for_this_task was set to 21600 seconds. It was ran for 8 fold cross validation (looped over for 8 times with 8 different training and test dataset) so the total run time was approximately 2 days. 

The issue is it produced around 330 GB worth of temp file in the hidden folder which took up all the memory causing run to stop. This did not happen previously when I ran the same file for same duration. 
Is there a reason why these many files are generated and a way to prevent this to happen in future?

I cannot attach the entire log file as it is 125 MB in size. Thus, I have attached initial part of the file. 
Please let me know if any other information is needed

Thank you.
[size problem.txt](https://github.com/automl/auto-sklearn/files/1868311/size.problem.txt)

**Comment by mfeurer** [comment]
330 GB is very extreme and I never saw that much output myself. I do not know why it generated that much output. Could you please check in the logfile how many calls to the target algorithm Auto-sklearn did. You can see this by looking for the last occurence of the string `num_run`. Also, you can [check what kind of files are the largest ones](https://askubuntu.com/a/644214), maybe there's something odd in there.

A general solution would be to [restrict the number of function evaluations to a low number ~2000](https://github.com/automl/auto-sklearn/issues/428).

**Comment by frehseg** [comment]
Hi, I have a similar problem on a dataset with 32 inputs at 3000 points. After a run of ~12h on 4 processors, 30Gb of disk space are taken up by 7000+ model files in .auto-sklearn/models/. Many files are 100+ MB and of type libsvm_svc. This is with ensemble_size=10, ensemble_nbest=20. num_run is 2300 (per processor?). Are the model files never deleted?

PS: Thanks for the fantastic work!

**Comment by mfeurer** [comment]
Correct, model files are never deleted. We'd be looking for a contributor on this ;)

**Comment by koolkao** [comment]
Hi I found that model files that are left in the tmp directory are being used across invocations of the AutoSklearnClassifier function. This led to the observation that if I ran this function in a for loop, performance actually improves over time, along with the statistic "Number of target algorithm runs". 

This caught me by surprise since this implies the algorithm remembers data it was fed previously. This would make CV estimate on AutoSklearnClassifier performance invalid. 

But I'm new to auto ML in general. Is this the intended behavior? 

Awesome package BTW

**Comment by mfeurer** [comment]
Hey, it took quite a while, but we finally added a new argument `max_models_on_disc` to Auto-sklearn, which governs the number of models and predictions kept on disc (https://automl.github.io/auto-sklearn/master/api.html). 

Please reopen if there are still issues with this.
