### ISSUE TITLE
Errors with parallelizing auto-sklearn tasks

### ISSUE THREAD

**Issue by chengrunyang** [automl/auto-sklearn#460]
I encounter the following error when re-fitting `autosklearn.classification.AutoSklearnClassifier` in parallel (in bash script), which does not occur when I run those tasks sequentially:

```
  File "/home/craig/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 306, in refit
    return self._automl.refit(X, y)
  File "/home/craig/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 842, in refit
    return super().refit(X, y)
  File "/home/craig/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 474, in refit
    for identifier in self.models_:
TypeError: 'NoneType' object is not iterable
```

Could you provide some insights on why this happens, and how to avoid that? Thanks!

**Comment by mfeurer** [comment]
Unfortunately it's not possible for me to say why the code fails given the traceback. Did you have a look at the logfiles, and do they contain output of the ensemble builder process? Also, is it possible that you provide me with further details and ideally a minimal working example which allows to reproduce this error?

**Comment by chengrunyang** [comment]
I assume there would be an output of the ensemble builder only if autosklearn creates some temporary files (correct me if I am wrong), thus there might not be outputs occasionally since the following error also appears sometimes in parallelization:

```
lockfile.LockFailed: failed to create /tmp/autosklearn_tmp_166456_137/.auto-sklearn/en-cs-keuka-7388a700.1673574287457515441332128
```

The working example is attached as a zip file. Run `run.sh` and the logs will be outputted into `log.txt`, a file created in the same folder. You may find in the log both the `LockFailed` error and the `TypeError` mentioned above.
[demo.zip](https://github.com/automl/auto-sklearn/files/1900734/demo.zip)

**Comment by mfeurer** [comment]
Hey, you need to increase the time you give to each single run. Currently, you give two seconds to each run, which does not allow Auto-sklearn to work. Please try at least 1 minute. We have just merged a fix into the development branch which should raise an exception in such cases.
