### ISSUE TITLE
how to set it GPU enabled?

### ISSUE THREAD

**Issue by chikiuso** [automl/auto-sklearn#461]
how to set it GPU enabled? I try the example it works as cpu.

**Comment by mfeurer** [comment]
Auto-sklearn does not support using GPUs for now, please see [the scikit-learn FAQ](http://scikit-learn.org/stable/faq.html#will-you-add-gpu-support). When we re-add XGBoost in the next release it might be possible, though. If you're interested you could already see how this works in the development branch.

**Comment by mfeurer** [comment]
We removed XGBoost support again and decided to focus the package on sklearn models to simplify installation and maintainability. Other models, such as XGBoost or LightGBM can of course be added manually. For neural networks, please check https://github.com/automl/Auto-PyTorch/
