### ISSUE TITLE
any progress in deep learning?

### ISSUE THREAD

**Issue by szldmgy** [automl/auto-sklearn#462]
In the paper "auto-sklearn", you mentioned to promote the methods applying to modern deep learning, are there any progress? Thank you.

**Comment by mfeurer** [comment]
We did some work in this direction which resulted in [this paper](http://ml.informatik.uni-freiburg.de/papers/16-AUTOML-AutoNet.pdf). However, we do not maintain an implementation of that piece of work.

**Comment by mfeurer** [comment]
A maintained implementation is now available at https://github.com/automl/Auto-PyTorch/
