### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by YaraRAA** [automl/auto-sklearn#467]
I'm able to successfully install auto-sklearn in a conda environment based on your instructions (https://automl.github.io/auto-sklearn/stable/installation.html) and auto-sklearn 0.3.0 shows up when I check conda list. However, when I try to run: 

import autosklearn.regression 

in jupyter notebook, I get the following error:

ModuleNotFoundError: No module named 'autosklearn'

Am I doing something wrong? I was able to successfully use this module on another machine so I'm a little perplexed. Thank you. Yara

**Comment by mfeurer** [comment]
Hey, could you please check the following:

* in case you have multiple kernels, you have selected the right one
* the jupyter notebook was installed in the same environment as auto-sklearn - it sometimes happens that the alternative shell (ipython/jupyter) are used from a global environment
* whether `import autosklearn.classification` works?
* if not, could you go through the contents of your PYTHONPATH inside the notebook and see whether auto-sklearn is installed there?

**Comment by mfeurer** [comment]
I just pushed a new release - please reopen if this issue is still present with the latest version.
