### ISSUE TITLE
ufunc 'isfinite' not supported for the input types

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#47]
I am running AutoSklearn on my own data loaded with http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_files.html#sklearn.datasets.load_files with the same structure as in http://scikit-learn.org/stable/datasets/twenty_newsgroups.html

`c = SGDClassifier(alpha=0.01, n_iter=10, penalty='l2', loss="log" , random_state=42, class_weight='auto')`
works fine but 
```
c = AutoSklearnClassifier( time_left_for_this_task=300, per_run_time_limit=90, ml_memory_limit=10000)
```
fails

in predict
    classifier.fit(X_train, y_train)
  File "/home/centos/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/centos/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 260, in fit
    encode_labels=False)
  File "/home/centos/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/data/xy_data_manager.py", line 27, in __init__
    self.info['has_missing'] = np.all(np.isfinite(data_x))
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by mfeurer** [comment]
Thanks for reporting this; I think this is the same problem as in #31 and #42; Due to a current refactor I might need a day in order to merge that PR.

**Comment by Motorrat** [comment]
Yes, it is also a sparse matrix format, so this is probably a duplicate.

**Comment by mfeurer** [comment]
I just merged the outstanding pull requests.

**Comment by Motorrat** [comment]
I can confirm that the above works and gets to the same results 
SGDClassifier Precision: 0.20 Test FR Recall: 0.53 F1: 0.29
Auto-sklearn Precision: 0.28 Recall: 0.31 F1: 0.29 classifier.fit(X_train, y_train, metric='f1_metric')
AutoSklearnClassifier( time_left_for_this_task=72000, per_run_time_limit=19000, ml_memory_limit=10000)

there are about 70k records in the dataset that consist of unfiltered texts - so tens of thousands of distinct words.

**Comment by danitico** [comment]
I'm having the same error. Any help?
