### ISSUE TITLE
Question about time_left_for_this_task and per_run_time_limit

### ISSUE THREAD

**Issue by coder-zjh** [automl/auto-sklearn#473]
Sorry to disturb you,maybe i'm going to ask you a silly question.For example,if i set three algorithms in 'include_estimators',then i set 'per_run_time_limit' =1200 and 'time_left_for_this_task'=3600,is that means each algorithm will be fit in 1200 seconds and the total time is 3600 seconds.

**Comment by mfeurer** [comment]
Nope, that's not correct. Auto-sklearn will run for a total of 3600 seconds and will optimize the hyperparameters in this time. The choice of the algorithm from `include_estimators` is one of those hyperparameters. For each target algorithm run it will use 1200 seconds. You can read more about this in the paper on [Auto-WEKA](https://www.cs.ubc.ca/labs/beta/Projects/autoweka/papers/autoweka.pdf).

**Comment by coder-zjh** [comment]
I see.Thank you for your time.I think i have some progress in understanding Auto-sklearn.                                           
And this is maybe the reason when i set only one algorithm in 'include_estimators' and i make  'per_run_time_limit' and 'time_left_for_this_task' have the same value,then Auto-sklearn will report me '**Time limit for a single run is higher than total time limit. Capping the limit for a single run to the total time given to SMAC**'.Maybe i should add the value of 'time_left_for_this_task'.Thank you again.
