### ISSUE TITLE
How to use best estimator in other sklearn functions

### ISSUE THREAD

**Issue by JoaoFreitax** [automl/auto-sklearn#483]
I would like some information regarding the use of AutoSklearnClassifier best estimator in other sklearn functions,  I'm trying to use the function "sklearn.model_selection.cross_val_score(estimator, X, y=None, groups=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch=‘2*n_jobs’)" but I'm not sure how to pass the obtained estimator through fit/refit function.

**Comment by mfeurer** [comment]
Hey, the `AutoSklearnClassifier` is a direct replacement for scikit-learn's cross-validation. Check out our cross-validation example: http://automl.github.io/auto-sklearn/dev/examples/example_crossvalidation.html

You won't be able to use your custom estimator, but instead Auto-sklearn will use several built-in estimators and search for the best configuration given your data.

**Comment by JoaoFreitax** [comment]
Hey, thanks for your reply, I know it is a direct replacement but I would like to run it nevertheless because I want to split my dataset to search for a model and then, I would like to do a cross-validation on all of my data and get those results, that is why AutoSklearnClassifier doesn't fit my needs...

So basically no luck for me to use the model to apply afterwards?!

**Comment by mfeurer** [comment]
> So basically no luck for me to use the model to apply cv afterwards?!

From what I understanding you want to use the scikit-learn CV functionality here as it does cross-validation on the model you pass.

> I want to split my dataset to search for a model and then, I would like to do a cross-validation on all of my data and get those results

You can run Auto-sklearn with the holdout strategy to search for a model (by invoking `fit`) and then train it on a larger dataset by calling `refit`. `refit` will take the best configurations found using `fit`, but train them on new data.

**Comment by JoaoFreitax** [comment]
> From what I understanding you want to use the scikit-learn CV functionality here as it does cross-validation on the model you pass.
Yea that is what I want, but to pass the model to it I need a model that should be saved in some variable in `AutoSlearnClassifier`. In my idea what makes sense is that this variable would be changed when we call `fit()`.
It is like you say if `refit` uses the best configurations found using `fit` then I simply want to use those configurations somewhere else. Where can I find this best configurations?

**Comment by Motorrat** [comment]
@JoaoFreitax To rephrase the question: Do you want to obtain the  ensemble of classifiers found by autosklearn that you can run in a separate pipeline?

**Comment by JoaoFreitax** [comment]
@Motorrat Yea, exactly, any clue?

**Comment by Motorrat** [comment]
I am going to point you to the example of how I am using it. If you need more specific usage I guess you should look at the ensemble class in the source code or maybe somebody else can provide more guidance. 
So check this https://github.com/paypal/autosklearn-zeroconf/blob/b6b7c2d2a3531c645c6d739558f885382273b7d9/bin/dataTransformationProcessing.py#L189 
and then see how ensemble.fit_ensemble() and ensemble.show_models() are used below in that document. 
To use the resulting ensemble https://github.com/paypal/autosklearn-zeroconf/blob/da586ab6a5c6a571ac4f8b9c433a0e7c63b57129/bin/zeroconf.py#L233

**Comment by JoaoFreitax** [comment]
thanks for your reply,
I feel I had already tried this but it returns an error, `RuntimeError: scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class autosklearn.automl.AutoMLClassifier'> with constructor (self, *args, **kwargs) doesn't  follow this convention.` this error is when I use `sklearn.model_selection.cross_val_score()`. 
Plus is there a difference between ensemble.fit_ensemble() and ensemble.fit()?

**Comment by mfeurer** [comment]
Could you please open a separate issue for the `RuntimeError` and provide code to reproduce the error.

I don't get the second part: What do you refer to as `ensemble`? Do you mean the `AutoSklearnClassifier`?
