### ISSUE TITLE
Examples for extending auto-sklearn

### ISSUE THREAD

**Issue by ianchute** [automl/auto-sklearn#486]
Hello, can you add examples for extending auto-sklearn?
A basic starter example or template will make the job much easier than painstakingly reading the docs.

**Comment by Motorrat** [comment]
Maybe this could be of help as an example https://github.com/paypal/autosklearn-zeroconf

**Comment by mfeurer** [comment]
Please the new examples in [the examples section](http://automl.github.io/auto-sklearn/master/examples/index.html) of the documentation.
