### ISSUE TITLE
Mismatch in number of features

### ISSUE THREAD

**Issue by davidwaroquiers** [automl/auto-sklearn#487]
Dear all,

I have trained an ML regression model on some training set X_train/y_train (using cross-validation), call it automl_regr. I have then done a refit on this X_train/y_train (needed because I use cross-validation and not hold-out). I have then dumped the model to a pkl file using the joblib functionality of sklearn.

I then reload this model from the pkl file, and refits the model (this is needed because I am using cv and not holdout) using a larger sample set (actually all the samples I have, say X_full and y_full). I then try to get the prediction of X_full (hasn't changed since the refit) from that refitted model and I encounter the following problem : 
"ValueError: Number of features of the model must match the input. Model n_features is 18 and input n_features is 15".

Looking further, I have found that it comes from a specific model of the ensemble : an extra trees model (see end of this message for the str representation of this model). Note that the initial number of features is 50 and I guess that the preprocessing reduces this to 18/15, but I have no clue why this happens.

Do you have any ideas or advice ? (could it be because I reload the model from file ? I haven't tried to do fit on X_train/y_train, refit on X_full/y_full and predict on X_full in the same run, though I have done fit on X_train/y_train, refit on X_train/y_train and predict on X_train, which worked perfectly. Should I try to disable preprocessing completely ?). Note also that not refitting the model after reloading it from file works. Is the fact of refitting a second time a problem ?

Thank you

All the best,

David Waroquiers

Model that causes the problem : 

SimpleRegressionPipeline({'categorical_encoding:__choice__': 'one_hot_encoding', 'imputation:strategy': 'most_frequent', 'preprocessor:__choice__': 'extra_trees_preproc_for_regression', 'regressor:__choice__': 'extra_trees', 'rescaling:__choice__': 'none', 'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True', 'preprocessor:extra_trees_preproc_for_regression:bootstrap': 'True', 'preprocessor:extra_trees_preproc_for_regression:criterion': 'mse', 'preprocessor:extra_trees_preproc_for_regression:max_depth': 'None', 'preprocessor:extra_trees_preproc_for_regression:max_features': 0.9475355777493452, 'preprocessor:extra_trees_preproc_for_regression:max_leaf_nodes': 'None', 'preprocessor:extra_trees_preproc_for_regression:min_samples_leaf': 2, 'preprocessor:extra_trees_preproc_for_regression:min_samples_split': 12, 'preprocessor:extra_trees_preproc_for_regression:min_weight_fraction_leaf': 0.0, 'preprocessor:extra_trees_preproc_for_regression:n_estimators': 100, 'regressor:extra_trees:bootstrap': 'True', 'regressor:extra_trees:criterion': 'friedman_mse', 'regressor:extra_trees:max_depth': 'None', 'regressor:extra_trees:max_features': 0.8378206177334736, 'regressor:extra_trees:max_leaf_nodes': 'None', 'regressor:extra_trees:min_impurity_decrease': 0.0, 'regressor:extra_trees:min_samples_leaf': 8, 'regressor:extra_trees:min_samples_split': 5, 'regressor:extra_trees:n_estimators': 100, 'categorical_encoding:one_hot_encoding:minimum_fraction': 0.00041433516636782},
dataset_properties={
  'task': 4,
  'sparse': False,
  'multilabel': False,
  'multiclass': False,
  'target_type': 'regression',
  'signed': False})

**Comment by mfeurer** [comment]
Thanks for reporting this issue. It should be fixed in the development branch. If possible, I suggest that you temporarily use a different branch.
