### ISSUE TITLE
Error while installing auto-sklearn - "failed building wheel for pyrfr"

### ISSUE THREAD

**Issue by sundarsri96** [automl/auto-sklearn#488]
The installation for auto-sklearn is not working because it throws the error that "failed building wheel for pyrfr". Can you help me out with this, please?

Input:
pip install auto-sklearn

Output:
Collecting auto-sklearn
Requirement already satisfied: joblib in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.11)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.0 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.4.6)
Requirement already satisfied: lockfile in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.12.2)
Requirement already satisfied: pynisher<0.5,>=0.4 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.4.2)
Collecting smac<0.9,>=0.8 (from auto-sklearn)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (39.1.0)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.11.0)
Requirement already satisfied: Cython in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.28.2)
Requirement already satisfied: nose in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.3.7)
Requirement already satisfied: scikit-learn<0.20,>=0.19 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.19.1)
Collecting pyrfr<0.8,>=0.6.1 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/c3/c6/c555cfa3c7d0078dded091d4901ed52344bbb925077aa70b871faf35fd58/pyrfr-0.7.4.tar.gz
Requirement already satisfied: pandas in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.23.0)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (5.4.5)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (3.12)
Requirement already satisfied: numpy>=1.9.0 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.14.3)
Requirement already satisfied: scipy>=0.14.1 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.1.0)
Requirement already satisfied: liac-arff in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (2.2.1)
Requirement already satisfied: typing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0->auto-sklearn) (3.6.4)
Requirement already satisfied: pyparsing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0->auto-sklearn) (2.2.0)
Requirement already satisfied: docutils>=0.3 in ./anaconda3/lib/python3.6/site-packages (from pynisher<0.5,>=0.4->auto-sklearn) (0.14)
Requirement already satisfied: sphinx in ./anaconda3/lib/python3.6/site-packages (from smac<0.9,>=0.8->auto-sklearn) (1.7.4)
Collecting sphinx-rtd-theme (from smac<0.9,>=0.8->auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/5d/01/f367780d51e9b353cec890257c84202a340f645d5a037b61a52c93669764/sphinx_rtd_theme-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas->auto-sklearn) (2.7.3)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas->auto-sklearn) (2018.4)
Requirement already satisfied: Jinja2>=2.3 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.10)
Requirement already satisfied: Pygments>=2.0 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.2.1)
Requirement already satisfied: babel!=2.0,>=1.3 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.5.3)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (0.7.10)
Requirement already satisfied: imagesize in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.18.4)
Requirement already satisfied: packaging in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (17.1)
Requirement already satisfied: sphinxcontrib-websupport in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (2018.4.16)
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /home/aifordesign/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bhn5nmx1/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-0l_njh38 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pyrfr._regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
distributed 1.21.8 requires msgpack, which is not installed.
tensorboard 1.7.0 has requirement bleach==1.5.0, but you'll have bleach 2.1.3 which is incompatible.
bleach 2.1.3 has requirement html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre, but you'll have html5lib 0.9999999 which is incompatible.
Installing collected packages: pyrfr, sphinx-rtd-theme, smac, auto-sklearn
  Running setup.py install for pyrfr ... error
    Complete output from command /home/aifordesign/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bhn5nmx1/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-dmn3u4d8/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'pyrfr._regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/home/aifordesign/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bhn5nmx1/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-dmn3u4d8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-bhn5nmx1/pyrfr/

**Comment by mfeurer** [comment]
Please install `swig` and try again.

**Comment by sundarsri96** [comment]
I tried installing auto-sklearn after installing swig but the error message is as follows:
Input:
pip install auto-sklearn

Output:
Requirement already satisfied: auto-sklearn in ./anaconda3/lib/python3.6/site-packages (0.3.0)
Requirement already satisfied: Cython in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.28.2)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.11.0)
Requirement already satisfied: joblib in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.11)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.0 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.4.6)
Requirement already satisfied: pyrfr<0.8,>=0.6.1 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.7.4)
Requirement already satisfied: pynisher<0.5,>=0.4 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.4.2)
Requirement already satisfied: nose in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.3.7)
Requirement already satisfied: scikit-learn<0.20,>=0.19 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.19.1)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (39.1.0)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (5.4.5)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (3.12)
Requirement already satisfied: numpy>=1.9.0 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.14.3)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.23.0)
Requirement already satisfied: smac<0.9,>=0.8 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.8.0)
Requirement already satisfied: lockfile in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.12.2)
Requirement already satisfied: liac-arff in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (2.2.1)
Requirement already satisfied: scipy>=0.14.1 in ./anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.1.0)
Requirement already satisfied: pyparsing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0->auto-sklearn) (2.2.0)
Requirement already satisfied: typing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0->auto-sklearn) (3.6.4)
Requirement already satisfied: docutils>=0.3 in ./anaconda3/lib/python3.6/site-packages (from pynisher<0.5,>=0.4->auto-sklearn) (0.14)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas->auto-sklearn) (2.7.3)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas->auto-sklearn) (2018.4)
Requirement already satisfied: sphinx in ./anaconda3/lib/python3.6/site-packages (from smac<0.9,>=0.8->auto-sklearn) (1.7.4)
Requirement already satisfied: sphinx-rtd-theme in ./anaconda3/lib/python3.6/site-packages (from smac<0.9,>=0.8->auto-sklearn) (0.4.0)
Requirement already satisfied: Jinja2>=2.3 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.10)
Requirement already satisfied: Pygments>=2.0 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.2.1)
Requirement already satisfied: babel!=2.0,>=1.3 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.5.3)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (0.7.10)
Requirement already satisfied: imagesize in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (2.18.4)
Requirement already satisfied: packaging in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (17.1)
Requirement already satisfied: sphinxcontrib-websupport in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->smac<0.9,>=0.8->auto-sklearn) (1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.9,>=0.8->auto-sklearn) (2018.4.16)
distributed 1.21.8 requires msgpack, which is not installed.
tensorboard 1.7.0 has requirement bleach==1.5.0, but you'll have bleach 2.1.3 which is incompatible.
bleach 2.1.3 has requirement html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre, but you'll have html5lib 0.9999999 which is incompatible.

**Comment by mfeurer** [comment]
According to the first line of your output (`Requirement already satisfied: auto-sklearn in ./anaconda3/lib/python3.6/site-packages (0.3.0)`), Auto-sklearn is successfully installed. Why it still tries to install some dependencies is something that I cannot answer.

**Comment by mfeurer** [comment]
I just pushed a new release - please reopen if this issue is still present with the latest version.
