### ISSUE TITLE
Where is the estimator, xgradient_boosting?

### ISSUE THREAD

**Issue by kaiweiang** [automl/auto-sklearn#489]
Hi, I'm trying to use the xgradient_boosting but I'm unable to.
When I run the following code, 
`[i for i in autosklearn.pipeline.components.classification._classifiers]`
I got
 `['adaboost',
 'bernoulli_nb',
 'decision_tree',
 'extra_trees',
 'gaussian_nb',
 'gradient_boosting',
 'k_nearest_neighbors',
 'lda',
 'liblinear_svc',
 'libsvm_svc',
 'multinomial_nb',
 'passive_aggressive',
 'qda',
 'random_forest',
 'sgd']`

It seems the xgradient_boosting is missing.
I've checked that my `/autosklearn/pipeline/components/classification` has the `xgradient_boosting.py`.

Would appreciate any help, thanks.

**Comment by mfeurer** [comment]
The part of the documentation which you're referring to is actually incorrect and xgboost is currently not available. It will be available in the upcoming release again (see #271).
