### ISSUE TITLE
Possibility to pause the model fitting and resume it later? 

### ISSUE THREAD

**Issue by kaiweiang** [automl/auto-sklearn#492]
Hi, this is a question rather than an issue.

In the auto-sklearn, Is it possible to pause the model fitting and get the current best ensemble of models then, as well as to resume the fitting afterwards? 

Thanks

**Comment by mfeurer** [comment]
Yes, this is definitively possible. Please have a look at the [parallel example](http://automl.github.io/auto-sklearn/dev/examples/example_parallel.html). If you start the different workers one after the other, this will result in the desired behavior. In general, the communication between the different instances of Auto-sklearn goes via the temporary directory, so if you keep that you can always resume the training process by creating a new instance of Auto-sklearn with a new seed and the flag `shared_mode=True`.
