### ISSUE TITLE
How to get the mean_test_score of the final ensemble? 

### ISSUE THREAD

**Issue by kaiweiang** [automl/auto-sklearn#493]
Hi, again this is a question rather than an issue.

I'm aware that attribute `cv_results_` lists the `mean_test_score` for every individual model. However, how can I identify which is the mean_test_score of the final ensemble? Essentially, I want to know the mean score of the validation sets of the final ensemble found by auto-sklearn.

thanks

**Comment by mfeurer** [comment]
Unfortunately, this is not easily possible. Currently, assuming that your instance of auto-sklearn is called `automl`, the following code will do:
```python
automl._automl.ensemble_.trajectory_[-1]
```
This number is maximized, and with the upcoming 0.4 version will be minimized.

**Comment by kaiweiang** [comment]
thanks for replying.

> This number is maximized, and with the upcoming 0.4 version will be minimized.

Can you further explain it?

Besides, are the attributes such as `_automl.ensemble_.trajectory_` documented? If they are, can you provide the link?

Thank you

**Comment by mfeurer** [comment]
> Can you further explain it?

In version 0.3, higher is better. This will change in 0.4, where lower will be better.

> Besides, are the attributes such as _automl.ensemble_.trajectory_ documented? If they are, can you provide the link?

Nope, this is so far private, sorry.

**Comment by kaiweiang** [comment]
Understood. Thank you.
