### ISSUE TITLE
Autosklearn can't find xgboost

### ISSUE THREAD

**Issue by adamhaber-atidot** [automl/auto-sklearn#499]
Hello,

I'm working on a binary classification problem and got decent results with xgboost so far.
I'm now trying to compare auto-sklearn's performance (xgboost included) to "vanilla" xgboost.

When I do `import xgboost` everything goes smoothly. However, when I'm trying to fit an auto-sklearn classifier with `include_estimators=['xgboost']` I get the following error:

```ValueError: Trying to include unknown component: xgboost```

How can I "help" autosklearn to find xgboost?

**Comment by mfeurer** [comment]
It's called `xgradient_boosting`. Not very intuitive, sorry.

**Comment by berndtlindner** [comment]
I think it's now `gradient_boosting`?

**Comment by mfeurer** [comment]
We replaced xgboost by scikit-learn's new [HistGradientBoosting](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html) to reduce dependence on further packages.
