### ISSUE TITLE
How save model in file?

### ISSUE THREAD

**Issue by WarmongeR1** [automl/auto-sklearn#5]
Hi all,
I took example (from docs), and i want to save classifier to file.  
But if:
```python
with open('dump_autosk.pkl', 'wb') as fio:
    pickle.dump(automl, fio)
```

I got
```
TypeError: Pickling an AuthenticationString object is disallowed for security reasons
``` 

Can i save model in file?

**Comment by mfeurer** [comment]
Hi,
at the moment it is not possible to save the found models to a file. I will leave this issue open to remind us of adding this feature.

**Comment by mglowacki100** [comment]
Hi,
Here is nice approach to saving model:
http://rhiever.github.io/tpot/examples/IRIS_Example/

**Comment by mfeurer** [comment]
This is not the same as the thread creator asked for. You can achieve something similar by using `AutoSklearnClassifier.show_models()`, which prints you the members of the final ensemble, together with their weight. So far, this is only possible because of the rather simple ensemble considered and will possibly vanish in the near future.

**Comment by mfeurer** [comment]
auto-sklearn supports pickle with commit 9415f38fcfc79a255ffb7a716d3814c6c73cfb3a

**Comment by devonbrackbill** [comment]
I'm not able to get pickle to work with commit [9415f38](https://github.com/automl/auto-sklearn/commit/9415f38fcfc79a255ffb7a716d3814c6c73cfb3a). When I install the development branch + the refactor/cleanupcomponents branch and run the [test/test_automl/test_pickle.py file](https://github.com/automl/auto-sklearn/blob/9415f38fcfc79a255ffb7a716d3814c6c73cfb3a/test/test_automl/test_pickle.py) I still get the following error: `TypeError: Pickling an AuthenticationString object is disallowed for security reasons`. Any ideas what I'm doing wrong? Or how I could help make pickle work here?

**Comment by mfeurer** [comment]
Sorry for the late reply. I think there was an error on my side. Can you please try the latest version of the development branch? That should work. Is there any reason why you want to use refactor/cleanupcomonents?

**Comment by mfeurer** [comment]
Sorry, my bad. Of course you wanted to use the branch because the commit was in there. Please only use the development branch now.

**Comment by devonbrackbill** [comment]
Thank you! It works on the development branch. My mistake for using the incorrect branch.

**Comment by mfeurer** [comment]
No mistake on your side, the changes are only there since yesterday.

**Comment by RedLiN5** [comment]
Hi guys. I've tried [9415f38](https://github.com/automl/auto-sklearn/commit/9415f38fcfc79a255ffb7a716d3814c6c73cfb3a) to save model. 
But I got this error: 
```Python
File "automl_classification.py", line 73, in main
    pickle.dump(automl, f)
_pickle.PicklingError: Can't pickle <class 'smac.runhistory.runhistory.RunKey'>: attribute lookup RunKey on smac.runhistory.runhistory failed
```
Does anyone know why it doesn't work?

**Comment by mfeurer** [comment]
See issue #138. A fix is under construction.

**Comment by namankumar** [comment]
A clean hack for saving the best model: 

```
x = automl.show_models()
results = {"ensemble": x}
pickle.dump(results, open('fname'.pickle','wb'))

```

**Comment by gstempeck** [comment]
When you save the models using show_models() like namankumar lists, how do you re-load and execute the predict() from the pickle file?

When I pickle.dump(classifierobj) I get a MemoryError but I assume that's the correct way to reload classifierobj to call predict().

**Comment by mfeurer** [comment]
Yes, that's the correct way to do this. I cannot explain when/why this happens as it never occured to me. Could you please provide some information about the data you're using (number of features and number of data points, sparse or not) and your system (especially RAM and bit)?
