### ISSUE TITLE
can it be used on Windnows

### ISSUE THREAD

**Issue by Sandy4321** [automl/auto-sklearn#504]
if not , when?

**Comment by mfeurer** [comment]
From [the documentation](http://automl.github.io/auto-sklearn/stable/installation.html#windows):

> auto-sklearn relies heavily on the Python module resource. resource is part of Python’s Unix Specific Services and not available on a Windows machine. Therefore, it is not possible to run auto-sklearn on a Windows machine.

Please consult the page linked above for possible alternatives. If you know any alternatives to the resource module or want to contribute any other possibility for the execution of Auto-sklearn on a Windows machine, please let us know.

**Comment by SultanMu** [comment]
Running a Docker container on windows solves this. Python 3.6 seems to work perfectly.

**Comment by byrro** [comment]
Docker is a great option, as suggested. As an alternative to containerization, you could use www.vagrantup.com and run Linux virtualized within windows.

**Comment by mfeurer** [comment]
Yes, there's a docker image for Auto-sklearn: https://hub.docker.com/r/mfeurer/auto-sklearn/
