### ISSUE TITLE
cross-validated performance of the final ensemble

### ISSUE THREAD

**Issue by MassimilianoGrassiDataScience** [automl/auto-sklearn#511]
If cross-validation is used, I would like to know how to get the cross-validated performance estimate of the final ensemble (aka the one that will be used to predict new cases).

I need it because I'm comparing both the final model provided by auto-sklearn and several other models I "manually" created, in order to choose the one that shows the best cv performance and apply only this to a independent test set.

Thank you

**Comment by kaiweiang** [comment]
You can refer to #493

**Comment by MassimilianoGrassiDataScience** [comment]
Thanks
