### ISSUE TITLE
meta learning work or not

### ISSUE THREAD

**Issue by xujinfan** [automl/auto-sklearn#516]
I have run some data, when I set " initial_configurations_via_metalearning=0", I find the accuracy may be better than "initial_configurations_via_metalearning=25".

**Comment by mfeurer** [comment]
This can definitively happen. We've shown in [our original publication](https://ml.informatik.uni-freiburg.de/papers/15-AAAI-MI-SMBO.pdf) that meta-learning improves in most cases, but can also degrade performance.
