### ISSUE TITLE
Remove Cython and numpy build dependencies

### ISSUE THREAD

**Issue by adithyabsk** [automl/auto-sklearn#519]
In order to allow autosklearn to be built without any unnecessary build dependencies and reduce constraints on users, it would make sense to remove these pre-build dependencies. Pull requests #518 and automl/ConfigSpace#82 attempted to resolve this problem. The following links were the sources of the proposed solution.
https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py
numpy/numpy#2434
numpy/numpy#432

Upon further testing, I found that although the install worked locally when I would install the package with the implemented changes using "pip install git+[repo]" the installation would fail. I closed the PR because of both this issue and the discovery that using "install_requires" in setup script was discouraged as it uses easy_install instead of pip which don't play nicely together. using pyproject.toml seems to be the correct solution to the chicken and egg problem of build tooling as evidenced though discussions linked below:
https://github.com/pypa/pip/issues/3691
https://github.com/pandas-dev/pandas/pull/16745/files

I would strongly suggest migrating to this standard.

**Comment by mfeurer** [comment]
I believe this was fixed in commit https://github.com/automl/auto-sklearn/commit/185170ec570c29670f9384c0c0118ab152e6e232#diff-2eeaed663bd0d25b7e608891384b7298 via #611. Please reopen if this issue still exists.
