### ISSUE TITLE
ValueError: No models fitted! after hour

### ISSUE THREAD

**Issue by zyxue** [automl/auto-sklearn#520]
I am familiar with sklearn, but this is my first time to try auto-sklearn, any possible reason?

```
[ERROR] [2018-07-25 20:29:10,053:AutoML(1):2a013f70bf5777bde222af3f397d816c] Error creating dummy predictions: {'error': 'Memout (used more than 3072 MB).', 'configuration_origin':
[WARNING] [2018-07-25 20:29:19,613:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2018-07-25 20:29:19,613:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
Traceback (most recent call last):
  File "benchmark_scripts/train_automl.py", line 254, in <module>
    main()
  File "benchmark_scripts/train_automl.py", line 226, in main
    clf_list = [train_it_wrapper(train_args[0])]
  File "benchmark_scripts/train_automl.py", line 58, in train_it_wrapper
    return train_it(*args)
  File "benchmark_scripts/train_automl.py", line 53, in train_it
    clf.fit(Xs, ys)
  File "/path/to/venv/lib/python3.6/site-packages/autosklearn/estimators.py", line 466, in fit
    dataset_name=dataset_name,
  File "/path/to/venv/lib/python3.6/site-packages/autosklearn/estimators.py", line 248, in fit
    self._automl.fit(*args, **kwargs)
  File "/path/to/venv/lib/python3.6/site-packages/autosklearn/automl.py", line 954, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "/path/to/venv/lib/python3.6/site-packages/autosklearn/automl.py", line 199, in fit
    only_return_configuration_space,
  File "/path/to/venv/lib/python3.6/site-packages/autosklearn/automl.py", line 477, in _fit
    self._load_models()
  File "/path/to/venv/lib/python3.6/site-packages/autosklearn/automl.py", line 667, in _load_models
    raise ValueError('No models fitted!')
ValueError: No models fitted!

real    60m15.630s
user    26m45.757s
sys     4m44.382s
```

More information if helpful

```
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core
```
```
pip freeze | grep auto
auto-sklearn==0.4.0
```

**Comment by mfeurer** [comment]
Thanks a lot for trying Auto-sklearn!

It appears that your dataset is rather large and Auto-sklearn fails to work with it (see the first line of the output: `[ERROR] [2018-07-25 20:29:10,053:AutoML(1):2a013f70bf5777bde222af3f397d816c] Error creating dummy predictions: {'error': 'Memout (used more than 3072 MB).', 'configuration_origin':`). If you can afford it, please increase the memory limit by setting `ml_memory_limit` to a value larger than 3072. I hope this helps.

**Comment by zyxue** [comment]
The dataset isn't huge
```
In [5]: df.shape
Out[5]: (931053, 66)
```
Do you have a suggestion on how to configure `autosklearn.classification.AutoSklearnClassifier` besides `ml_memory_limit`, please?

Yes, I have access to a big machine with 128 vCPUs, and ~2TB memory. I would prefer to have auto-sklearn to push the performance. I tried GradientBoostingClassifier myself and could use it as a baseline.

**Comment by zyxue** [comment]
I see other warnings after enlarging `ml_memory_limit` by 10x, do they matter?
```
/path/to/venv/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
[WARNING] [2018-07-27 06:15:56,124:EnsembleBuilder(1):2a013f70bf5777bde222af3f397d816c] No models better than random - using Dummy Classifier!
[WARNING] [2018-07-27 06:15:56,203:EnsembleBuilder(1):2a013f70bf5777bde222af3f397d816c] No models better than random - using Dummy Classifier!
[WARNING] [2018-07-27 06:15:58,208:EnsembleBuilder(1):2a013f70bf5777bde222af3f397d816c] No models better than random - using Dummy Classifier!
[WARNING] [2018-07-27 06:16:00,216:EnsembleBuilder(1):2a013f70bf5777bde222af3f397d816c] No models better than random - using Dummy Classifier!
[WARNING] [2018-07-27 06:16:02,224:EnsembleBuilder(1):2a013f70bf5777bde222af3f397d816c] No models better than random - using Dummy Classifier!
..... (many more the same messages)
```

**Comment by mfeurer** [comment]
First of all, the message you see is not an issue as long as it disappears before the end. Basically, the ensemble script searches for models to combine, but finds no model which performs better than predicting the majority class.

You're data isn't huge to modern standards, but for some algorithms in Auto-sklearn (scikit-learn) it is. Simply fitting a random forest (the default configuration in Auto-sklearn) to ~600k data points (the number of data used to fit the model) takes quite some time, and together with the preprocessing in Auto-sklearn also quite some memory. If you pass the categorical features indicator memory usage increases a lot.

My suggestions are: 

* Use Auto-sklearn in parallel: http://automl.github.io/auto-sklearn/stable/examples/example_parallel.html#sphx-glr-examples-example-parallel-py
* Increase the memory limit to 8-14 GB on your machine (assuming that you have ~16GB per process)
* Increase the total runtime to several hours (`per_run_time_limit`)
* Increase the runtime for a single machine learning model to something between 30 and 60 minutes (assuming that some models finish within that time).

I hope this helps. Please don't hesitate to ask again if this doesn't help.

**Comment by zyxue** [comment]
Thank you for your detailed instruction. Yeah, I've run it, and it finishes successfully, but auto-sklearn doesn't beat my GradientBoostingClassifier (GBC) baseline. Is it supposed to be the other way, is auto-sklearn expected to outperform GBC? For GBC, I set everything to default but the max_depth to 2

**Comment by mfeurer** [comment]
It depends, it should be able to at least match your baseline. You can check the logfiles for how much it searched (if you store them) and whether it sufficiently tested GBC or XGBoost.

**Comment by zyxue** [comment]
Thank you, let me check the log files.

**Comment by mfeurer** [comment]
Ah, one more thing. If you find that only gradient boosting gives decent performance, you could also tune only gradient boosting. See [this example](http://automl.github.io/auto-sklearn/stable/manual.html#restricting-the-searchspace).

**Comment by mfeurer** [comment]
Closing as this issue has gone stale - please reopen if this issue still exists.

**Comment by SibianDG** [comment]
The link: [http://automl.github.io/auto-sklearn/stable/examples/example_parallel.html#sphx-glr-examples-example-parallel-py](http://automl.github.io/auto-sklearn/stable/examples/example_parallel.html#sphx-glr-examples-example-parallel-py) doesn't exist anymore...

**Comment by eddiebergman** [comment]
Updated link:

https://automl.github.io/auto-sklearn/master/examples/60_search/example_parallel_n_jobs.html#sphx-glr-examples-60-search-example-parallel-n-jobs-py
