### ISSUE TITLE
Set ensemble size to 1 vs looking at best model in cv_results

### ISSUE THREAD

**Issue by teresaconc** [automl/auto-sklearn#529]
I'm currently trying to get an ordered list of best models from the optimization (without getting an ensemble model). I am aware that the "best" model is kind of a general idea, but overall I am looking for the model who can better generalize a certain prediction.

Relatively only to the single best model: what are the differences in practice of running fit/fit_ensemble with ensemble_size = 1 or simply looking at the best performed model from the cv_results? Will they frequently output the same model?

**Comment by mfeurer** [comment]
> what are the differences in practice of running fit/fit_ensemble with ensemble_size = 1 or simply looking at the best performed model from the cv_results

The first actually runs a process in parallel, building an actual ensemble which can then be used together with the predict function. The second one is simply a convenience function to make Auto-sklearn look more like scikit-learn. 

> Will they frequently output the same model?

They should, if not, please note here as that would be a bug.

**Comment by teresaconc** [comment]
Yes! They output the same, I was comparing the wrong models hence getting different results.
Thanks
