### ISSUE TITLE
xgboost version

### ISSUE THREAD

**Issue by dimidd** [automl/auto-sklearn#531]
Hi,

When installing using pip, it get's stuck installing xgboost==0.7post3, which fails on MacOs. I did manage to install xgboost==0.7post4, which is functionally identical. Could we use it to satisfy the xgboost requirement?

Details: https://github.com/dmlc/xgboost/issues/3118

**Comment by tmielika** [comment]
xgboost 0.80 works fine too?

**Comment by dimidd** [comment]
Well, I'm able to install it, but I think auto-sklearn requires xgboost < 0.8 for some reason.

**Comment by tmielika** [comment]
https://github.com/automl/auto-sklearn/pull/533

**Comment by mfeurer** [comment]
It should be possible to use other versions of XGBoost if the interface doesn't change. However, keep in mind that they're not tested. @tmielika I'll have a look at your PR soonish, unfortunately, I'm currently swamped until the end of next week.

**Comment by mfeurer** [comment]
I just merged #533, this issue will be gone in the upcoming 0.4.2 release.
