### ISSUE TITLE
auto-sklearn installation

### ISSUE THREAD

**Issue by tmielika** [automl/auto-sklearn#532]
It would be great if step ```curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install``` would not be needed but ```pip install auto-sklearn``` would suffice.

It seems that in current setup Cython and numpy are needed for cythonizing but others can be installed as a part of pip install.

**Comment by mfeurer** [comment]
Agreed, but I'm closing this for now as it is a duplicate of #519.

**Comment by mfeurer** [comment]
Documented in #1237
