### ISSUE TITLE
How to specify no explicit memory constraint?

### ISSUE THREAD

**Issue by PGijsbers** [automl/auto-sklearn#534]
It is possible to not restrict the memory usage of auto-sklearn, i.e. let it use any and all memory the machine has? From reading the documentation, it seems that you always need to specify an explicit limit.

**Comment by mfeurer** [comment]
I'm afraid that this isn't possible. Is there something which prevents you from setting it to a very high value (such as 64GB)?

**Comment by mfeurer** [comment]
You can expect the same behavior as without a memory limit as long as you do not hit it. Both will make use of swap memory if a machine learning model allocates more memory than available. Preventing swapping on a single user machine or preventing interfering with others on a multi user machine are the most important reasons for the memory limit (a third reason might me memory limits by a computer cluster).

**Comment by PGijsbers** [comment]
Clear. Thanks very much!
