### ISSUE TITLE
Log Auto-sklearn configuration

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#536]
to allow for easier debugging with logfiles.

**Comment by Mattemyo** [comment]
I would be willing to help out! It would be great if there some more specifications for this issue.

**Comment by mfeurer** [comment]
Thanks for the offer. The idea is basically to log all settings at the beginning of a run so that one can inspect the options later. I think the [`fit` method](https://github.com/automl/auto-sklearn/blob/master/autosklearn/automl.py#L143) would be a good point to add this.

If you are going to work on this, please make the pull request to the development branch.

**Comment by Motorrat** [comment]
We have this logger logic set up for the extention of auto-sklearn https://github.com/paypal/autosklearn-zeroconf/blob/master/bin/zeroconf.py#L99 Maybe it can be pushed over to Auto-sklearn or at least serve as inspiration?

**Comment by Mattemyo** [comment]
@Motorrat Interesting. I see that your code is copyrighted. How does that apply to open source project? What are they allowed to copy or use from code that is protected from copyright?

**Comment by Motorrat** [comment]
This code is also copyrighted. Have you seen this license? https://github.com/automl/auto-sklearn/blob/master/LICENSE.txt 
 Both projects are using the same bsd  license.

**Comment by mfeurer** [comment]
Added in #931.
