### ISSUE TITLE
Only two possible outcomes predicted

### ISSUE THREAD

**Issue by binarybehemoth** [automl/auto-sklearn#539]
With the regressor, I trained a set of data which mapped to floats normalized to the range 0 to 1. However, after the training, when I called predict(), all the values had only two possible outcomes. What could be the problem possibly?

**Comment by mfeurer** [comment]
Could you please provide a minimal example so that we can reproduce the behavior on our side? I have never seen this behavior before I do not know where it comes from.

**Comment by mfeurer** [comment]
Closing this issue as it stalled. Please reopen with a minimal example if this is still of interest to you.
