### ISSUE TITLE
Testing performance is not tracked with X_test, y_test

### ISSUE THREAD

**Issue by henrylinarundo** [automl/auto-sklearn#543]
automl.cv_results_['mean_test_score'] still records the hold-out / CV performance within X_train, y_train, even after X_test, y_test were passed in automl.fit(). I used AutoSklearnRegressor, but I believe AutoSklearnClassifier behaves the same. If the testing performance is tracked by a different property, please indicate them in the doc, thanks.

**Comment by mfeurer** [comment]
Thanks for pointing this out. Testing performance is indeed tracked differently (not documented yet). However, the current implementation is in line with scikit-learn, which also stores the validation performance by the key `mean_test_score` (see [here](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV)).

You can use the following piece of code as a starting point:
```
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

import autosklearn.classification


def main():
    X, y = sklearn.datasets.load_breast_cancer(return_X_y=True)
    X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)

    automl = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=15,
        per_run_time_limit=10,
        tmp_folder='/tmp/autosklearn_holdout_example_tmp',
        output_folder='/tmp/autosklearn_holdout_example_out',
        disable_evaluator_output=False,
        # 'holdout' with 'train_size'=0.67 is the default argument setting
        # for AutoSklearnClassifier. It is explicitly specified in this example
        # for demonstrational purpose.
        resampling_strategy='holdout',
        resampling_strategy_arguments={'train_size': 0.67},
        delete_tmp_folder_after_terminate=False,
        delete_output_folder_after_terminate=False,
    )
    automl.fit(X_train, y_train, dataset_name='digits',
               X_test=X_test, y_test=y_test)
    for key, value in automl._automl.runhistory_.data.items():
        print(value.additional_info.get('test_loss', 1.0))


if __name__ == '__main__':
    main()
```
The `runhistory_` is an instance of https://automl.github.io/SMAC3/stable/apidoc/smac.runhistory.runhistory.html#smac.runhistory.runhistory.RunHistory

**Comment by jorgehpo** [comment]
Hi, is there any update on this?

I would like to compute the scores on the  test data for all the models listed in cv_results_.
However, since I can only access the models used in the ensemble (get_models_with_weights), this is not possible.

Thank you.

**Comment by mfeurer** [comment]
Hey, we do finally have a good interface and an example for doing this without any extra scripts: https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_pandas_train_test.html#sphx-glr-examples-40-advanced-example-pandas-train-test-py

Please reopen if this doesn't solve the issue or you have further questions/requests.
