### ISSUE TITLE
strange behavior of Score

### ISSUE THREAD

**Issue by ByMyTry** [automl/auto-sklearn#545]
If I fit a AutoSklearnClassifier with :
   resampling_strategy='cv',
   resampling_strategy_arguments={'folds': 10},
I get best_score from sprint statistic equal ~0.90.

But if i use cross_val_score from sklearn I get 0.34.

code:
In [91]: autoClf = asc.classification.AutoSklearnClassifier(         
...:................tmp_folder='/tmp/autosklearn_cv_example_tmp', 
...:................output_folder='/tmp/autosklearn_cv_example_out',
...:................delete_tmp_folder_after_terminate=False,               
...:................resampling_strategy='cv',                
...:................resampling_strategy_arguments={'folds': 10},
...:............)

In [92]: class TestClf(BaseEstimator, ClassifierMixin):            
...:................def __init__(self):                              
...:........................self.autoClf = autoClf                              
...:................def fit(self, X, y):                        
...:........................self.autoClf.refit(X, y)   
...:........................return self                                 
...:................def predict(self, X):
...:........................return self.autoClf.predict(X)
...:................def score(self, X, y):
...:........................return cross_val_score(self, X, y, scoring='f1_macro', cv=10).mean()

In [93]: testClf = TestClf()
In [94]: testClf.score(X, y)
Out[94]: 0.3430201126824274

Can you give some explanation please, why it's so different.
p.s. [(code](url
[issue.txt](https://github.com/automl/auto-sklearn/files/2401927/issue.txt)
) in atach)

**Comment by mfeurer** [comment]
Hi @ByMyTry, I cannot reproduce your issue. However, I assume the `cross_val_score` does not work together with a fitted classifier. Could you please:
1. provide reasoning for your code? Why do you want to use `cross_val_score` after fitting Auto-sklearn with cross-validation?
2. provide a fully runable script to allow us debugging this?

**Comment by ByMyTry** [comment]
I want to check fitted automl classifier quality with sklearn tools (like cross_val_score)
I already found the cause of the problem. It was my fault (just need to set the object of StratifiedKFold class to cv parameter).

And one more question. What do you think about rename couple methods:
fit -> find_best_model (something like that),
refit -> fit.
It give users opportunity to use autosklearn classes like extended sklearn classifier.
Like in my case (with sklearn cross_val_score).
Is is just little offer. I'm interested in your opinion about this.

**Comment by mfeurer** [comment]
Hey,

> I want to check fitted automl classifier quality with sklearn tools (like cross_val_score)

So you basically want to check how robust the found classifier is to different test datasets?

> What do you think about renaming a pair of methods:

The methods are in line with scikit-learn's own hyperparameter tuning tools. `fit()` performs hyperparameter optimization and returns a usable model. The only differences to scikit-learn is that the `refit` argument is missing which cannot easily be implemented under time constraints.
