### ISSUE TITLE
Can I restrict the searching space of Auto-Sklearn? For example, I just want to search for the n_estimators and max_depth parameters in Random Forest. Searching for every parameter seems too slow to me.

### ISSUE THREAD

**Issue by xiangning-chen** [automl/auto-sklearn#546]

**Comment by mfeurer** [comment]
No, this is not easily possible. You'd have to go into the code and do the changes manually.

**Comment by mfeurer** [comment]
We do now have an example of how to replace an existing component by a similar component, but with different hyperparameters: https://automl.github.io/auto-sklearn/master/examples/80_extending/example_restrict_number_of_hyperparameters.html#sphx-glr-examples-80-extending-example-restrict-number-of-hyperparameters-py

I hope this helps. Please reopen if you have further questions in this direction.
