### ISSUE TITLE
About Extending 

### ISSUE THREAD

**Issue by cxnthu** [automl/auto-sklearn#548]
I follow the extending part of the doc and implement a child of 'AutoSklearnClassificationAlgorithm' and then call 'add_classifier'. However, the autosklearn does not search my algorithm. Can you provide a simple example? Thanks, hope to see the reply soon.

**Comment by mfeurer** [comment]
@ahn1340 is working on an example in #510. If that doesn't work for you, please post a minimal example so that we can reproduce your issue.

**Comment by mfeurer** [comment]
@cxnthu you can now find multiple examples [in the examples section](http://automl.github.io/auto-sklearn/master/examples/index.html).
