### ISSUE TITLE
I can't find pyMetaLearn and LearnedDistanceRF

### ISSUE THREAD

**Issue by Ismailhachimi** [automl/auto-sklearn#551]
Hi, i'm trying to understand the code, and while checking the autosklearn.metalearning.metalearning.KNearestDatasets modules, there's a pyMetaLearn module and a LearnedDistanceRF class that are imported inside them. I cloned the git but i can't figure out how the dependencies work.

Can anyone explain this to me ? 
Thanks in advance

**Comment by mfeurer** [comment]
Hey, these modules and imports should no longer be there and definitively need to be removed. Please ignore them for now.

**Comment by Ismailhachimi** [comment]
Alright Thank you.
