### ISSUE TITLE
Objects features

### ISSUE THREAD

**Issue by ByMyTry** [automl/auto-sklearn#552]
Hi.
I have objects features in my data and when i try to fit autosklearn model i get error because of model trying convert objects to float. What can i do in this case?
I am thincking of make my own autosklearn-preprocessor which will delete objects features from data.
How do you think, will it work?

**Comment by mfeurer** [comment]
Auto-sklearn will accept the same type of data as scikit-learn's random search. Therefore, we don't support any special objects and you need to perform the preprocessing outside of Auto-sklearn.

**Comment by mfeurer** [comment]
Please reopen if that's not correct.
