### ISSUE TITLE
Extracting accuracy and other metrics for all the models tried

### ISSUE THREAD

**Issue by knithinreddy3** [automl/auto-sklearn#556]
Is there a way I can extract the metrics for different models being tested while the fit() function is running?

**Comment by mfeurer** [comment]
We currently do not offer a programmatic way to do so unless you set Auto-sklearn to work in parallel mode. Then, you can extract the information from a file called runhistory.json in the temporary Auto-sklearn directory.

**Comment by franchuterivera** [comment]
Hello!, I think this is something specified in this [example](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_pandas_train_test.html#sphx-glr-examples-40-advanced-example-pandas-train-test-py).

If this is not the case, kindly re-open this issue.
