### ISSUE TITLE
Parallelization with Cross Validation

### ISSUE THREAD

**Issue by aleniandrea** [automl/auto-sklearn#557]
I am trying to run the code using a custom BaseCrossValidator object passed to resampling_strategy into the costructor of AutoSklearnClassifier. If i run the code following this [example](https://automl.github.io/auto-sklearn/stable/examples/example_crossvalidation.html#sphx-glr-examples-example-crossvalidation-py) the classifier works perfectly, below the code used:

```
start_time = time.time()
tmp_folder,output_folder = create_folder()
X_train, X_test, y_train, y_test,indices_train,indices_test = sklearn.model_selection.train_test_split(X_flank, y_flank,indices_flank,random_state=42)
kf = KFold(n_splits=4,random_state=42,shuffle=True)
gkf = GroupCV
gkf.__name__ = 'KFold'
args = {'cv_function':kf,'groups':group_flank[indices_train],'random_state':42}

automl = autosklearn.classification.AutoSklearnClassifier(
    tmp_folder=tmp_folder,
    output_folder=output_folder,
    delete_tmp_folder_after_terminate=False,
    resampling_strategy=gkf,
    resampling_strategy_arguments=args
)
automl.fit(X_train.copy(), y_train.copy(), dataset_name='age')
automl.refit(X_train.copy(), y_train.copy())
#print(automl.show_models())

predictions = automl.predict(X_test)
elapsed_time = time.time() - start_time
print("Time taken: {}".format(elapsed_time))
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, predictions))
```

the GroupCV is a custom crossvalidator.
If i am trying to run the code in parallel using this other [example](https://automl.github.io/auto-sklearn/stable/examples/example_parallel.html#sphx-glr-examples-example-parallel-py)  the code crashes, i thought that was a problem of my BaseCrossValidator so i have tried also passing 'cv' as option but still it's not working.

This is the error: AttributeError: 'Imputation' object has no attribute 'preprocessor'

**Comment by mfeurer** [comment]
Unfortunately, it's not possible to debug the code without your GroupCV class. Can you reproduce the code with some other splitter from scikit-learn? If not, can you provide a self-contained example which reproduces the error?
