### ISSUE TITLE
Add  new metadata to the existing data repository

### ISSUE THREAD

**Issue by PRBorole** [automl/auto-sklearn#561]
Hi,

I would like to add more outside data sets in the metadata repository. I found all the scripts that I need to run to generate the metafeatures in scripts folder. Which files do I need to create and where should I put them after running 04_create_aslib_files.py? Also, how do I make sure that these added datasets are utilized when I run autosklearn next time?

Thank you in advance!
Piyush

**Comment by mfeurer** [comment]
You need to replace the files under [`autosklearn.metalearning.files`](https://github.com/automl/auto-sklearn/tree/master/autosklearn/metalearning/files). You can check the logfile of Auto-sklearn the next time you run it to see whether they're used.

**Comment by mfeurer** [comment]
Closing this as the question was answered and there appears to be no further question.
