### ISSUE TITLE
How to read the model running memory

### ISSUE THREAD

**Issue by liujing0055** [automl/auto-sklearn#564]
I know that I can limited the memory according to ml_memory_limit before the model fit,I want to know the memory that the model is running on.Is there a way to get it? 
                                                                                                                                  Thank you very much

**Comment by mfeurer** [comment]
Yes, the support vector machine is actually using this to set the kernel cache size: https://github.com/automl/auto-sklearn/blob/master/autosklearn/pipeline/components/classification/libsvm_svc.py
