### ISSUE TITLE
Something strange about the code in method load_ensemble

### ISSUE THREAD

**Issue by xiaodineu** [automl/auto-sklearn#566]
I have checked the code and find something strange in file backend, method load_ensemble.
line 387, sort result seems like this in the picture
![1](https://user-images.githubusercontent.com/42017222/46990935-1ecd2480-d136-11e8-8582-a8184a446949.PNG)
pick the last one seems not correct, Could you have a look at this?

**Comment by mfeurer** [comment]
Indeed, there's an error in the sorting. I just pushed a fix in PR #567. Please let me know if that fixes the issue for you.

**Comment by xiaodineu** [comment]
It works centainly.
But, is there any problems to fix this by sorting the ensembles by createtime like this?
in file backend, method load_ensemble, line387
indices_files.sort(key=lambda f: time.ctime(os.path.getmtime(f)))

**Comment by mfeurer** [comment]
They're both fine, this is just personal preference. I'll merge now.
