### ISSUE TITLE
Difficulties to set feat_type

### ISSUE THREAD

**Issue by xiaodineu** [automl/auto-sklearn#570]
Hi!
Automl.fit () has a parameter feat_type. Does this parameter only affect the process of onehot_encoder? Will other parts use this parameter?

Now I encounter a problem that  the CSV data we use does not provide feature types. So it's difficult to set feat_type. For example, column with values of 1, 2, 3, 4, I don't know whether this column is numeric or categorical. So there needs to be a process of discrimination. eg. if the count of non-repetitive values of this column is below a certain threshold (T), we treat this the column as categorical column.

But we found that onehot_encoder's hyper-parameter minimum_fraction might help us. Assuming that feat_type is used only in onehot_encoder, we define  all columns as categorical columns in automl. fit (), and then handed over to onehot_encoder, which automatically determines which columns are genuine category types and do onehot_encoder. That is to say, using this hyper-parameter minimum_fraction to determine the threshold T mentioned above. Of course, columns with too many values (such as more than 1000) should be specified as numeric because of computational resource constraints.

Can we do so? Will this bring any other problems?
Thanks !

**Comment by xiaodineu** [comment]
I have looked at the source code in detail and found that the parameter minimum_fraction was different from what I had previously imagined, so can we modify the source code and add a parameter to control which columns need to be encoded? If the number of non duplicate values of the column is less than a threshold, we will perform onehot on it. This parameter(f) may be a fraction, row number of data (N) , threshold is compute by f*N.
Can you give me some advice? thanks!

**Comment by mfeurer** [comment]
> Does this parameter only affect the process of onehot_encoder?

Yes.

> Will other parts use this parameter?

No.

> Now I encounter a problem that the CSV data we use does not provide feature types.

While this is part of the AutoML problem, Auto-sklearn does not provide any solution here. You could check (very) recent literature such as [this](https://link.springer.com/chapter/10.1007/978-3-030-01768-2_30).

> That is to say, using this hyper-parameter minimum_fraction to determine the threshold T mentioned above.

That could work, but it only works as long as your data is of type integer, positive and as long as each feature has roughly the same properties.

> so can we modify the source code and add a parameter to control which columns need to be encoded?

This should definitively be possible. Basically, you want to infer the categorical columns in the one hot encoder based on a hyperparameter. If you add the hyperparameter to the configuration space of the one hot encoder it will automatically be searched over. You can then simply add your code in the beginning of the fit method and ignore the `feat_type` array which is passed by the user.

**Comment by xiaodineu** [comment]
Thanks, I will have a try.
