### ISSUE TITLE
Error while installing auto-sklearn - "failed building wheel for pyrfr"

### ISSUE THREAD

**Issue by laffinm** [automl/auto-sklearn#573]
The installation for auto-sklearn is not working because it throws the error that "failed building wheel for pyrfr". Does anyone have any suggestions please? The error at the end says `error: command 'gcc' failed with exit status 1.` I installed gcc but the error persists.

Input:
curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install

Output:
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   209  100   209    0     0   1251      0 --:--:-- --:--:-- --:--:--  1251
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (40.5.0)
Requirement already satisfied: nose in ./anaconda3/lib/python3.6/site-packages (1.3.7)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (1.11.0)
Requirement already satisfied: Cython in ./anaconda3/lib/python3.6/site-packages (0.28.2)
Requirement already satisfied: numpy>=1.9.0 in ./anaconda3/lib/python3.6/site-packages (1.14.3)
Requirement already satisfied: scipy>=0.14.1 in ./anaconda3/lib/python3.6/site-packages (1.0.1)
Requirement already satisfied: scikit-learn<0.20,>=0.19 in ./anaconda3/lib/python3.6/site-packages (0.19.1)
Collecting xgboost==0.7.post3
  Using cached https://files.pythonhosted.org/packages/cb/1c/a2ec1798d444e2b86b27fdbf18d9ab08c25c3d374de77429b55a76f42404/xgboost-0.7.post3.tar.gz
    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost
    + cd ./xgboost/
    + [[ darwin18 == \d\a\r\w\i\n* ]]
    + LIB_XGBOOST=libxgboost.dylib
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Applications/Xcode.app/Contents/Developer/usr/bin/make] - checked OK
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    c++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
    In file included from /Users/matthewlaffin/anaconda3/gcc/include/c++/bits/postypes.h:40:0,
                     from /Users/matthewlaffin/anaconda3/gcc/include/c++/bits/char_traits.h:40,
                     from /Users/matthewlaffin/anaconda3/gcc/include/c++/string:40,
                     from /Users/matthewlaffin/anaconda3/gcc/include/c++/stdexcept:39,
                     from /Users/matthewlaffin/anaconda3/gcc/include/c++/array:38,
                     from /Users/matthewlaffin/anaconda3/gcc/include/c++/tuple:39,
                     from /Users/matthewlaffin/anaconda3/gcc/include/c++/mutex:38,
                     from /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include/dmlc/thread_local.h:9,
                     from src/c_api/c_api_error.cc:6:
    /Users/matthewlaffin/anaconda3/gcc/include/c++/cwchar:44:19: fatal error: wchar.h: No such file or directory
     #include <wchar.h>
                       ^
    compilation terminated.
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    c++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/logging.cc -o build/logging.o
    c++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/c_api/c_api.cc -o build/c_api/c_api.o
    c++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/learner.cc -o build/learner.o
    In file included from /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include/dmlc/logging.h:10:0,
                     from include/xgboost/logging.h:11,
                     from src/logging.cc:7:
    /Users/matthewlaffin/anaconda3/gcc/include/c++/cstdio:42:19: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
                       ^
    compilation terminated.
    make: *** [build/logging.o] Error 1
    In file included from include/xgboost/data.h:10:0,
                     from src/c_api/c_api.cc:3:
    /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include/dmlc/base.h:187:23: fatal error: sys/types.h: No such file or directory
     #include <sys/types.h>
                           ^
    compilation terminated.
    make: *** [build/c_api/c_api.o] Error 1
    In file included from /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/include/dmlc/io.h:8:0,
                     from src/learner.cc:7:
    /Users/matthewlaffin/anaconda3/gcc/include/c++/cstdio:42:19: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
                       ^
    compilation terminated.
    make: *** [build/learner.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Applications/Xcode.app/Contents/Developer/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost
    /bin/sh: line 0: cd: R-package/src: No such file or directory
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Applications/Xcode.app/Contents/Developer/usr/bin/make] - checked OK
    Makefile:43: /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target `/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/matthewlaffin/anaconda3/xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-dtrbc6ux/xgboost/
Requirement already satisfied: lockfile in ./anaconda3/lib/python3.6/site-packages (0.12.2)
Requirement already satisfied: joblib in ./anaconda3/lib/python3.6/site-packages (0.11)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.6/site-packages (5.4.3)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.6/site-packages (3.12)
Requirement already satisfied: liac-arff in ./anaconda3/lib/python3.6/site-packages (2.3.1)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.6/site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas) (2.7.0)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas) (2018.4)
Requirement already satisfied: numpy>=1.9.0 in ./anaconda3/lib/python3.6/site-packages (from pandas) (1.14.3)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.0 in ./anaconda3/lib/python3.6/site-packages (0.4.7)
Requirement already satisfied: Cython in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0) (0.28.2)
Requirement already satisfied: typing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0) (3.6.4)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0) (1.14.3)
Requirement already satisfied: pyparsing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.0) (2.2.0)
Requirement already satisfied: pynisher>=0.4 in ./anaconda3/lib/python3.6/site-packages (0.5.0)
Requirement already satisfied: docutils>=0.3 in ./anaconda3/lib/python3.6/site-packages (from pynisher>=0.4) (0.14)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.6/site-packages (from pynisher>=0.4) (5.4.3)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from pynisher>=0.4) (40.5.0)
Collecting pyrfr<0.8,>=0.7
  Using cached https://files.pythonhosted.org/packages/c3/c6/c555cfa3c7d0078dded091d4901ed52344bbb925077aa70b871faf35fd58/pyrfr-0.7.4.tar.gz
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /Users/matthewlaffin/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-m428phi8/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-wheel-rd67pn39 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pyrfr._regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build
  creating build/temp.macosx-10.6-x86_64-3.6
  creating build/temp.macosx-10.6-x86_64-3.6/pyrfr
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I./include -I/Users/matthewlaffin/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/matthewlaffin/anaconda3/include/python3.6m/Python.h:11,
                   from pyrfr/regression_wrap.cpp:173:
  /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command /Users/matthewlaffin/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-m428phi8/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-record-5hy11e0q/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'pyrfr._regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.macosx-10.6-x86_64-3.6
    creating build/temp.macosx-10.6-x86_64-3.6/pyrfr
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I./include -I/Users/matthewlaffin/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                     from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                     from /Users/matthewlaffin/anaconda3/include/python3.6m/Python.h:11,
                     from pyrfr/regression_wrap.cpp:173:
    /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/matthewlaffin/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-m428phi8/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-record-5hy11e0q/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-m428phi8/pyrfr/
Collecting smac
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from smac) (40.5.0)
Requirement already satisfied: pynisher>=0.4.1 in ./anaconda3/lib/python3.6/site-packages (from smac) (0.5.0)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.3 in ./anaconda3/lib/python3.6/site-packages (from smac) (0.4.7)
Requirement already satisfied: scipy>=0.18.1 in ./anaconda3/lib/python3.6/site-packages (from smac) (1.0.1)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.6/site-packages (from smac) (5.4.3)
Collecting pyrfr>=0.5.0 (from smac)
  Using cached https://files.pythonhosted.org/packages/ed/0f/4d7e42a9dfef3a1898e03cffa8f1cfcd1f96507d718808b2db584c6f8401/pyrfr-0.8.0.tar.gz
Requirement already satisfied: sphinx in ./anaconda3/lib/python3.6/site-packages (from smac) (1.7.2)
Requirement already satisfied: joblib in ./anaconda3/lib/python3.6/site-packages (from smac) (0.11)
Requirement already satisfied: sphinx-rtd-theme in ./anaconda3/lib/python3.6/site-packages (from smac) (0.4.2)
Requirement already satisfied: scikit-learn>=0.18.0 in ./anaconda3/lib/python3.6/site-packages (from smac) (0.19.1)
Requirement already satisfied: cython in ./anaconda3/lib/python3.6/site-packages (from smac) (0.28.2)
Requirement already satisfied: typing in ./anaconda3/lib/python3.6/site-packages (from smac) (3.6.4)
Requirement already satisfied: numpy>=1.7.1 in ./anaconda3/lib/python3.6/site-packages (from smac) (1.14.3)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from smac) (1.11.0)
Requirement already satisfied: docutils>=0.3 in ./anaconda3/lib/python3.6/site-packages (from pynisher>=0.4.1->smac) (0.14)
Requirement already satisfied: pyparsing in ./anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.5,>=0.4.3->smac) (2.2.0)
Requirement already satisfied: Jinja2>=2.3 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (2.9.6)
Requirement already satisfied: Pygments>=2.0 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (2.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (1.2.1)
Requirement already satisfied: babel!=2.0,>=1.3 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (2.5.3)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (0.7.10)
Requirement already satisfied: imagesize in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (2.18.4)
Requirement already satisfied: packaging in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (17.1)
Requirement already satisfied: sphinxcontrib-websupport in ./anaconda3/lib/python3.6/site-packages (from sphinx->smac) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->smac) (1.0)
Requirement already satisfied: pytz>=0a in ./anaconda3/lib/python3.6/site-packages (from babel!=2.0,>=1.3->sphinx->smac) (2018.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac) (2018.10.15)
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /Users/matthewlaffin/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-4be0xiwq/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-wheel-wsxzsjsz --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pyrfr._regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build
  creating build/temp.macosx-10.6-x86_64-3.6
  creating build/temp.macosx-10.6-x86_64-3.6/pyrfr
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I./include -I/Users/matthewlaffin/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/matthewlaffin/anaconda3/include/python3.6m/Python.h:11,
                   from pyrfr/regression_wrap.cpp:173:
  /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr, smac
  Running setup.py install for pyrfr ... error
    Complete output from command /Users/matthewlaffin/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-4be0xiwq/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-record-63vak91k/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'pyrfr._regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.macosx-10.6-x86_64-3.6
    creating build/temp.macosx-10.6-x86_64-3.6/pyrfr
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I/Users/matthewlaffin/anaconda3/include -arch x86_64 -I./include -I/Users/matthewlaffin/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                     from /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                     from /Users/matthewlaffin/anaconda3/include/python3.6m/Python.h:11,
                     from pyrfr/regression_wrap.cpp:173:
    /Users/matthewlaffin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/matthewlaffin/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-4be0xiwq/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-record-63vak91k/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/n5/ytgn6kc566j7k20zvvs92tzc0000gn/T/pip-install-4be0xiwq/pyrfr/

**Comment by zhangjunli177** [comment]
I have a similar issue before, but can't remember whether it's same as yours. And also not sure whether you used ubuntu16.04. 
I fixed my issue with following way, run the following command before run the “curl ... install” command:
sudo apt-get install build-essential swig

**Comment by mfeurer** [comment]
Did you install gcc the following way inside Anaconda?: `http://automl.github.io/auto-sklearn/stable/installation.html#anaconda-installation`.

Furthermore, Stackoverflow suggests that limits.h is part of libc.

Closing this as we don't support OSX.

**Comment by shyamal-anadkat** [comment]
Try this - https://gist.github.com/simonprovost/051952533680026b67fa58c3552b8a7b

**Comment by canozkan42** [comment]
`conda install swig`
`pip install Cmake` 
`pip install wheel setuptools --upgrade`
before installing auto-sklearn solved it for me.

**Comment by theashwanigupta** [comment]
Thanks @canozkan42, I was able to install it on mac(conda) by following your instructions

**Comment by Proryanator** [comment]
> `conda install swig` `pip install Cmake` `pip install wheel setuptools --upgrade` before installing auto-sklearn solved it for me.

This worked for me, appreciate it!

**Comment by L20L020801** [comment]
> pip install wheel setuptools --upgrade

Appreciate this so much
