### ISSUE TITLE
Feature Importance

### ISSUE THREAD

**Issue by kaiweiang** [automl/auto-sklearn#580]
Hi,

I am wondering if autosklearn is able to return a list of feature importance of the final ensemble model after fitting? If not, any idea how I can manually retrieve it?

Thanks

**Comment by mfeurer** [comment]
No, Auto-sklearn can not give any general feature importance information. However, some of the models Auto-sklearn uses can give you feature importance information. Please check my answer to #524 to find out how that's possible. Please reopen if this doesn't answer your question.
