### ISSUE TITLE
paper results reproduction

### ISSUE THREAD

**Issue by leun123** [automl/auto-sklearn#583]
Hi!

Has anyone tried to reproduce the paper results?

I had some problems with missing values, object/categorical variables and multi-classes problem.

Do I have to pre-processes the data myself before trying auto-sklearn?

Thanks!!

**Comment by mfeurer** [comment]
Hi, this is a duplicate issue and there are already multiple issues on this such as #543 #544 #471 #424 and PR #550. If you have a question regarding a specific error please open a new issue for it.
