### ISSUE TITLE
string labels in multi-class classification

### ISSUE THREAD

**Issue by leun123** [automl/auto-sklearn#586]
Hi, I am trying to run autosklearn in the "yeast" dataset but had the following problem:

ValueError: could not convert string to float: 'MIT'

I have string labels in the y values and sklearn cannot handle it.

Does it support LabelBinarizer() or should I go for LabelEncoder for the best option?
Thanks in advance!

**Comment by leun123** [comment]
I was able to run using LabelBinarizer but had a lot of warnings and the accuracy score was not good at all (33%).

/usr/local/lib/python3.5/dist-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

**Comment by mfeurer** [comment]
Well, the label binarizer does `Binarize labels in a one-vs-all fashion`, which removes quite a lot of information, which is an issue if you actually encode the target. Therefore, LabelEncoder is the correct method here. However, I'm surprised that Auto-sklearn doesn't handle that itself. Could you please provide an example so we can reproduce this?

**Comment by leun123** [comment]
Sure! Thanks for helping.

I used the following code:

Got this message: ValueError: could not convert string to float: 'MIT'
MIT is one of the categorical targets.


### Python

import numpy as np
import pandas as pd
import pickle
import random

### Sklearn

import sklearn.datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, log_loss , confusion_matrix, classification_report, f1_score, recall_score, precision_score,precision_recall_fscore_support

### Auto-sklearn Packages

import autosklearn.classification
import sklearn.model_selection

### Defined Error Rate:
def balanced_error_rate(confusion_matrix):
    
    import numpy
    classes_accuracies = []
    for i in range(0, len(confusion_matrix)):
        for j in range(0, len(confusion_matrix[0])):
            if i == j:
                classes_accuracies.append(confusion_matrix[i][j]/confusion_matrix[i].sum())
    return 100*(1-numpy.mean(classes_accuracies))

### Auto Sklearn
train = pd.read_csv('/home/leo_avila92/datasets/yeast/train.csv')
test = pd.read_csv('/home/leo_avila92/datasets/yeast/test.csv')

y_train = train.loc[:, train.columns == 'class']
x_train = train.loc[:, train.columns != 'class']

y_test = test.loc[:, test.columns == 'class']
x_test = test.loc[:, test.columns != 'class']

y_train['class'].unique()

random.seed(123)

automl = autosklearn.classification.AutoSklearnClassifier(
time_left_for_this_task= 21600, 
per_run_time_limit = 1800,
ml_memory_limit= 4096,
seed = 123,
tmp_folder='/tmp/autosklearn_yeast_tmp',
output_folder='/tmp/autosklearn_yeast_out',
delete_tmp_folder_after_terminate=False,
resampling_strategy='cv',
resampling_strategy_arguments={'folds': 10},
ensemble_size=1, #(default=50)
#initial_configurations_via_metalearning=0 #(default=25)
)


automl.fit(x_train.copy(), np.ravel(y_train.copy()), dataset_name='yeast')
automl.refit(x_train.copy(), y_train.copy())

y_hat = automl.predict(x_test)

### Metrics
print("Error Rate: {:0.5f}%" .format(100*(1-sklearn.metrics.accuracy_score(y_test, y_hat))))
print("Balanced Error Rate: {:0.5f}%".format(balanced_error_rate(sklearn.metrics.confusion_matrix(y_test, y_hat))))
print("\nConfusion Matrix: \n", sklearn.metrics.confusion_matrix(y_test, y_hat))
print("\nClassification Report: \n", sklearn.metrics.classification_report(y_test, y_hat))

**Comment by leun123** [comment]
Then, I encoded the targets and it worked just fine.

### Python

import numpy as np
import pandas as pd
import pickle
import random

### Sklearn

import sklearn.datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, log_loss , confusion_matrix, classification_report, f1_score, recall_score, precision_score,precision_recall_fscore_support

### Auto-sklearn Packages

import autosklearn.classification
import sklearn.model_selection

### Defined Error Rate:
def balanced_error_rate(confusion_matrix):
    
    import numpy
    classes_accuracies = []
    for i in range(0, len(confusion_matrix)):
        for j in range(0, len(confusion_matrix[0])):
            if i == j:
                classes_accuracies.append(confusion_matrix[i][j]/confusion_matrix[i].sum())
    return 100*(1-numpy.mean(classes_accuracies))

### Data
train = pd.read_csv('/home/leo_avila92/datasets/yeast/train.csv')
test = pd.read_csv('/home/leo_avila92/datasets/yeast/test.csv')

y_train = train.loc[:, train.columns == 'class']
x_train = train.loc[:, train.columns != 'class']

y_test = test.loc[:, test.columns == 'class']
x_test = test.loc[:, test.columns != 'class']

y_train['class'].unique()

### Label Encoding
encoder = preprocessing.LabelEncoder()
encoder.fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)


### Auto-Sklearn
random.seed(123)

automl = autosklearn.classification.AutoSklearnClassifier(
time_left_for_this_task= 120, 
per_run_time_limit = 30,
ml_memory_limit= 4096,
seed = 123,
tmp_folder='/tmp/autosklearn_yeast1_tmp',
output_folder='/tmp/autosklearn_yeast1_out',
delete_tmp_folder_after_terminate=False,
resampling_strategy='cv',
resampling_strategy_arguments={'folds': 10},
ensemble_size=1, #(default=50)
#initial_configurations_via_metalearning=0 #(default=25)
)


automl.fit(x_train.copy(), np.ravel(y_train.copy()), dataset_name='yeast')
automl.refit(x_train.copy(), y_train.copy())

y_hat = automl.predict(x_test)

### Metrics
print("Error Rate: {:0.5f}%" .format(100*(1-sklearn.metrics.accuracy_score(y_test, y_hat))))
print("Balanced Error Rate: {:0.5f}%".format(balanced_error_rate(sklearn.metrics.confusion_matrix(y_test, y_hat))))
print("\nConfusion Matrix: \n", sklearn.metrics.confusion_matrix(y_test, y_hat))
print("\nClassification Report: \n", sklearn.metrics.classification_report(y_test, y_hat))

**Comment by mfeurer** [comment]
Thanks a lot. Could you please provide us with a link to the dataset and format the code such that it can be copy/pasted (see [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/))?

We'll have a look at this.

**Comment by leun123** [comment]
@mfeurer I edited the comment above so you can copy the code.

I am trying both auto-sklearn and auto-weka so I used datasets available at: 

https://www.cs.ubc.ca/labs/beta/Projects/autoweka/datasets/

To change from .arff to .csv I used the weka tool Arff Viewer: opened the dataset and saved as .csv

**Comment by franchuterivera** [comment]
Hello, 

Autosklearn can now encode categorical values in the features/targets automatically (you can use the current development branch for this), and our recommendation for that is to use a pandas dataframe directly (List, np.ndarray, pandas frames are also supported).

here is your updated example:
`
 ### Python
 import numpy as np
 import pandas as pd
 import pickle
 import random
 
 ### Sklearn
 
 import sklearn.datasets
 from sklearn import metrics
 from sklearn import preprocessing
 import sklearn.model_selection
 from sklearn.metrics import accuracy_score, log_loss , confusion_matrix, classification_report,      f1_score, recall_score, precision_score,precision_recall_fscore_support
 
 ### Auto-sklearn Packages
 
 import autosklearn.classification
 import sklearn.model_selection
 
 ### Defined Error Rate:
 def balanced_error_rate(confusion_matrix):
 
     import numpy
     classes_accuracies = []
     for i in range(0, len(confusion_matrix)):
         for j in range(0, len(confusion_matrix[0])):
             if i == j:
                 classes_accuracies.append(confusion_matrix[i][j]/confusion_matrix[i].sum())
     return 100*(1-numpy.mean(classes_accuracies))
 
 ### Data
 # Using http://archive.ics.uci.edu/ml/datasets/Yeast via
 # https://www.openml.org/d/181
 import sklearn.datasets
 X, y = sklearn.datasets.fetch_openml(data_id=181, return_X_y=True, as_frame=True)
 X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
     X, y, random_state=1
 )
 
 ### Label Encoding
 # Encoding is not necessary if a dataframe is provided
 # Autosklearn will dynamically detect which columns need
 # encoding, if they have the proper dtype (categorical, bool)
 ### Auto-Sklearn
 random.seed(123)
 
 automl = autosklearn.classification.AutoSklearnClassifier(
     time_left_for_this_task= 120,
     per_run_time_limit = 30,
     ml_memory_limit= 4096,
     ensemble_memory_limit=2048,
     seed = 123,
     tmp_folder='/tmp/autosklearn_yeast1_tmp',
     output_folder='/tmp/autosklearn_yeast1_out',
     delete_tmp_folder_after_terminate=False,
     resampling_strategy='cv',
     resampling_strategy_arguments={'folds': 10},
     ensemble_size=1, #(default=50)
     #initial_configurations_via_metalearning=0 #(default=25)
 )
 
 automl.fit(X_train, y_train, dataset_name='yeast')
 automl.refit(X_train, y_train)
 
 y_hat = automl.predict(X_test)
 
 print(f"y_hat={y_hat}")
 print(f"y_test={y_test}")
 
 ### Metrics
 print("Error Rate: {:0.5f}%" .format(100*(1-sklearn.metrics.accuracy_score(y_test, y_hat))))
 print("Balanced Error Rate: {:0.5f}%".format(balanced_error_rate(sklearn.metrics.                    confusion_matrix(y_test, y_hat))))
 print("\nConfusion Matrix: \n", sklearn.metrics.confusion_matrix(y_test, y_hat))
 print("\nClassification Report: \n", sklearn.metrics.classification_report(y_test, y_hat))

`
The requirement is that the columns are properly defined as category/bool, for this automatic encoding to happen.

Notice how I am using the yeast dataset from https://www.openml.org/d/181 which is the same one from WEKA, but it facilitates your work. You can also create a pandas dataframe yourself (like you do above in your example). Just make sure the type is a category:

`y
0       MIT
1       MIT
2       MIT
3       NUC
4       MIT
       ... 
1479    ME2
1480    NUC
1481    ME2
1482    NUC
1483    CYT
Name: class_protein_localization, Length: 1484, dtype: **category**`

Kindly reopen if further help is needed, we will be happy to help.
