### ISSUE TITLE
Are you supposed to get the same results when fitting automl using different seeds?

### ISSUE THREAD

**Issue by leun123** [automl/auto-sklearn#587]
Hi, I tried to run automl in different datasets (mnist, convex, waveform, ...) using seeds = 26, 42 and 123 and each time I get the same results for classification, it includes accuracy score and confusion matrix. The ranking for models can vary but the first place model was always the same, for example, random forest.

The seed was defined in the beginning of my jupyter notebook using random.seed(26) and inside the automl classifier as below:

automl = autosklearn.classification.AutoSklearnClassifier(
time_left_for_this_task = 21600, #6 hours
per_run_time_limit = 900, # 15 minutes
ml_memory_limits = 4096,
seed=26,
tmp_folder = '/tmp/autosklearn_convex26_tmp',
output_folder = '/tmp/autosklearn_convex26_out',
delete_tmp_folder_after_terminate = False,
resampling_strategy = 'cv',
resampling_strategy_arguments = {'folds': 10},
ensemble_size = 1, #best_model
)

Results:
Error Rate of 18.47% for each run (1-autosklearn.metrics.accuracy_score(y_test, y_hat))

**Comment by mfeurer** [comment]
Short answer: No.

By default, Auto-sklearn uses meta-learning to warmstart the optimization procedure. In some cases the meta-learning configurations are either already very good so I doesn't improve, or the dataset you're working on is actually included in the meta-data, or there's not enough time for further improvements.

MNIST and waveform are definitely included in the meta-data, and therefore, I expect it's a combination of the three issues. You could try without meta-learning to make sure that there's no other issue.

**Comment by leun123** [comment]
Sure! Thanks for helping.

I used the following code:

Got this message: ValueError: could not convert string to float: 'MIT'
MIT is one of the categorical targets.

#####################################################################
# Python

import numpy as np
import pandas as pd
import pickle
import random

# Sklearn

import sklearn.datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, log_loss , confusion_matrix, classification_report, f1_score, recall_score, precision_score,precision_recall_fscore_support

# Auto-sklearn

import autosklearn.classification
import sklearn.model_selection

def balanced_error_rate(confusion_matrix):
    
    import numpy
    classes_accuracies = []
    for i in range(0, len(confusion_matrix)):
        for j in range(0, len(confusion_matrix[0])):
            if i == j:
                classes_accuracies.append(confusion_matrix[i][j]/confusion_matrix[i].sum())
    return 100*(1-numpy.mean(classes_accuracies))

train = pd.read_csv('/home/leo_avila92/datasets/yeast/train.csv')
test = pd.read_csv('/home/leo_avila92/datasets/yeast/test.csv')

y_train = train.loc[:, train.columns == 'class']
x_train = train.loc[:, train.columns != 'class']

y_test = test.loc[:, test.columns == 'class']
x_test = test.loc[:, test.columns != 'class']

y_train['class'].unique()

encoder = preprocessing.LabelEncoder()

random.seed(123)

automl = autosklearn.classification.AutoSklearnClassifier(
time_left_for_this_task= 21600, 
per_run_time_limit = 1800,
ml_memory_limit= 4096,
seed = 123,
tmp_folder='/tmp/autosklearn_yeast_tmp',
output_folder='/tmp/autosklearn_yeast_out',
delete_tmp_folder_after_terminate=False,
resampling_strategy='cv',
resampling_strategy_arguments={'folds': 10},
ensemble_size=1, #(default=50)
#initial_configurations_via_metalearning=0 #(default=25)
)


automl.fit(x_train.copy(), np.ravel(y_train.copy()), dataset_name='yeast')
automl.refit(x_train.copy(), y_train.copy())

y_hat = automl.predict(x_test)

# Metrics
print("Error Rate: {:0.5f}%" .format(100*(1-sklearn.metrics.accuracy_score(y_test, y_hat))))
print("Balanced Error Rate: {:0.5f}%".format(balanced_error_rate(sklearn.metrics.confusion_matrix(y_test, y_hat))))
print("\nConfusion Matrix: \n", sklearn.metrics.confusion_matrix(y_test, y_hat))
print("\nClassification Report: \n", sklearn.metrics.classification_report(y_test, y_hat))

#########################################################################

**Comment by leun123** [comment]
Then, I encoded the targets and it worked just fine.

### Python

import numpy as np
import pandas as pd
import pickle
import random

### Sklearn

import sklearn.datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, log_loss , confusion_matrix, classification_report, f1_score, recall_score, precision_score,precision_recall_fscore_support

### Auto-sklearn Packages

import autosklearn.classification
import sklearn.model_selection

### Defined Error Rate:
def balanced_error_rate(confusion_matrix):
    
    import numpy
    classes_accuracies = []
    for i in range(0, len(confusion_matrix)):
        for j in range(0, len(confusion_matrix[0])):
            if i == j:
                classes_accuracies.append(confusion_matrix[i][j]/confusion_matrix[i].sum())
    return 100*(1-numpy.mean(classes_accuracies))

### Data
train = pd.read_csv('/home/leo_avila92/datasets/yeast/train.csv')
test = pd.read_csv('/home/leo_avila92/datasets/yeast/test.csv')

y_train = train.loc[:, train.columns == 'class']
x_train = train.loc[:, train.columns != 'class']

y_test = test.loc[:, test.columns == 'class']
x_test = test.loc[:, test.columns != 'class']

y_train['class'].unique()

### Label Encoding
encoder = preprocessing.LabelEncoder()
encoder.fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)


### Auto-Sklearn
random.seed(123)

automl = autosklearn.classification.AutoSklearnClassifier(
time_left_for_this_task= 120, 
per_run_time_limit = 30,
ml_memory_limit= 4096,
seed = 123,
tmp_folder='/tmp/autosklearn_yeast1_tmp',
output_folder='/tmp/autosklearn_yeast1_out',
delete_tmp_folder_after_terminate=False,
resampling_strategy='cv',
resampling_strategy_arguments={'folds': 10},
ensemble_size=1, #(default=50)
#initial_configurations_via_metalearning=0 #(default=25)
)


automl.fit(x_train.copy(), np.ravel(y_train.copy()), dataset_name='yeast')
automl.refit(x_train.copy(), y_train.copy())

y_hat = automl.predict(x_test)

### Metrics
print("Error Rate: {:0.5f}%" .format(100*(1-sklearn.metrics.accuracy_score(y_test, y_hat))))
print("Balanced Error Rate: {:0.5f}%".format(balanced_error_rate(sklearn.metrics.confusion_matrix(y_test, y_hat))))
print("\nConfusion Matrix: \n", sklearn.metrics.confusion_matrix(y_test, y_hat))
print("\nClassification Report: \n", sklearn.metrics.classification_report(y_test, y_hat))

**Comment by leun123** [comment]
I tried without meta-learning, with datasets not inluded in the meta-data and giving more budge time and results started to change.

Thanks!

**Comment by mfeurer** [comment]
Cool. I'm closing this now, please reopen if the issue still exists or you have any further queestions.
