### ISSUE TITLE
Get best model predictions without running ensembles

### ISSUE THREAD

**Issue by hmendozap** [automl/auto-sklearn#59]
When running a modified version of the script in which I don't want ensembles (ie. without ensemble builder script) just the best model to make a prediction over my test dataset, I get the obvious error that ```self._ensemble._get_model_identifiers() is NoneType```.

Is that the intended behaviour such that one must create an ensemble of 1 or should I file it as a bug?

**Comment by Motorrat** [comment]
to find (ten) best classifiers you can use this script
```
atsklrn_temp_salt=/YOUR_PATH/c0117d274efb6b8a11bf94969dac9fd9/
for quality in $(grep obj $atsklrn_temp_salt/log-run*|sed -e 's/^.*obj\ \(.*$\)/\1/'|sort|uniq|head -10); do grep final -A 1  $(grep -l "$quality" $atsklrn_temp_salt/log-run*|sort|head -1); done;
```
change `head -10` to `head -1` to find the single best classifier.

**Comment by mfeurer** [comment]
Commit 5e4686afc1f0aae8218743edde7c72d0f6e66175 adds this functionality, it's usage is demonstrated in `examples/example_holdout.py` (so far only in the development branch).
