### ISSUE TITLE
Support with large dataset 

### ISSUE THREAD

**Issue by htw2012** [automl/auto-sklearn#591]
Hi,

If we want to find architectures on large datasets such as ImageNet, how to change our code to support it?

Thanks

**Comment by mfeurer** [comment]
Auto-sklearn does not perform neural architecture search and NAS is out of scope for Auto-sklearn. Please look for a library which implements NAS. See for example [this literature overview](https://www.automl.org/automl/literature-on-neural-architecture-search/) and [this survey](https://www.automl.org/wp-content/uploads/2018/12/nas-1.pdf) to find out about the current state of the art of finding architectures for ImageNet.
