### ISSUE TITLE
How to deal with categorical column with value of negative integer?

### ISSUE THREAD

**Issue by xiaodineu** [automl/auto-sklearn#594]
When we get column like this [-9,-8,-9,-8,-10,-9,-8,-9,-8,-9,-8,-10,-9,-8]. We treat it as categorical column and set corresponding feat_type categorical. Then we got a error in one_hot_encoder  procedure, when calculating meta-features:

X needs to contain only non-negative integers. 

Should I modify this part of the code to be compatible with negative values or performing label-encoder before? Can you give me some advice ? Thanks!

**Comment by mfeurer** [comment]
Please apply the label encoder before.

Reasoning: the one hot encoder expects the positive integers to be indices into a label array.
