### ISSUE TITLE
Decision Tree (classifier->decision_tree->max_depth)	

### ISSUE THREAD

**Issue by jianswang** [automl/auto-sklearn#596]
Shouldn't be the max_dept for decision tree classifier an integer?
Why the results I get for max_depth are with decimals(1.9460823349231 and 0.11202027212876)?
Can you help to clear my doubt?

**Comment by mfeurer** [comment]
This is a duplicate of #569 and was resolved via #590. It's already included in the latest 0.4.2 release.
