### ISSUE TITLE
Error with example

### ISSUE THREAD

**Issue by WarmongeR1** [automl/auto-sklearn#6]
Hi all,
I took example (from docs), and i got error:

```python
Traceback (most recent call last):
  File "/home/warmonger/Develop/AutoInformatisation/TagEmitter/src/pydigest/exampl.py", line 25, in <module>
    print automl.score(X_test, y_test)
  File "/home/warmonger/Develop/venv/pocket2/local/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 360, in score
    prediction = self.predict(X)
  File "/home/warmonger/Develop/venv/pocket2/local/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 139, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/warmonger/Develop/venv/pocket2/local/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 329, in predict
    raise ValueError("No models fitted!")
ValueError: No models fitted!
```

pip freeze:
```
alembic==0.7.6
AutoSklearn==0.0.1.dev0
beautifulsoup4==4.3.2
blinker==1.3
boto==2.38.0
bz2file==0.98
cffi==1.1.0
chardet==2.3.0
cma==1.1.6
cryptography==0.9
cssselect==0.9.1
Cython==0.22
DAWG-Python==0.7.2
decorator==4.0.2
docopt==0.6.2
enum34==1.0.4
Flask==0.10.1
Flask-Admin==1.1.0
Flask-Admin-Profiler==0.0.1
Flask-DebugToolbar==0.10.0
Flask-Migrate==1.4.0
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-WTF==0.11
gensim==0.11.1.post1
gevent==1.0.2
greenlet==0.4.7
grequests==0.2.0
HPOlib==0.1.0
HPOlibConfigSpace==0.1.dev0
idna==2.0
ipaddress==1.0.7
itsdangerous==0.24
Jinja2==2.7.3
langdetect==1.0.5
liac-arff==2.0.2
lockfile==0.10.2
lxml==3.4.4
Mako==1.0.1
MarkupSafe==0.23
matplotlib==1.4.3
mock==1.0.1
MySQL-python==1.2.5
naiveBayesClassifier==0.1.3
ndg-httpsclient==0.4.0
networkx==1.10
nltk==3.0.2
nose==1.3.7
numpy==1.9.0
objgraph==2.0.0
pandas==0.16.0
ParamSklearn==0.1.dev0
pocket==0.3.5
protobuf==2.6.1
psutil==3.1.1
psycopg2==2.6
pyasn1==0.1.7
pycparser==2.13
-e git+https://bitbucket.org/mfeurer/pymetalearn/@2767d4d9eca801ad23247ced586a91957ef583e5#egg=pyMetaLearn-master
pymongo==3.0.3
pymorphy2==0.8
pymorphy2-dicts==2.4.393442.3710985
pyOpenSSL==0.15.1
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.4
PyYAML==3.11
readability-lxml==0.5.1
requests==2.7.0
rutermextract==0.2
scikit-learn==0.15.2
scipy==0.14.0
six==1.9.0
smart-open==1.2.1
SQLAlchemy==1.0.4
textblob==0.9.0
topia.termextract==1.1.0
umemcache==1.6.3
Werkzeug==0.10.4
WTForms==2.0.2
zope.interface==4.1.2
```

**Comment by mfeurer** [comment]
Hi,

the `pip freeze` doesn't show anything suspicious. Can you please tell me which OS you're working on?

Besides that, the error means something went wrong inside auto-sklearn. To debug, can you please

1. rerun the example
2. find out the temporary directory of auto-sklearn, it is saved in the variable `AutoSklearnClassifier.tmp_dir`
3. zip that directory and send it to me so I can figure out what's going wrong.

Best,
Matthias

**Comment by WarmongeR1** [comment]
My code

```python
# -*- encoding: utf-8 -*-

import autosklearn
import sklearn.datasets

digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target
import numpy as np

indices = np.arange(X.shape[0])
np.random.shuffle(indices)
X = X[indices]
y = y[indices]

X_train = X[:1000]
y_train = y[:1000]
X_test = X[1000:]
y_test = y[1000:]
automl = autosklearn.AutoSklearnClassifier(time_left_for_this_task=300,
                                           per_run_time_limit=30)

automl.fit(X_train, y_train)

print automl.score(X_test, y_test)

```
tmp folder:
https://www.dropbox.com/s/m06ueysutbi97lr/autosk_tmp.zip?dl=0

**Comment by WarmongeR1** [comment]
OS: xUbuntu 14.04 

```bash
$ uname -a 
Linux work-laptop 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mfeurer** [comment]
Hi,
thanks for the detailed error log. I can see the error as well as the error message, but I don't understand the reason why it occurs. The problem is that SMAC (the internal optimization tool) does a command line call in order to run scikit-learn, but cannot import a part of auto-sklearn. 

If you want to find out more, can you please copy the file `bb2ebe616e5e8c00795451fb02e3e4b7_Manager.pkl` from the uploaded zip file to some location on your machine and try to run the following command from within your virtual environment, replacing the first positional argument with the path to the copied file and tell me the output:

    python /home/warmonger/Develop/venv/auto_sk2/local/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/SMAC_cli_holdout.py /tmp/autosk_tmp/bb2ebe616e5e8c00795451fb02e3e4b7_Manager.pkl holdout 0 5.0 2147483647 -1 -balancing:strategy 'none' -classifier 'random_forest' -imputation:strategy 'mean' -preprocessor 'no_preprocessing' -random_forest:bootstrap 'True' -random_forest:criterion 'gini' -random_forest:max_depth 'None' -random_forest:max_features '1.0' -random_forest:max_leaf_nodes 'None' -random_forest:min_samples_leaf '1' -random_forest:min_samples_split '2' -random_forest:n_estimators '100' -rescaling:strategy 'min/max'

Thanks in advance.

**Comment by WarmongeR1** [comment]
I copy ```bb2ebe616e5e8c00795451fb02e3e4b7_Manager.pkl``` in folder ```/tmp/a``` and run:

```bash
python /home/warmonger/Develop/venv/auto_sk2/local/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/SMAC_cli_holdout.py /tmp/a/bb2ebe616e5e8c00795451fb02e3e4b7_Manager.pkl holdout 0 5.0 2147483647 -1 -balancing:strategy 'none' -classifier 'random_forest' -imputation:strategy 'mean' -preprocessor 'no_preprocessing' -random_forest:bootstrap 'True' -random_forest:criterion 'gini' -random_forest:max_depth 'None' -random_forest:max_features '1.0' -random_forest:max_leaf_nodes 'None' -random_forest:min_samples_leaf '1' -random_forest:min_samples_split '2' -random_forest:n_estimators '100' -rescaling:strategy 'min/max'

Result for ParamILS: SAT, 0.133874, 1, 0.047138, 1, acc_metric: 0.047138047138;pac_metric: 0.390416676765;auc_metric: 0.00249940622403;bac_metric: 0.0484475926245;f1_metric: 0.0485363455358;duration: 0.133874177933;num_run:00000
```
and got files in ```/tmp/a```:

https://www.dropbox.com/s/w9jm68sqmgug5c0/autosk_tmk2.zip?dl=0

**Comment by mfeurer** [comment]
Hi,
I am sorry, I can only tell you the issue, but not how to fix it. The problem seems to be that your virtualenv is no longer present in python calls done via subprocess.Popen. I have not seen this issue before and did not find anything on google.

**Comment by WarmongeR1** [comment]
i made big refactoring (pull request #7).
Now i can run example script in virtualenv in bash.
I can't run example in pycharm ( Don't understand why).
If this tool will fit, then I will continue to do refactoring

**Comment by mfeurer** [comment]
Okay, I will have a look at the PR. It might take a while because of its size.

Regarding pyCharm, I have the same issue there. A virtualenv for a project is not present any more when using subprocess.Popen. Thus, it can only be run from a normal bash shell.

**Comment by mfeurer** [comment]
Can I consider this issue solved?

**Comment by WarmongeR1** [comment]
Yes.
