### ISSUE TITLE
Hyperparameter floating point precision in configuration search space

### ISSUE THREAD

**Issue by hmendozap** [automl/auto-sklearn#60]
**Not critical**

When adding a `UniformFloat` or `Constant` hyperparameter to the configuration space of any component, the string conversion to the _'parameter configuration space file'_ has only 10 decimal digits precision that mismatches the native float precision (53 bits) when running auto-sklearn and setting the hyperparameter for a component.

**Comment by mfeurer** [comment]
I opened up an [issue](https://github.com/automl/ConfigSpace/issues/11) in the upstream ConfigSpace package.
