### ISSUE TITLE
How to set the parameter initial_configurations_via_metalearning

### ISSUE THREAD

**Issue by xiaodineu** [automl/auto-sklearn#607]
Hi!
Since meta_learning is proved to be very effective，I have doubts about how to set this parameter. Is the default value 25 the best value verified by experiments? Or have you ever perform any experiments to determine which value is better for a new dataset?

**Comment by mfeurer** [comment]
It was most effective in our experiments in our [2015 AAAI paper](https://ml.informatik.uni-freiburg.de/papers/15-AAAI-MI-SMBO.pdf).
