### ISSUE TITLE
SMAC and Ensemble Selection time budgets

### ISSUE THREAD

**Issue by alexgcsa** [automl/auto-sklearn#616]
Hello,

Regarding time budgets for SMAC and Ensemble Selection, how is this performed in Auto-SKLearn?

Given the total time for the task (given by the user), do you perform SMAC to optimize the pipelines in a percentage of this time? And the remaining,  you allocate for performing ensemble selection? 

I could not find this in the code.

Thanks in advance.

Alex de Sá

**Comment by mfeurer** [comment]
Hey @alexgcsa, they are done in parallel by default. If you want to do this one after the other check out [this example](https://automl.github.io/auto-sklearn/master/examples/example_sequential.html#sphx-glr-examples-example-sequential-py). Keep in mind that you cannot really allocate any time limit to the ensemble building as it just takes some time (hopefully seconds) and stops afterwards. I hope this helps.
