### ISSUE TITLE
Some datasets show "no model" or "no argument" error after training, maybe Python moudule confilct?

### ISSUE THREAD

**Issue by kaishu** [automl/auto-sklearn#620]
For certain datasets,
after training, following error messages show:
`ValueError: Refit can only be called if 'ensemble_size' != 0`
`AttributeError: 'NoneType' object has no attribute 'get_models_with_weights'`
But I'm sure I have set ensemble number to 50,
and the `AttributeError` looks like the model is not generated thus the object became `NoneType`.

I tried to remove all Python modules except autosklearn and essential modules to load data,
with same arguments,
these datasets can be trained succesfully,
Maybe autosklearn has conflict with some Python Modules? (due to the number of modules is big, currently I haven't found what cause this...)

**Comment by mfeurer** [comment]
Could you please report the output of `print(automl.sprint_statistics())`? It prints how many configurations were successfully fitted during the hyperparameter optimization (docs are [here](https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.sprint_statistics)).

**Comment by eddiebergman** [comment]
We require further information to deal with this issue but it seems no models were found. This will be closed as this is documented in other issues such as #1288
