### ISSUE TITLE
Ensemble selection when ensemble size=1

### ISSUE THREAD

**Issue by jianswang** [automl/auto-sklearn#623]
When the ensemble size is 1, and even if the final successful algorithm validation score is the best, the algorithms considered for selection are those before the final successful algorithm. Why is that so?

**Comment by mfeurer** [comment]
Sorry, but I do not get the issue. Could you please check whether this is a duplicate of #566 and if not give an example of what's going wrong?

**Comment by jianswang** [comment]
It is due to the same sorting issue. Thanks.
