### ISSUE TITLE
loss metrics cv_results_ and indices_files results don't match when ensemble size=1

### ISSUE THREAD

**Issue by jianswang** [automl/auto-sklearn#626]
How is cv_results_ obtained? The scores for loss metrics from cv_results for each algorithm do not seem to match with the indices_files when ensemble size is 1. 

The two are exactly the same for normal metrics but not for loss metrics such as log loss for classification and mean squared error for regression.

**Comment by mfeurer** [comment]
Could you please give an example of how this looks like and how we could reproduce this issue?

**Comment by jianswang** [comment]
From automl.py,
        for run_key in self.runhistory_.data:
            run_value = self.runhistory_.data[run_key]
            config_id = run_key.config_id
            config = self.runhistory_.ids_config[config_id]

            param_dict = config.get_dictionary()
            params.append(param_dict)
            **mean_test_score**.append(1 - run_value.cost)

From ensemble_selection,
for j, pred in enumerate(predictions):
                # TODO: this could potentially be vectorized! - let's profile
                # the script first!
                fant_ensemble_prediction[:,:] = weighted_ensemble_prediction + \
                                             (1. / float(s + 1)) * pred
                scores[j] = 1 - calculate_score(
                    solution=labels,
                    prediction=fant_ensemble_prediction,
                    task_type=self.task_type,
                    metric=self.metric,
                    all_scoring_functions=False)

            all_best = np.argwhere(scores == np.nanmin(scores)).flatten()
            best = np.random.choice(all_best)
            ensemble.append(predictions[best])
            **trajectory.append(scores[best])**
            order.append(best)

From backend.py,
        with open(**indices_files[-1]**, 'rb') as fh:
            ensemble_members_run_numbers = pickle.load(fh)

For easier comparison, let's assume the ensemble_size=1.
The mean_test_score for each algorithm matches with the trajectory which includes all the scores for algorithms in the case of metrics such as F1,Recall,etc.
However, the mean_test_score do not seem to match with the trajectory in the case of loss metrics such as mean squared error(regression) and log loss(classification).
Why is that so?

**Comment by jianswang** [comment]
I realized that validation scores for metrics out of the scale of 0 to 1 will be having issues.

in _fast or _slow from ensemble_selection.py,
       for i in range(ensemble_size):
            scores = np.zeros((len(predictions)))
            s = len(ensemble)
            if s == 0:
                weighted_ensemble_prediction = np.zeros(predictions[0].shape)
            else:
                ensemble_prediction = np.mean(np.array(ensemble), axis=0)
                weighted_ensemble_prediction = (s / float(s + 1)) * \
                                               ensemble_prediction
            fant_ensemble_prediction = np.zeros(weighted_ensemble_prediction.shape)
            for j, pred in enumerate(predictions):
                # TODO: this could potentially be vectorized! - let's profile
                # the script first!
                fant_ensemble_prediction[:,:] = weighted_ensemble_prediction + \
                                             (1. / float(s + 1)) * pred
                **scores[j] = 1 - calculate_score(
                    solution=labels,
                    prediction=fant_ensemble_prediction,
                    task_type=self.task_type,
                    metric=self.metric,
                    all_scoring_functions=False)**

in _loss from abstract_evaluator.py,
        if not isinstance(self.configuration, Configuration):
            if all_scoring_functions:
                return {self.metric: 1.0}
            else:
                return 1.0
        **score = calculate_score(
            y_true, y_hat, self.task_type, self.metric,
            all_scoring_functions=all_scoring_functions)
        if hasattr(score, '__len__'):
            err = {key: self.metric._optimum - score[key] for key in score}
        else:
            err = self.metric._optimum - score
        return err**

in cv_results_ from automl.py,
        for run_key in self.runhistory_.data:
            run_value = self.runhistory_.data[run_key]
            config_id = run_key.config_id
            config = self.runhistory_.ids_config[config_id]
            param_dict = config.get_dictionary()
            params.append(param_dict)
            **mean_test_score.append(1 - run_value.cost)**

**Comment by mfeurer** [comment]
Could you please format your code with markdown as explained in the tutorial which is linked next to the 'close and comment' button?

**Comment by jianswang** [comment]
I have formatted the codes in the previous comment.

**Comment by mfeurer** [comment]
Thank you for reporting this. I get the issue, the code assumes that everything which could be optimized has to be maximized. Actually, the metric would know whether something needs to be maximized or minimized, but this information is not taken into account.

Would you like to contribute a fix to this?

**Comment by jianswang** [comment]
I can try to fix it but I am only free next week. What do you say? 
What are the guidelines for pull request?

**Comment by mfeurer** [comment]
There's no hurry on this and I'd be very happy if you take this on.

Regarding PR guidelines: please point to the PR to the development branch. Ideally there's also a unit test for every piece of code you change. Please request a review from me once you're done.

**Comment by mfeurer** [comment]
Thanks a lot for the fix in #642.
