### ISSUE TITLE
Reading of ensemble indices_files 

### ISSUE THREAD

**Issue by jianswang** [automl/auto-sklearn#627]
with open(indices_files[-1], 'rb') as fh:
ensemble_members_run_numbers = pickle.load(fh)

Why do we pick the last indices_files to be read? 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.0.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.1.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.2.ensemble',  
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.3.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.4.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.5.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.6.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.7.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.8.ensemble', 
            '/tmp/autosklearn_tmp_20496_9435/.auto-sklearn/ensembles/1.9.ensemble'

What if the indices_files which has the best ensemble is in between? Let's say in this case, 1.5.ensemble.

**Comment by mfeurer** [comment]
That's another instance of the model selection problem. At this point we don't have any test set left to decide which ensemble to use. Therefore, we simply assume that the last one in the list is the best.
