### ISSUE TITLE
Change requrements to reflect the move to sklearn 0.17

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#64]
I have upgraded autosklearn a few weeks ago and it dropped the requirement for sklearn 0.16.1. So I could successfully run it with current 0.17.x release. Now I am installing autosklearn from a scratch and can not get it over the sklearn 0.16.1 requirement. 
Is it something that has to be changed in requ.txt or there is more to it?
P.S. first install was on CentOS now it is on Ubuntu 14.04

**Comment by mfeurer** [comment]
We have not tried running auto-sklearn with scikit-learn 0.17 but most of the algorithms should still work. You have to change requ.txt and the setup.py.

**Comment by salamanders** [comment]
Any word on 0.17?  its been out for a while

**Comment by mfeurer** [comment]
We have it in the development branch; I hope we can merge it into master next week

**Comment by mfeurer** [comment]
auto-sklearn uses 0.17. Closing this now.
