### ISSUE TITLE
  Failed building wheel for scikit-learn when installing from requ.txt

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#65]
I have removed scikit-learn 0.17 from anaconda hoping to be able to install the version autosklearn requires. When running pip install -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requ.txt

I get a rather cryptic message 

> Building wheels for collected packages: scikit-learn
>   Running setup.py bdist_wheel for scikit-learn: started
>   Running setup.py bdist_wheel for scikit-learn: finished with status 'error'
>   Complete output from command /home/USERNAME/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Caf5WC/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpgPVyFnpip-wheel- --python-tag cp27:
>   Failed building wheel for scikit-learn

The problem is actually a missing compiler. This fixes it:
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get install build-essential`
for RedHat (6.5) `sudo yum groupinstall 'Development Tools'`

**Comment by Motorrat** [comment]
SMAC requires Java - ../anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/binaries/smac-v2.08.01-development-1/smac-v2.08.01-development-1/smac: line 23: exec: java: not found

it would also be nice to have as prerequisite

**Comment by Motorrat** [comment]
To upgrade autosklearn via `pip install --upgrade autosklearn` uninstall setup tools first. 
`pip uninstall setuptools`. They will be reinstalled automatically afterwards.

**Comment by Motorrat** [comment]
Another time just uninstalling setuptools did not help for `pip install --upgrade autosklearn`. 

> Could not import setuptools which is required to install from a source distribution.
> Please install setuptools.

So I had to do `pip install --upgrade setuptools`

**Comment by mfeurer** [comment]
You could try

    pip uninstall autosklearn
    pip install autosklearn

in order to upgrade it with having to deal with setuptools.

**Comment by mfeurer** [comment]
auto-sklearn is not using Java any more? Can I close this?

**Comment by Motorrat** [comment]
> auto-sklearn is not using Java any more?
If that's a statement and not a question then of course this can be closed.
I assume no other dependence of auto-sklearn uses Java either?

**Comment by mfeurer** [comment]
Sorry for the bad formulation of that statement. auto-sklearn does not use Java any more. I'm closing this now.
