### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by ArlindKadra** [automl/auto-sklearn#652]
Hey all,

When running Auto-Sklearn in parallel with `n_jobs` and providing a `True` flag for `delete_tmp_folder_after_terminate` and `delete_output_folder_after_terminate`, the directories are not deleted in the end. This is not reflected in the documentation, where for both parameters the following is written:
```
delete_tmp_folder_after_terminate: string, optional (True)
remove tmp_folder, when finished.......
```

**Comment by Motorrat** [comment]
Shouldn't `shared_mode=True` be set for this logic to kick in?

**Comment by mfeurer** [comment]
@Motorrat there's a new `n_jobs` argument which makes Auto-sklearn behave more like scikit-learn and spawns multiple instances on a single machine. We provide an example [here](https://automl.github.io/auto-sklearn/master/examples/example_parallel_n_jobs.html#sphx-glr-examples-example-parallel-n-jobs-py).

**Comment by gui-miotto** [comment]
@mfeurer , is this the desired deletion behavior or is it something to be fixed?

**Comment by beeb** [comment]
Is there a plan to allow for temp and output folder deletion when running n_jobs > 1?
