### ISSUE TITLE
How auto-sklearn generate several ensemble models?(not only one ensemble model) and sort according to score

### ISSUE THREAD

**Issue by joshua-xia** [automl/auto-sklearn#653]
I am also using H2O 's automl, it output several algos models and sort those models according to the score, can auto-sklearn also output several ensemble models sort according to score? till now I set ensemble size = 1 to include only one algo model in a ensemble model, how to output  several ensemble models? Thanks

**Comment by mfeurer** [comment]
I'm not familiar, could you please provide us with a screenshot/output of what you expect? 

In case you are looking for all models found by Auto-sklearn, you can try the `cv_results_` attribute after fitting, which gives similar output to scikit-learn's grid and random search.

**Comment by mfeurer** [comment]
Closing this issue as it has become stale. Please reopen if this is still an issue.
