### ISSUE TITLE
Can't get get_estimator() after upgrading autosklearn

### ISSUE THREAD

**Issue by BBELAOUCHA** [automl/auto-sklearn#659]
Hello, 
I updated my autosklearn to 0.5.0. I am saving automl object using dill, but when loading it I do not have access to AutosklearnObject._automl.models_[X]._final_estimator.choice.get_estimator() anymore. I could access to that object when i was using autosklearn 0.4.2

With autosklearn 0.5.0 I am getting the following error when trying to access to AutosklearnObject._automl:

-------------------------------------------------------------------------------------------------------------
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/anaconda3/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    381                 if cls in self.type_pprinters:
    382                     # printer registered in self.type_pprinters
--> 383                     return self.type_pprinters[cls](obj, self, cycle)
    384                 else:
    385                     # deferred printer

~/anaconda3/lib/python3.6/site-packages/IPython/lib/pretty.py in inner(obj, p, cycle)
    559                 p.text(',')
    560                 p.breakable()
--> 561             p.pretty(x)
    562         if len(obj) == 1 and type(obj) is tuple:
    563             # Special case for 1-item tuples.

~/anaconda3/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

~/anaconda3/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

~/anaconda3/lib/python3.6/site-packages/sklearn/base.py in __repr__(self)
    286     def __repr__(self):
    287         class_name = self.__class__.__name__
--> 288         return '%s(%s)' % (class_name, _pprint(self.get_params(deep=False),
    289                                                offset=len(class_name),),)
    290 

~/anaconda3/lib/python3.6/site-packages/sklearn/base.py in get_params(self, deep)
    226         """
    227         out = dict()
--> 228         for key in self._get_param_names():
    229             # We need deprecation warnings to always be on in order to
    230             # catch deprecated param values.

~/anaconda3/lib/python3.6/site-packages/sklearn/base.py in _get_param_names(cls)
    207                                    " %s with constructor %s doesn't "
    208                                    " follow this convention."
--> 209                                    % (cls, init_signature))
    210         # Extract and sort argument names excluding 'self'
    211         return sorted([p.name for p in parameters])

RuntimeError: scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class 'autosklearn.automl.AutoMLClassifier'> with constructor (self, *args, **kwargs) doesn't  follow this convention.

-----------------------------------------------------------------------------------------------------------
The type of AutosklearnObject._automl is list

Python 3.6.8

**Comment by mfeurer** [comment]
There was a major change in the internals of Auto-sklearn for 0.5.X which makes it impossible to unpickle old models. I'm afraid that you have to rebuild the models or use the older Auto-sklearn version.
