### ISSUE TITLE
How does autosklearn optimize prediction threshold

### ISSUE THREAD

**Issue by hamaxostichus** [automl/auto-sklearn#661]
Hello,
I am wondering how autosklearn figure out which threshold it uses for bi-class prediction.
Basically what threshold it uses to transfer a predicted list of probabilities (value [0,1]) to a list of binary (0 or 1) labels, and how is that threshold defined?
Thank you!

**Comment by mfeurer** [comment]
Auto-sklearn uses a threshold of 0.5 for binary or the max probability for multiclass, check out this piece in [automl.py](https://github.com/automl/auto-sklearn/blob/master/autosklearn/automl.py#L1034). You can use `predict_proba` instead to apply a threshold yourself.

**Comment by mfeurer** [comment]
Closing as this issue has been stale for more than a year - please re-open if this is still an issue.
