### ISSUE TITLE
sklearn onehotencoder error

### ISSUE THREAD

**Issue by SlowMonk** [automl/auto-sklearn#663]
from sklearn.preprocessing import OneHotEncoder

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-dc2c7bf22001> in <module>
----> 1 from sklearn.preprocessing import OneHotEncoder

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/xgboost/sklearn.py in <module>
      7 import warnings
      8 import json
----> 9 from .core import Booster, DMatrix, XGBoostError
     10 from .training import train
     11 

ImportError: attempted relative import with no known parent package

**Comment by mfeurer** [comment]
This error appears to happen within the xgboost package. Could you please post the version numbers of scikit-learn, numpy, scipy and xgboost?

**Comment by mfeurer** [comment]
We removed XGBoost from Auto-sklearn in the latest 0.6.0 release. Therefore, this should no longer be a problem.
