### ISSUE TITLE
Predict and predict_proba can only be called if 'ensemble_size != 0'

### ISSUE THREAD

**Issue by adrian-bender** [automl/auto-sklearn#668]
Hi, I've download and installed auto-sklearn succesfully but I can't get it work. Here is my code.

```
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

X, y = sklearn.datasets.load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier(        
	time_left_for_this_task=120,
	per_run_time_limit=60,
)
automl.fit(X_train, y_train)
y_hat = automl.predict(X_test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))
```

The code trigger many warnings and finally an error, here is the log:
[AutoML(1)f00fc4935fefc8f83f31eff3100a845d.log](https://github.com/automl/auto-sklearn/files/3113828/AutoML.1.f00fc4935fefc8f83f31eff3100a845d.log)

Could you help me, please?

**Comment by mfeurer** [comment]
The log file looks fine. Could you please post the traceback of the error?

**Comment by adrian-bender** [comment]
Yes, sure.

```
Traceback (most recent call last):
  File "basic_autosklearn.py", line 17, in <module>
    y_hat = automl.predict(X_test)
  File "/mnt/c/Users/Public/Machine Learning/Python/autosklearn/ab_autosklearn_env/lib/python3.6/site-packages/autosklearn/estimators.py", line 682, in predict
    return super().predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/mnt/c/Users/Public/Machine Learning/Python/autosklearn/ab_autosklearn_env/lib/python3.6/site-packages/autosklearn/estimators.py", line 513, in predict
    return self._automl[0].predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/mnt/c/Users/Public/Machine Learning/Python/autosklearn/ab_autosklearn_env/lib/python3.6/site-packages/autosklearn/automl.py", line 1036, in predict
    n_jobs=n_jobs)
  File "/mnt/c/Users/Public/Machine Learning/Python/autosklearn/ab_autosklearn_env/lib/python3.6/site-packages/autosklearn/automl.py", line 590, in predict
    raise ValueError("Predict and predict_proba can only be called "
ValueError: Predict and predict_proba can only be called if 'ensemble_size != 0'
```

**Comment by adrian-bender** [comment]
Hi, a comment to a previous post gave me an idea. I downgraded my numpy version to 1.16.2 (I had installed the last release = 1.16.3) and now the issue has been solved.

(I'm still seeing a lot of warnings)

Thank you.

**Comment by mfeurer** [comment]
Thanks a lot for the clarification. Indeed, the unit tests are failing as well. I'm re-opening this because it is a pretty big issue.

**Comment by Thedudejohan** [comment]
After re-installing Auto-sklearn yesterday, i am receiving the same error when i follow the example code from: https://automl.github.io/auto-sklearn/stable/

**Comment by YMMS** [comment]
@adrian-bender  @Thedudejohan  I met the same problem too. But when I downgraded the numpy to 1.16.2,  it still raises `ValueError`. I think it is a pretty big issue.

```
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    run(group_train_X, group_train_y, run_time, n_jobs)
  File "main.py", line 125, in run
    pred_y = automl.predict(test_X, n_jobs=n_jobs)
  File "/home/yangming/.pyenv/versions/TMCI/lib/python3.5/site-packages/autosklearn/estimators.py", line 820, in predict
    return super().predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/home/yangming/.pyenv/versions/TMCI/lib/python3.5/site-packages/autosklearn/estimators.py", line 513, in predict
    return self._automl[0].predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/home/yangming/.pyenv/versions/TMCI/lib/python3.5/site-packages/autosklearn/automl.py", line 590, in predict
    raise ValueError("Predict and predict_proba can only be called "
ValueError: Predict and predict_proba can only be called if 'ensemble_size != 0'
```

**Comment by Shugyousha** [comment]
I posted this in another issue (https://github.com/automl/auto-sklearn/issues/667) that is most likely due to the same update but will post it here as well:

We have just been bitten by this as well. The culprit is this changed default value:

The allow_pickle function parameter default value has been changed from True to False since numpy 1.16.3 (the newest one).

(from https://www.numpy.org/devdocs/reference/generated/numpy.load.html)

numpy versions lower than 1.16.3 (i. e. 1.16.2 or 1.16.1 should work). A clean solution would be to allow pickling explicitly in the cases that auto-sklearn is using it.

**Comment by mfeurer** [comment]
Thanks a lot at all for posting the solution of downgrading to numpy 1.16.2. Indeed, the last unit tests using conda used numpy 1.16.2 and they fail since 1.16.3. The unit tests using a plain ubuntu installation together with 1.15.4 are still fine.

**Comment by huangwei2013** [comment]
Q：    
    ValueError: Cannot load file containing pickled data when allow_pickle=False
A：
    (2019.01 Numpy security to make a revise(cover v1.10-v1.16.x), 1.16.3 to fixed, while autosklearn still the same)

    manully: numpy/lib/npyio.py
        from
            allow_pickle=False
        to
            allow_pickle=True

**Comment by mfeurer** [comment]
Fixed via #675. Will work again in the next release.

**Comment by moelliDo** [comment]
I assume this issue had been resolved in the past? However, it appears to me again: 

> Traceback (most recent call last):
  File "somefile.py", line 74, in <module>
    y_hat = model.predict(X_test)
  File "/home/user/venv/lib/python3.6/site-packages/autosklearn/estimators.py", line 682, in predict
    return super().predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/home/user/venv/lib/python3.6/site-packages/autosklearn/estimators.py", line 513, in predict
    return self._automl[0].predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/home/user/venv/lib/python3.6/site-packages/autosklearn/automl.py", line 1036, in predict
    n_jobs=n_jobs)
  File "/home/user/venv/lib/python3.6/site-packages/autosklearn/automl.py", line 590, in predict
    raise ValueError("Predict and predict_proba can only be called "
ValueError: Predict and predict_proba can only be called if 'ensemble_size != 0'

I'm using:
Ubuntu 16.04 LTS
python3.6.10
auto-sklearn==0.6.0
numpy==1.18.1

**Comment by mfeurer** [comment]
@moelliDo could you please post the constructor call to the classifier? It looks like you have an ensemble size of zero, which leads to an empty model, which can't be used to predict something. Please try using an ensemble size > 0.

**Comment by moelliDo** [comment]
@mfeurer you are right, I called the classifier using `ensemble_size==0` as the documentation for fit() states, that:
 

> Fit both optimizes the machine learning models and builds an ensemble out of them. To disable ensembling, set ensemble_size==0 [Source](https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.fit)

Setting the ensemble_size to 1 results in an "ensemble" having only one model. However, the results  vary significantly. Sometimes the model metrics such as the F1-score are below 0.01. If I run the exact same script on the exact same dataset again, F1-scores of >0.7 are obtained. This is related to #783. This time, however, no error or obvious warning is getting displayed such that I do not know how to interpret these results?
