### ISSUE TITLE
cannot load ensemble

### ISSUE THREAD

**Issue by AndreaMonjaraz** [automl/auto-sklearn#671]
I'm trying to run the Extending Auto-Sklearn with Classification Component example and i got this error:

/usr/local/lib/python3.6/dist-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
[WARNING] [2019-04-29 12:13:53,655:EnsembleBuilder(1):44fd5e1470653a53325cc47fcc435fdf] Error loading /tmp/autosklearn_tmp_19208_991/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/autosklearn/ensemble_builder.py", line 316, in read_ensemble_preds
    y_ensemble = self._read_np_fn(fp=fp)
  File "/usr/local/lib/python3.6/dist-packages/autosklearn/ensemble_builder.py", line 645, in _read_np_fn
    predictions = np.load(fp)
  File "/home/user/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 451, in load
    Allow saving object arrays using Python pickles. Reasons for disallowing
ValueError: Cannot load file containing pickled data when allow_pickle=False

[WARNING] [2019-04-29 12:13:53,718:EnsembleBuilder(1):44fd5e1470653a53325cc47fcc435fdf] No models better than random - using Dummy Score!

I tried with different numpy 1.14 and 1.16.2 and none of that worked

**Comment by jvitorfranca** [comment]
I'm with the same issue, it seems to be a problem with the update of the library. Hope they fix it soon.

**Comment by AlexRuizE** [comment]
Same issue here, broke my scripts.

**Comment by mfeurer** [comment]
Please check the solution presented in #668.
