### ISSUE TITLE
Stopping the process of fitting and giving a model based on the current fitted models

### ISSUE THREAD

**Issue by jianswang** [automl/auto-sklearn#672]
Is there a way that I can quit the process of fitting and still get a model based on the current available models? 

When I start the process of fitting, I have noticed that there are 4 processes ( 3S and 1R ), how do I know whether which is the main/child process?

**Comment by mfeurer** [comment]
Sorry, this is currently not implemented.

**Comment by mfeurer** [comment]
Regarding your second question, you can potentially use a tool like [pstree](https://en.wikipedia.org/wiki/Pstree) to figure this out.

**Comment by mfeurer** [comment]
Ah, and this is a duplicate of #397 so I'm closing it.
