### ISSUE TITLE
conflict of pickle.dump() and numpy.save()

### ISSUE THREAD

**Issue by mu-triv** [automl/auto-sklearn#673]
Saving the files "predictions_ensemble_M_N.npy" calls the function pickle.dumps() in the file backend.py.
Loading the files "predictions_ensemble_M_N.npy" calls the function numpy.load() in the file ensemble_builder.py.

While loading the files, this makes the error: ValueError: Cannot load file containing pickled data when allow_pickle=False

_A_ simple fix for this issue is to explicitly allow pickle. Otherwise, we need to use in both saving and loading pickle or numpy._

**Comment by mfeurer** [comment]
Thanks for reporting this. I'm closing this issue as it is a duplicate of #668
