### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_models_with_weights'

### ISSUE THREAD

**Issue by Lggggggx** [automl/auto-sklearn#674]
I tried to apply auto-sklearn to regression task. But i got some strange problems.
The default values are used for all parameters except for a few.

    automl = autosklearn.regression.AutoSklearnRegressor(
        tmp_folder='./tmp5/autosklearn_regression_example_tmp/',
        output_folder='./tmp5/autosklearn_regression_example_out/',
        n_jobs=8,
        delete_output_folder_after_terminate=False,
        delete_tmp_folder_after_terminate=False,
        time_left_for_this_task=3600*4,
        ml_memory_limit=1024*12,
        ensemble_size=10,
    )

There is no mistakes in the training process and the log seems like fine.
An error occurued when show_models() is called.
```
Traceback (most recent call last):
  File "autosklearn_regression.py", line 64, in main
    print(automl.show_models())
  File "/home/li/anaconda3/lib/python3.7/site-packages/autosklearn/estimators.py", line 530, in show_models
    return self._automl[0].show_models()
  File "/home/li/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py", line 838, in show_models
    models_with_weights = self.get_models_with_weights()
  File "/home/li/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py", line 835, in get_models_with_weights
    return self.ensemble_.get_models_with_weights(self.models_)
AttributeError: 'NoneType' object has no attribute 'get_models_with_weights'
```
The output of the autoregressor.sprint_statistics():
```
auto-sklearn results:
  Dataset name: australian_big_qt50_lr
  Metric: r2
  Best validation score: 0.705186
  Number of target algorithm runs: 294
  Number of successful target algorithm runs: 138
  Number of crashed target algorithm runs: 45
  Number of target algorithms that exceeded the time limit: 58
  Number of target algorithms that exceeded the memory limit: 53
```
When trying use the fiited model to predict, an error occurued.
```
ValueError: Predict and predict_proba can only be called if 'ensemble_size != 0'
```
It seems that there is not a singel model in the ensembel. That doesn`t make sense.
It seems like a simple question, but i have no idea to solve it.
I would appreciate it if you could have time to look at this issue.

**Comment by mfeurer** [comment]
Could you please check if this is a duplicate of #668 ?

**Comment by Lggggggx** [comment]
Thank you for your quick reply. I have already checked the #668 issue. And i have downgraded my numpy version to 1.16.2. I also checked the other issues, such like checking the cython's version, ConfigSpace's version.
```  
This is the info about package
package           version
auto-sklearn      0.5.1
ConfigSpace       0.4.10
Cython            0.28.5
numpy             1.16.2
scikit-learn      0.19.2

ubuntu            18.04.1 LTS
python            3.7.2
gcc               7.3.0
SWIG              3.0.12
```

**Comment by Lggggggx** [comment]
One point needs to be emphasized. The official regression example(example_regression.py) works fine. There is no bug.

**Comment by mfeurer** [comment]
Okay, this is surprising then. Do you still have the log file around? Could you please upload that?

**Comment by Lggggggx** [comment]
These are the log files.
[AutoML(1791095845):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168492/AutoML.1791095845.australian_big_qt50_lr.log)
[AutoML(1872583848):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168493/AutoML.1872583848.australian_big_qt50_lr.log)
[AutoML(2365658986):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168494/AutoML.2365658986.australian_big_qt50_lr.log)
[AutoML(3751350723):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168495/AutoML.3751350723.australian_big_qt50_lr.log)
[AutoML(3834805130):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168496/AutoML.3834805130.australian_big_qt50_lr.log)
[AutoML(4153361530):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168497/AutoML.4153361530.australian_big_qt50_lr.log)
[AutoML(327741615):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168490/AutoML.327741615.australian_big_qt50_lr.log)
[AutoML(953453411):australian_big_qt50_lr.log](https://github.com/automl/auto-sklearn/files/3168491/AutoML.953453411.australian_big_qt50_lr.log)

And i found that the directory structure is different between my regression(with problem) and the official regression example(example_regression.py). There is no 'ensembles' folder in my regression!

This is the tmp_folder of  my regression.
![2019-05-11 09-32-38 的屏幕截图](https://user-images.githubusercontent.com/13412302/57563421-433d6680-73d0-11e9-9a44-0e9f90d4f91f.png)
This is the tmp_folder of the official regression example.
![2019-05-11 09-33-14 的屏幕截图](https://user-images.githubusercontent.com/13412302/57563423-47698400-73d0-11e9-90e7-f5b2127643b6.png)

**Comment by Lggggggx** [comment]
I think I've found the cause of the problem. Probably because the size of data set is too big(10000, 396), and i use the default value of the parameter(ensemble_memory_limit). It is beyond the memory limit. 
This problem seems to be the same as the #513.
Thank you for your patience in answering my question.

**Comment by Loopiezlol** [comment]
encountering this myself - what did you to fix it? decrease the default ensemble memory upper bound?
