### ISSUE TITLE
Bump sklearn vesrion

### ISSUE THREAD

**Issue by adithyabsk** [automl/auto-sklearn#681]
Are there any plans to bump the sklearn version to 0.21? The current version is a 1+ years old. Also, is there documentation on how to setup the project locally and run tests?

**Comment by tmielika** [comment]
https://github.com/automl/auto-sklearn/pull/664 attempted to do that but build is failing.

**Comment by mfeurer** [comment]
Yes, we are planning to do so, but we'll probably take until mid July to finish that.

**Comment by mfeurer** [comment]
> Also, is there documentation on how to setup the project locally and run tests?

Not really, and this also somewhat depends on your setup (IDE or CLI). If you have a more specific question on this I can maybe answer that.

**Comment by esztermarton** [comment]
What's the status of this? Are there any open branches?

**Comment by mfeurer** [comment]
We're close in PR #703.

**Comment by No-Stream** [comment]
This would be awesome. 

In particular, after downgrading, I'm missing the iterative imputer (experimental) is pretty powerful and has improved results with missing data for me. (Paired with BayesianRidge by default for fast, good results, KNeighborsRegressor for fast handling of nonlinearities, and RF for best performance / similar to R's MissForest.) Would be happy to try a PR once this branch is merged.

**Comment by mfeurer** [comment]
Okay, we have support for 0.21.X with the latest release of 0.6.0. Support for 0.22.X is coming within the next 1-3 months.

**Comment by mfeurer** [comment]
Closing this as we now support 0.22 with the latest release of Auto-sklearn 0.7.0. We'll be working on support of sklearn 0.23 soonish.
