### ISSUE TITLE
Official support for vscode dev container (docker) environment (e.g. for mac use)

### ISSUE THREAD

**Issue by songololo** [automl/auto-sklearn#682]
I've been unable to get `auto-sklearn` running on my mac.

However, `vscode` will soon support development inside a docker container and this approach is now working for me (see [`dev-containers`](https://github.com/microsoft/vscode-dev-containers))

Note that this currently requires the `vscode-insiders` edition.

Hence my question, would there be interest in creating an official `vscode` `dev-container` definition for `auto-sklearn`?

Here is an example of my setup:
- Create a `.devcontainer` folder with the following files:
- `devcontainer.json`
```
{
	"name": "Python 3",
	"context": "..",
	"dockerFile": "Dockerfile",
	"extensions": [
		"ms-python.python"
	]
}
```
- `Dockerfile` - this has been created from a hybrid `vscode` example and the `auto-sklearn` `Dockerfile`:
```
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM python:3

# Copy default endpoint specific user settings overrides into container to specify Python path
COPY .devcontainer/settings.vscode.json /root/.vscode-remote/data/Machine/settings.json

# Install git, process tools
RUN apt-get update && apt-get -y install git procps build-essential curl swig

RUN mkdir /workspace
WORKDIR /workspace

# Install pylint
RUN pip install pylint

# install auto-sklearn dependencies
RUN curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt \
| xargs -n 1 -L 1 pip3 install

# install auto-sklearn
RUN pip install auto-sklearn jupyter

# install own dependencies
RUN pip install pandas matplotlib seaborn tqdm asyncpg

# Install Python dependencies from requirements.txt if it exists
COPY .devcontainer/requirements.txt.temp requirements.txt* /workspace/
RUN if [ -f "requirements.txt" ]; then pip install -r requirements.txt && rm requirements.txt*; fi

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash

```

`vscode` will then detect the dev container config, and offers to create the dev container.

I've been able to run `jupyter` and, thus-far, `auto-sklearn` appears to be working as intended.

PS - for those trying the above setup, and if referencing a database or port on the host system (from the dev container), change `localhost` to `host.docker.internal`.

**Comment by mfeurer** [comment]
Thank you very much for posting this solution @songololo! It sounds like this will make it a lot easier to develop for/with Auto-sklearn on OSX & Windows. However, given that we in Freiburg don't really have the time to take care of the official docker file, I'm afraid that we won't be able to 'officially' support this.

However, I'd like to add this 'issue' to the list of possible solutions to run Auto-sklearn on Windows and OSX. Would you like to create a PR to update [the documentation page](https://github.com/automl/auto-sklearn/blob/development/doc/installation.rst)?

**Comment by franchuterivera** [comment]
A docker image is available and the documentation has been enhanced with this [here](https://automl.github.io/auto-sklearn/master/installation.html). I am closing this issue as it appears to be solved.
