### ISSUE TITLE
The process doesn't stop when the process is keyboardinterrupted

### ISSUE THREAD

**Issue by ghk829** [automl/auto-sklearn#683]
The process doesn't stop when the process is keyboardinterrupted.

The issue is related to the issuses.

First one is related to **pynisher library when buillding ensemble_models**

I did a pull request for the pynisher

``` python
# ensemble_builder.py line 151

safe_ensemble_script = pynisher.enforce_limits(
                wall_time_in_s=int(time_left),
                mem_in_mb=self.memory_limit,
                logger=self.logger
            )(self.main)

```

Second issue is  related to **class ExecuteTaFuncWithQueue**

The logic should be maded when the process is keyboardInterrupted

The last one is when n_job > 1 ,

``` python

# estimators.py line 402


```
I suggest that the logic should be try except KeyboardInterrupted.

**Comment by franchuterivera** [comment]
Hello! Thank you very much for your interest in Auto-Sklearn.

Since this PR, we have enabled distributed worker support via dask. That being said, there is no support to nicely stop a running job  in a distributed environment. For this reason, I will be closing this issue.
