### ISSUE TITLE
Fördermittel von Bundesministerium für Bildung und Forschung for adding  "explain the output of any machine learning model" with SHAP

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#685]
https://github.com/slundberg/shap/blob/master/README.md

http://www.foerderdatenbank.de/Foerder-DB/Navigation/Foerderrecherche/suche.html?get=cf6731d5e96daac995a4ee21fa9a8ad9;views;document&doc=14105

https://www.plattform-lernende-systeme.de/foerderungki.html
Erklärbarkeit und Transparenz des Maschinellen Lernens und der Künstlichen Intelligenz

Unterstützt werden Forschungs- und Entwicklungsvorhaben zur Nachvollziehbarkeit, Erklärbarkeit und Transparenz des ML bzw. der KI (v.a. im Hinblick auf praxisrelevante Anwendungen). Gefördert werden vorzugsweise Verbundprojekte, in begründeten Ausnahmefällen auch Einzelvorhaben, in grundsätzlich drei Arten von Projekten, die auch kombiniert werden können: 1) Grundlagenorientierte, interdisziplinäre Projekte, die durch eine Zusammenarbeit vor allem der Fachgebiete Physik, Kognitionswissenschaften und Informatik zustande kommen 2) Methodenentwicklungsprojekte, die sich mit der essentiellen Weiterentwicklung schon bestehender Ideen beschäftigen 3) Werkzeugentwicklungsprojekte, die sich mit der Neuentwicklung von Werkzeugen für die Nachvollziehbarkeit beschäftigen.

Antragsfrist: 03. Juni 2019

**Comment by mfeurer** [comment]
Thank you very much for sharing these. Unfortunately, the deadline is a bit too tight for us.

In case your plan was to collaboratively write such a proposal, please email us directly regarding such inquiries.

**Comment by akshayparanjape** [comment]
**Did anybody further try using SHAP for auto-sklearn models?** 
I tried and the individual tree models from auto-sklearn ensembles are not currently supported by SHAP TreeExaplainer but one can always use KernelExplainer for ensemble or individual model and that works smoothly. 
Any update on this would be useful.
