### ISSUE TITLE
Parallel Usage with n_jobs=-1

### ISSUE THREAD

**Issue by Chowkah** [automl/auto-sklearn#692]
Hello,

I tried to use auto-sklearn in parallel as suggested here: https://github.com/automl/auto-sklearn/blob/master/examples/example_parallel_n_jobs.py

Unfortunately, I faced two issues. First when setting n_jobs=-1 I get "IndexError: list index out of range". However, when setting it to the number of cores in my machine (e.g. 24) the error disappears. Second, I can see some very high peaks at the cpu utilization even when n_jobs=1 (sometimes even around 100% for some minutes within an 8h run) and I wonder what happens when setting n_jobs=24 (I have 24 cores at my machine) or any other high value. I already tried it and after a few minutes the cpu utilization was way over 100%. Is there any suggestion on how many cores it is safe to use?

I would be very happy about any suggestion, thanks!

**Comment by manugarri** [comment]
same here. I dont think n_jobs=-1 works.

**Comment by mfeurer** [comment]
Thanks to @Ashafix this is fixed and will be available in the next release.

> I already tried it and after a few minutes the cpu utilization was way over 100%. Is there any suggestion on how many cores it is safe to use?

Setting `n_jobs=1` only means to Auto-sklearn uses only a single core. scikit-learn and numpy can still use all cores and you have to manually disable that, for example via:

```bash
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export OMP_NUM_THREADS=1
```

**Comment by chengrunyang** [comment]
Hi @mfeurer , by saying that "setting n_jobs=1 only means to Auto-sklearn uses only a single core", does that mean auto-sklearn uses at most one core at any time? This seems a bit ambiguous given the API documentation that ``auto-sklearn uses a single core for fitting the machine learning model and a single core for fitting an ensemble" (https://automl.github.io/auto-sklearn/master/api.html).
