### ISSUE TITLE
AutoSklearn does not predict most of the test dataset

### ISSUE THREAD

**Issue by asmgx** [automl/auto-sklearn#694]
I am currently using AutoSkleam to predict regression values
something like 

Yr    Mth    Cnt
14    1        2010
14    2        1950 
14    3        2090
14    4        2100
...........
...........
19    2        3110
19    3        3260

When I use Auto Sklearn to predict a test dataset
it gives 
Predicted_Cnt
3000
NaN
NaN
NaN
3120
NaN
NaN
NaN
NaN
NaN
NaN
4500
NaN
NaN
1950
NaN
NaN
NaN

I dont know why I am getting so many NaNs ?

anyone know why?

**Comment by mfeurer** [comment]
Could you please check whether XGBoost part of the final ensemble? If yes, it might be the same issue as https://github.com/automl/auto-sklearn/issues/636.

**Comment by mfeurer** [comment]
Closing this as I suspect XGBoost to be the culprit here, which we removed in the latest 0.6.0 release. Please reopen if the error persists.
