### ISSUE TITLE
can not install autosklearn in ubantu with python =3.6

### ISSUE THREAD

**Issue by ajoeajoe** [automl/auto-sklearn#697]
Building wheels for collected packages: pyrfr
  Building wheel for pyrfr (setup.py) ... error
  ERROR: Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr, sphinx-rtd-theme, smac, auto-sklearn
  Running setup.py install for pyrfr ... error
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-l63aqf_6/pyrfr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mlo5kpfh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-l63aqf_6/pyrfr/

**Comment by ajoeajoe** [comment]
I have searched for a long time , and just can not know why, so I open for help.

**Comment by Den4ikNestor** [comment]
ajoeajoe, I'd had the same problem.

* Try to install **pyrfr** package. 
* If the installation couses the error (now the problem should be in **swig**) use the command ***"conda install gxx_linux-64 gcc_linux-64 swig"*** which is mentioned in documentation
* Then try to install **auto-sklearn** package again with ***"pip install auto-sklearn"*** command

**Comment by ajoeajoe** [comment]
apt-get install swig, it works, Many thx @Den4ikNestor
