### ISSUE TITLE
xgboost tests failed (autosklearn 0.5.x)

### ISSUE THREAD

**Issue by mu-triv** [automl/auto-sklearn#698]
autosklearn tests on xgboost failed when xgboost0.90 has been released

In autosklearn v0.5.1 or v0.5.2 requirements.txt, xgboost should be specified:

xgboost>=0.80,<0.90

**Comment by mfeurer** [comment]
Thanks a lot for reporting this, we're currently working on it in #703.

**Comment by mfeurer** [comment]
We removed XGBoost in the latest 0.6.0 release. Therefore, this should no longer be an issue.
