### ISSUE TITLE
FAIL: test_metadata_generation (test.test_scripts.test_metadata_generation.TestMetadataGeneration)

### ISSUE THREAD

**Issue by mu-triv** [automl/auto-sklearn#699]
running autosklearn 0.5.x with openml v.0.9.0, this test failed

**Comment by mfeurer** [comment]
Thank you very much for reporting this. We're tackling this issue in #703.

**Comment by mfeurer** [comment]
Closing this as the tests on travis-ci are passing. Please reopen if this is still an issue.
