### ISSUE TITLE
to turn pre-processing off use no_preprocessing

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#70]
AutoSklearnClassifier( include_preprocessors=('no_preprocessing',))

It would be great to have an explicit list of preprocessors and estimators that could be used in  include_preprocessors and include_estimators parameters of AutoSklearnClassifier.

**Comment by Motorrat** [comment]
candidate for the list of estimators classifier:choice, Type: Categorical, Choices: {adaboost, bernoulli_nb, decision_tree, extra_trees, gaussian_nb, gradient_boosting, k_nearest_neighbors, lda, liblinear_svc, libsvm_svc, multinomial_nb, passive_aggressive, proj_logit, qda, random_forest, sgd}

**Comment by mfeurer** [comment]
Documented in #273. Will be merged to development/master soon.
