### ISSUE TITLE
Scaling factors for metafeatures should not be learned using test data

### ISSUE THREAD

**Issue by bjschoenfeld** [automl/auto-sklearn#701]
In kND.py, the `_scale` method uses the test data (`other`) to learn the min and max values used to scale the metafeatures. It is typically not a good idea to use test data to learn any parameters.

https://github.com/automl/auto-sklearn/blob/1c6af59ff61f1d0a3b54b16a35ffbc5d2d3828cd/autosklearn/metalearning/metalearning/kNearestDatasets/kND.py#L165-L166

Would it be a good idea to use sklearn's `MinMaxScaler` anyways?

**Comment by mfeurer** [comment]
> It is typically not a good idea to use test data to learn any parameters.

I agree. Do you want to submit a pull request taking care of this?

> Would it be a good idea to use sklearn's MinMaxScaler anyways?

If it can handle pandas, yes.
