### ISSUE TITLE
unable to turn off preprocessing

### ISSUE THREAD

**Issue by shaheerakr** [automl/auto-sklearn#706]
this code runs successfully 
`reg = AutoSklearnRegressor(n_jobs=4,
                           time_left_for_this_task=60,
                           per_run_time_limit=5,
                           tmp_folder='/tmp/autosklearn_regression_example_tmp',
                           output_folder='/tmp/autosklearn_regression_example_out',
                           include_preprocessors=["no_preprocessing",])
`
when i try to fit data
`reg.fit(X_train,y_train)
`
these are the errors that occur
`
ValueError: Trying to set illegal value 'fast_ica' (type '<class 'str'>') for hyperparameter 'preprocessor:__choice__, Type: Categorical, Choices: {no_preprocessing}, Default: no_preprocessing' (default-value has type '<class 'str'>').
`

**Comment by Robotuks** [comment]
I don't know the reason behind this error but I can get rid of it by not specifying `tmp_folder` and `output_folder` in `AutoSklearnRegressor`

**Comment by mfeurer** [comment]
I cannot reproduce this issue with the latest version (0.6.0). Could you please try again with the latest version of Auto-sklearn and report back?
