### ISSUE TITLE
Can't use imbalanced-learn because of difference in scikit-learn version requirements

### ISSUE THREAD

**Issue by mjorgen1** [automl/auto-sklearn#708]
I am running an imbalanced dataset on auto-sklearn. I found the imbalanced-learn package within scikit-learn-contrib (https://github.com/scikit-learn-contrib/imbalanced-learn). To use this package though, I need scikit-learn(>=0.21) version. However, autosklearn needs scikit-learn-0.19.2. So I am rather stuck. Let me know if anyone has been able to get around this version issue or found another package that can be used for imbalanced data before running auto-sklearn.

**Comment by lacava** [comment]
have you tried installing autosklearn, and then upgrading scikit-learn to 0.21? I imagine this causes some compatibility issues, but I have run autosklearn this way without issues on a limited set of problems. I'm not sure if there are known issues with using the latest version of scikit-learn.

**Comment by mfeurer** [comment]
Auto-sklearn finally supports sklearn 0.21.X. Therefore, I'm closing this issue. Please reopen if you have any further issues or questions.

**Comment by vbersier** [comment]
Suggesting to re-open this issue as `imbalanced-learn` 0.7.0 requires `scikit-learn` 0.23.x.

**Comment by mfeurer** [comment]
Closing this again as the latest release (0.12.0, pushed a few minutes ago) uses 0.23.X.
