### ISSUE TITLE
Analyzing the top K cross-validated models

### ISSUE THREAD

**Issue by Shoeboxam** [automl/auto-sklearn#709]
I would like to retain, restore or re-fit the top K cross-validated models, to conduct more in-depth analysis than just taking the model with the best score. I don't see any information in the documentation about this, and I'm not seeing an obvious way to plug the hyperparams from `automl.cv_results_['params'][0]` back into an object to re-fit. Thank you for any pointers.

**Comment by anneursula** [comment]
HI! Did, by any chance, someone find a way to do this? I am currently trying to do the exact same thing..

**Comment by anneursula** [comment]
It could be if I understood correctly. My goal is to analyse all algorithms that ran successfully during 'fit()' (with ensemble_size=0) and refit each o of those on my data. I'm thinking I could fit automl, save all configurations from cv_results_ and then fit single models with these configurations?

**Comment by mfeurer** [comment]
I cannot think of an easier way to do so.

**Comment by eddiebergman** [comment]
Documented access to individual model pipelines and should be improved in #709, closing for now.
