### ISSUE TITLE
Unlimited ML Memory

### ISSUE THREAD

**Issue by jernsting** [automl/auto-sklearn#715]
I have seen, that auto-sklearn uses pynisher to internally enforce the memory and time limits for ml-Tasks. Is it possible to set the ml_memory_limit to None to use the full available ram or is there a limit somewhere else?

**Comment by mfeurer** [comment]
Unfortunately, this is not possible at the moment. To achieve the same result, you can pass an unrealistically high number.

**Comment by mfeurer** [comment]
Hey @jernsting we added this in PR #865 and this feature will be available in the next release. Please reopen if this does not solve your issue.
