### ISSUE TITLE
import autosklearn.classification failing in jupyter notebook

### ISSUE THREAD

**Issue by BobbyMadasu** [automl/auto-sklearn#716]
Hi there, 

After installing, while trying to run import autosklearn.classification in jupyter note book, it throws ModuleNotFoundError. 

But the same works in shell. 

Finally found, it is due to missing psutil. I tried to reinstall auto-sklearn using pip3 and found that psutil is missing and exit with code 1.

Installed psutil using pip3 and reinstalled auto-sklearn using pip3 and it worked.

**Comment by mfeurer** [comment]
Closing this as a) `psutil` is in the requirements file and b) the issue comes with a solution to fix the described problem. Thanks for reporting and providing a solution, too.
