### ISSUE TITLE
How to use autosklearn?

### ISSUE THREAD

**Issue by bartspiering** [automl/auto-sklearn#721]
Hi,

I have been testing autosklearn and it gives me pretty nice results. I have a few questions on how to successfully use autosklearn towards production. I am using the AutoSklearnRegressor.

- First of all I am not very sure on how to interpret the results provided by the show_models method. What do the weights mean? Are all the SimpleRegressionPipelines used for the learning and the outcome of the predictions or is it just a ranking for which of them performs the best?
- Should the AutoSklearnRegressor object be used in production or should the settings provided by show_models be used to implemented by myself in Sci Kit Learn?
- Can I optimize my results by aiming on specific preprocessors and regressors that previously have been giving me good results looking at the results in show_models?
- I was also wondering why the r2 score in the sprint_statistics differs from the r2 score where the tests are compared with the predictions(like in the examples on the website)

Thank you in advance for helping me understand things better!

**Comment by mfeurer** [comment]
Thanks for your interest in Auto-sklearn. I'll do my best answering these below:

> What do the weights mean?

The models are combined into an ensemble. The prediction of each single SimpleRegressionPipeline is multiplied with its weight and the weighted predictions are summed up. Weights are learned following the [ensemble selection](https://www.cs.cornell.edu/~alexn/papers/shotgun.icml04.revised.rev2.pdf) method.

> Should the AutoSklearnRegressor object be used in production or should the settings provided by show_models be used to implemented by myself in Sci Kit Learn?

You can do both. The second might be simpler to deploy and easier to debug if something goes wrong.

> Can I optimize my results by aiming on specific preprocessors and regressors that previously have been giving me good results looking at the results in show_models?

Yes, check [this part](https://automl.github.io/auto-sklearn/master/manual.html#restricting-the-searchspace) of the manual.

> I was also wondering why the r2 score in the sprint_statistics differs from the r2 score where the tests are compared with the predictions(like in the examples on the website)

Could you please point to an exact location in the code?
