### ISSUE TITLE
AutoSklearnRegressor ignores feat_type

### ISSUE THREAD

**Issue by Sylvus** [automl/auto-sklearn#722]
Hi,

I'm using the latest version from Github (0.6.0) and the AutoSklearnRegressor.fit() function. I have 20 columns and I am passing the parameter feat_type with 20 strings. Even if all of those strings are "Categorical", auto-sklearn still reports an error. With numpy I get the following error:

```
/usr/local/lib/python3.6/dist-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    536 
    537     """
--> 538     return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'My String'
```

With pandas it is a different one:

```
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    534         # make sure we actually converted to numeric:
    535         if dtype_numeric and array.dtype.kind == "O":
--> 536             array = array.astype(np.float64)
    537         if not allow_nd and array.ndim >= 3:
    538             raise ValueError("Found array with dim %d. %s expected <= 2."

ValueError: could not convert string to float: 'My String'
```

What is going on? Here is my function call:
`
automl.fit(X_train, y_train, feat_type=feature_types)
`

**Comment by mfeurer** [comment]
Hi, Auto-sklearn indeed cannot handle strings. You need to first encode them as integers. This used to be the case with scikit-learn, too, but they upgraded the one hot encoder, which we don't reflect yet.

I'll keep this issue open to remind us to either update Auto-sklearn or document this behavior.

**Comment by mfeurer** [comment]
Auto-sklearn by now supports pandas input and would give a proper error message here, added in #889
