### ISSUE TITLE
Obtaining cv_results_ while fitting

### ISSUE THREAD

**Issue by soumya1704** [automl/auto-sklearn#728]
I'm attempting `AutoSklearnClassifier.fit` with `time_left_for_this_task=7200`. So far it has not crashed and I can use `cv_results_` to get an idea of the models tried by autosklearn.

Now I plan to set the time to 24hrs, but I fear that my app might crash while fitting. Is it possible to get cv_results_ while fit is running. Or pausing fit every few intervals to obtain cv_results_ and resuming again?

**Comment by mfeurer** [comment]
There are two ways you can achieve this:

1. By inspecting the log files of Auto-sklearn in the `tmp_folder`. If you don't pass an argument here, a random temporary directory will be used.
2. By miss-using the parallel capabilities of Auto-sklearn. You can run [this example](https://automl.github.io/auto-sklearn/master/examples/example_parallel_manual_spawning.html) sequentiall by removing all multiprocessing code. Then, later instantiations of Auto-sklearn will take the output of previous runs into account.

Please reopen if you have any further questions.
