### ISSUE TITLE
which paper to cite?

### ISSUE THREAD

**Issue by amueller** [automl/auto-sklearn#73]
Hey.
Which paper should someone cite using this package?
I think that should be in the readme or on the website.

Also there is mention of a paper in the icml workshop, but no link to the paper.

Thanks,
Andy

**Comment by Motorrat** [comment]
I guess they refer to this paper on their group page https://papers.nips.cc/paper/5872-efficient-and-robust-automated-machine-learning

**Comment by amueller** [comment]
Thats publish way after the workshop they refer to ;)
That is probably the best paper to cite, but that should still be on the website.

**Comment by mfeurer** [comment]
Yes, please cite the NIPS paper.

**Comment by amueller** [comment]
@mfeurer I'd highly recommend putting up a pretty visible thing on the auto-skearn frontpage saying "if you use this, please cite this paper". Totally acceptable, and few people will make an effort to find the right citation for software.

**Comment by mfeurer** [comment]
The [new documentation](automl.github.io/auto-sklearn/) correctly references the NIPS paper, I have to add the text about the license though.

**Comment by amueller** [comment]
sweet :)

**Comment by mfeurer** [comment]
Okay, the [development branch documentation](http://automl.github.io/auto-sklearn/dev/index.html#citing-auto-sklearn) now has the bibtex entry.
