### ISSUE TITLE
temp folder eating spaces - can the models be deleted during autosklearn execution

### ISSUE THREAD

**Issue by BobbyMadasu** [automl/auto-sklearn#730]
Hi there, 

Would like to know, if we can keep deleting some files which is stored in the folder /tmp for autosklearn execution. 

du -sh autosklearn_15Oct2019_tmp gives be about 6.6.G

Are we allowed to delete models folder under /tmp/*/models while autosklearn is running to free up some space?

**Comment by mfeurer** [comment]
Hey, it took quite a while, but we finally added a new argument `max_models_on_disc` to Auto-sklearn, which governs the number of models and predictions kept on disc (https://automl.github.io/auto-sklearn/master/api.html). 

Please reopen if there are still issues with this.
