### ISSUE TITLE
[question] autosklearn in aws lamdbda serverless, install dependency like swig

### ISSUE THREAD

**Issue by CodesInTheShell** [automl/auto-sklearn#736]
Anyone tried to deploy a trained model to AWS lambda? 
I can't seem to find a resolution to install dependencies like swig in aws lambda or lambda layers.

**Comment by cturner500** [comment]
There's also a 15min function limit to deal with I believe?

**Comment by CodesInTheShell** [comment]
The idea is to train the model separately, but deploy the model for prediction on lambda + api gateway

**Comment by cturner500** [comment]
Yes, that works.  Are you using a requirements.txt file?

**Comment by CodesInTheShell** [comment]
awesome, I will try it, thanks.

**Comment by Loopiezlol** [comment]
might wanna look into AWS Lambda layers - you can pre-load large dependencies in the running environment without having to reinstall on hot lambda executions

**Comment by CodesInTheShell** [comment]
Here's what I tried:

1. Deploying flask hello app along with autosklearn + requirements.txt using zappa but I got OSError: [Errno 28] No space left on device

2. Package autosklearn and its requirements to lambda layer so that I can import it to a function but hit the package limit. I had 188.9 MB zip 514.6 MB unzipped

**Comment by CodesInTheShell** [comment]
I guess my only option now is to dockerize the app and run on GCP Cloud Run as serverless container.
 The app will enable us for auto development and deployment of ML models capable of integration. https://www.youtube.com/watch?v=h_Y8ud7b3LU
