### ISSUE TITLE
[question!] No models better than random - using Dummy Score!

### ISSUE THREAD

**Issue by Yemeng-Kang** [automl/auto-sklearn#739]
[WARNING] [2019-11-07 18:29:07,226:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!

what I should do to deal with this problem?

**Comment by LevineHuang** [comment]
Encountered the same problem.

**Comment by krwarner** [comment]
See #512 it is basically a warning message that is outputted at the beginning before auto sklearn starts to find better models. It will eventually go away.

**Comment by mfeurer** [comment]
Indeed, this is only a warning which is emitted when there is no better model than a random one. As soon as there is a better model, this error message goes away. However, this error message seems to be very confusing, so we should really remove it.

**Comment by Rong-Inspur** [comment]
@mfeurer Hi, I would like to help and make my first contribution here.

**Comment by SusheendharVijay** [comment]
What happens if the model does not find a better model than random within given time? What is the dummy score?

**Comment by michaeloc** [comment]
> What happens if the model does not find a better model than random within given time? What is the dummy score?

According with my experiments, if you have a dummy score all the time, you won't have a good trained model, because will be a random. I tried to run with 50k samples and trying to follow the rule of 1 day of training and 3 or 6GB memory. With 5k of data and 32 features I can training and the messages (dummy....) only appear in the beginning as it was said.

**Comment by mfeurer** [comment]
> What is the dummy score?

It is always predicting the majority class.

**Comment by mfeurer** [comment]
Thanks to @Rong-Inspur we will have a better error message in the next release.
