### ISSUE TITLE
broken links in docs generated from examples

### ISSUE THREAD

**Issue by lebedov** [automl/auto-sklearn#740]
The links on each of the following pages to the other page are not being generated properly:
<https://automl.github.io/auto-sklearn/master/examples/example_parallel_n_jobs.html>
<https://automl.github.io/auto-sklearn/master/examples/example_parallel_manual_spawning.html>

**Comment by valgeff** [comment]
I have written a fix, see https://github.com/automl/auto-sklearn/pull/777

**Comment by mfeurer** [comment]
Thanks a lot @valgeff the links should be fine now in the development branch (https://automl.github.io/auto-sklearn/development/examples/index.html).
