### ISSUE TITLE
0.6.0 Release date?

### ISSUE THREAD

**Issue by sjonnii** [automl/auto-sklearn#743]
Hi!

Not really an issue per say, but I was wondering if there is a set date for releasing version 0.6.0? The official auto-sklearn website says that you're currently on release 0.6.0, but I do see that there is no tag for it, and the latest pip version currently is 0.5.2

Thank you! 
-Sigurjon

**Comment by YichaoOU** [comment]
To add to it, I think 0.5.2 only works with sklearn 0.19? But my mlxtend 0.17 requires sklearn >=0.20.

**Comment by mfeurer** [comment]
Please excuse the long delay, but 0.6.0 is finally on pypi.
