### ISSUE TITLE
Please help me with error TypeError: __init__() got an unexpected keyword argument 'file'  Error showing for this line ->from azureml.train.automl import AutoMLConfig

### ISSUE THREAD

**Issue by Aatmaj1** [automl/auto-sklearn#744]

**Comment by Aatmaj1** [comment]
Tried updating the packages didn'y work

**Comment by Ashafix** [comment]
The error you are getting seems to be from a different library (https://pypi.org/project/azureml-train-automl/), not auto-sklearn. Probably better to check here: https://docs.microsoft.com/en-us/azure/machine-learning/

**Comment by mfeurer** [comment]
Closing this as it appears to be unrelated to Auto-sklearn as pointed out by @Ashafix
