### ISSUE TITLE
Attribute Error: 'OneHotEncoder" object has no attribute 'preprocessor'

### ISSUE THREAD

**Issue by JuliaGast** [automl/auto-sklearn#748]
Dear all,

When working with autosklearn I run into the following problem:
- When running autosklearn.fit, I want to pickle.load all models, which have automatically been pickled by autosklearn ( ....model) and use them to predict on a given dataset.
- for this I have an observer who observes the directory into which autosklearn automatically stores pickled models, as soon as a new model is pickled, it pickle.loads this model and runs model.predict(X).
- But: this then throws an error (see below) and crashed
- if I, after I pickle.load the model run model.fit(X_train, y_train), the error no longer appears
- this makes me think that for some reason the model is not fitted before being pickled (which is actually not the case when reading autosklearn documentation)

Has anybody encountered this problem yet? If so, what is the reason and is there a workaround?

(I use autosklearn version 0.5.2 and tried it  with scikit learn 0.19.2 and 0.21.3)

> type of model:  <class 'autosklearn.pipeline.regression.SimpleRegressionPipeline'>
Exception in thread Thread-1:
Traceback (most recent call last): ...
  File " .../lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File " .../lib/python3.7/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File " .../lib/python3.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File " .../lib/python3.7/site-packages/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File " .../_helper.py", line 102, in on_moved
    self._cback(event.dest_path) # note that this may result in callbacks with a file outside of models_dir, if it was moved somewhere else
  File  .../_helper.py", line 93, in _cback
    else: self.callback(path, self.ref)
  File " .../auto_sklearn.py", line 272, in _directory_changed
    pickle_model.predict(X_train)
  File " .../lib/python3.7/site-packages/autosklearn/pipeline/regression.py", line 96, in predict
    y = super().predict(X, batch_size=batch_size)
  File " .../lib/python3.7/site-packages/autosklearn/pipeline/base.py", line 141, in predict
    return super().predict(X).astype(self._output_dtype)
  File " .../lib/python3.7/site-packages/sklearn/utils/metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File " .../lib/python3.7/site-packages/sklearn/pipeline.py", line 306, in predict
    Xt = transform.transform(Xt)
  File " .../lib/python3.7/site-packages/autosklearn/pipeline/components/data_preprocessing/one_hot_encoding/__init__.py", line 97, in transform
    return self.choice.transform(X)
  File " .../lib/python3.7/site-packages/autosklearn/pipeline/components/data_preprocessing/one_hot_encoding/one_hot_encoding.py", line 60, in transform
    if self.preprocessor is None:
AttributeError: 'OneHotEncoder' object has no attribute 'preprocessor'

>

**Comment by mfeurer** [comment]
I haven't encountered this or a similar problem. Could you maybe post the code of the unpickling observer, maybe that helps to trace this error.

**Comment by JuliaGast** [comment]
Thank you for your reply.
Attached you find a code snippet containing the unpicklick observer (with a comment showing which line fails without fit)

class MyHandler(FileSystemEventHandler):

    def on_created(self, event):
        if event.is_directory: return None
        _directory_changed(event.src_path)

    def on_moved(self, event):
        if event.is_directory: return None
        _directory_changed(event.dest_path)

    def _directory_changed(fname): 
        if fname.endswith ('model'): 
            with open(fname, 'rb') as file_:
                pickle_model = pickle.load(file_)       		 
                pickle_model.fit(X_train, y_train) # OneHotEncoder needs refitted 
                #and for some reason, it's used in the pipeline even if the pipeline says categorical_encoding=='no_encoding' :-/

                pickled_model.predict(X_train) # this line fails if the previous line is commented
 
    def start_training_and_watch_directory(models_dir, X_train, y_train):
        auto_sklearn =  autosklearn.regression.AutoSklearnRegressor(tmp_folder=models_dir)
        observer = Observer()
        observer.schedule(MyHandler(), models_dir+'/.auto-sklearn/models', recursive=True)
        observer.start()
        auto_sklearn.fit(X_train, y_train) 
        observer.stop()
        observer.join()

[autosklearn_onehotencodersnippet.txt](https://github.com/automl/auto-sklearn/files/4034899/autosklearn_onehotencodersnippet.txt)

**Comment by mfeurer** [comment]
I can't see any obvious error here. Do you use cross-validation? If not, could you please post the snippet you use to start Auto-sklearn?

**Comment by JuliaGast** [comment]
resolved with upgrading sklearn to 0.21.3
