### ISSUE TITLE
Is there a way to leverage multiprocessing in .predict()?

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#75]
My understanding is that when the predict method is called a whole ensemble of the models need to be run on the prediction X dataset. And it does so on one core only. Is there a way to fan it out to all the cores so the models run in parallel?

**Comment by mfeurer** [comment]
By rewriting the predict-method to use the joblib in `sklearn.externals`, one could use all cores on a single machine.

**Comment by mfeurer** [comment]
@Motorrat can this be closed because of #239 and #242?

**Comment by Motorrat** [comment]
I guess so. Thanks!
