### ISSUE TITLE
 the project is no longer maintained?

### ISSUE THREAD

**Issue by licsh** [automl/auto-sklearn#752]
as the title describes

**Comment by mfeurer** [comment]
Indeed, I currently don't have the time to work on Auto-sklearn. I will come back to the project early next year to create a new release for scikit-learn 0.21 which will also include plenty bugfixes.

@gui-miotto currently prepares the package for the latest scikit-learn release, so we should also be able to put out a release for scikit-learn 0.22 soon afterwards.

If you're looking for the latest features, you could have a look at the current master branch, it contains everything that would go into a current release.

**Comment by mfeurer** [comment]
Closing this as I pushed the 0.6.0 release to pypi last week.
