### ISSUE TITLE
mutlilabel task 

### ISSUE THREAD

**Issue by chenkejin** [automl/auto-sklearn#754]
i want to know whether autosklearn support  multilabel task, thank you!

**Comment by mfeurer** [comment]
Yes, it does. However, we should really have an example for this. Therefore, I'm leaving this open.

**Comment by sirignanoj** [comment]
What kind of example are you looking for?

**Comment by chenkejin** [comment]
> What kind of example are you looking for?

using autosklearn tool to slove  multilabel task

**Comment by mfeurer** [comment]
Yes, it should show to format the data, put it into Auto-sklearn, and the show the results.

**Comment by mfeurer** [comment]
We do now have an example merged with #919.
