### ISSUE TITLE
Using auto-sklearn in windows 10

### ISSUE THREAD

**Issue by mjbahmani** [automl/auto-sklearn#755]
Hi,
Before I open this issue, I have searched a lot about how to install it on windows 10
Then I found that it does not support windows 10!
Is it correct?

**Comment by mjbahmani** [comment]
Also in ubuntu,
pip install autosklearn
got following error:

```
ERROR: Could not find a version that satisfies the requirement autosklearn (from versions: none)
ERROR: No matching distribution found for autosklearn
```
I found a solution for that based the following code:

```
apt-get remove swig
apt-get install swig3.0 build-essential -y
ln -s /usr/bin/swig3.0 /usr/bin/swig
apt-get install build-essential
pip install --upgrade setuptools
pip install auto-sklearn
```

**Comment by mfeurer** [comment]
Yes, Auto-sklearn does not support Windows. However, there's something called Ubuntu subsystem, and you can install Auto-sklearn in there as described in #431.
