### ISSUE TITLE
Auto sklearn vs AutoKeras

### ISSUE THREAD

**Issue by giorgio79** [automl/auto-sklearn#756]
What is the difference? :) Which one is better?

**Comment by mfeurer** [comment]
On a very high level, Auto-sklearn uses "traditional" machine learning methods together with Bayesian optimization, while Auto-sklearn performs neural architecture search for deep neural networks. The only performance comparison I'm aware of is https://arxiv.org/pdf/1908.05557.pdf. However, when using data which is suited for deep neural networks, I expect Auto-Keras to outperform Auto-sklearn.
