### ISSUE TITLE
time_left_for_this_task is not respected 

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#76]
This is probably functioning like designed but is not convenient from my point of view. I see tasks started at the end of the "time_left_for_this_task" and overrunning it by "per_run_time_limit", they are not killed when "time_left_for_this_task" is up. 

In my particular situation I set per_run_time_limit=time_left_for_this_task to accommodate very slow models as well. The result is that the fit time is doubled over the "time_left_for_this_task". 

This is probably upstream (SMAC) but just want to file it here so you are aware of it.

For me this is important as I am working on a massively parallel implementation so that the execution time can be rather short (hours). Doubling this time by just one runaway model goes against the hair of this initiative.

**Comment by mfeurer** [comment]
Thanks for reporting this, I just created an upstream issue as [#88](https://github.com/automl/SMAC3/issues/88).

**Comment by mfeurer** [comment]
Okay, this is fixed in the development branch and will be released in version 0.1.3 (not the next bugfix release).
