### ISSUE TITLE
Autosklearn requires scikit v <=21.3, conflicts with multiple libraries

### ISSUE THREAD

**Issue by iXanthos** [automl/auto-sklearn#768]
Greetings,

I am trying to run `autosklearn` as a part of my master's thesis, using external HPC infrastructure. The problem is that other libraries (e.g. `autopytorch`, `tpot`) require `scikit learn >= 0.22`, while autosklearn runs on `scikit-learn 21.3`. This creates major compatibility issues and I find it weird that this has not been updated, since 0.22 has been released at 3rd of December, 2019. Can this be updated? Are there issues with scikit-learn 0.22 and auto-sklearn that have not been adressed? In my opinion this is crucial as autosklearn is a major automl library and not having up-to-date dependencies is problematic.

Best regards

**Comment by gui-miotto** [comment]
Hi @iXanthos , this is going to be updated soon. We are about to start working on it.
Please, stay tuned for the next release.

**Comment by iXanthos** [comment]
> Hi @iXanthos , this is going to be updated soon. We are about to start working on it.
> Please, stay tuned for the next release.

I see, thank you for the reply.

**Comment by GuidoBartoli** [comment]
Thanks @gui-miotto, I am having the same issue as @iXanthos and I hope this will be fixed in the next release.

Cheers

**Comment by GuidoBartoli** [comment]
I would also like to add that auto-sklearn depends on smac 0.8. The latest version now is 0.12, but if I upgrade it, auto-sklearn gives this error:

`ModuleNotFoundError: No module named 'smac.facade.smac_facade'`

Will the next release also support the latest smac package?

Thanks

**Comment by mfeurer** [comment]
> Will the next release also support the latest smac package?

Yes.
