### ISSUE TITLE
Is it safe to build ensemble before all tasks are completed?

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#77]
As [pointed out]( https://github.com/automl/auto-sklearn/issues/76) some tasks are not completing within the time budget. Is it safe to build ensemble before all tasks are completed? Experimentally I have learned that the results are OK that way. Also the tasks that do not complete after some hours seem to run into out of memory or some other error anyway. So this is just to reconfirm that there is no catch.

**Comment by mfeurer** [comment]
Yes, it is safe to build the ensemble before all tasks are complete. This is even the default setting, when you run auto-sklearn it builds ensembles in a parallel process all of the time.
