### ISSUE TITLE
Get model co-efficients From Regressor -not classifier.

### ISSUE THREAD

**Issue by domainoverflow** [automl/auto-sklearn#776]
Hi, #776 and #524 

I would be grateful if anyone could point me to an example. I opened a new issue because all the other issues under this topic were meant for classifier. The difference in this case, being a regression instead. Thanks in advance for your valuable time. I wrote full details above.

**Comment by mfeurer** [comment]
Is this still of interest to you? If yes, could you please describe the specific issue with adapting the existing examples for regression?

Also, we have pushed a new example on how to analyze the models given by auto-sklearn that might be of interest to you: https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_get_pipeline_components.html#sphx-glr-examples-40-advanced-example-get-pipeline-components-py

**Comment by domainoverflow** [comment]
Hi Matthias,

thank you. Yes it is still of my interest. Let me try your example and I will report back. many thanks!

________________________________
