### ISSUE TITLE
How to disable Bayesian optimization?

### ISSUE THREAD

**Issue by chengrunyang** [automl/auto-sklearn#779]
Is there a way to disable the Bayesian optimization subroutine when fitting on a new dataset? I am curious about how the performance would be different when there is no such fine-tune. Thanks!

**Comment by mfeurer** [comment]
Do you want to use random search instead of Bayesian optimization? If that's the case, please check this examples: https://automl.github.io/auto-sklearn/master/examples/example_random_search.html

**Comment by chengrunyang** [comment]
Thanks for the pointer! I see `initial_configurations_via_metalearning=0` in the example. If I still want to use metalearning, and just replace Bayesian optimization with random search, should I leave this argument out by letting `initial_configurations_via_metalearning=25` (default)?

**Comment by mfeurer** [comment]
Yes, you need to leave this argument out. The reason why it's set to zero in that example is to make it be random.

**Comment by mfeurer** [comment]
Closing this issue as I believe this is solved.
