### ISSUE TITLE
Passing a object to the classifier

### ISSUE THREAD

**Issue by pbrandl** [automl/auto-sklearn#780]
Hello, I would like to pass an arbitrary object to the AutoML classifier. The object should be preprocessed with a special preprocessor which I want to pass to the classifier's parameter `include_preprocessors`. The preprocessor turns the object into a 2d-array which then is passed to the fit function of the AutoML classifier. 

Is this possible? E.g. by disabling the input checks?

**Comment by mfeurer** [comment]
> Is this possible?

We don't support this out of the box.

> E.g. by disabling the input checks?

Maybe, but you'd have to disable quite a lot of input checks. Auto-sklearn is built on the scikit-learn pipeline object, and I'm not sure if that would allow such objects in the first place. It might be easier if you use the Auto-sklearn pipeline alone as in [here](https://github.com/automl/HPOlib2/blob/master/hpolib/benchmarks/ml/autosklearn_benchmark.py), add the hyperparameters of your object to the search space, and tune this manually with for example [SMAC3](https://github.com/automl/SMAC3).

**Comment by eddiebergman** [comment]
I'm not sure anything can be done here or what the question was specifically asking about. It seems that there was a need for having a unique data pre-processor and the data should be passed through this pre-processor before reaching fit of any model.

It seems the easiest solution would have been to just pre-process the data manually beforehand and then pass that processed data to autosklearn and let autosklearn handle it from there.

Having only a specific pre-processor active is not currently possible nor do we support passing custom objects, instead, you would need to extend Autosklearn with anew component.

I'm closing this as it's been a while and we have other issues related to data-preprocessing which falls close to this. Having the a pipeline structure that allows you to specifically send data to custom preprocessors is a feature requested which would cover thisuse case if the suggested solution would not work.
