### ISSUE TITLE
Retrieving the number of predictors used by an autosklearn.estimators.AutoSklearnClassifier object 

### ISSUE THREAD

**Issue by vlagani** [automl/auto-sklearn#782]
Hello,

in my understanding, auto-sklearn also optimizes over different feature selection algorithms. This should mean that during prediction an autosklearn.estimators.AutoSklearnClassifier object may  use fewer predictors than the ones included in the original dataset. This is because the preprocessor step of each single model included in the ensemble may pre-select a subset of the features passed in input.

I wonder if there is an easy way for counting the number of predictors actually used by an autosklearn.estimators.AutoSklearnClassifier object. 

Kind regards,

Vincenzo

**Comment by mfeurer** [comment]
We have created a new example on how to analyze the model(s) created by auto-sklearn: https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_get_pipeline_components.html#sphx-glr-examples-40-advanced-example-get-pipeline-components-py

It is specific for PCA, but can be changed to work with other pre-processors as well.

Summing up, yes, there are possibilities to get the number of features used per model, but we do not provide those numbers directly. Instead, we provide mechanisms to inspect the trained model.
