### ISSUE TITLE
Save/Restore scaler

### ISSUE THREAD

**Issue by LucCADORET** [automl/auto-sklearn#787]
Hi, great work on the library.

I was wondering is there is a way to use/get the scaler from the `AutoSklearnClassifier` once it has build his model. The reason I want to do this, is to be able to scale some test data after training is complete.

**Comment by franchuterivera** [comment]
One way to do this is to run autosklearn as exemplified [here](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_get_pipeline_components.html#sphx-glr-examples-40-advanced-example-get-pipeline-components-py).

You will then have an estimator called `automl`. Autosklearn finds an ensemble of [pipelines](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html)  which can be obtained via `automl.automl_.get_models_with_weights()` (which will return each pipeline with the weight in the ensemble).

This way you can have access to the scaler for example. Please let us know if this is not what you are looking for.
