### ISSUE TITLE
Refit pretrained model with extra classes

### ISSUE THREAD

**Issue by Robotuks** [automl/auto-sklearn#789]
Hi,
I want to refit pretained model with updated data which has new classes added to it. This is how I tried to do it:
```
loaded_model = pickle.load(open("pretrained_model.pickle", 'rb'))
loaded_model.refit(new_x, new_y)
prediction = loaded_model.predict(new_x_test)
```
On `predict()` I receive `IndexError: index 7 is out of bounds for size 5`. There were 5 classes originally, later I added 2 more.
It seems `.refit()` does not update number of classes found in new training data. 
Is there a way I can make this work?
From what I found `.fit()` updates count of classes but then I lose pretrained model classification pipeline.

THANKS FOR AWESOME LIBRARY!

**Comment by mfeurer** [comment]
Hi @Robotuks I'm afraid that this isn't easily possible using Auto-sklearn. You could probably hack around this be calling `fit` on each model inside the ensemble of the loaded model.

However, I'm not sure if that's a too good idea as the configurations found during the tuning probably won't work that well any more if you add two new classes. If affordable, I would go for retraining from scratch.
