### ISSUE TITLE
Failure to start for a large dataset

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#79]
For a dataset that is 14GB of size on disk in an h5 format (sparse matrix)  and 36 GB in RAM  I get this error immediately after the autosklearn starts.

```
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-e.py", line 75, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 348, in _fit
    data_manager_path = self._backend.save_datamanager(datamanager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 134, in save_datamanager
    pickle.dump(datamanager, fh, -1)
SystemError: error return without exception set
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-e.py", line 86, in <module>
    pool.map(spawn_classifier, [fit_delay+60*i for i in range(max_pool_size)])
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
SystemError: error return without exception set

```

There is enough free space on the disk and in RAM.

**Comment by mfeurer** [comment]
This looks like the sparse matrix is too big to be processed by the pickle module. We have to save the member attributes of the data manager on its own in order to avoid this problem, possibly using `sklearn.external.joblib` instead of pickle.

**Comment by yasserabbass** [comment]
I have the same error with 3G dataset on disk. and also 36G of RAM

**Comment by Motorrat** [comment]
Could this be the root case? http://stackoverflow.com/questions/12569977/python-large-iterations-number-fail

**Comment by yasserabbass** [comment]
I think the problem was in python 2, I tried the same on python 3 and it didn't show the same error at least for now

**Comment by mfeurer** [comment]
@Motorrat does this exception still occur with python3? If yes, could you please provide me the following information:

1. python version, numpy version, scipy version, sklearn version
2. I cannot reproduce this issue on my machine, thus I need you to provide some information about the data you're using. Assuming that your data is confidential, I would like to know the shape of the dataset and the percentage of non-zero entries. Ideal would be a script which generates a similar dummy dataset, for example like this:
```
import numpy as np
import scipy.sparse
row = np.random.randint(0, 100000000, size=100000000)
col = np.random.randint(0, 100000000, size=100000000)
data = np.ones_like(row)
m = scipy.sparse.csr_matrix((data, (row, col)), shape=(100000000, 100000000))
m.shape
import pickle
with open('/tmp/mfeurer.pkl', 'wb') as fh:
    pickle.dump(m, fh, protocol=-1)
```

**Comment by yasserabbass** [comment]
I had used the Bosch Production Line Performance data from kaggle. it contains 3 csv each about 2 GB on disk. It worked with python 3 but not with python 2.
But I noticed something strange autosklearn does not deal with pandas data frames. I'm not sure why

It would be great if autosklearn can handle pandas

**Comment by mfeurer** [comment]
I opened a new issue for handling pandas data.

**Comment by mfeurer** [comment]
@Motorrat could you please check if this issue still is there with the latest release of auto-sklearn (0.2.0)?

**Comment by mfeurer** [comment]
I just pushed a new auto-sklearn version (0.3.0). Please reopen if the issue still exists.
