### ISSUE TITLE
Auto-sklearn Not Compatible with Python3.8

### ISSUE THREAD

**Issue by polarCatZhao** [automl/auto-sklearn#790]
In the documentation for installation [https://automl.github.io/auto-sklearn/master/installation.html#installation](url), under the section System requirements, it requires Python>=3.5. However, auto-sklearn won't work with Python3.8. 

Line 24 in autosklearn/util/stopwatch.py  `self._cpu_tic = time.clock()` is not compatible with Python3.8 because in Python3.8

> The function time.clock() has been removed, after having been deprecated since Python 3.3 

according to [https://docs.python.org/3/whatsnew/3.8.html](url).

**Comment by ashley8jain** [comment]
yeah. same issue occurred on my PC. is there any solution?

**Comment by gui-miotto** [comment]
Hey guys, thanks for raising the issue. This problem has been fixed by @julian in #778 .
@mfeurer , since the development branch is not currently passing all tests, is there anything we could do here besides waiting for the next release?

**Comment by mfeurer** [comment]
> is there anything we could do here besides waiting for the next release?

I'm afraid there's nothing which can be done until the next release. If one has plenty of time and doesn't require the meta-learning to work, one can use the development branch.

**Comment by anupraas** [comment]
Python3.7 may be used as a workaround for the moment.

**Comment by goktug97** [comment]
While waiting, you can directly edit the autosklearn.util.stopwatch in site-packages to use with Python 3.8
```bash
file=$(python -c "import autosklearn;print(autosklearn.__path__[0])")/util/stopwatch.py; sed -i 's/clock/process_time/g' $file
```

**Comment by mfeurer** [comment]
Hey everybody, we did a new release a few days ago (0.7.0) which finally supports Python3.8.
