### ISSUE TITLE
Document parallel auto-sklearn better

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#792]
In particular, point to the SMAC3 documentation. So far, there's only an issue on this yet: https://github.com/automl/SMAC3/issues/609

**Comment by franchuterivera** [comment]
Hi @mfeurer , do you think this is needed? It looks like an old reference to psmac which we no longer have. Also, I believe new example for parallel are now available. But if you think more documentation is needed I can add it?
