### ISSUE TITLE
About output model and how to put it in production

### ISSUE THREAD

**Issue by ajoeajoe** [automl/auto-sklearn#796]
1, is autosklearn only output an ensemble model?
    can it output a model with only one algorithm , like autoweka, may be only by through specify the "include_estimators" an algorithm?

2 , How save model in file that can be used to predict by sklearn.

**Comment by mfeurer** [comment]
> 1, is autosklearn only output an ensemble model? can it output a model with only one algorithm , like autoweka, may be only by through specify the "include_estimators" an algorithm?

You can ask auto-sklearn to only include a single model in the final ensemble by setting `ensemble_size=1`.

> 2 , How save model in file that can be used to predict by sklearn.

Auto-sklearn does not support export to plain sklearn. Please check [this section of the manual](https://automl.github.io/auto-sklearn/master/manual.html#model-persistence) for what you can do.

**Comment by ajoeajoe** [comment]
Thanks
