### ISSUE TITLE
Running search in parallel?

### ISSUE THREAD

**Issue by stevenpollack** [automl/auto-sklearn#8]
Can it be done? Is this feature being developed?

**Comment by mfeurer** [comment]
Hi,
no, at the moment this is not possible. We will add a simple parallel mode in the near future, so stay tuned.

**Comment by mfeurer** [comment]
An explanation of how to do this was added with commit 0c548a60c7c191ca75e4278d45af9a152c9b08f1 and can be found in the [development branch documentation](http://automl.github.io/auto-sklearn/dev/manual.html#parallel-computation).
