### ISSUE TITLE
Is it possible to know how long meta learning takes?

### ISSUE THREAD

**Issue by LishengSun** [automl/auto-sklearn#805]
Hi auto-sklearn team,

I would like to know if it's possible to know, say, given 'time_left_for_this_task=3600, initial_configurations_via_metalearning=25', the proportion of time used for meta-learning (i.e. for computing the meta-features as well as the distance with seen datasets)? 

Thank you in advance!

**Comment by mfeurer** [comment]
Hey @LishengSun, you can check the logfile in Auto-sklearn's temporary output directory. There will be two lines like:
```
[DEBUG] [2020-04-02 13:20:38,946:AutoMLSMBO(1)::breast_cancer] Looking for initial configurations took  0.17sec
[INFO] [2020-04-02 13:20:38,946:AutoMLSMBO(1)::breast_cancer] Time left for breast_cancer after finding initial configurations: 297.94sec
```
which mark the end of the meta-learning part. The beginning of meta-learning is marked by a line like:
```
[INFO] [2020-04-02 13:20:38,358:AutoMLSMBO(1)::breast_cancer] Metadata directory: /home/feurerm/sync_dir/projects/automl_competition_2015/auto-sklearn/autosklearn/metalearning/files/accuracy_binary.classification_dense
```
and the difference between the time stamps should be the time meta-learning takes.

**Comment by LishengSun** [comment]
Hi @mfeurer, thank you for your reply! I am checking the log and am interested in the datasets you use to warm start the search. I would like to know which datasets you use and in which order they are processed. For example: 
`[INFO] [2020-03-25 09:54:54,957:autosklearn.metalearning.optimizers.metalearn_optimizer.metalearner] 233 0.8205610076618818 Configuration:
  balancing:strategy, Value: 'none'
...`
and 
`[INFO] [2020-03-25 09:54:54,958:autosklearn.metalearning.optimizers.metalearn_optimizer.metalearner] 75153 0.9687283037560379 Configuration:
  balancing:strategy, Value: 'none'
  categorical_encoding:__choice__, Value: 'no_encoding'
...`

Are the first numbers 233 and 75153 the dataset IDs and the second numbers 0.8205610076618818 and 0.9687283037560379 the L1 distance in the meta-feature space? 

Thanks!!

**Comment by mfeurer** [comment]
Yes, that's exactly what's happening. You can check out the code [here](https://github.com/automl/auto-sklearn/blob/210d497ab66e018a4851994c71e31c0ee42a5ab2/autosklearn/metalearning/optimizers/metalearn_optimizer/metalearner.py#L30).

**Comment by mfeurer** [comment]
Closing this as I think the question is answered. Please reopen if you have any further questions.
