### ISSUE TITLE
Could not delete output dir: /tmp/autosklearn_output/...

### ISSUE THREAD

**Issue by gitDawn** [automl/auto-sklearn#811]
Hi,

After I'm running the auto-sklearn, get the result and save it as pickle file with  
 `pickle.dump(automl, open(file_name, 'wb')`, I'm now trying to load all the models to a list.

When I try the following:  

```
def load_model(model_file):
    loaded_model = pickle.load(open(model_file, 'rb'))
    return loaded_model

my_file = './models/1139 max.pickle'
list_models = []
for i in range(100):
    model1 = load_model( my_file )
    list_models.append( model1 )
```

I'm getting errors:  

```
Could not delete output dir: /tmp/autosklearn_output_6156_5743
Could not delete tmp dir: /tmp/autosklearn_tmp_6156_5743
Could not delete output dir: /tmp/autosklearn_output_6156_5743
Could not delete tmp dir: /tmp/autosklearn_tmp_6156_5743
Could not delete output dir: /tmp/autosklearn_output_6156_5743
Could not delete tmp dir: /tmp/autosklearn_tmp_6156_5743
...

```

What is the problem and how can I solve it?

Thanks!
Shahar

**Comment by mfeurer** [comment]
Hey, I'm not really sure why these happen, but I think these are only warnings and can be safely ignored in your case. Is the code otherwise behaving as expected?

**Comment by gitDawn** [comment]
Yes, the loaded models seems to have the same results as the saved ones. Is there any way to suppress these warnings?

**Comment by mfeurer** [comment]
No, sorry, there's currently no way to do so.

**Comment by gitDawn** [comment]
Ok, thanks. It would be nice-to-have, but I'm closing the issue.
