### ISSUE TITLE
get timestamps of start and end of training of algorithm

### ISSUE THREAD

**Issue by rupeshchandgude** [automl/auto-sklearn#818]
Is there any way to get time of start of training and end of training of each algorithm from logs generated after fit method? I looked into logs but not able to get it. Can anybody help me out?

**Comment by mfeurer** [comment]
We don't log the exact start and end time of model building. The only thing we log is the beginning and end of the call to the function we are optimizing, and the function we are optimizing is loading the data, building a model, and predicting. If that's of help for you, the start is marked by:
```
[DEBUG] [2020-04-13 12:48:44,504:pynisher] Function called with argument: ()
```
and the end is marked by:
```
[DEBUG] [2020-04-13 12:48:44,979:pynisher] function returned properly: (None, 0)
```
