### ISSUE TITLE
'RuntimeWarning: Mean of empty slice' during metafeature calculation

### ISSUE THREAD

**Issue by he-ritter** [automl/auto-sklearn#819]
Hello,

When building my own metafeatures using the scripts provided, the following warnings appear during 03_calculate_metafeatures:

```
[Memory] Calling __main__--WORKINGDIR-03_calculate_metafeatures.calculate_metafeatures...
calculate_metafeatures(254)
254
/home/XXX/.local/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1667: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/home/XXX/.local/lib/python3.6/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py:437: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(values)
```

Is this something to worry about or can it be ignored?

**Comment by mfeurer** [comment]
I think this is nothing to worry about, but I have encountered similar warnings when computing meta-features (for example on dataset 75221). We'll have a look into this in the mid-future.

**Comment by eddiebergman** [comment]
This is documented and collected in PR #1238 and will be handled there and recreated as an issue for whatever is not fixed in that PR.
