### ISSUE TITLE
Pandas version incorrect in 0.7.0

### ISSUE THREAD

**Issue by gmeans** [automl/auto-sklearn#848]
It seems like something happened to the PR that updates the pandas version for version 0.7.0.

https://github.com/automl/auto-sklearn/blob/bb8396b3dbe2e61cfdf65b5fbd9793b1d2d3dffc/requirements.txt#L15

The release says there is a fix that allows for pandas > 1.x , however as you see in the link above that tagged release still has the requirements.txt saying < 1.0.

**Comment by mfeurer** [comment]
We have fixed this via #948. The fix will be available in the next release
