### ISSUE TITLE
How to use saved fitted model with pickle to run predict in new data

### ISSUE THREAD

**Issue by joaomiraglia** [automl/auto-sklearn#849]
Hello,
this is the same question as this: https://github.com/automl/auto-sklearn/issues/5#issuecomment-323444616, but I couldn't find an answer.

I managed to save my fitted model to a file with pickle and reload it.
But it is reloaded as a dictionary, and I'm not being able to use this dictionary to run predict on new data.

I save it like this:
```
x = automl.show_models()
results = {"ensemble": x}
pickle.dump(results, open('file.pickle','wb'))
```

Load it like this:
`automl = pickle.load(open('file.pickle','rb'))`

And when I run predict
`y_hat = automl.predict(X_test)`

Get the following error
`AttributeError: 'str' object has no attribute 'predict'`

Because the file is loaded back as a dictionary.

Thank you.

**Comment by cturner500** [comment]
Here's what we have working in production:  

pickle.dump(model, open(filename, 'wb'))
loaded_model = pickle.load(filename)
predictions = loaded_model.predict(model_data)

If this works, I would not go with the show_models() approach.

**Comment by mfeurer** [comment]
Thanks @cturner500 for answering this question!

**Comment by piyushandilya** [comment]
I'm getting the same error

`import pickle as pickle

#Save
pickle.dump(model, open("saved_supervised_model.pkl", "wb"))

#Load
saved_model = pickle.load(open("saved_supervised_model.pkl", "rb"))`

The "saved_model" is of type 'str' and obviously it doesn't have the function "predict". This model is supposed to be of the type as was the original model. Somehow pickle is serializing the model but not able to de-serialize it back into the object type.

**Comment by mfeurer** [comment]
Could you please open a new issue with a fully reproducible example?
