### ISSUE TITLE
some semantic mistakes

### ISSUE THREAD

**Issue by jh-jeong** [automl/auto-sklearn#85]
It seems that there are some semantic errors in the codes.
I found that:
1) `pipeline/components/classification/decision_tree.py` &`pipeline/components/regression/decision_tree.py` : `max_depth` is not properly assigned
2) `ensembles/ensemble_selection.py`: In `EnsembleSelection._sorted_initialization()`, `predictions` is used as a parameter of `calculate_score`, but maybe it will generate an error since `predictions` would be a 3-d array.

**Comment by mfeurer** [comment]
Merged, thanks a lot.
