### ISSUE TITLE
AutoML, Time series,

### ISSUE THREAD

**Issue by ikramelmbarki** [automl/auto-sklearn#850]
I've a multivariate time series and I wanna work with an autoML package for regression and classification problems?
what is the best package to work with ?
I found that there is TPOT but it don't accept the column as a date as an object or datetime and if i transform it to int type  i don't know if it's the best transformation that will help to choose the right algorithms for my dataset, and also found that there is Auto sklearn and others

**Comment by mfeurer** [comment]
Hey @ikramelmbarki Auto-sklearn currently does not support any time series. Unfortunately, I'm not aware of any package which does AutoML for time series, so I can't really help here, sorry.
