### ISSUE TITLE
import autosklearn fails in Jupyter notebook

### ISSUE THREAD

**Issue by tochukwuokafor** [automl/auto-sklearn#853]
I have installed auto-sklearn using Ubuntu 18.04. I am able to import auto-sklearn in Ubuntu but unable to import it in Jupyter notebook. I get the following error: 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3c38f1248582> in <module>
----> 1 import autosklearn

ModuleNotFoundError: No module named 'autosklearn'
```

Is there a solution to this?

**Comment by mfeurer** [comment]
Hey, if you can import the module with the regular python interpreter, but not with Jupyter, and given the error message you posted, it looks like there is an issue with your installation. Can you check whether the path you installed Auto-sklearn to is in the `PYTHONPATH` of the interpreter running the Jupyter notebook?

**Comment by tochukwuokafor** [comment]
Thank you so much for the feedback @mfeurer . It works now. I shall close the issue now.
