### ISSUE TITLE
What is the difference between ensemble_size and ensemble_nbest?

### ISSUE THREAD

**Issue by weir12** [automl/auto-sklearn#855]
Hi:
Thank you for developing this project,which is very helpful to non-experts in machine learning (like me).
I am not very clear about the meaning of these two parameters: `ensemble_size
`  &&  `ensemble_nbest`
My current perception is that `ensemble_size` is used to control the number of models of the  ensemble.
 `ensemble_nbest` is used to control the number of models added to ensemble during  each iteration.
That is just my guess, please tell me the correct concept.
Thanks

**Comment by mfeurer** [comment]
Hey, sure:
* `ensemble_size`: yes, for ensemble size your understanding is correct, it's how many models are added to the ensemble. Models can be repeatedly added, so there might not be that many unique models in the ensemble in the end, though. You can see the explanation in Section 2.1 of the 2004 paper (I pasted a link at the bottom).
* `ensemble_nbest`: this one determines how many models to consider at most being worth to add to the ensemble. It's similar to the concept of Model Library Pruning which is explained in section 8 of the 2006 paper (which is also in the link at the bottom). We use it to reduce the number of models considered in practice. We should maybe rename it to library pruning to make it clearer.

[Paper](https://www.cs.cornell.edu/~caruana/ctp/ct.papers/caruana.icml04.icdm06long.pdf)

**Comment by weir12** [comment]
Thank you for your help.
That is a very clear answer for my confusion.
Looking forward to the releasing of the new library:)
