### ISSUE TITLE
meat learning script in regression 

### ISSUE THREAD

**Issue by feigeZzzz** [automl/auto-sklearn#859]
[load_task line 38-41](https://github.com/automl/auto-sklearn/blob/master/scripts/update_metadata_util.py)
There's  a problem for regression when add new dataset in meta learning. For regression,  the code map the continuous regression target to discrete target. I'm curious why the develope team do that to convert a regression problem to a classification problem. And there's a bug happend, when we map the training set target to discrete target, the testing set target will encounter a error for not finding mapping values in y_train.
@rcalsaverini @tmielika @Julian @vicentealencar @larskotthoff

**Comment by Julian** [comment]
Please don't ping random people when filing an issue ticket.

**Comment by mfeurer** [comment]
This is a mistake as described in #840. Closing this because it is a duplicate.
