### ISSUE TITLE
run auto-sklearn in windows

### ISSUE THREAD

**Issue by thinker111** [automl/auto-sklearn#860]
Hi,guys

    I just successfully installed SMAC(which is the basic compent of auto-sklearn) in WSL and I just try to install auto-sklearn,it runs well too. 
The Installation tutorial I have put it on https://blog.csdn.net/potun7890/article/details/106350912
Hope it will be useful for you.

Best wishes!

PS:When you install WSL, please select Ubuntu 18.04 in Microsoft Store instead of 20.04. At present, the 20.04 version is not stable, and  swig, in it, is forced to be version 4.0 when installing SMAC inputing the command 'sudo apt get install build essential swig' ,resulting in the segmentation fault (core dumped) .

**Comment by Stajo3** [comment]
when do "curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install"
report 'OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443'
it seems like https://raw.githubusercontent.com/automl/auto-sklearn/master is not available?

**Comment by thinker111** [comment]
I undate the solution for error 443 : https://blog.csdn.net/potun7890/article/details/106350912
add 199.232.68.133 raw.githubusercontent.com  into /etc/hosts 
then try again

**Comment by Stajo3** [comment]
> I update the solution for error 443 : https://blog.csdn.net/potun7890/article/details/106350912
> add 199.232.68.133 raw.githubusercontent.com into /etc/hosts
> then try again

use 18.04 instead of 20.04.That really works!thanks for your share!appreciate

**Comment by mfeurer** [comment]
Thanks a lot for your tutorial @thinker111 

There's good news - as of recently we have uploaded wheels for the pyrfr package which means that one does no longer need SWIG during the installation and can use the latest Ubuntu!

I'm closing this issue for now and will reference it from the manual.
