### ISSUE TITLE
Dockerfile is not working

### ISSUE THREAD

**Issue by wlongxiang** [automl/auto-sklearn#867]
## Describe the bug ##
The provided dockerfile does not build on Mac.

## To Reproduce ##

- Run docker build on the provided Dockerfile
- See error:

```
Collecting lazy_import
  Downloading lazy_import-0.2.2.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ogvjzynh/lazy-import/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ogvjzynh/lazy-import/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zdklootb
         cwd: /tmp/pip-install-ogvjzynh/lazy-import/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ogvjzynh/lazy-import/setup.py", line 6, in <module>
        readme = infile.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 621: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt   | xargs -n 1 -L 1 pip3 install' returned a non-zero code: 123
```

## Environment and installation: ##

Please give details about your installation:

* OS: Mac
* Conda
* Python3.7
* Auto-sklearn version: 0.0.7

**Comment by Oli2** [comment]
I have experienced the same issue with Ubuntu:
Collecting lazy_import
  Downloading lazy_import-0.2.2.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-saqtau5s/lazy-import/setup.py'"'"'; __file__='"'"'/tmp/pip-install-saqtau5s/lazy-import/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-odo3uzej
         cwd: /tmp/pip-install-saqtau5s/lazy-import/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-saqtau5s/lazy-import/setup.py", line 6, in <module>
        readme = infile.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 621: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt   | xargs -n 1 -L 1 pip3 install' returned a non-zero code: 123

**Comment by mfeurer** [comment]
The issue here is that `lazy_import` has special characters in the readme and silently assumes that your system uses UTF-8 encoding (https://github.com/mnmelo/lazy_import/issues/11).

Can you please check whether changing the encoding of your shell to UTF-8 solves this issue (see for example here for the BASH shell: https://stackoverflow.com/a/28478933)

**Comment by Oli2** [comment]
Thank you @mfeurer.  Setting LANG=C.UTF-8 doesn't seem to solve this problem. I will try to investigate it further.

Collecting lazy_import
  Downloading lazy_import-0.2.2.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4s_43ivq/lazy-import/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4s_43ivq/lazy-import/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k0wah_rg
         cwd: /tmp/pip-install-4s_43ivq/lazy-import/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4s_43ivq/lazy-import/setup.py", line 6, in <module>
        readme = infile.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 621: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt   | xargs -n 1 -L 1 pip3 install' returned a non-zero code: 123
bash-3.2# locale
LANG="C.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
bash-3.2#

**Comment by mfeurer** [comment]
As a hotfix you could clone the lazy import package, apply the fix I linked above and install the package prior to installing Auto-sklearn.

**Comment by Oli2** [comment]
All done and after applying the fix, it now works as expected. Thanks!

**Comment by wlongxiang** [comment]
After fix lazy_import, I ran into another error for smac package, see error below:
```
Collecting smac>=0.12
  Using cached smac-0.12.2.tar.gz (214 kB)
  WARNING: Generating metadata for package smac produced metadata for project name unknown. Fix your #egg=smac fragments.
Requirement already satisfied (use --upgrade to upgrade): unknown from https://files.pythonhosted.org/packages/8d/31/eb9806705d01c3211b729dd58117f6ab5337558e7f6dbff54bd93a42c3c3/smac-0.12.2.tar.gz#sha256=02c6d969c8a0f208c32835dd3d53d362d7d1f334c7ef3b0f95c3471ab2311b7d in /usr/local/lib/python3.5/dist-packages (from auto-sklearn)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 399, in _resolve_one
    assert req_to_install.is_direct
AssertionError
The command '/bin/sh -c pip3 install   auto-sklearn   jupyter' returned a non-zero code: 2
```

**Comment by mfeurer** [comment]
Could you please try changing the dockerfile to install auto-sklearn and jupyter separately? Then we'd see which one of both fails.

**Comment by mfeurer** [comment]
We have updated the dockerfile to circumvent this issue and are now running online tests with the docker image. You can find it here: https://github.com/automl/auto-sklearn/packages/326379

Please reopen if this issue persists.
