### ISSUE TITLE
about extending auto-sklearn——LGBMregressor

### ISSUE THREAD

**Issue by bonnie233** [automl/auto-sklearn#878]
I had try to write my own LgbmRegressor to add into auto-sklearn like follow：

from ConfigSpace.configuration_space import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformFloatHyperparameter, \
    UniformIntegerHyperparameter, UnParametrizedHyperparameter,CategoricalHyperparameter

import sklearn.metrics
import autosklearn.regression
import autosklearn.pipeline.components.regression
from autosklearn.pipeline.components.base import AutoSklearnRegressionAlgorithm
from autosklearn.pipeline.constants import SPARSE, DENSE, \
    SIGNED_DATA, UNSIGNED_DATA, PREDICTIONS

class LgbmRegression(AutoSklearnRegressionAlgorithm):
    def __init__(self,num_leaves,learning_rate,max_depth,reg_alpha,reg_lambda,
                 objective,num_class,n_estimators,device,gpu_platform_id,
                 gpu_device_id,is_unbalance=True,random_state=None,num_thread=5):
        
        self.is_unbalance = is_unbalance
        self.objective = objective
        self.num_class = num_class
        self.num_leaves = num_leaves
        self.learning_rate = learning_rate
        self.n_estimators = n_estimators
        self.device = device
        self.gpu_platform_id = gpu_platform_id
        self.gpu_device_id = gpu_device_id
        self.max_depth = max_depth
        self.random_state = random_state
        self.reg_alpha = reg_alpha
        self.reg_lambda = reg_lambda
        self.num_thread = num_thread
        self.estimator = None
        

    def fit(self, X, y,validX,validY):
        self.is_unbalance = is_unbalance
        self.objective = objective
        self.num_class = num_class
        self.num_leaves = num_leaves
        self.learning_rate = learning_rate
        self.n_estimators = n_estimators
        self.device = device
        self.gpu_platform_id = gpu_platform_id
        self.gpu_device_id = gpu_device_id
        self.max_depth = max_depth
        self.random_state = random_state
        self.reg_alpha = reg_alpha
        self.reg_lambda = reg_lambda
        self.num_thread = num_thread

        import lightgbm as lgb
        self.estimator = lgb.LGBMRegressor(is_unbalance=self.is_unbalance, 
                                           objective=self.objective,
                                           num_class=self.num_class,
                                           num_leaves=self.num_leaves,
                                           learning_rate=self.learning_rate,
                                           n_estimators=self.n_estimators, 
                                           device= self.device,
                                           gpu_platform_id=self.gpu_platform_id,
                                           gpu_device_id=self.gpu_device_id,
                                           max_depth = self.max_depth,
                                           random_state = self.random_state,
                                           reg_alpha=self.reg_alpha,
                                           reg_lambda=self.reg_lambda,
                                           num_thread=self.num_thread)
        self.estimator.fit(X, y, eval_set=[(np.array(validX),validY)], eval_metric='multi_logloss',verbose=False,early_stopping_rounds=20)
        return self

    def predict(self, X):
        if self.estimator is None:
            raise NotImplementedError
        return self.estimator.predict(X)

    @staticmethod
    def get_properties(dataset_properties=None):
        return {'shortname': 'LGBM',
                'name': 'LgbmRegression',
                'handles_regression': True,
                'handles_classification': True,
                'handles_multiclass': True,
                'handles_multilabel': True,
                'is_deterministic': True,
                'input': (SPARSE, DENSE, UNSIGNED_DATA, SIGNED_DATA),
                'output': (PREDICTIONS,)}

    @staticmethod
    def get_hyperparameter_search_space(dataset_properties=None):
        cs = ConfigurationSpace()
        num_leaves = UniformIntegerHyperparameter(
            name='num_leaves', lower=30, upper=35, default_value=31
        )
        learning_rate = UniformFloatHyperparameter(
            name='learning_rate', lower=0.01, upper=0.1, log=True, default_value=0.01)
        max_depth = UniformIntegerHyperparameter(
            name='max_depth', lower=6, upper=8, default_value=6
        )
        reg_alpha = UniformFloatHyperparameter(
            name='reg_alpha', lower=0.001, upper=1, default_value=0.001, log=True
        )
        reg_lambda = UniformFloatHyperparameter(
            name='reg_lambda', lower=0.001, upper=1, default_value=0.001, log=True
        )
        
        #UnParametrized
        objective = UnParametrizedHyperparameter(
            name='objective', value='multiclass')
        num_class = UnParametrizedHyperparameter(
            name='num_class', value=3)
        n_estimators = UnParametrizedHyperparameter(
            name='n_estimators', value=100)
        device = UnParametrizedHyperparameter(
            name='device', value='gpu')
        gpu_platform_id = UnParametrizedHyperparameter(
            name='gpu_platform_id', value=0)
        gpu_device_id = UnParametrizedHyperparameter(
            name='gpu_device_id', value=0)
        
        cs.add_hyperparameters([num_leaves,learning_rate,max_depth,
                                reg_alpha,reg_lambda,objective,num_class,
                                n_estimators,device,gpu_platform_id,gpu_device_id])
        return cs
autosklearn.pipeline.components.regression.add_regressor(LgbmRegression)
cs = LgbmRegression.get_hyperparameter_search_space()

and use follow sentence to run：
model = autosklearn.regression.AutoSklearnRegressor(time_left_for_this_task=7200,per_run_time_limit=7000,n_jobs=5,ml_memory_limit=204800,include_estimators=["LgbmRegression"])

model.fit(trainX, trainY,validX,validY)

but i got a error：
Traceback (most recent call last):
  File "Atest_auto.py", line 104, in <module>
    result_df = LT.train(X,Y,index_df,begin_date,end_date)
  File "/home1/data1/code/public/auto_valid1.py", line 227, in train
    result = test_train(X,Y,index_df,train_end_date,test_end_date)
  File "/home1/data1/code/public/auto_valid1.py", line 185, in test_train
    model.fit(trainX, trainY,validX,validY)
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/estimators.py", line 819, in fit
    dataset_name=dataset_name,
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/estimators.py", line 417, in fit
    load_models=True,
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/estimators.py", line 16, in _fit_automl
    return automl.fit(load_models=load_models, **kwargs)
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py", line 1121, in fit
    load_models=load_models,
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py", line 213, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py", line 502, in _fit
    _proc_smac.run_smbo()
  File "/home/sai/anaconda3/lib/python3.7/site-packages/autosklearn/smbo.py", line 489, in run_smbo
    smac.optimize()
  File "/home/sai/anaconda3/lib/python3.7/site-packages/smac/facade/smac_ac_facade.py", line 567, in optimize
    incumbent = self.solver.run()
  File "/home/sai/anaconda3/lib/python3.7/site-packages/smac/optimizer/smbo.py", line 181, in run
    logger=self.logger)
  File "/home/sai/anaconda3/lib/python3.7/site-packages/smac/optimizer/pSMAC.py", line 54, in read
    configuration_space)
  File "/home/sai/anaconda3/lib/python3.7/site-packages/smac/runhistory/runhistory.py", line 510, in update_from_json
    new_runhistory.load_json(fn, cs)
  File "/home/sai/anaconda3/lib/python3.7/site-packages/smac/runhistory/runhistory.py", line 474, in load_json
    ) for id_, values in all_data["configs"].items()
  File "/home/sai/anaconda3/lib/python3.7/site-packages/smac/runhistory/runhistory.py", line 474, in <dictcomp>
    ) for id_, values in all_data["configs"].items()
  File "ConfigSpace/configuration_space.pyx", line 1385, in ConfigSpace.configuration_space.Configuration.__init__
ValueError: Tried to specify unknown hyperparameter balancing:strategy

i try to understand what’wrong， but it‘s difficult to me。so i want to ask for your help，what should i do to resolve it。

**Comment by mfeurer** [comment]
This appears to be an issue in the way Auto-sklearn handles parallel runs -- it accidentally reads in results from a classification run and crashes due to the different search spaces.

Could you please do the following two things and try again:
1. Make sure all output files from Auto-sklearn in your temporary directory are deleted, and if not, delete them manually.
2. Manually give `tmp_folder` and `output_folder` as arguments to Auto-sklearn. Please make sure to always delete them before re-running the script, and to not reuse such a folder in multiple scripts.

**Comment by bonnie233** [comment]
Thank you very much for your answer. It really worked
In addition, I have two more questions that need your help:
1. def predict(self, X):
    if self.estimator is None:
        raise NotImplementedError
    return self.estimator.predict(X)

do I need to def predict_proba for Regressor? Although theLGBMRegressor‘s predict()  function to output a category-based probability, but in my experiment ,i define it like before and it output a floating point number

2. another question is about whether the optimal model and parameters obtained by auto-Sklearn can be found under the tMP_folder directory defined by us? Because there seem to be multiple files generated in this directory, I'm not sure if there is a final optimal model and optimal parameters

**Comment by mfeurer** [comment]
> do I need to def predict_proba for Regressor

No, that's only for classification

> another question is about whether the optimal model and parameters obtained by auto-Sklearn can be found under the tMP_folder directory defined by us

Please check out my answer in this issue: https://github.com/automl/auto-sklearn/issues/872

**Comment by mfeurer** [comment]
Closing as the issue appears to be resolved - please reopen if that's not the case.
