### ISSUE TITLE
Is there a way for the most optimial SKLearn Algorithm to be identified?

### ISSUE THREAD

**Issue by mgiardinelli** [automl/auto-sklearn#880]
Is there a way to understand what algorithm auto-sklearn identified was the best approach, along with the associated hyperparameters? It would be great to use it to understand what is the most optimal approach, given a classification or regression challenge. 

Thanks!

**Comment by mgiardinelli** [comment]
Looks like this could be the method that would show what I am asking. I was looking right over it in the docs. https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.show_models

**Comment by mfeurer** [comment]
Please also check out my answer here https://github.com/automl/auto-sklearn/issues/872

Closing this as it appears to be solved. Please reopen if you have any further questions.

**Comment by shabir1** [comment]
I run the auto-sklearn on some data with ensemble size 50, now I want the algorithms selected with their parameter.
show_models() returns the models in string format need to parse it for getting classifier selected with parameter values.
I also tried get_models_with_weights().
Is there any easy way to get just algorithm name and their hyperparameters?

**Comment by mfeurer** [comment]
@shabir1 Please do not comment on closed issues but open a new issue.
