### ISSUE TITLE
About the comparison between datasets

### ISSUE THREAD

**Issue by Xiaoyuwang13** [automl/auto-sklearn#883]
For the metalearning part of autosklearn, I am curious that which part of the code implement the  comparison between datasets based on distance？
For example，in  the 
_**auto-sklearn/autosklearn/metalearning/metalearning/kNearestDatasets/kND.py /**_，def kNearestDatasets , #94  _Names of the most similar datasets, sorted by similarity_ , which part of code are use similarity to compare datasets then recommended good configuration？

Thanks in advance！

**Comment by mfeurer** [comment]
We use scikit-learn's kNN for comparing the datasets based on their meta-feature description, see [here](https://github.com/automl/auto-sklearn/blob/v.0.7.0/autosklearn/metalearning/metalearning/kNearestDatasets/kND.py#L71).
