### ISSUE TITLE
compability information of auto-sklearn

### ISSUE THREAD

**Issue by reddyprasade** [automl/auto-sklearn#904]
`We already installed your prerequisite in local machine Still it Shows Detected unsupported operating system: win32. Please check the compatibility information of auto-sklearn`

Collecting auto-sklearn
  Using cached auto-sklearn-0.8.0.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\reddy\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\reddy\\AppData\\Local\\Temp\\pip-install-qe2yfu4e\\auto-sklearn\\setup.py'"'"'; __file__='"'"'C:\\Users\\reddy\\AppData\\Local\\Temp\\pip-install-qe2yfu4e\\auto-sklearn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\reddy\AppData\Local\Temp\pip-pip-egg-info-7tdy1e_u'
         cwd: C:\Users\reddy\AppData\Local\Temp\pip-install-qe2yfu4e\auto-sklearn\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\reddy\AppData\Local\Temp\pip-install-qe2yfu4e\auto-sklearn\setup.py", line 13, in <module>
        sys.platform
    ValueError: Detected unsupported operating system: win32. Please check the compability information of auto-sklearn: http://automl.github.io/auto-sklearn/stable/installation.html#windows-osx-compability
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mfeurer** [comment]
Thanks @reddyprasade for brining this up - apparently the link is broken and should be https://automl.github.io/auto-sklearn/master/installation.html#windows-osx-compatibility

Long story short, we don't support Windows as it does not support the [resource](https://docs.python.org/3/library/resource.html) module.

@franchuterivera could you please fix the link and check whether there are more broken links in the docs?

**Comment by mfeurer** [comment]
Closing this as we updated the error message in Auto-sklearn.
