### ISSUE TITLE
Is it possible to turn preprocessing off completely?

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#91]
I have binary features (in a sparse matrix) and have great results running SGDclassifier on this dataset without any preprocessing. Is it possible to tell autosklearn to drop any preprocessing whatsoever?
Even though I have included include_preprocessors=('no_preprocessing',) into the AutoSklearnClassifier() I see the following in this or another form in every model call

```
 -imputation:strategy 'mean' -one_hot_encoding:minimum_fraction '0.1' -one_hot_encoding:use_minimum_fraction 'True' -preprocessor:__choice__ 'no_preprocessing' -rescaling:__choice__ 'min/max'
```

**Comment by mfeurer** [comment]
No, that's not possible at the moment. Will consider this as a feature for a future version.

**Comment by saurabh11baghel** [comment]
Hi,

Is there any progress on this issue? Can we turn off all the pre-processing?

**Comment by mfeurer** [comment]
Hi @saurabh11baghel, unfortunately, there's no one working on this.

**Comment by eddiebergman** [comment]
This should hopefully have been addressed and can now be done with extending with a NoPreprocessingComponenet, seen in this [example](https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_data_preprocessor.html#create-nopreprocessing-component-for-auto-sklearn). Closing for now but if it still comes up, feel free to re-open this.
