### ISSUE TITLE
Readme Code Coverage Image Issue 

### ISSUE THREAD

**Issue by bhadreshpsavani** [automl/auto-sklearn#913]
This issue appears on the Github page [Readme.md ](https://github.com/automl/auto-sklearn)
![image](https://user-images.githubusercontent.com/26653468/89117673-4503b600-d4bd-11ea-9aa0-521ba859fa2d.png)
![image](https://user-images.githubusercontent.com/26653468/89117684-50ef7800-d4bd-11ea-8b7c-dd79f2444360.png)

It's not a consistent issue When you load readme page multiple times you will get this issue

**Comment by mfeurer** [comment]
Thanks for notifying us. I can reproduce this. However, I've got no clue what to do about this as we neither host the readme.md file nor the code coverage image. Do you have any suggestions?

**Comment by bhadreshpsavani** [comment]
I am also not sure about the solution. Even I saw such issue first time

**Comment by mfeurer** [comment]
Thanks again, but I'll close this then as there's not really something we can do here and this doesn't have high priority on our side.
