### ISSUE TITLE
Feature specific categorical encoding

### ISSUE THREAD

**Issue by shikharsharma23** [automl/auto-sklearn#915]
I have following two questions 

1) When reading a dataset, is there an ability where auto-sklearn determines which columns are categorical vs numerical based on data. This way it can even work with string data. Is there a workaround for this ?

2) Can categorical_encoding choice be feature specific. Currently, there is a common choice for all features

**Comment by mfeurer** [comment]
> When reading a dataset, is there an ability where auto-sklearn determines which columns are categorical vs numerical based on data.

No, we currently don't have this. On the development branch we have just started allowing pandas data frames, where it detects categorical columns based on the data type.

> This way it can even work with string data.

Unfortunately, we don't support string data. If you have string data you'd have to encode either to categories or using a feature extractor for text prior to passing it to Auto-sklearn.

> Can categorical_encoding choice be feature specific. Currently, there is a common choice for all features

Unfortunately not, the same encoding will be applied to all categorical features. The reasoning here is that if we would search for this on a per-feature basis we would get an exponential growth of the search space with respect to the number of categorical features.
