### ISSUE TITLE
show_models or score() is "killed"

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#92]
this is the code I run after running multiprocess fit with exactly the same AutoSklearnClassifier call.

```
seed = 1
c = AutoSklearnClassifier(
        shared_mode=True, tmp_folder=atsklrn_tempdir, output_folder=atsklrn_tempdir,
        delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False,
        ensemble_size=0, initial_configurations_via_metalearning=0,
        include_preprocessors=('no_preprocessing',),
        seed=seed)
c._task = BINARY_CLASSIFICATION
c._metric = F1_METRIC
c._precision = '32'
c._dataset_name = 'Truffles'
c.run_ensemble_builder(
    time_left_for_ensembles=0,
    max_iterations=1,
    ensemble_size=25,
    ).wait()

time.sleep(10)
print(c.show_models())
print(c.score(X_test,y_test))
```

and all I get is 
`Killed`

**Comment by Motorrat** [comment]
I believe it was killed because it has exhausted all the available memory (went over 50GB). I have restarted it after I have cleaned up the memory and the show_memory completed. The same issue is discussed in #30 I wonder whether show_model() needs all that memory footprint to just show the models.

**Comment by mfeurer** [comment]
No, it there is no need to load all models. It's related to #45.

**Comment by mfeurer** [comment]
I just uploaded version 0.1 to pypi. Could you please check whether this is still an issue?

**Comment by Motorrat** [comment]
It would help if you could assign my profile to the issues I have opened and where you expects feedback. Otherwise it is hard for me to track the ones where I can't supply feedback immediately and need to put them to my "backlog".

**Comment by mfeurer** [comment]
With the latest release, auto-sklearn does no longer load all models after the optimization is finished. @Motorrat could you please check whether this issue is solved in your use case?

**Comment by mfeurer** [comment]
I just pushed a new auto-sklearn version (0.3.0). @Motorrat please reopen if the issue still exists.
