### ISSUE TITLE
Pandas Version Error mismatched

### ISSUE THREAD

**Issue by nithinreddyy** [automl/auto-sklearn#944]
IncorrectPackageVersionError: 'pandas 1.1.2' version mismatch (<1.0)

I'm getting the above error and i tried installing all the versions of pandas and I'm still stuck at that error.  Thanks in advance.

**Comment by mfeurer** [comment]
Did you try any pandas version below 1.0 such as 0.25.3?

**Comment by nithinreddyy** [comment]
> Did you try any pandas version below 1.0 such as 0.25.3?

Yes, I tried all the versions. But I'm getting the same error

**Comment by mfeurer** [comment]
Could you please try installing pandas 0.25.3 again and add 
```
import pandas as pd
print(pandas.__version__)
```
 and post the output?
