### ISSUE TITLE
Pipeline Export

### ISSUE THREAD

**Issue by amybachir** [automl/auto-sklearn#952]
Is there a way to export the best pipeline into python code and save to a file?

**Comment by charlesfu4** [comment]
Do you mean to export the best pipeline in a sklearn manner? Right now, I know some operations can tear down the pipeline into different blocks. There is an pipeline extraction example for the obtained model.
```
from sklearn.pipeline import Pipeline
transform_pip = Pipeline([('data_pre', model.get_models_with_weights()[0][1][0]),
                         ('feature_pre', model.get_models_with_weights()[0][1][1])])
```

From the sequence above, the estimator will be:
```
estimator = model.get_models_with_weights()[0][1][2]
```

If the ensemble is activated, the first two entries should also be taken into account. BTW, I used pickle to save the best pipeline.

**Comment by Rob192** [comment]
Thanks for the answer. I am trying to figure out how to use it. This would be very usefull indeed to have an export method built-in the `AutoSklearnClassifier`. The output would be a pure sklearn pipeline that could be used later on. E.g. on Windows for which auto-sklearn is not available. It would also maybe be lighter ?

**Comment by eddiebergman** [comment]
Hi @Rob192,

This seems like a nice idea, we'll look into it soon or feel free to provide your own PR if you have some extra time :)

Best,
Eddie
