### ISSUE TITLE
auto-sklearn doesn't work with new smac version of 13.0

### ISSUE THREAD

**Issue by medphisiker** [automl/auto-sklearn#963]
Hello, 
auto-sklearn=0.9 does not work with the new version of the smac==13.0.
If you do everything as usual:

`!apt-get install build-essential swig`
`!pip install auto-sklearn==0.9`
`!pip install arff`

We will get an error after the call:

`from autosklearn.experimental.askl2 import AutoSklearn2Classifier`

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-8ec583bd06b3> in <module>()
      1 # an error appears here
----> 2 from autosklearn.experimental.askl2 import AutoSklearn2Classifier

3 frames
/usr/local/lib/python3.6/dist-packages/autosklearn/automl.py in <module>()
     19 from sklearn.model_selection._split import _RepeatedSplits, \
     20     BaseShuffleSplit, BaseCrossValidator
---> 21 from smac.tae.execute_ta_run import StatusType
     22 from smac.stats.stats import Stats
     23 import joblib

ModuleNotFoundError: No module named 'smac.tae.execute_ta_run'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`

The thing is that it is now being installed smac==13.0

The problem is solved by simply rolling back to the previous version of the library by

`!pip install smac==0.12.3`

And now everything is working again! =)

My jupiter notebook with problem and it's solution.

https://colab.research.google.com/drive/1t6LrYcdY2NcVsw-Kec2DPM_b5coAvVjd?usp=sharing

**Comment by mfeurer** [comment]
Thanks for reporting this and sorry for the hassle. 

I'm currently working on a new release to fix this issue which should be there within the next few hours -> closing this.

**Comment by medphisiker** [comment]
It's okay, it's very easy to fix =)

And thank you for your library )
