### ISSUE TITLE
Can a conditional pipeline be created?

### ISSUE THREAD

**Issue by svsaraf112** [automl/auto-sklearn#972]
I am trying to extend auto-sklearn with CatBoost, for which I want to use the native categorical encoding used by the algorithm. I don't want to use one-hot-encoding for CatBoost, but at the same time I would like to have it for other algorithms, hence I cannot include or exclude certain things at a high level from the pipeline. Is there a way to create a conditional pipeline? 

Thanks!

**Comment by mfeurer** [comment]
No, sadly that's not possible right now in an easy fashion. You'd need to change the installed Auto-sklearn and add a statement that it is forbidden [here](https://github.com/automl/auto-sklearn/blob/v0.10.0/autosklearn/pipeline/classification.py#L275). You can have a look at the code slightly above to see how forbidden statements are created. Please let me know if you need any further help.

**Comment by svsaraf112** [comment]
This was helpful. Was able to create the conditional pipeline by adding forbidden statements

**Comment by franchuterivera** [comment]
Hello, I see this question has been answered, hence I am closing this issue. 

Thanks a lot for using Auto-sklearn!
