### ISSUE TITLE
automl error

### ISSUE THREAD

**Issue by tmrb** [automl/auto-sklearn#999]
## Describe the bug ##
Please describe the bug you're experiencing is precise as possible.

## Actual behavior, stacktrace or logfile ##
Please describe the expected behavior here. If there is a stacktrace, please paste it here. If there is no stacktrace printed, please upload the logfile which was stored in the `tmp_folder`

## Environment and installation: ##

Please give details about your installation:

* OS
* Is your installation in a virtual environment or conda environment?
* Python version
* Auto-sklearn version

**Comment by mfeurer** [comment]
Closing this as it contains no content and it seems that the content is in #1000.
